### ISSUE TITLE
How to add v-model to vue-editor?

### ISSUE THREAD

**Issue by andrei-bostan** [nhn/tui.editor#1001]
## Summary
I am trying to make an editor where if I click on specific documents it will change the content of the text. Problem is, I set it to :initial-value and then it doesn't change. I've tried using v-model, :value, but it doesn't work

## Code
```
       <v-row>
        <v-col  cols="12">
          <editor 
            :options="editorOptions"
            :initialValue="editorText"
            height="600px"
            initialEditType="wysiwyg"
            />
        </v-col>
      </v-row>
    </v-container>
</template>

<script lang="ts">
import { mapGetters } from 'vuex';
import 'codemirror/lib/codemirror.css';
import '@toast-ui/editor/dist/toastui-editor.css';

import { Editor } from '@toast-ui/vue-editor';

export default Vue.extend({
  components: {
    editor: Editor
  },
  data() {
    return {
        editorOptions: {
        },
        editorText:''
    };
  },
  computed: {
    ...mapGetters([
      'currentDocument',
    ])
  },
  methods: {
    updateText() {
      this.editorText = this.currentDocument.content;
    }
  },
  watch: {
        "$store.getters.currentDocument": "updateText",
    },
```

## Version
Latest version 2.1.2, I believe

**Comment by Aky22** [comment]
You have a workaround for this issue. If you add a key to the editor component and update it when the data is loaded, then it will work. I know that it's not the best and the most beautiful solution for the problem, but it works.

**Comment by seonim-ryu** [comment]
@andrei-bostan 

> I am trying to make an editor where if I click on specific documents it will change the content of the text.

I have a question. Are you sure you want to implement this feature? Please make sure this is what I understand. 

1. There is a button on the page that uses the Editor.
2. Clicking this button dynamically changes the contents of the editor.

If the function you are trying to implement is correct, I think you can do it by calling the `setMarkdown` API.
