### ISSUE TITLE
Editor WISIWIG 사진첨부 크기조절 질문

### ISSUE THREAD

**Issue by koko0869** [nhn/tui.editor#1002]
## Summary
Chrome에서 WISIWIG 사진첨부시 크기조절을 지원합니까?

## Screenshots
![image](https://user-images.githubusercontent.com/53290910/82631257-06858b80-9c30-11ea-965a-f087306188a0.png)

Chrome에서 위와같이 사진을 첨부했을 때 사진 크기 조절을 할 수 없습니까?

## Version
"@toast-ui/react-editor": "^2.1.2"

## Additional context
IE에서는 크기조절이 가능하던데 Chrome에서 지원을 하지 않는 것인지 여쭤봅니다.
크롬에서 사진조절을 해야 할 경우 어떻게 해야할까요 
예제 코드가 부탁드립니다.

**Comment by seonim-ryu** [comment]
@koko0869 It's currently a bug in IE to resize the image in WYSIWYG mode. It shouldn't work like that. Instead, there is a way to resize the image using the `image` tag in markdown mode.

![mde](https://user-images.githubusercontent.com/18183560/83210006-af823800-a194-11ea-8f96-9e5ca185ccfb.png)

And if possible, please write in English when posting the issue. I also want you to change the title and content in English to the currently registered issue. Other people can confirm this issue.
