### ISSUE TITLE
Paste HTML in editor seems not working

### ISSUE THREAD

**Issue by StephaneRavet** [nhn/tui.editor#1003]
## Describe the bug
When i paste HTML content in tui.editor, the content is raw text.

## To Reproduce
1. Copy some HTML content from a web page
2. Go to https://nhn.github.io/tui.editor/latest/tutorial-example15-editor-with-all-plugins
3. Paste content in editor
4. you see no markdown translation, only raw text.

## Expected behavior
I expect HTML content to be parse and transform into markdown syntax as README.md says :
* Copy and Paste : Paste anything from browser, screenshot, excel, powerpoint, etc.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Chrome
 - Version 81

**Comment by seonim-ryu** [comment]
@StephaneRavet I think this is normal behavior, not a bug. If you copy and paste the html data, it is correct that the html comes out as the WYSIWYG editor handles the html. However, the Markdown editor treats the Markdown syntax as a string and converts the Markdown text to Html to show in the preview. So, I think that the data pasted into the Markdown editor comes out as raw text.

**Comment by StephaneRavet** [comment]
Ok, i founded a work-around for my need : use a browser extension.
https://chrome.google.com/webstore/detail/copy-as-markdown/dgoenpnkphkichnohepecnmpmihnabdg

Thanks for reply and thanks for your great work ! 👏
