### ISSUE TITLE
[REACT] WYSIWYG mode is not usable for editing text

### ISSUE THREAD

**Issue by oguera** [nhn/tui.editor#1006]
## Describe the bug
When using the React Component within a minimal setup and the `initialEditType` is set to `wysiwyg` the Editor is loosing focus on every click. This means you can't edit text in the `wysiwyg` edit type.

## To Reproduce
1. Create a minimal React Component (in my case a functional component) with the Editor
2. choose `wysiwyg` as initialEditType in the tui editor component
3. start the application
4. click into editor
5. the editor will instantly loose it's focus again

## Expected behavior
The focus should stay and the user should be able to type.

## Desktop (please complete the following information):
 - OS: [Linux 18.04, macOS, Windows] - Tested on all of those devices
 - Browser [Chrome, Chromium, Firefox]
 - Version [latest]

## Additional context
Can someone reproduce the bug with the react wrapper? The demo in the docs seems to work fine (it's not the react wrapper though). https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-with-wysiwyg-mode

**Comment by chriskn** [comment]
I have the same issue when I use the WYSIWYG Editor inside a  React.Component class.

**Comment by seonim-ryu** [comment]
@oguera The image below is a test of [react-editor](https://github.com/nhn/tui.editor/tree/master/apps/react-editor) in a storybook. In this case, it cannot be reproduced.

![test](https://user-images.githubusercontent.com/18183560/83214122-c463c900-a19e-11ea-82b4-5271a377db90.gif)

However, looking at the comments below, it seems to be a problem when used inside `React.Component` class, can you show the React component code you used?

**Comment by chriskn** [comment]
Hi @seonim-ryu , 
@oguera and I figured out that the issue was related to another library and had nothing to do with the editor. This issue can be closed. Thank you for your support.
