### ISSUE TITLE
Unable to convert back Custom Container Syntax to markdown 

### ISSUE THREAD

**Issue by kishorethecoder** [nhn/tui.editor#101]
## Version
1.03

## Test Environment

Windows 10
## Current Behavior

i have requirement to add the custom container  for Info,warning && error and was successfully able   to added the container with the markdown-it-container plugin 
```js
        markdownInstance.use(markdowncontainer, 'InfoBox', {

            validate: function (params) {
                return params.trim().match(/^InfoBox/);
            },

            render: function (tokens, idx) {
                var m = tokens[idx].info.trim().match(/^InfoBox/);

                if (tokens[idx].nesting === 1) {
                    // opening tag 
                    return '<div class="infoBox alert alert-info"><div>Info</div><p>' + markdownInstance.utils.escapeHtml(m[1] || "") + '</p>\n';
                } else {
                    // closing tag 
                    return '</div>\n';
                }
            }, marker: ':'
        });
```
I have forked the tui-editor and customized it to add the required buttons which was raised in the ticket #91. And also, i  had managed to use the plugin in wysiwg mode by exposing the markdownit instance from the convertor

```js
 /**
 * get markdownit
 * @returns {markdownit} - markdownit instance
 * @memberof Convertor
 * @static
 */
  static getMarkdownit() {
    return markdownit;
  }
```
But , i'm facing the challenge on preserving the markdown syntax while switching from wysiwyg mode to markdown as div is getting removed from the html in wysiwyg
[819](https://github.com/nhnent/tui.editor/blob/ad983ec604b251b5b28efb09b503bcdf3ed824c7/src/js/wysiwygEditor.js#L819 ) in the getHtml method

## Expected Behavior

how to preserve the markdown syntax?

**Comment by sohee-lee7** [comment]
@kishorethecoder I'm sorry for late reply. Currently there is not way to preserve markdown syntax. I think when customize convertor, it need to prevent to removing tag that used for custom feature. For prevent to removing special tag, we have to implement about option like marking for tag. I will discuss this feature with my team members.
