### ISSUE TITLE
Disable automatic links in wysiwyg

### ISSUE THREAD

**Issue by dang-gun** [nhn/tui.editor#1017]
## Summary
워지웍스(wysiwyg) 모드에서 url 입력시 자동으로 링크로 변환되는 기능을 막고 싶습니다.

## Version
2.0

## Additional context
워지웍스(wysiwyg) 모드에서 url 입력했을때 자동으로 링크로 변환되는 기능을 막을 수 있는 옵션이 있나요?
도구모음을 사용한 링크 걸기만 허용하고 싶습니다.

마크다운 모드에서 url을 입력하면 링크로 변하지 않는데 이것을 워지웍스에서도 같은 동작이 되게 하고 싶습니다.

**Comment by seonim-ryu** [comment]
@dang-gun
> ⚠️ Please change the issue title and issue content to English so that other foreigners can confirm the issue.

I think you're trying to prevent the url from being converted to `a` tag when you enter the url and then hit enter in WYSIWYG. Currently, the editor does not provide an option to turn it off.
![wwe](https://user-images.githubusercontent.com/18183560/83825936-a30e5a00-a715-11ea-9998-f69528f831c2.png)
