### ISSUE TITLE
How to use the chart plug-in when the type is area or line

### ISSUE THREAD

**Issue by zhuyuyi** [nhn/tui.editor#1018]
## Summary
I like this library very much, and our team is using this library.
But I don't konw how to use the chart plug-in when the type is area or line.
It always prompts me invalid chart data.
So dear author, could you tell me how to use it when the type is area or line.
Can you give me an example？
Thanks.

## Version
2.1.0

**Comment by seonim-ryu** [comment]
@zhuyuyi
> But I don't konw how to use the chart plug-in when the type is area or line.

Are you talking about setting the chart's `type` option? In [this example](https://nhn.github.io/tui.editor/latest/tutorial-example06-editor-with-chart-plugin), would you like to change the type value to `line` or `area`?

![chart](https://user-images.githubusercontent.com/18183560/83827225-c090f300-a718-11ea-8cb6-d9c823110e0d.png)

**Comment by zhuyuyi** [comment]
Thank you.
