### ISSUE TITLE
Stored XSS in WYSIWYG mode only while removing blockquotes 

### ISSUE THREAD

**Issue by NkxxkN** [nhn/tui.editor#1021]
## Describe the bug

While auditing a client using tui editor in WYSIWYG only mode, I found a persistent XSS which requires user interaction.

It is different from https://github.com/nhn/tui.editor/issues/703 because it can be triggered by removing an input from another user, and not from copy/pasting a payload. This means that it can be leverage as a stored XSS. 

The payload is a little bit different too:
`<svg><svg onload=alert('xss')>` is enough to trigger the XSS.

The code vulnerable is the following: 
https://github.com/nhn/tui.editor/blob/master/apps/editor/src/js/wwCodeBlockManager.js#L354

`firstLine` is not sanitized properly.

## To Reproduce
1. Create blockquotes.
2. Copy `<svg><svg onload=alert('xss')>`.
3. `[CURSOR HERE]<svg><svg onload=alert('xss')>`.
4. Press delete key.
5. XSS is triggered

## Expected behavior

No XSS :)

## Screenshots

![tui editor before](https://user-images.githubusercontent.com/5072452/83628111-476a9200-a598-11ea-9af1-a85eca02e31b.gif)

## Desktop:
 - OS: Mac
 - Browser:
  - Chrome: 81.0.4044.138
  - Firefox: 76.0.1

**Comment by seonim-ryu** [comment]
@NkxxkN Thanks for reporting the bug. Test the PR and I'll merge if there is no problem.

**Comment by NkxxkN** [comment]
Sorry I forgot to link the PR https://github.com/nhn/tui.editor/issues/1022
