### ISSUE TITLE
 React Editor: code-syntax-highlight plugin doesn't work with next ssr

### ISSUE THREAD

**Issue by WinmezzZ** [nhn/tui.editor#1034]
## Describe the bug
React Editor: code-syntax-highlight plugin doesn't work with next ssr

## To Reproduce
1. Editor.tsx
 ```tsx
import { NextComponentType } from 'next'
import { Editor } from '@toast-ui/react-editor'
import colorSyntaxPlugin from '@toast-ui/editor-plugin-color-syntax'
import codeSyntaxHighlightPlugin from '@toast-ui/editor-plugin-code-syntax-highlight'
import hljs from 'highlight.js'

const EditorComponent: NextComponentType = () => {
  return (
    <Editor
      usageStatistics={false}
      useCommandShortcut={true}
      previewStyle="vertical"
      height="400px"
      initialEditType="markdown"
      initialValue="hello"
      plugins={[codeSyntaxHighlightPlugin.bind(hljs), colorSyntaxPlugin]}
    />
  )
}

export default EditorComponent
```
2. index.tsx
```tsx
import { NextPage } from 'next'
import dynamic from 'next/dynamic'

const EdiorComponent = dynamic(() => import('./Editor'), { ssr: false })

const EditPage: NextPage = () => {
  return (
    <div>
      <h2>EditPage</h2>
      <EdiorComponent />
    </div>
  )
}

export default EditPage
```
3. In fact, you can see editor.tsx file has no srr from index.ts => `{ ssr: false }`, so it was rendered by client, then code highlight still not work but color-syntax plugin works well, then I tried all codes on a new client react app project,all of them works
code highlight not work

## Expected behavior
code highlight works

## Screenshots
next app
![image](https://user-images.githubusercontent.com/40154766/84053507-98d5af80-a9e4-11ea-8ace-9f28fa214962.png)

create-react-app
![image](https://user-images.githubusercontent.com/40154766/84053616-bf93e600-a9e4-11ea-8078-7d905b2dd5b9.png)

Editor code
![image](https://user-images.githubusercontent.com/40154766/84053954-3df08800-a9e5-11ea-991d-f023452b26dd.png)

## Desktop (please complete the following information):
 - OS: Windows
 - Browser chrome 
 - Version  83

## Additional context
Fllow those screenshots will found it has diffirent property `codeBlockLanguages` of thier's instance,
one is empty array, one is all hljs languages string array, they all rendered by client but show diffirent result, the problem maybe from `next` ? Need your help thanks!

**Comment by seonim-ryu** [comment]
@WinmezzZ First, I have a question. Can you check if the same problem occurs even when used like this? I wonder why you used `bind`.
```js
<Editor
  // ...
  plugins:{[[codeSyntaxHighlight, {hljs }]]}
/>
```
And if possible, can you debug how the result will be when I run the following code?

> https://github.com/nhn/tui.editor/blob/eb0ba4f6fb6ac74f099913e48da66710fb3fee48/plugins/code-syntax-highlight/src/js/helper.js#L13

**Comment by WinmezzZ** [comment]
Yeah! I tried id again and it works. 

The main reasons for this problem maybe I refered this issue of code[https://github.com/nhn/tui.editor/issues/909](https://github.com/nhn/tui.editor/issues/909), and another reason may be that I had used typescript and were get type errors when using sample codes. 

![image](https://user-images.githubusercontent.com/40154766/84489621-8acdaa80-acd4-11ea-9537-7006466551ce.png)
I resolved it by as never

That is my fault, and suggest you can update the types files. Thank you in the end.

**Comment by seonim-ryu** [comment]
@WinmezzZ I got it. The type for the `hljs` option in the plugin is missing. Thanks for reporting the issue. I'll try to fix it soon.

**Comment by bum-hyun** [comment]
<img width="1088" alt="스크린샷 2020-11-16 오후 12 36 17" src="https://user-images.githubusercontent.com/50093439/99210167-70aa7200-2808-11eb-8510-97734efadfdb.png">

예시대로 했는데, 하이라이팅이 안되네요..

**Comment by bum-hyun** [comment]
> <img alt="스크린샷 2020-11-16 오후 12 36 17" width="1088" src="https://user-images.githubusercontent.com/50093439/99210167-70aa7200-2808-11eb-8510-97734efadfdb.png">
> 
> highlight plugin doesn't work on next.
> 
> <img alt="스크린샷 2020-11-16 오후 12 43 00" width="1341" src="https://user-images.githubusercontent.com/50093439/99210490-486f4300-2809-11eb-9852-b5fa043dc748.png">

Ok...I missed import css
`import "highlight.js/styles/github.css";` then, It works
