### ISSUE TITLE
Newlines not returned in getMarkdown

### ISSUE THREAD

**Issue by zabeloliver** [nhn/tui.editor#1038]
## Version
 * @toast-ui/editor
 * @version 2.1.2 | Wed May 13 2020

## Test Environment
Chrome 83.0, Editor in WYSIWYG-Mode

## Current Behavior
Writing some markdown with new-lines, like this.
A
**B**
_C_
~~D~~

Lorem Ipsum
dolor....

## Expected Behavior
Using this in a form by getting the content via ```getMarkdown();```. Expected behaviour would be to get new-lines encoded as "\n"

## Actual Behaviour
It returns a string without new-lines as a single string ```A**B**_C_~~D~~Lorem Ipsum dolor....```.

**Comment by seonim-ryu** [comment]
@zabeloliver I think it returns well because it contains newline characters? Not like this? Can you give me a screenshot?
![result](https://user-images.githubusercontent.com/18183560/84460584-4840a980-aca5-11ea-9882-c94e7b96e60e.gif)

**Comment by zabeloliver** [comment]
Hi, 
thanks for your reply! I figured it out. I'm using the editor in a form and on submit i attached editor.getMarkdown() to an hidden input field. I did not think about, that an input field does not take newlines, so i replaced it by an hidden textarea and now it is working as expected.
Thank you!
