### ISSUE TITLE
getHtml() can't get the highlight style code.

### ISSUE THREAD

**Issue by codingcn** [nhn/tui.editor#1042]
## Describe the bug
```
alert(this.$refs.editor.invoke('getHtml'))
```

**As shown in the figure, I can't get the complete code highlight style through getHtml(), I think this is abnormal.**

Some styles are missing`hljs-meta` `hljs-keyword` `hljs-string`...

![getHtml()](https://user-images.githubusercontent.com/16743078/84248472-0b0cd800-ab3c-11ea-9922-47e5e7dc1a3a.png)

## Desktop (please complete the following information):
 - OS:linux
 - Browser chrome

**Comment by seonim-ryu** [comment]
@codingcn It's right that only the data that goes inside the code block comes out. Because the tags you're talking about are tags created through the renderer.

![api-result](https://user-images.githubusercontent.com/18183560/84461279-06b0fe00-aca7-11ea-98b4-11730e7e8d90.png)

**Comment by codingcn** [comment]
@seonim-ryu How can I get the complete html after rendering.

**Comment by seonim-ryu** [comment]
@codingcn What is the required purpose? I think there is no way other than the way you get it directly from DOM when the `change` event fires. 🤔 

Or maybe when I look at the screenshot, you are using `highlight.js` and is there any way to get it through the [API of the `hljs` instance](https://highlightjs.readthedocs.io/en/latest/api.html)?

**Comment by codingcn** [comment]
I am developing an article editor and want to save the final article html (including these tags `hljs-meta` `hljs-keyword` `hljs-string`) directly into the database instead of markdown. I do not want to rely on `highlight.js` when displaying One extra rendering, I think this is unnecessary.

**Comment by codingcn** [comment]
I finally solved the problem successfully with the following code, I think this official getHtml() should generate these tags( `hljs-meta hljs-keyword hljs-string`) by default

```js
let sourceHtml = this.$refs.editor.invoke('getHtml')

let tmpDOM = new DOMParser().parseFromString(sourceHtml, 'text/html').body

tmpDOM.querySelectorAll('pre code').forEach((block) => {
     hljs.highlightBlock(block);
});
                
let contentHtml = tmpDOM.innerHTML
console.log(contentHtml);
```

**Comment by Jeffryhui** [comment]
> I finally solved the problem successfully with the following code, I think this official getHtml() should generate these tags( `hljs-meta hljs-keyword hljs-string`) by default
> 
> ```js
> let hljs = require('highlight.js');
> let sourceHtml = this.$refs.editor.invoke('getHtml')
> let tmpDOM = new DOMParser().parseFromString(sourceHtml, 'text/html').body
> 
> tmpDOM.querySelectorAll('pre code').forEach((block) => {
>      hljs.highlightBlock(block);
> });
>                 
> let contentHtml = tmpDOM.innerHTML
> console.log(contentHtml);
> ```

没在框架中使用。咋获取到带高亮标签的内容

**Comment by codingcn** [comment]
> > I finally solved the problem successfully with the following code, I think this official getHtml() should generate these tags( `hljs-meta hljs-keyword hljs-string`) by default
> > ```js
> > let hljs = require('highlight.js');
> > let sourceHtml = this.$refs.editor.invoke('getHtml')
> > let tmpDOM = new DOMParser().parseFromString(sourceHtml, 'text/html').body
> > 
> > tmpDOM.querySelectorAll('pre code').forEach((block) => {
> >      hljs.highlightBlock(block);
> > });
> >                 
> > let contentHtml = tmpDOM.innerHTML
> > console.log(contentHtml);
> > ```
> 
> 没在框架中使用。咋获取到带高亮标签的内容

```
let sourceHtml = this.editor.getHtml()
```

**Comment by Jeffryhui** [comment]
> > > I finally solved the problem successfully with the following code, I think this official getHtml() should generate these tags( `hljs-meta hljs-keyword hljs-string`) by default
> > > ```js
> > > let hljs = require('highlight.js');
> > > let sourceHtml = this.$refs.editor.invoke('getHtml')
> > > let tmpDOM = new DOMParser().parseFromString(sourceHtml, 'text/html').body
> > > 
> > > tmpDOM.querySelectorAll('pre code').forEach((block) => {
> > >      hljs.highlightBlock(block);
> > > });
> > >                 
> > > let contentHtml = tmpDOM.innerHTML
> > > console.log(contentHtml);
> > > ```
> > 
> > 
> > 没在框架中使用。咋获取到带高亮标签的内容
> 
> ```
> let sourceHtml = this.editor.getHtml()
> ```

直接editor.getHtml()拿到的还是不带highlight的class类

**Comment by Jeffryhui** [comment]
@codingcn 
代码大概是这样的
```js
import Editor from '@toast-ui/editor';
import '@toast-ui/editor/dist/i18n/zh-cn';
import 'highlight.js/styles/solarized-dark.css';
import codeSyntaxHighlightPlugin from "@toast-ui/editor-plugin-code-syntax-highlight";
import colorSyntaxPlugin from "@toast-ui/editor-plugin-color-syntax";
import hljs from 'highlightjs'
const editor = new Editor({
    el: document.getElementById('post-content'),
    height: '500px',
    initialEditType: 'markdown',
    previewStyle: 'vertical',
    initialValue:'',
    plugins:[[codeSyntaxHighlightPlugin,{hljs}],colorSyntaxPlugin],
    language:'zh_CN',
    name:'post_content',
    events:{
        change:function(){
            $(".post-content-ele").val(editor.getHtml())
            $("#post-markdown-ele").val(editor.getMarkdown())
        }
    }
});
```
`editor.getHtml()`拿到的并没有`( hljs-meta hljs-keyword hljs-string)`这些标签
