### ISSUE TITLE
HTML Injection

### ISSUE THREAD

**Issue by bananphone12** [nhn/tui.editor#1043]
## Describe the bug
HTML Injection

## To Reproduce
1. Go to any field that accepts user input
2. Paste: `"><img src="https://i.imgur.com/WTQw28G.png" height=200>`
3. Save text field, and refresh the page, image will now be embedded in page.
4. See screenshot

## Expected behavior
HTML characters would be escaped or sanitized and image would not load in the DOM.

## Screenshots
![2020-06-10_9-03-19](https://user-images.githubusercontent.com/31215334/84288669-198ccc80-ab07-11ea-837a-6b321bb8693e.png)

**Comment by seonim-ryu** [comment]
@bananphone12 I think this is normal operation. Maybe it was pasted into the Markdown editor. In this case, the string of the `img` tag after the `">` character is parsed as html and the image is rendered properly.

![mde](https://user-images.githubusercontent.com/18183560/84461752-3280b380-aca8-11ea-9109-3edf1edcf426.png)

**Comment by bananphone12** [comment]
@seonim-ryu Thanks for the update, I thought this might be expected behavior with rich text fields like markdown. Figured I'd report it anyway and should have mentioned this in bug report.
