### ISSUE TITLE
Will Chart,UML or other plug-ins be used in WYSIWYG in the future

### ISSUE THREAD

**Issue by zhuyuyi** [nhn/tui.editor#1053]
## Summary
Will Chart,UML or other plug-ins be used in WYSIWYG in the future?
Is there a way to insert custom plug-ins in WYSIWYG？

## Version
2.1.0

## Additional context
If it is similar to Markdown in WYSIWYG, it is more perfect to use custom plug-ins.

**Comment by seonim-ryu** [comment]
@zhuyuyi The custom plugin you're talking about seems to say this. Would you like to check it out?

> https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/plugins.md#creating-the-user-plugin

**Comment by zhuyuyi** [comment]
![1592535559(1)](https://user-images.githubusercontent.com/41852761/85092355-1d61d280-b21c-11ea-85c1-33a4be32e329.jpg)
You see this photo. Chart can't be rendered.
Is there any way to render it?

> @zhuyuyi The custom plugin you're talking about seems to say this. Would you like to check it out?
> 
> > https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/plugins.md#creating-the-user-plugin

**Comment by zhuyuyi** [comment]
![1592535559(1)](https://user-images.githubusercontent.com/41852761/85092658-c27cab00-b21c-11ea-8031-3afd145ef542.jpg)
