### ISSUE TITLE
Whitelist HTML tags

### ISSUE THREAD

**Issue by Fl0ux** [nhn/tui.editor#1058]
## Summary
I would like to whitelist some HTML tags so they can be rendered in the Viewer.

## Version
2.2.0

## Additional context
The main idea is to have a simple way to render a YouTube video. If I paste a YouTube link in the WYSIWYG editor, I will then transform it as an iframe using PHP. After that, when using the Viewer, I would like my iframe to be rendered.

Is there a way for doing this ? Or maybe it is a wrong way to do it... thanks for your help !

**Comment by seonim-ryu** [comment]
@Fl0ux I think the `customHTMLSanitizer` option will allow you to use the tags you need. By default, the Editor is sanitizing unnecessary tags, but using this option will not sanitize. So you can use tags like `iframe` that you need. Below is a usage example. (Note: Example of creating a viewer using the Editor's factory function)

```js
import Editor from '@toast-ui/editor';

const editor = Editor.factory({
  el: document.querySelector('#editor'),
  height: '500px',
  viewer: true,
  initialValue: '<iframe></iframe>',
  customHTMLSanitizer: html => html
});
```
However, it should be noted that if you use this option, you have to handle the tags with the XSS vulnerability, and tags like `iframe`` may disappear when you switch to WYSIWYG mode in the Editor.

**Comment by Fl0ux** [comment]
Thanks, it is working ! I added DOMPurify to avoid XSS problems.
