### ISSUE TITLE
whether setTooltip method is supported

### ISSUE THREAD

**Issue by robinv8** [nhn/tui.editor#1069]
## Summary
for toolbaritem, Is the setTooltip method not supported now?

## Version
v 2.2.0

**Comment by seonim-ryu** [comment]
@robinv8 The `setTooltip` API was not officially provided before, but how did you use it? 
Can you give me an example? Currently, when setting a tooltip on a toolbar button, the tooltip text can be set using `tooltip` in the options below.

> Options: https://nhn.github.io/tui.editor/latest/toolbarButtonOptions
> Example: https://nhn.github.io/tui.editor/latest/tutorial-example19-customizing-toolbar-buttons

**Comment by robinv8** [comment]
@seonim-ryu Thanks, i try
