### ISSUE TITLE
How can I inject some preprocess code to the to-mark renderer for some custom markdown syntax without use of plugins?

### ISSUE THREAD

**Issue by zifnab87** [nhn/tui.editor#1074]
Hi! Thanks for the great work! 

I would like to add some custom syntax highlighting that should appear only on the viewer and not in the editor. E.g I would like to color some links the same color when they are in the same curly brace set `{ [a link](url) [another link](url) }`. Or some times I want to replace a link with some other html based on some requirements I have. Can I have access to the render / parser and how easy it is to customize Tui-editor and add custom Markdown without the use of plugins? Is there a similar approach to html-to-markdown converter found in https://github.com/nhn/tui.editor/issues/1066 that works in the other direction? 
Possibly related to https://github.com/nhn/tui.editor/issues/615 -
I also found a codesandbox  https://codesandbox.io/s/6wq6j that has an example that could work although it is for version 1.4" - Although there is an option `customConvertor` I passed what I saw in the example but it seems that the API has changed.

Thanks in advance for any help!
Michail

**Comment by seonim-ryu** [comment]
@zifnab87 I think the feature you are trying to implement is related to this issue #998 . If the markdown data is set to `{ [a link](url) [another link](url) }`, a node is created with `paragraph`. As commented in the link below, when rendering `paragraph` using the `customHTMLRenderer` option, I think you can find and replace the character corresponding to the brace(`{ }`).

> https://github.com/nhn/tui.editor/issues/998#issuecomment-635844253

You can read more about the Custom Html Renderer [here](https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/custom-html-renderer.md).

**Comment by zifnab87** [comment]
Hi @seonim-ryu! Thanks for the comment!- here is an example of what I am trying to do.. I need to have access to the whole markdown of the left so I can customize the html being created but at the same time I need to be able to fallback to the default behavior. I want to be able to do what is pictured without the `rel` plugin I made. Does the approach you propose lead to each of the paragraphs to be processed separately? 

![image](https://user-images.githubusercontent.com/526062/87096286-2b1edc80-c24b-11ea-8caf-9ef0fe16f30a.png)
