### ISSUE TITLE
how to render html tag in wysiwyg mode?

### ISSUE THREAD

**Issue by cs-ajay-chakkar** [nhn/tui.editor#1079]
@seonim-ryu 

How to support html tag and markdown syntax rendering in wysiwyg mode?

I already have text in html and want to give support with for markdown and html in wysiwyg mode.
I am trying to add html tags but it's showing as it is in wysiwyg mode.Also markdown syntax is not rendering.

I was trying like this -
```
<h1>Heading 1</h1>

**bold** 
```

but in wysiwyg mode it rendering as it is.

Expected output is - 
# Heading 1

**bold**

Is there any way to render it while editing?

**Comment by seonim-ryu** [comment]
@cs-ajay-chakkar I think the usability you understand is wrong. The WYSIWYG Editor is for users who are not familiar with markdown syntax. So, if you type markdown syntax or html in the WYSIWYG editor, it is recognized as text. If you want to style it, you have to use the toolbar in WYSIWYG

**Comment by jmch1220** [comment]
> ****a
a
a
a
a
a
a
a

a
