### ISSUE TITLE
How to render HTML tags in markdown mode

### ISSUE THREAD

**Issue by MythosMa** [nhn/tui.editor#1082]
## Summary
I have a requirement that mark some words to other colors. I used <span> tag to deal it. But in markdown mode, it will be writed in content like this:
```
you are a <span style="cursor: pointer; text-decoration: line-through; font-weight: bold; color: rgb(255, 110, 88);"> clever</span> boy
```
![image](https://user-images.githubusercontent.com/30307817/86904334-2242e380-c143-11ea-977f-26c42150f00f.png)

This works correctly in Preview mode.

I know "wysiwyg" mode supports this requirement. But I want know how it works in markdown mode.

Thank you!

**Comment by seonim-ryu** [comment]
@MythosMa Did you ask how the text entered in the markdown editor is displayed in the preview? If it is correct, when entering text corresponding to the html tag in the markdown editor such as `<span>`, parse this text before showing it in the preview area and convert it `dom` if it is valid html. The preview area shows the `dom` created like this.

I am not sure if this is the answer you want. 🤔

**Comment by MythosMa** [comment]
@seonim-ryu 
Sorry for my question.
I mean if I have  text like " This is a red apple "。I want to hightlight the word "red", so I make text " This is a <span style="background: #FF0000">red</span> apple " and call setMarkdown() to put in editor.
Then the text will be rendered as this:
![image](https://user-images.githubusercontent.com/30307817/87909193-5ea70580-ca9a-11ea-96ae-c565cc9951f8.png)

But my request is the text will be rendered like this in markdown editor mode ( not in wysiwyg mode and preview mode) :
![image](https://user-images.githubusercontent.com/30307817/87909323-a037b080-ca9a-11ea-9cbc-6994fa92c722.png)

I tried to change dom for this request. But it destoryed the editor and I couldn't put currect text in editor.

So I think that is it not support for my request.

Thanks!

**Comment by kgirma** [comment]
Running into the same issue. We just want to set html using the setHTML() function but each time we do that the ```<tags>``` get removed with sanitization.
