### ISSUE TITLE
How to prevent some html tags to get removed from sanitizer

### ISSUE THREAD

**Issue by JensUweB** [nhn/tui.editor#1086]
## Summary
As described in #684 you implemented an option to prevent specific html tags from getting sanitized, right?
But this option seems to not exist in EditorOptions, so how do I use it?

## Screenshots
![allowedTagsToSanitize_not_working](https://user-images.githubusercontent.com/58864964/87040065-6a6c0f80-c1f0-11ea-9d70-c250b507e6a5.JPG)

## Version
@toast-ui/editor: 2.2.0

## Additional context
My team and I need an option to prevent specific html tags from getting removed by the sanitizer, so that we can use html inside the editor e.g. to position or style elements. We need to get something like this to work in markdown & wysiwyg: `<div class="text-center">my awesome centered text</div>`

I also tried to disable the sanitizer completely with `useDefaultHTMLSanitizer: false`, but this has no effect at all. Your sanitizer still removes every bit of html like crazy.

We are working on an big content management system (wich is going well so far) and your editor is a mission critical part. We need to remove your editor completely from our project, if we don't get this to work somehow.

**Comment by JensUweB** [comment]
Never mind. Just use `<span class="my-global-class">my text</span>` for custom styling. Oh and I found out that the sanitizer has nothing to do with removing html tags like `<div>` on my own.

**Comment by kgirma** [comment]
@JensUweB Can you elaborate on this? We're trying to add an underline feature with the <u> tag like this <u>UNDERLINED</u> but each time we set it using the setMarkdown() function it removes the tag. If you do this on the actual markdown editor it works just fine.

We tried setMarkdown, setHTML, Replace Text and so on... Thanks in advance.

**Comment by Rahulsingh9521** [comment]
I am using `<center>` tag in the markdown and when I am extracting the html through `getHTML()` to save in DB some how `<center> `tag is getting replaced by `<p>` tag 

how we can prevent the replacement of `<center>` tag
