### ISSUE TITLE
2.2.0 에디터 커스텀 플러그인 미리보기 문제

### ISSUE THREAD

**Issue by hiphop5782** [nhn/tui.editor#1088]
## Summary
커스텀 플러그인 미리보기 제한 설정

## Screenshots
![image](https://user-images.githubusercontent.com/10623781/87107737-84166100-c29b-11ea-94c6-69345b292ea1.png)

## Version
2.2.0

## Additional context

현재 toastui editor 1.4.8 버전에서 2.2.0으로 마이그레이션 진행중입니다.
커스텀 플러그인 6개를 제작하여 사용하고 있으며 대부분의 기능이 2.2.0에서도 정상적으로 작동하고 있습니다.
한 가지 문제점이 발견되었고, 그 현상은 다음과 같습니다.

2.x 에서 markdown 작성 시 구문 강조 기능이 개선되었는데 이 부분이 커스텀 플러그인과 호환되지 않는 현상이 발생하고 있습니다.[참조링크](https://ui.toast.com/weekly-pick/ko_20200318/#%EB%8D%94-%EC%A0%95%ED%99%95%ED%95%B4%EC%A7%84-%EA%B5%AC%EB%AC%B8-%EA%B0%95%EC%A1%B0)

따라서 첨부스크린샷 1번처럼 커스텀 플러그인의 미리보기 화면이 나오는 현상이 발생하고 있습니다.
또한 커스텀 플러그인 블록에 구문을 작성할 경우 스크롤이 자동으로 이동하는 현상이 발생하고 있습니다.
뷰어에서는 정상적으로 작동을 하고 있습니다.

이슈에서 검색을 해 보았으나 이와 관련된 내용을 찾지 못하여 질문을 드립니다.
ToastUI Editor의 markdown 모드에서 미리보기를 전체 또는 선택적으로 제한할 수 있습니까?

감사합니다

**Comment by seonim-ryu** [comment]
@hiphop5782 If possible, I would like you to add the issue in English.

It's hard to fix the issue just by looking at this. I need to know what custom plugin you are writing and using so I can see if there is a problem with the Editor. Can you give me code that can be checked with JSFiddle or CodePen?

And the function to limit the preview is that you want to resize the preview area? If it's right, there are no options, but I think you should solve it using css instead.
