### ISSUE TITLE
How to customize an underline toolbar button?

### ISSUE THREAD

**Issue by bocanhcam** [nhn/tui.editor#1097]
Seem like we can use underline text with this tag`<ins>`. (I don't know if this is a right way or not).
So how can I custom a toolbar button to add the tag

**Comment by seonim-ryu** [comment]
@bocanhcam First, to customize the toolbar button, refer to the example page below.

> https://nhn.github.io/tui.editor/latest/tutorial-example19-customizing-toolbar-buttons

And I think you can use it by registering the command to add the `<ins>` tag you said.
```js
const editor = new Editor({ ... });

editor.addCommand('wysiwyg', { // register command
  name: 'underline',
  exec() {
    editor.setHtml('<ins>foo</ins>');
  }
});

editor.exec('underline'); // execute command
```
Instead, there is something to watch out for. When converting to markdown, there is no markdown syntax, so you should consider how to handle this.
