### ISSUE TITLE
List rendering in table gets broken when switching back and forth from WYSIWYG to markdown view

### ISSUE THREAD

**Issue by arnoldgreving** [nhn/tui.editor#1099]
## Describe the bug
When creating a table with a list inside, then the rendering of the lists gets broken after switching from the Markdown to the WYSISYG views. See the examples below.

The problem occurs with editor version 2.2.0

I'm using the Table Merged Cell plugin

## To Reproduce
1. Create a table, for instance:
   ![image](https://user-images.githubusercontent.com/12486907/87428619-e5fc0100-c5e2-11ea-8447-16370943b0b7.png)

2. Then click on the **Markdown** link at the bottom of the editor.
    ![image](https://user-images.githubusercontent.com/12486907/87429028-7fc3ae00-c5e3-11ea-845a-9c9917985395.png)

3. Then click on the **WYSIWYG** link at the bottom of the editor.
    ![image](https://user-images.githubusercontent.com/12486907/87429472-1f813c00-c5e4-11ea-8d8c-8262139fbd90.png)

4. Then click on the **Markdown** link at the bottom again.
    ![image](https://user-images.githubusercontent.com/12486907/87429569-43448200-c5e4-11ea-9915-97cb75e22840.png)

## Expected behavior
In all cases the markdown text should be unchanged when switching between views.
![image](https://user-images.githubusercontent.com/12486907/87428619-e5fc0100-c5e2-11ea-8447-16370943b0b7.png)

## Desktop (please complete the following information):
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 78.01

**Comment by seonim-ryu** [comment]
@arnoldgreving I think this issue is related to the issue below. This will be fixed and released this week.

> https://github.com/nhn/tui.editor/issues/1059

**Comment by arnoldgreving** [comment]
> @arnoldgreving I think this issue is related to the issue below. This will be fixed and released this week.
> 
> > #1059

@seonim-ryu Just back from my holiday. I've upgraded to version 2.3.1 and the problem is gone. Thank you for fixing it!
