### ISSUE TITLE
how to use plugins?

### ISSUE THREAD

**Issue by inVisement** [nhn/tui.editor#1103]
how would you get code syntax highlight working through cdn?
It seems referenced files are broken.
Thanks

**Comment by seonim-ryu** [comment]
@inVisement Please check the documents below.
> Using Plugin : https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/plugins.md
> Using `code-syntax-highlight` : https://github.com/nhn/tui.editor/tree/master/plugins/code-syntax-highlight

**Comment by Ats1999** [comment]
> @inVisement Please check the documents below.
> 
> > Using Plugin : https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/plugins.md
> > Using `code-syntax-highlight` : https://github.com/nhn/tui.editor/tree/master/plugins/code-syntax-highlight

Well, i followed the same syntax to include plugin in my editor, The error i got in react is.
```js
 Line 136:32:  Parsing error: Unexpected token

  134 |                         usageStatistics={false}
  135 |                        ref={this.editorRef}
> 136 |                        plugins:[chart, uml]
      |                                ^
  137 |                        onChange={this.getTextContent}
  138 |                     />
  139 |                 </div>
```

# Using the way array can be passed as props
```js
plugins={[chart, uml]}
```
i got error.
