### ISSUE TITLE
Is there any ordered list options for indentation numbered list?

### ISSUE THREAD

**Issue by fransyosuaa** [nhn/tui.editor#1115]
Hello, quick question, is there any options for change ordered list with indentation?

As for now, even thou I use indentation (tab), it will make new ordered list with 1, 2, 3 order list (see below)

![image](https://user-images.githubusercontent.com/50573124/88005126-d32d8300-cb32-11ea-8aad-ea3c68c56201.png)

What I want, is using a, b, c for first indentation, and then i, ii, iii, for second indentation.

Is that possible with tui.editor? I'm using version 2.2.0 btw.

**Comment by seonim-ryu** [comment]
@fransyosuaa Currently, it does not provide the function. According to the markdown specification, only numbers can be used in ordered lists.

> https://spec.commonmark.org/0.29/#lists

**Comment by fransyosuaa** [comment]
.
