### ISSUE TITLE
Bind one toolbar to multiple editors

### ISSUE THREAD

**Issue by mvind** [nhn/tui.editor#1125]
Hi everyone! 

Suppose I wanted to multiple distinct editors on a page, but only one toolbar for the whole page. 
How could I build this? My naive idea would be to conditional render each toolbar by looking at which editor is focused. 

Or can you use one editor and style it in a way such that it appears as multiple distinct editors? 

Thanks for reading, and I hope my question make sense! 
/mvind

**Comment by chrisj74** [comment]
+1 Be interested in understanding how this could be done.

**Comment by seonim-ryu** [comment]
@mvind I have a question. Is the feature you described like the image below?

![multi](https://user-images.githubusercontent.com/18183560/89601208-f1b7ac00-d89e-11ea-9243-e653ebec84a5.png)

If this is correct, I think you can implement the toolbar yourself and use the Editor's [`getInstances()`](https://nhn.github.io/tui.editor/latest/ToastUIEditor#getInstances) API to get an instance of each editor and then [execute the command](https://nhn.github.io/tui.editor/latest/tutorial-example18-using-command). (I haven't tested it)
