### ISSUE TITLE
XSS Reflected Grab Cookie

### ISSUE THREAD

**Issue by RamadhanR** [nhn/tui.editor#1127]
## Describe the bug
The non-persistent (or reflected) cross-site scripting vulnerability is by far the most basic type of web vulnerability. These holes show up when the data provided by a web client, most commonly in HTTP query parameters (e.g. HTML form submission), is used immediately by server-side scripts to parse and display a page of results for and to that user, without properly sanitizing the content. the cookies obtained allow hackers to log in without using an account, obviously this is very dangerous

## To Reproduce
payload : </script><script>alert(1)</script>
1. Go to 'https://www.nhn.com/en/os/subOurService.nhn?cat=207&no=93'
2. And i add payload XSS to url
3. tara, XSS Reflected Bug is visible
![image](https://user-images.githubusercontent.com/28753336/88550811-f8a90980-cfd6-11ea-9549-e92ef9b1374f.png)
5. grab cookie, i use payload " </script><script>alert(document.cookie)</script> " and enter
![image](https://user-images.githubusercontent.com/28753336/88552222-b08ae680-cfd8-11ea-885f-6c402709b1d6.png)

Thank you

## Expected behavior
I hope this bug will be resolved soon, so there is no data theft or other allotment

## Desktop (please complete the following information):
 - OS: [Window 10 Home]
 - Browser [Chrome]
 - Version [None]

**Comment by seonim-ryu** [comment]
@RamadhanR First of all, this is not an editor issue, but thanks for reporting. It looks like a serious problem and I'll let the person who manages it handle it.

**Comment by seonim-ryu** [comment]
This issue was delivered to the team managing the site above, and is not an editor issue, so it is closed.

**Comment by RamadhanR** [comment]
hi @seonim-ryu 
Can you help me? I want something for my hard work finding these bugs, if possible
I would be very grateful <3
thanks for the response

**Comment by RamadhanR** [comment]
my mother is sick, I really need money
