### ISSUE TITLE
Getting  TypeError: o.a.createRef is not a function  while rendering the component.

### ISSUE THREAD

**Issue by Ats1999** [nhn/tui.editor#1128]
```
// this error i am getting on the browser's console.
TypeError: o.a.createRef is not a function
```
## Summary
I have installed this editor using *npm*.  I got its error while rendering the component.
I have just followed the code, as of npm website.

# Code
```js
import 'codemirror/lib/codemirror.css';
import '@toast-ui/editor/dist/toastui-editor.css';

import { Editor } from '@toast-ui/react-editor';

class MyComponent extends React.Component {
  editorRef = React.createRef();

  handleClick = () => {
    this.editorRef.current.getInstance().exec('Bold');
  };

  render() {
    return (
      <>
        <Editor
          previewStyle="vertical"
          height="400px"
          initialEditType="markdown"
          initialValue="hello"
          ref={this.editorRef}
        />
        <button onClick={this.handleClick}>make bold</button>
      </>
    );
  }
}
```

# Error

## Screenshots
<a href="https://github.com/Ats1999/Assingment/blob/master/Screenshot%20(306).png">Issue</a>

## Version
```
"tsutils": "^3.17.1"
"react": "^16.13.1"
"react-dom": "^16.13.1"
"react-scripts": "3.4.1"
```

**Comment by Ats1999** [comment]
Kindly help me.

**Comment by seonim-ryu** [comment]
@Ats1999 I cannot reproduce. It seems to be a React issue, can you give me the React's version installed on your local?

**Comment by bdevg** [comment]
> @Ats1999 I cannot reproduce. It seems to be a React issue, can you give me the React's version installed on your local?

React version: ^16.13.1

But, when I write same code on code sandbox the. It is working fine.

**Comment by Ats1999** [comment]
> @Ats1999 I cannot reproduce. It seems to be a React issue, can you give me the React's version installed on your local?

Ya. My react version is also ^16.13.1.

**Comment by seonim-ryu** [comment]
@Ats1999 The version I was talking about was asking to check in `package-lock.json`.  The version installed on your local machine. 🤔
