### ISSUE TITLE
`getChildrenText()` doesn't account for indentation

### ISSUE THREAD

**Issue by derek-knox** [nhn/tui.editor#1133]
https://github.com/nhn/tui.editor/blob/5a6772fe60dda56689e38c0d2fa914e516f1365a/libs/toastmark/src/html/render.ts#L141 `getChildrenText()` doesn't account for indentation. I have a few questions:
1. @dongwoo-kim [Is this intentional](https://github.com/nhn/tui.editor/blame/5a6772fe60dda56689e38c0d2fa914e516f1365a/libs/toastmark/src/html/render.ts#L141)? Can you add any context?
    - Currently we're using a custom `getChildrenTextWithIndentation()` to account for the lost indentation (snippet below)
1. Is there an existing method in Toast UI that takes a Toastmark AST node as an argument and returns the markdown with indentation preserved?

```javascript
const getChildrenTextWithIndentation = (parentNode, { options: { softbreak } }) => {
  const buffer = [];
  const walker = parentNode.walker();
  const { lineOffsets } = parentNode;
  let event = walker.next();
  let lineCount = 0;

  while (event) {
    const { node } = event;

    // TODO need to account for various inline types like anchor links
    if (node.type === 'text') {
      const indent = ' '.repeat(lineOffsets[lineCount]);
      const line = `${indent}${node.literal}`;
      buffer.push(line);
      lineCount += 1;
    }

    event = walker.next();
  }

  return buffer.join(softbreak);
};
```

**Comment by seonim-ryu** [comment]
@derek-knox This is right what ToastMark intended. According to the [CommonMark specification](https://spec.commonmark.org/0.29/), there is no case of indents being included in text nodes. So there is no method you implemented by handling indents. I have a question. In what case are you trying to use that function?

**Comment by derek-knox** [comment]
@seonim-ryu Our use case is that we have files with markdown in the form of both `.md`, `.html.md`, and `.html.md.erb` as a result of the Middleman static site generator https://middlemanapp.com/basics/templating-language/. What this means is that our source markdown files aren't always pure markdown syntax and instead have ERB (embedded ruby). This isn't a problem when rendering as the pipeline steps are followed. However, when we want to provide a WYSIWYG experience for editing the raw source without messing up the existing ERB code, we need to some how differentiate it as otherwise Toast UI consumes ERB as markdown (which breaks the ERB code via indentation, character escaping, etc. changes).

To answer your question, we were previously going the route of a custom paragraph renderer that would account for ERB, but we've opted (at least for now) to do a pre-processing step to dynamically convert "template code" (ERB in our case) to a codeblock only in WYSIWYG mode, but raw in Markdown mode.

We may be stretching the limits of Toast UI, but have so far been able to work within its constraints.
