### ISSUE TITLE
how to insert html tag at current cursor position(wysiwyg)?

### ISSUE THREAD

**Issue by kmins** [nhn/tui.editor#1134]
좋은 프로그램 감사합니다.

I've tried to use API 'insertText' to fix this problem, but '<' is automatically rendered to '\\<' 
is there solution?

**Comment by seonim-ryu** [comment]
@kmins I think you're trying to add the following text in WYSIWYG Editor.
```
<span>foo</span>
```
First of all, you shouldn't try to enter a tag as a string in WYSIWYG. And in the current WYSIWYG Editor only html that matches the markdown syntax can be added using the command. But what is the function you are trying to make?

**Comment by bdevg** [comment]
Are you using react?
