### ISSUE TITLE
'@toast-ui/vue-editor@^1.1.1' is not in the npm registry.

### ISSUE THREAD

**Issue by imjonos** [nhn/tui.editor#1137]
## Describe the bug
 npm install --save @toast-ui/vue-editor
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@toast-ui%2fvue-editor - Not found
npm ERR! 404 
npm ERR! 404  '@toast-ui/vue-editor@^1.1.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nos/.npm/_logs/2020-08-06T09_36_50_434Z-debug.log

## To Reproduce
npm install --save @toast-ui/vue-editor

**Comment by trentmon** [comment]
@toast-ui/react-editor isn't in registry too

**Comment by Ats1999** [comment]
> @toast-ui/react-editor isn't in registry too

I have toady installed it reacts version.

**Comment by seonim-ryu** [comment]
@imjonos @trentmon @Ats1999 Currently it works fine when I install the Editor's wrapper. Looking at the [npm status](https://status.npmjs.org/), it looks like there was a problem with npm yesterday. I think this is the cause, can you check if the same problem still occurs?

> Aug 6, 2020
> Issues accessing npmjs.com and installing scoped packages

**Comment by trentmon** [comment]
it's ok now
