### ISSUE TITLE
How to get text and html(both) for sending to the server in React. 

### ISSUE THREAD

**Issue by Ats1999** [nhn/tui.editor#1138]
# When user clicks *submit* button then I want to send the data to the server for further processing.
 When I look for the docs, then I only found for pure javaScript. I didn't found any documentation about how to get markdown text and HTML using react.

**Comment by seonim-ryu** [comment]
@Ats1999 The Editor provides [`getMarkdown()`](https://nhn.github.io/tui.editor/latest/ToastUIEditor#getMarkdown) and [`getHtml()`](https://nhn.github.io/tui.editor/latest/ToastUIEditor#getHtml) APIs. I think you can call this API to get the value, and refer to the following for how to call the instance method in React wrapper.

> https://github.com/nhn/tui.editor/tree/master/apps/react-editor#instance-methods

**Comment by bdevg** [comment]
> @Ats1999 The Editor provides [`getMarkdown()`](https://nhn.github.io/tui.editor/latest/ToastUIEditor#getMarkdown) and [`getHtml()`](https://nhn.github.io/tui.editor/latest/ToastUIEditor#getHtml) APIs. I think you can call this API to get the value, and refer to the following for how to call the instance method in React wrapper.
> 
> > https://github.com/nhn/tui.editor/tree/master/apps/react-editor#instance-methods

Can you help with this issue.
https://github.com/nhn/tui.editor/issues/1141
