### ISSUE TITLE
Why viewer doesn't render data from state, when data is passed as state using this.setState().

### ISSUE THREAD

**Issue by bdevg** [nhn/tui.editor#1141]
Viewer is not rendering anything when markdown is passed form `props` or fetched from any network. 
[Check this live on codesandbox](https://codesandbox.io/s/focused-currying-qsn8s?file=/src/index.js)

**Comment by seonim-ryu** [comment]
@bdevg I checked the code on the CodeSandBox. I have a question. Why are you trying to initialize with `state` value? Can't you initialize with the value passed by `props`? And according to the React component's life cycle, `componentDidMount` is executed after `render`, so there will be no `this.state.md` value at the time `render` is called. 

So I think you should set the value of `this.state.md` to `this.props.md` in the `constructor`
```js
constructor(props){
  // ...
  this.state={
    md: this.props.md
  }
}
```
or set the value of `initialValue` to `props` when creating an instance.
```js
<Viewer
  // ...
  initialValue={this.props.md}
/>
```

**Comment by bdevg** [comment]
Okey. I'll try.
