### ISSUE TITLE
Is the text background color not supported?

### ISSUE THREAD

**Issue by su2021803** [nhn/tui.editor#1146]
Is the text background color not supported?

< example >

![스크린샷 2020-08-14 오전 10 29 14](https://user-images.githubusercontent.com/69658670/90202579-0e149500-de19-11ea-8d02-9697082a84d8.png)

**Comment by Ats1999** [comment]
Are you using react Wrapper?

**Comment by su2021803** [comment]
> Are you using react Wrapper?

No. I using Vue Wrapper.

**Comment by seonim-ryu** [comment]
@su2021803 Right. Background is not provided because it is not a markdown specification. Instead, I think it could be made as a plugin in the future.
