### ISSUE TITLE
how can i user editor just with jquery?

### ISSUE THREAD

**Issue by oopsRookie** [nhn/tui.editor#1154]
## Summary
i just used jquery in my project, without other frameworks like vue,node etc?
so can i use it? and how?

## Additional context
i just fond view.js and viewer.js in the package of jquery-editor. And there is no any css files.

**Comment by seonim-ryu** [comment]
@oopsRookie Do you want to use a wrapper? First, you can check out the jQuery wrapper [here](https://github.com/nhn/tui.editor/tree/master/apps/jquery-editor). And the question of "Additional context" seems to ask how to include CSS files when used as CDN. If that's correct, you should include CSS files you need in the Editor first as described below.

> https://github.com/nhn/tui.editor/tree/master/apps/editor#using-in-browser-environment-by-cdn

**Comment by oopsRookie** [comment]
> 
> 
> @oopsRookie Do you want to use a wrapper? First, you can check out the jQuery wrapper [here](https://github.com/nhn/tui.editor/tree/master/apps/jquery-editor). And the question of "Additional context" seems to ask how to include CSS files when used as CDN. If that's correct, you should include CSS files you need in the Editor first as described below.
> 
> > https://github.com/nhn/tui.editor/tree/master/apps/editor#using-in-browser-environment-by-cdn

thank you. but i dont use cdn.  do you mean i need include editor and jquery-editor these two package into my project? [here the link](https://github.com/nhn/tui.editor/tree/master/apps) because i just find two js file(editor.js and viewer.js) in jquery-editor.
sorry, i dont know what the wrapper is. i tried to import editor.js and viewer.js, but UI didnt display.(i guess miss css file).

**Comment by seonim-ryu** [comment]
@oopsRookie If you don't use CDN, it seems that you are developing in a node environment. If so, you can import CSS files this way.

> https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/getting-started.md#using-in-node-environment
