### ISSUE TITLE
No Highlight color for selceted empty lines

### ISSUE THREAD

**Issue by Mainpat** [nhn/tui.editor#1156]
## Describe the bug
When you have empty lines and select text or the empty lines you don't have any higligth indicator for the empty lines.
This is sometimes a problem when you mark text to delete and don't see which lines you have all selected.

## To Reproduce
1. Go to https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic
2. Switch to WYSIWYG Editor Mode
3. Enter x empty lines 
4. Mark the empty lines
5. You don't have any highlight marker to see that you have select the empy lines

## Expected behavior
We expected that the empy lines are also highlited

## Screenshots
![grafik](https://user-images.githubusercontent.com/29457881/90794221-d459f780-e30c-11ea-8951-4982f03df711.png)

## Desktop (please complete the following information):
 - OS: Windows
 - Browser Firefox
 - Version 79

**Comment by seonim-ryu** [comment]
@Mainpat This is not the Editor's bug. In Firefox, newlines ​​in `contenteditable="true"` are not selected. If you look at the image below, it was tested in Firefox.

![firefox](https://user-images.githubusercontent.com/18183560/90841340-60186600-e397-11ea-8b2f-1e54e73009d8.gif)

The part where text is entered is an element with `contenteditable="true"` set, and it can be considered the same as the WYSIWYG editor.

```html
<div contenteditable="true"></div>
```

**Comment by Mainpat** [comment]
I see thanks for the info
