### ISSUE TITLE
Highlight code in CodeBlock

### ISSUE THREAD

**Issue by kelvinkoko** [nhn/tui.editor#1158]
Is it possible to highlight code syntax in "CodeBlock"
e.g.
```kotlin
val test = 123
fun doSomething() {
   ...
}
```
Can TuiEditor support code syntax highlight like the above?

**Comment by seonim-ryu** [comment]
@kelvinkoko First of all, it seems to be the same issue as this one. 

> https://github.com/nhn/tui.editor/issues/1149

There are a lot of things to be improved in the case of the WYSIWYG's code block, but it is difficult to improve it in the current structure, so it will be improved in the 3.0 update.

**Comment by vmangelovv** [comment]
@seonim-ryu and when will be this update?

**Comment by igorjacauna** [comment]
Seems version 3 fixed this

**Comment by kelvinkoko** [comment]
Since v3 fixed this issue, I close this issue
