### ISSUE TITLE
Editor is not working well in https://ui.toast.com/

### ISSUE THREAD

**Issue by easylogic** [nhn/tui.editor#1159]
## Describe the bug
Editor is not working well in https://ui.toast.com/.
preview area's width is zero. 
So I can't show preview.

## To Reproduce
1. Go to 'https://ui.toast.com'
2. Click 'Editor' 
3. Show preview area 

## Screenshots
<img width="1105" alt="스크린샷 2020-08-24 오전 11 45 33" src="https://user-images.githubusercontent.com/591983/90998769-da4b2380-e5ff-11ea-869c-fff045108c97.png">

## Desktop (please complete the following information):
 - OS: MacOS 10.14.6
 - Browser : chrome 
 - Version: 84.0.4147.135

**Comment by seonim-ryu** [comment]
@easylogic I checked the issue and it is now fixed. Thanks for reporting the issue. I'll close this issue.
