### ISSUE TITLE
How to test if editor has changes inside content?

### ISSUE THREAD

**Issue by hrvoj3e** [nhn/tui.editor#1166]
Is tis possible ATM?

```js
if (editor.hasChanges()) {
  // alert user in some way
  // ask to save first
}
```

Use case
 - load empty editor
 - user writes something
 - user wants to navigate away from editor with unsaved changes

Use case 2
 - load editor with initial value
 - user edits something
 - user wants to navigate away from editor with unsaved changes

**Comment by seonim-ryu** [comment]
@hrvoj3e There is an option to set hooks in the Editor's instance options. When the content is changed, the function set in the hook option is executed, so I think you can use this.

> https://github.com/nhn/tui.editor/blob/master/apps/editor/src/js/editor.js#L108
