### ISSUE TITLE
How to use youtube plugin in react viewer. Same markdown shows youtube viedeos in editor, while not in viewer.

### ISSUE THREAD

**Issue by Ats1999** [nhn/tui.editor#1169]
I am providing the code sandbox link. You can check it live. Same youtube plugin is rendering in react editor, while not in viewer. 
[Code sandbox live](https://codesandbox.io/s/adoring-violet-kb2wv?file=/src/App.js)

**Comment by seonim-ryu** [comment]
@Ats1999 It is because the editor used in your `youtube` plugin (`Toast Editor`) and the editor used in the Viewer are different. When using it in a wrapper, you can do it like this, and we'll update the documentation as well.

> https://github.com/nhn/tui.editor/issues/899#issuecomment-633979500

**Comment by Ats1999** [comment]
I think `editor` is not exported from `@toast-ui/react-editor`. We can have a reference to the `Editor` and `Viewer` component.
[Check this code sandbox](https://codesandbox.io/s/blissful-brook-5kpz0)
