### ISSUE TITLE
How to use addImageBlobHook in React. 

### ISSUE THREAD

**Issue by Ats1999** [nhn/tui.editor#1170]
Whenever the user clicks on the image icon to upload image, i want to upload image to the server. I went through some issues, but i didn't get the point. 

[#57 ](https://github.com/nhn/tui.editor/issues/57)
```js
...
    hooks: {
        addImageBlobHook: this.onAddImageBlob(),
    },
...
```
Do i have to pass hooks to as props to the Editor component? 
If possible, provide a cod example. 
Thanku.

**Comment by seonim-ryu** [comment]
@Ats1999 Would you like to use it like this?

```js
hooks={{
  addImageBlobHook: (blob, callback) => {
    const uploadedImageURL = uploadImage(blob);
    
    callback(uploadedImageURL, "alt text");
      
    return false;
  }
}}
```

**Comment by Ats1999** [comment]
> @Ats1999 Would you like to use it like this?
> 
> ```js
> hooks={{
>   addImageBlobHook: (blob, callback) => {
>     const uploadedImageURL = uploadImage(blob);
>     
>     callback(uploadedImageURL, "alt text");
>       
>     return false;
>   }
> }}
> ```

Yes

**Comment by Ats1999** [comment]
> @Ats1999 Would you like to use it like this?
> 
> ```js
> hooks={{
>   addImageBlobHook: (blob, callback) => {
>     const uploadedImageURL = uploadImage(blob);
>     
>     callback(uploadedImageURL, "alt text");
>       
>     return false;
>   }
> }}
> ```

I didn't see it's documentation, that where how we can use hooks. 
Do I need to pass it as plugins in editor?
Any example would be appreciated.

**Comment by Ats1999** [comment]
Hi,

**Comment by Ats1999** [comment]
> ```js
> se;
> ```

Why we are returning false.?
