### ISSUE TITLE
Viewer allows setting check box but no download changes

### ISSUE THREAD

**Issue by posel** [nhn/tui.editor#1175]
<!--

## Summary
The viewer (object viewer) allows check / uncheck checkboxes, which is great. But I didn't found how to get and stores modifications.
Is there a way how to download changes or somehow get information about the checklist status?

## Screenshots
![image](https://user-images.githubusercontent.com/36728060/91885936-d9159880-ec88-11ea-8712-0193fa9d22b0.png)

## Version
All editors

## Additional context
Editors are great, ... but checklists would be more usefull when it allows display them and modify.

**Comment by js87zz** [comment]
@posel 
Please make sure you have filled out issue respecting our form and given us as much context as possible.

**Comment by posel** [comment]
Sorry, I don't know, why there is no comment- I wrote it including images.

Currently, viewer displays markdown code great including the checkboxes that are clickable even in the viewer. Great - but how can system save the checkbox settings? Viewer has no function like getMarkdown() to get the update and save them.

Is it possible to get although function to save the markdown with checkbox updates?

![image](https://user-images.githubusercontent.com/36728060/91935531-342da680-ecee-11ea-8e90-0b7d98df527c.png)
