### ISSUE TITLE
Editor does not close itself correctly - how to destroy it manually?

### ISSUE THREAD

**Issue by posel** [nhn/tui.editor#1185]
## Describe the bug
Editor does not clean its memory and some data structures are blocked repeatable open in the same window:
Open editor in div:
![image](https://user-images.githubusercontent.com/36728060/92245436-ab1c9800-eec4-11ea-8665-7ac417d87a2e.png)

Then close div, destroy all release all data structures with link the div content and open again:
![image](https://user-images.githubusercontent.com/36728060/92245499-bff92b80-eec4-11ea-8388-4ba2f6e34497.png)

Exactly the same open - but editor does not load itself. It is necessary to release window object to work it again. 

## To Reproduce
1. Open editor by java script in div with 100% size
2. Close div
3. Open again

BTW, when placed within a table, it behaves better - but it has relation with the former report.

## Desktop (please complete the following information):
any windows browser, mobile not tested

**Comment by seonim-ryu** [comment]
@posel I don't know exactly what the situation is when I look at the images. So, I would like to give an example page with something like the CodePen rather than an image.

But for now, how about deleting an instance of the Editor to close the dialog and re-creating it when it is opened?

```js
const editor = new Editor({ ... }); // create an instance

editor.remove(); // remove an instance
```

**Comment by posel** [comment]
I've remove all objects with editor but it does not help.
Unfortunately I tried to integrate it to a framework that creates pop-up windows that are free for resize, close and repeatable open. The simple example makes no such problem.
Nevertheless, thanks for recommendation.
