### ISSUE TITLE
Inserting HTML Element in Line

### ISSUE THREAD

**Issue by JLNPWRLFT** [nhn/tui.editor#1191]
I am working on a Tagging-Plugin right now but I ran into some problems.

![image](https://user-images.githubusercontent.com/62693023/92610648-39738e00-f2b8-11ea-96b1-553d796286e9.png)

Content that is prefixed with an `@` will result in rendering a list with items (e.g. Users). 

Once I click on one of the items I want to insert an element into this current line and this current position, like this: 

```
<pre class=" CodeMirror-line " role="presentation">
<span role="presentation" style="padding-right: 0.1px;">Lorem Ipsum <span>@USER</span> ....</span>
</pre>
```

The reason for that is that I want to add an EventListener to this Element whenever you click on it to be able to render a list again of all the items that match.

I noticed already that it is already implemented for `bold`. Whenever I close a string with "**", the following HTML gets injected into the line. 

```
<pre class=" CodeMirror-line " role="presentation">
  <span role="presentation" style="padding-right: 0.1px;">
    <span class=" tui-md-strong tui-md-delimiter" data-tui-mark="">**</span>
    <span class=" tui-md-strong" data-tui-mark="">Test</span>
    <span class=" tui-md-strong tui-md-delimiter" data-tui-mark="">**</span>
  </span>
</pre>
```

How can I implement this?

**Comment by seonim-ryu** [comment]
@JLNPWRLFT How did you attach the elements? It seems to be pasted by searching dom directly without using the Editor's API. I don't think I can give you an answer by looking at this. Can you give me an example page with the CodePen or something?

**Comment by JLNPWRLFT** [comment]
> @JLNPWRLFT How did you attach the elements? It seems to be pasted by searching dom directly without using the Editor's API. I don't think I can give you an answer by looking at this. Can you give me an example page with the CodePen or something?

The elements aren't attached. They are just a <div> that gets placed absolute under the `CodeMirror-cursor`-Element 

```
    const cursorPos = cursor.getBoundingClientRect();

    popUp.setAttribute('style', "" +
        "position: absolute;" +
        "left:" + cursorPos.x + "px;" +
        "top:" + (cursorPos.y + 20) + "px;");

```

**Comment by seonim-ryu** [comment]
@JLNPWRLFT I think you can add an element by calling the `addWidget()` API below. It will be difficult if you want to adjust the position of the element yourself. The `popup` variable corresponds to the element you are adding, so refer to the code below.

```html
<div id="editor"></div>
<button id="btn">click</button>
<div id="popup">foo</div>
```
```js
document.getElementById('btn').addEventListener('click', () => {
  const currentEditor = editor.getCurrentModeEditor();
  const range = currentEditor.getRange();
  const popup = document.querySelector('#popup');

  currentEditor.addWidget(range, popup);
});
```

**Comment by JLNPWRLFT** [comment]
I figured out how to render a HTML Element in Line now. 




**JS**



Widget: (screenshot)
```        
editor.addWidget(range, element, 'bottom');
```

![image](https://user-images.githubusercontent.com/62693023/93988312-d6d6c380-fd88-11ea-867a-c6d78e5b6460.png)


When I click on one of the items in the list from the widget, it will render into the Editor as HTMLElement:
```
        this._insertedContent = this._cm.markText(
            start, this.currentRange.end, {
                replacedWith: reference,
            });
```

HTML: 
```
<span class="CodeMirror-widget" role="presentation" cm-ignore-events="true">
   <span class="reference">
          <span class="reference-symbol">@</span>
          <span class="reference-content">superadmin</span>
   </span>
</span>
```

![image](https://user-images.githubusercontent.com/62693023/93988438-fbcb3680-fd88-11ea-911a-ebabc3e4dd8f.png)


But when I change to the preview tab now it doesnt render the inserted HTML Element, so I need to define some custom Rendering for that element. How can I do that?

I found [this](https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/custom-html-renderer.md) but that only works with pre-defined things like heading, paragraph? ...

**Comment by dpatra** [comment]
> I figured out how to render a HTML Element in Line now.
> 
> **JS**
> 
> Widget: (screenshot)
> 
> ```
> editor.addWidget(range, element, 'bottom');
> ```
> 
> ![image](https://user-images.githubusercontent.com/62693023/93988312-d6d6c380-fd88-11ea-867a-c6d78e5b6460.png)
> 
> When I click on one of the items in the list from the widget, it will render into the Editor as HTMLElement:
> 
> ```
>         this._insertedContent = this._cm.markText(
>             start, this.currentRange.end, {
>                 replacedWith: reference,
>             });
> ```
> 
> HTML:
> 
> ```
> <span class="CodeMirror-widget" role="presentation" cm-ignore-events="true">
>    <span class="reference">
>           <span class="reference-symbol">@</span>
>           <span class="reference-content">superadmin</span>
>    </span>
> </span>
> ```
> 
> ![image](https://user-images.githubusercontent.com/62693023/93988438-fbcb3680-fd88-11ea-911a-ebabc3e4dd8f.png)
> 
> But when I change to the preview tab now it doesnt render the inserted HTML Element, so I need to define some custom Rendering for that element. How can I do that?
> 
> I found [this](https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/custom-html-renderer.md) but that only works with pre-defined things like heading, paragraph? ...
> 
> > The keys of the object is types of node of the AST...
> 
> How can I add custom keys to the AST?
> 
> @seonim-ryu

Hey @JLNPWRLFT ,

Your findings are good, have you solved, how to get the rendering part. Or when posting the content the @ part is only posted not the "@superadmin".
