### ISSUE TITLE
How to close Virtual Scroll for Editor Area?

### ISSUE THREAD

**Issue by MythosMa** [nhn/tui.editor#1193]
Hello!
  I find Editor Area is using Virtual Scroll for rendering long  text, so not all of the content will be rendered. When I use the browser‘s "Find", I lose some target words which not rendered yet.
 So is there any way to close Virtual Scroll or other way to avoid this problem? 
 Thanks!

**Comment by seonim-ryu** [comment]
@MythosMa Currently, virtual scrolling is not applied, and there are no options to set. And when I do a search ("find") in the browser, it is searched. Could you explain in more detail what the situation is?

**Comment by seonim-ryu** [comment]
@MythosMa I was mistaken. The virtual scrolling part you are talking about seems to be referring to the Markdown editor, and it is true that virtual scrolling is applied. Anyway, this part currently doesn't have an option to disable scrolling, and you have to add an option to provide it if necessary.

**Comment by MythosMa** [comment]
@seonim-ryu 
Thanks for your reply！
I mean when I use  "FIND" like the image below:
![image](https://user-images.githubusercontent.com/30307817/94138404-aaab6780-fe9a-11ea-9db3-ccf85d691f3a.png)

When Virtual scrolling is opening, the count of keywords witch not rendered will be lost in result.
![image](https://user-images.githubusercontent.com/30307817/94138999-88feb000-fe9b-11ea-966e-6355abd76af4.png)

So I need an option to close virtual scroll.
Now I will try to add this option.
Thank you!
