### ISSUE TITLE
Some package can't download  

### ISSUE THREAD

**Issue by steavengong** [nhn/tui.editor#1194]
Some package can't download  

in your package.json  some dependence  need git://xxxxxx

I use verdaccio  but  these package don't download  into my storage 

when i have no internet   or  no cache    , it will be  install failed 

please update the  package.json

**Comment by seonim-ryu** [comment]
@steavengong Just looking at this, I can't figure out what's wrong with it. Also tell me the installation environment (OS, node, npm versions) and the Editor version. I wish I had a screenshot.

**Comment by steavengong** [comment]
OS  Mac_OS_10.15.6 
node 10.22.0
npm 6.14.8
@seonim-ryu

**Comment by steavengong** [comment]
@sean-nicholas 
tui-editor 1.4.10

**Comment by steavengong** [comment]
@seonim-ryu 
I use verdaccio build a private npm registry
I use yarn add tui-editor  into my project
install succuess 
i check the tui-editor in my project node_modules
![image](https://user-images.githubusercontent.com/10862092/93283440-1d657480-f803-11ea-9037-643fa8294de3.png)
squire-rte version is need download from github resource code
it will not download into my private registry ,buti it will be download into yarn cache folder

also i check the yarn.lock file
![image](https://user-images.githubusercontent.com/10862092/93283682-9a90e980-f803-11ea-8323-6476d650ff0d.png)
![image](https://user-images.githubusercontent.com/10862092/93283698-a4b2e800-f803-11ea-825d-2befab07ab98.png)
![image](https://user-images.githubusercontent.com/10862092/93283741-bbf1d580-f803-11ea-9007-5c23a63f7ac6.png)
these dependencies packages cannot download into my private registry

if i work in inner set cannot use outer net , in new project use tui-editor cannot install

**Comment by seonim-ryu** [comment]
@steavengong I got it. The npm package protocol appears to be the cause of this problem.

> https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

If possible, we want you to use version 2, but it seems that some users are using version 1.4, so I'll fix it.

**Comment by steavengong** [comment]
@seonim-ryu 
thanks
