### ISSUE TITLE
Github Alert received

### ISSUE THREAD

**Issue by jack9603301** [nhn/tui.editor#1198]
![Screenshot_20200913_120432](https://user-images.githubusercontent.com/9047180/93009960-7772f980-f5b9-11ea-98af-d93eb0312dda.png)

**Comment by seonim-ryu** [comment]
@jack9603301 It is related to the issues below, and this is a state of inquiries to npm.

> https://github.com/nhn/tui.editor/issues/733#issuecomment-690832329

**Comment by jack9603301** [comment]
This problem has been fixed in the latest version?

**Comment by seonim-ryu** [comment]
@jack9603301 I have asked the npm team to resolve this message, and I'll let you know when a reply comes.
