### ISSUE TITLE
Tooltips not appearing on Vue Editor Toolbar Buttons

### ISSUE THREAD

**Issue by JoseiToAoiTori** [nhn/tui.editor#1201]
## Describe the bug

When using the Vue component for the Editor, tooltips do not appear when you hover over buttons on the toolbar. Codemirror and Editor CSS is imported as ESModules and the toolbar buttons are not customized in any way.

## To Reproduce
1. `yarn add @toast-ui/vue-editor`
2. Inside a new Vue component, import Codemirror and Editor CSS along with the editor itself. Also register the Editor component.
3. Create an Editor component with props like these:

```js
<Editor initialEditType="wysiwyg" :options="editorOptions" :ref="`editor-${id}`" :initialValue=`anObject[key]" @focus="changed = true" @change="handleInput(id)"/>
```

## Expected behavior
When the Editor is rendered out, hovering over the toolbar buttons should bring up tooltips describing what the button does.

## Screenshots

No tooltips appear on the Editor when it's a vue component.

![](https://i.imgur.com/A2N4nYC.png)

However, on the demo hosted at https://ui.toast.com/tui-editor/, tooltips do appear.

![](https://i.imgur.com/Hb5PhAc.png)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome (Latest)

## Additional context

The full code in question can be found [here](https://github.com/r-anime/awards-web/blob/master/frontend/jurorApps/pages/AppPage.vue).

**Comment by seonim-ryu** [comment]
@JoseiToAoiTori When I run it from `@toast-ui/vue-editor`'s storybook, it works fine. So I think this problem is caused by the overlapping styles of your service code and tooltip. Would you like to check if the tooltip is generated well in the page you developed as follows, and check if the style of the service code has affected it?

![storybook](https://user-images.githubusercontent.com/18183560/93950962-f9b0aa00-fd7f-11ea-8055-540d9c918309.png)

**Comment by JoseiToAoiTori** [comment]
The `tui-tooltip` element doesn't seem to be part of the DOM here.

![](https://i.imgur.com/kwD8XxM.png)

I also don't have any styles that would affect the editor other than this:

```css
.tui-editor-contents ol > li::before {
        color: initial;
}

.tui-editor-contents ul > li::before {
        background-color: initial;
}
```

**Comment by seonim-ryu** [comment]
@JoseiToAoiTori The `tui-tooltip` element is appended to an element outside the Editor's container. Could you check if it is found when searching in the entire `document`?

![tooltip](https://user-images.githubusercontent.com/18183560/94004164-3c51a100-fdd7-11ea-8ee9-42da25d1e30e.png)

**Comment by JoseiToAoiTori** [comment]
It's not found in the document or in the bundle generated by webpack. Just completely missing.

**Comment by pandavenger** [comment]
Hi, I'm working on the same project as @JoseiToAoiTori and we were able to manage a workaround by patching in a check to see if the tooltip is in the DOM, and re-adding it if it is not.

https://github.com/pandavenger/tui.editor/commit/6f274f3ab1510b5a40c9d4c9bc9a32ff5abee618 

However, this just outright does not seem like good coding practice, nor do we want to fix the problem by applying a patch every time. Do you have any suggestions on how to proceed from here?

**Comment by JoseiToAoiTori** [comment]
The issue still persists even after upgrading to v2.5.0. Is this going to be fixed or is the patch our only option?
