### ISSUE TITLE
Any suggestion on how to implement "Scroll to bottom"?

### ISSUE THREAD

**Issue by kelvinkoko** [nhn/tui.editor#1206]
## Summary
In WYIWYG mode, there is "scrollTop" api to control the scroll position. But i seems havent found "scrollHeight", any suggestion to make WYIWYG scroll to bottom in code?

Thank you

**Comment by seonim-ryu** [comment]
@kelvinkoko 
> ... to make WYIWYG scroll to bottom

Looking at the function you described, I think you want the ability to move the cursor to the end of the Editor. If that's correct, you can use the `moveCursorToEnd` API.

> https://github.com/nhn/tui.editor/blob/ff74fc7fd8fbb380643ec8da75ddea821d3974ef/apps/editor/src/js/editor.js#L466-L475

**Comment by kelvinkoko** [comment]
ah right, thank you very much!~
