### ISSUE TITLE
yarn can't install packages tui-editor

### ISSUE THREAD

**Issue by clark-tan** [nhn/tui.editor#1209]
## Describe the bug
yarn can't install packages tui-editor 

because 

 dependencies:
   squire-rte "github:seonim-ryu/Squire#fd40b4e3020845825701e9689f190bab3f4775d4"

error An unexpected error occurred: "https://raw.githubusercontent.com/seonim-ryu/Squire/fd40b4e3020845825701e9689f190bab3f4775d4/package.json: connect ECONNREFUSED 0.0.0.0:443".

**Comment by seonim-ryu** [comment]
@clark-tan I think this problem was caused by blocking on your company's firewall. Check it out.

**Comment by clark-tan** [comment]
> @clark-tan I think this problem was caused by blocking on your company's firewall. Check it out.

**Comment by clark-tan** [comment]
> @ clark-tan我认为此问题是由您公司防火墙上的阻止引起的。看看这个。

i think cause this 
it's 
  dependencies:
    squire-rte "github:seonim-ryu/Squire#fd40b4e3020845825701e9689f190bab3f4775d4"  
it maybe https:  not github: ?
