### ISSUE TITLE
Server Error ReferenceError: window is not defined in NextJS

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1222]
## Bug
I am trying to use this editor in **NextJS**. When i run coded and compiled then i got the error `Server Error ReferenceError: window is not defined in NextJS`.

It is rendering fine on the first render, but after compilation when I refresh the page then i got the error everytime.

## To Reproduce
**pages/index.js**
```js
import WriteArticleComponent from "../../components/ArticlesWrite";
import Head from 'next/head';
export default function ArticlesWrite(){

    return <div>
            <Head>
                <title>Write an article and help other dev's | B-Dev-G</title>
            </Head>
            <WriteArticleComponent/>
        </div>
}
```
**ArticlesWrite.js**
```js
import React from 'react'
// import for editor
import 'codemirror/lib/codemirror.css';
import '@toast-ui/editor/dist/toastui-editor.css';
import { Editor } from '@toast-ui/react-editor';
function ArticlesWrite() {

    return <Editor
        previewStyle="vertical"
        height="400px"
        initialEditType="markdown"
        initialValue={""}                       
        usageStatistics={false}
        language = "en"
    />
}

export default ArticlesWrite
```
Open the browser and refresh the page.

## Additional context
This problem doesn't happen when i dynamically import the components with no ssr.
```js
const WriteArticleComponent = dynamic(() => import('../../components/ArticlesWrite'), {
    ssr: false,
})
```

## The error is happening here 
```
node_modules\@toast-ui\editor\dist\toastui-editor.js:16:4
```

## For reference 
```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("codemirror"));
	else if(typeof define === 'function' && define.amd)
		define(["codemirror"], factory);
	else if(typeof exports === 'object')
		exports["Editor"] = factory(require("codemirror"));
	else
		root["toastui"] = root["toastui"] || {}, root["toastui"]["Editor"] = factory(root["CodeMirror"]);
})(window, function(__WEBPACK_EXTERNAL_MODULE__15__)
```

**Comment by seonim-ryu** [comment]
@Ats1999 This issue seems to be similar to the issue below. Will you try to solve it by referring to the comments in the link?

> Reference : https://github.com/nhn/tui.grid/issues/935

**Comment by Ats1999** [comment]
> @Ats1999 This issue seems to be similar to the issue below. Will you try to solve it by referring to the comments in the link?
> 
> > Reference : [nhn/tui.grid#935](https://github.com/nhn/tui.grid/issues/935)

We can generate an editor component without SSR, there is no problem. But the same this is happening with `Viewer` component also. I have to generate the page without SSR. I don't know when the next version will release. Is there any way to solve this issue now?
