### ISSUE TITLE
What i do wrong in instalation

### ISSUE THREAD

**Issue by Marcin1sto** [nhn/tui.editor#1232]
## Summary
 I try install this editor on my project, but only have problem with instalation. Look at screen please.
## Screenshots
File for webpack 
![obraz](https://user-images.githubusercontent.com/50157273/96503463-95381c00-1253-11eb-8447-411a94653a5b.png)
configuration skript
![obraz](https://user-images.githubusercontent.com/50157273/96503687-f2cc6880-1253-11eb-99e8-7013eb2463f1.png)
css file imported 
![obraz](https://user-images.githubusercontent.com/50157273/96503732-fd86fd80-1253-11eb-9b24-8dc739bdf822.png)
![obraz](https://user-images.githubusercontent.com/50157273/96503925-45a62000-1254-11eb-9d30-5769cd127230.png)

## Version
2.2.0

**Comment by seonim-ryu** [comment]
@Marcin1sto Are you saying that the editor module cannot be imported? Just looking at this, I don't know what the problem is... Please explain in more detail.
