### ISSUE TITLE
It's a GFM editor then why it doesn't support accordian 

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1233]
<details>
<summary>Accordian..</summary>
<p>

```c#
public class Order
{
    public int OrderId { get; set; }
    public int CustomerId { get; set; }

    public List<int> Products { get; set; }
}
\```

</p>
</details>

**Comment by seonim-ryu** [comment]
@Ats1999 I think you're talking about using `<details>` tag. It is not fully supported by the Editor, but it can be used.  If you set the Editor's instance option to ʻuseDefaultHTMLSanitizer: false` and enter the markdown value as follows, you can use it in the viewer.

```js
const editor = new Editor({
  // ...
  useDefaultHTMLSanitizer: false
});
```

![test](https://user-images.githubusercontent.com/18183560/96665296-8c4c6500-138f-11eb-89b0-0c3f3044ec22.png)

**Comment by Ats1999** [comment]
Is there any disadvantage of using `useDefaultHTMLSanitizer`

**Comment by seonim-ryu** [comment]
@Ats1999 Currently, the Editor is removing unnecessary html tags. For example, the Editor is sanitizing the `<script>` tag, so the `details` and `summary` tags are also being removed. When you want to turn off this feature, you use `useDefaultHTMLSanitizer: false`. However, turning off the option can lead to security issues. So you have to process the html you want to sanitize yourself using the options below.

> https://github.com/nhn/tui.editor/issues/733#issuecomment-621139121

**Comment by Ats1999** [comment]
Thanks
