### ISSUE TITLE
Is this editor support creating TOC by innerlinks?

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1234]
These inner links are useful for creating a table of contents. 
### See it's working in github
[Github url](https://github.com/Ats1999/ats1999/blob/master/test.md#heading-2)
### The same things doesn't work in _**toast ui**_
[ToastUI](https://bdevg.com/articles/Heading%20levels%205f8ee5dfadd12c2aa8ad9666#sub-sub-heading-2)
### Example is taken from 
[example](https://github.com/Ats1999/ats1999/blob/master/test.md#heading-2)

#### Style of the link is not the same as Github links 
If the link doesn't work then copy-paste the below texts.
```
- [Heading](#heading)
  * [Sub-heading](#sub-heading)
    + [Sub-sub-heading](#sub-sub-heading)
- [Heading](#heading-1)
  * [Sub-heading](#sub-heading-1)
    + [Sub-sub-heading](#sub-sub-heading-1)
- [Heading](#heading-2)
  * [Sub-heading](#sub-heading-2)
    + [Sub-sub-heading](#sub-sub-heading-2)


# Heading levels

> This is a fixture to test heading levels

<!-- toc -->

## Heading

This is an h1 heading

### Sub-heading

This is an h2 heading

#### Sub-sub-heading

This is an h3 heading

## Heading

This is an h1 heading

### Sub-heading

This is an h2 heading

#### Sub-sub-heading

This is an h3 heading

## Heading

This is an h1 heading

### Sub-heading

This is an h2 heading

#### Sub-sub-heading

This is an h3 heading
```

**Comment by seonim-ryu** [comment]
@Ats1999 It is also in our plan to provide the TOC function. However, it seems that it will be difficult to provide in v2, and it will be possible to provide this feature after v3 major version update. In the same way, when using the `<details>` tag, it is difficult to fully express elements in WYSIWYG due to the current internal structure, so this part must be solved first, but functions can be provided.

**Comment by Ats1999** [comment]
Oh!
I also request you a feature to auto generate hyper links based on h1,h2.. tags.

**Comment by seonim-ryu** [comment]
@Ats1999 

> Oh!
> I also request you a feature to auto generate hyper links based on h1,h2.. tags.

What function is this talking about? Can you explain in more detail?

**Comment by Ats1999** [comment]
Okey!
Suppose I have written the in in editor
```
# Heading levels

> This is a fixture to test heading levels

<!-- toc -->

## Heading

This is an h1 heading

### Sub-heading

This is an h2 heading

#### Sub-sub-heading

This is an h3 heading

## Heading

This is an h1 heading

### Sub-heading

This is an h2 heading

#### Sub-sub-heading

This is an h3 heading

## Heading

This is an h1 heading

### Sub-heading

This is an h2 heading

#### Sub-sub-heading

```
To create hyperlinks we use 
```
- [Heading](#heading)
  * [Sub-heading](#sub-heading)
    + [Sub-sub-heading](#sub-sub-heading)
- [Heading](#heading-1)
  * [Sub-heading](#sub-heading-1)
    + [Sub-sub-heading](#sub-sub-heading-1)
- [Heading](#heading-2)
  * [Sub-heading](#sub-heading-2)
    + [Sub-sub-heading](#sub-sub-heading-2)
``` 
This is what i want to automate. This can be done by adding any kind of control (button, control key, etc.). Whenever user clicks on the control, it should generate hyperlinks automatically.
