### ISSUE TITLE
Adding long code in codeblock make full screen scrollable insted of just code block.

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1238]
We might have lengthy codes to write. In any other markdown editor, when we type long code then they make just code block scrollable. But, this editor is making full screen scrollable.

## To Reproduce
1. You can see a scroll bar at the bottom of the code block.
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
2. paste this code in toast-ui/react editor and see this make full screen scrollable.

**Comment by ats1999** [comment]
Open this page in mobile phone 

https://bdevg.com/articles/Java%20and%20c++%20Programming%205f91139d90a17700084261d4

**Comment by seonim-ryu** [comment]
@ats1999 I think I'm talking about this part. This is a bug, so I'll fix it.

![bug](https://user-images.githubusercontent.com/18183560/97378231-37679c00-1905-11eb-8080-14f74acb3780.png)

**Comment by ats1999** [comment]
Thanks.
This also happens with viewer.

**Comment by ats1999** [comment]
Does this bug has been fixed?
