### ISSUE TITLE
Modification on customHTMLRenderer affects original content

### ISSUE THREAD

**Issue by darron1217** [nhn/tui.editor#1239]
## Summary
I'm using Toast UI Editor as a Markdown WYSIWYG editor. (Initialize with markdown content, saving markdown content)

My current config is
```js
      BACKEND_URL='http://localhost';

      customHTMLRenderer={{
        image: ({firstChild}, {origin}) => {
          const result = origin();
          const attributes = {
            ...result.attributes,
            src: BACKEND_URL + result.attributes.src,
          };
          return {...result, attributes};
        },
      }}
```

I registered customRenderer because my markdown image data format is like below.
```
![picture.jpg](/uploads/02_2845569914.jpg)
```

### Problem 1.
But after I register customRenderer, it adds `BACKEND_URL` on every mode change.
(Markdown -> WYSIWYG -> Markdown results `http://localhosthttp://localhost/uploads/02_2845569914.jpg`)

### Problem 2.
I want to add prefix to image src temporary. (Which means this should be removed when saving content)

How can I acheive it with Toast UI Editor?

## Version
2.5.0

**Comment by seonim-ryu** [comment]
@darron1217 For the first problem, if you change from Markdown to WYSIWYG, you edit the document with the html result shown in the preview. Then, when it comes back to Markdown, it takes the changed html and converts it to Markdown.

The only way to handle this is to use the `convertorBeforeHtmlToMarkdownConverted` event in the current structure. (This is not an official API)

When changing from WYSIWYG to Markdown, an event occurs, and in this event, it is checked and converted to a regular expression.

```js
editor.on('convertorBeforeHtmlToMarkdownConverted', html => {
  return html.replace('img src="http://', 'img src="');
});
```

And the second problem is, I don't think it's handled by the editor, but just before you save the document, you can use regular expressions to replace it.

**Comment by darron1217** [comment]
@seonim-ryu Got it. Thanks 👍
