### ISSUE TITLE
Is there some exposed API to call to convert markdown text to rendered html from markdown parser?

### ISSUE THREAD

**Issue by taurenshaman** [nhn/tui.editor#1241]
I found no revelant API from the [docs](https://nhn.github.io/tui.editor/latest/).

## Summary
My website imports tui.editor, and I need render markdown text in a datatable. I found  no revelant API from the [docs](https://nhn.github.io/tui.editor/latest/). So I must import another markdown parser, e.g. markdown-it.

```
// jquery.dataTables
render: function(data, type, row, meta) {
    if (type === 'display') {
       // 'data' is the markdown text
       // How to replace this line with tui.editor?
       let result = markdownit.render(data);
       return result;
     }
     return data;
}},
```

## Screenshots
![image](https://user-images.githubusercontent.com/1308706/97135727-1b8cba80-178c-11eb-89c8-49b820bb2fab.png)

## Version
v2.5.0

## Additional context
[the datatable demo](https://codepen.io/taurenshaman/pen/gOMpLpb)

Thanks for your time!

**Comment by seonim-ryu** [comment]
@taurenshaman Actually, I didn't understand the question well. As I guessed from the annotation in your code, I understood that you wanted to replace `markdown-it` with the parser used by TOAST UI Editor.

If it's right, you can write it like this. Make sure what I understand is correct, and explain in more detail if it is wrong.

```js
import { Parser, createRenderHTML } from '@toast-ui/toastmark';

// ...
// How to replace this line with tui.editor?
// let result = markdownit.render(data);

const parser = new Parser(); // This is the parser used by TOAST UI Editor
const renderHTML = createRenderHTML({ gfm: true });

const root = parser.parse(content);
const html = renderHTML(root);

return html;
```

**Comment by taurenshaman** [comment]
@seonim-ryu  Sorry, my app is running in Browser mode, not supporting Node.
The plugins example must be converted: 
```
        //const { Editor } = toastui;
        //const { chart, codeSyntaxHighlight, colorSyntax, tableMergedCell, uml } = Editor.plugin;

        const Editor = toastui.Editor;
        const chart = Editor.plugin.chart;
        const codeSyntaxHighlight = Editor.plugin.codeSyntaxHighlight;
        const colorSyntax = Editor.plugin.colorSyntax;
        const tableMergedCell = Editor.plugin.tableMergedCell;
        const uml = Editor.plugin.uml;
```
So I must initialize from `toastui`.

And the scripts of the page is: 
```
    <script src="~/apps/toast-ui/tui-code-snippet.js?v=2.3.2"></script>
    <script src="~/apps/toast-ui/toastui-editor-all.min.js?v=2.3.1"></script>
    <script src="~/apps/toast-ui/plugins/toastui-editor-plugin-chart.min.js"></script>
    <script src="~/apps/toast-ui/plugins/toastui-editor-plugin-code-syntax-highlight-all.min.js"></script>
    <script src="~/apps/toast-ui/plugins/toastui-editor-plugin-color-syntax.min.js"></script>
    <script src="~/apps/toast-ui/plugins/toastui-editor-plugin-table-merged-cell.min.js"></script>
    <script src="~/apps/toast-ui/plugins/toastui-editor-plugin-uml.min.js"></script>
```

But I found nothing about (export) toastmark in `https://github.com/nhn/tui.editor/blob/master/apps/editor/index.d.ts`
And also I tried from console and all are `undefined`:
![image](https://user-images.githubusercontent.com/1308706/97422550-eaa5b480-1948-11eb-9d71-fe6a9b0236a4.png)

**So should I import another toastmark  js file at first?**

Thank you very much!

**Comment by taurenshaman** [comment]
reactivate...

**Comment by clichedmoog** [comment]
https://codesandbox.io/s/toastmark-forked-botzc?file=/src/index.ts
Would anyone help me after this? I thought the variable html would got the rendered HTML but a function.

**Comment by christophersansone** [comment]
I just ran into this myself.  Just in case others wind up in this situation...

No guarantees that this is the right way to do it these days.  The official documentation seems to indicate you should just use the editor itself at all times.  That said, if you just want to use Toastmark to convert Markdown to HTML, this appears to be the correct incantation currently:

```javascript
import { Parser, createRenderHTML } from '@toast-ui/toastmark';

const parser = new Parser();
const root = parser.parse(content);
const renderHTML = createRenderHTML();
return renderHTML(root);
```

The only difference between @seonim-ryu's version and this one is that `createRenderHTML` returns a function, and then you call that function to perform the render.
