### ISSUE TITLE
Editor add `<br>` in code block when user press enter

### ISSUE THREAD

**Issue by ngthtung** [nhn/tui.editor#1244]
## Summary
Why Editor add `<br>` when user enter with code block?

## Screenshots
This is mode WTSIWYG: 
![image](https://user-images.githubusercontent.com/43090730/97273572-24ea5580-1866-11eb-9f9b-ef06dddb4021.png)

This is mode Markdown:
![image](https://user-images.githubusercontent.com/43090730/97273622-32074480-1866-11eb-8e91-971ef82cd7d5.png)

Actually: I wanna this ( no `<br>` in mode markdown ) :
![image](https://user-images.githubusercontent.com/43090730/97273756-5105d680-1866-11eb-8765-a232ebdebd85.png)

Is that config for this?

## Version
Lastest

**Comment by seonim-ryu** [comment]
@ngthtung Added `<br>` to match different usability between WYSIWYG and Markdown. In WYSIWYG, an empty newline is added when you hit enter, and there is no way to keep the added newline when you convert it to WYSIWYG -> Markdown -> WYSIWYG. 

Currently, the default specification is to add `<br>`, but we will discuss to add an option.

**Comment by ngthtung** [comment]
@seonim-ryu Thank you. So this is a feature need to be discussed? I will close this issues?

**Comment by stephantabor** [comment]
@seonim-ryu

These extra `<br>`s are problematic for things i'm using the editor for. For example when they get added before a markdown table you'll end up with output like 

```md
<br>
| Name |
| ---- |
```

which will render fine in your viewer, but if i take the output markdown and want to have it in a GitHub Readme, or run it through `markedjs` then the table won't be recognized.

**Comment by ngthtung** [comment]
+1, I have same problem.
