### ISSUE TITLE
Make this editor full screen onClick in react.

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1245]
I am trying to make this editor full screen using a button. I got the toolbar instance like this `const toolbar = editorRef.current.getInstance().getUI().getToolbar();`. Then i tried to add a button referring this issue  https://github.com/nhn/toast-ui.vue-editor/issues/15  and  https://github.com/nhn/tui.editor/issues/1024
```js
 const toolbar = editorRef.current.getInstance().getUI().getToolbar();
            toolbar.insertItem(5, {
                type: 'button',
                options: {
                    className: 'full-screen',
                    event: 'test',
                    tooltip: 'Full screen',
                    text: 'F',
                    el:getFullScreenButton(),
                    style: 'background:none;border-color:lime;',
                }
         });
```

#### getFullScreenButton()
```js
const getFullScreenButton =()=> {
        return `<button>B</button>`
    }
```
It reports  me 
```js
TypeError: this.el.appendChild is not a function
```
### What is the correct way to add a button in the React to the toolbar?

**Comment by seonim-ryu** [comment]
@ats1999 First of all, the value you returned is a string, so an error occurs. You have to make a dom and return it.

>https://github.com/nhn/tui.editor/blob/3a0e0a93ae1970c2232060bf3ff747dd22413563/apps/editor/src/js/ui/toolbar.js#L138

**Comment by ats1999** [comment]
```js
                  el:()=>{
                        return <button>B</button>
                    }

//-----------------------
return document.createElement("BUTTON").innerHTML="B"

// ---------------------
return <div>C</div>


```


### after removing
```js
toolbar.insertItem(5, {
                type: 'button',
                options: {
                    className: 'full-screen',
                    event: 'test',
                    tooltip: 'Full screen',
                    text: 'F',
                    style: 'background:none;border-color:lime;',
                }
            });
```
All of the above having the same error
> TypeError: this.el.appendChild is not a function
This adds a 

![Screenshot (462)](https://user-images.githubusercontent.com/54087826/98292401-c446df80-2000-11eb-82dd-e81b8ced0fb8.png)
button, but it doesn't add any text.

**Comment by seonim-ryu** [comment]
@ats1999 First of all, I think this code is wrong. Did you return at the same time as the assignment?

```js
document.createElement("BUTTON").innerHTML="B"
```
