### ISSUE TITLE
Is there a way to set line break for a placeholder option?

### ISSUE THREAD

**Issue by djbicycle** [nhn/tui.editor#1247]
## Summary
I know there is a option for placeholder in editor, 
but I cannot find a way to set link break in the content of the placeholder.
I tried &#13;&#10; for a line break, but it doesn't work.
Is there any way to do that?

## Version
@toast-ui/editor:  2.4.0
@toast-ui/vue-editor: 2.4.0

## Additional Content
I tried &#13;&#10; for a line break, but it doesn't work
`<editor
    :initialValue="value"
    ref="refEditor"
    :options="editorOptions"
    initialEditType="wysiwyg"
 />`
`editorOptions: {
        placeholder: "line1 &#13;&#10; line2"
  },`

**Comment by seonim-ryu** [comment]
@djbicycle First, put a newline character between the text you want to newline.

```js
const editor = new Editor({
  // ...
  initialEditType: 'wysiwyg',
  placeholder: 'line1 \n line2'
});
```
Then, you need to customize it. You can add a style to the CSS selector as follows.

```css
.tui-editor-contents-placeholder::before {
  white-space: pre;
}
```
![wwe](https://user-images.githubusercontent.com/18183560/98058486-36e07f80-1e88-11eb-8f7c-f5cd02d3e9c1.png)

**Comment by djbicycle** [comment]
> @djbicycle First, put a newline character between the text you want to newline.
> 
> ```js
> const editor = new Editor({
>   // ...
>   initialEditType: 'wysiwyg',
>   placeholder: 'line1 \n line2'
> });
> ```
> 
> Then, you need to customize it. You can add a style to the CSS selector as follows.
> 
> ```css
> .tui-editor-contents-placeholder::before {
>   white-space: pre;
> }
> ```
> 
> ![wwe](https://user-images.githubusercontent.com/18183560/98058486-36e07f80-1e88-11eb-8f7c-f5cd02d3e9c1.png)

It works, thank you!
