### ISSUE TITLE
I would like to use the editor as a CDN. Can I use CDN as below?

### ISSUE THREAD

**Issue by caleb-donghun** [nhn/tui.editor#1266]
## Summary
I would like to use the editor as a CDN. Can I use CDN as below?
-Editor, using YouTube Plug-in.

<script src="https://uicdn.toast.com/tui-editor/latest/tui-editor-Editor-full.js"></script>

-link stylesheet
https://uicdn.toast.com/tui-editor/latest/tui-editor.css 
https://uicdn.toast.com/tui-editor/latest/tui-editor-contents.css
https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/codemirror.css
https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css

## Screenshots
If applicable, add screenshots to help explain your question.

## Version
Write the version of the Editor you are currently using.

**Comment by seonim-ryu** [comment]
@caleb-donghun First of all, the URL of the CDN you gave me is version 1. Do you ever want to know the CDN information of version 1? If you want to know the latest version (v2) of the CDN usage information, please check the document below.

* https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/getting-started.md

**Comment by caleb-donghun** [comment]
@seonim-ryu 
Thank you for your quick answer!
I want to know the CDN address of version 1!
Please check!

**Comment by seonim-ryu** [comment]
@caleb-donghun First, the list of files provided by CDN in version 1 is as follows.

> https://github.com/nhn/tui.editor/tree/1.4-production/dist

The CDN URLs used in the first question you asked are all correct, and you have to load the files in the order of the example below. And files with relative paths of `../dist` can be regarded as being changed to CDN paths.

> https://github.com/nhn/tui.editor/blob/1.4-production/examples/example01-editor-basic.html

**Comment by caleb-donghun** [comment]
@seonim-ryu 
Thank you for your quick answer and for your help!
Have a good day!!!
