### ISSUE TITLE
【The editor is used within the VUE】I cannot use v-model to bidirectional bind text in the Editor. I cannot get the text in the Editor

### ISSUE THREAD

**Issue by 1537069101** [nhn/tui.editor#1269]
![image](https://user-images.githubusercontent.com/65661460/100333034-13cf6880-300d-11eb-836a-1f1602c5577f.png)
![image](https://user-images.githubusercontent.com/65661460/100333028-129e3b80-300d-11eb-908b-81669ea6639e.png)
Even if I give the initial value, the text in my editor is blank
![image](https://user-images.githubusercontent.com/65661460/100333079-2184ee00-300d-11eb-974e-082890498856.png)
Can someone help me？？？？

**Comment by js87zz** [comment]
@1537069101 
check this issue(#1067)
