### ISSUE TITLE
Provide alt text to addImageBlobHook

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1271]
## Current Behavior
Currently, addImageBlobHook takes two parameters `(blob, callback)`. In this way, we are not able to pass alt text `![alt](url)`. 

## Expected Behavior
can we have a third parameter `(blob, alt, callback)` and we can use it like this.
```js
callback(URL,alt)
```

**Comment by seonim-ryu** [comment]
@ats1999 The function you talked about is like this. If this is correct, I will make sure to include it when developing features.

> https://github.com/nhn/tui.editor/issues/692#issuecomment-557377258
