### ISSUE TITLE
build error in libs/squire.

### ISSUE THREAD

**Issue by joielee09** [nhn/tui.editor#1274]
## Summary

I am following this docs for making PR.
![image](https://user-images.githubusercontent.com/67178982/100549120-726a4000-32b4-11eb-88c8-956476513258.png)

I forked && cloned tui.editor.
I was trying to build libs/squire.
npm installed and did npm run build.
but got this error

## Screenshots
![image](https://user-images.githubusercontent.com/67178982/100548939-4c906b80-32b3-11eb-8799-9707f281fb0b.png)

## Version
the latest version of git repository

## Additional context

package.json in squire
![image](https://user-images.githubusercontent.com/67178982/100548982-8cefe980-32b3-11eb-994a-ba0fcddcc52c.png)

**Comment by js87zz** [comment]
@joielee09 
windows env doesn't support that script as default. 
Please look for the method to run the **makeFile** and **make** script in windows.
