### ISSUE TITLE
Got this bug on github  Dependabot.

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1282]
>Dependabot cannot update highlight.js to a non-vulnerable version

The latest possible version that can be installed is 9.18.5 because of the following conflicting dependency:
```
@toast-ui/editor-plugin-code-syntax-highlight@1.0.0 requires highlight.js@^9.18.1
The earliest fixed version is 10.4.1.
```
View logs or learn more about troubleshooting Dependabot errors.

**Comment by seonim-ryu** [comment]
@ats1999 I know. The major version of `highlight.js` has been upgraded, so I have to check if it affects the Editor and update the version, so I'm not getting merged. I'll let you know in the future.

**Comment by ats1999** [comment]
Sure
