### ISSUE TITLE
how to resize image on toast ui editor (not image edidtor)

### ISSUE THREAD

**Issue by sangeunnn** [nhn/tui.editor#1286]
## Summary
A clear and concise description of what the question is.

## Screenshots
If applicable, add screenshots to help explain your question.

## Version
Write the version of the Editor you are currently using.
2.0
## Additional context

hello, this is toast ui 2.0 editor user.
I'm working with this editor and now stuck with some problem that resizing images.
I googled and googled and googled but I couldn't find way to solve the problem.
how can I resize images (reduces), which are strictly translated to base64 strings on eidotor
is there any resize plugins or methods? please helppp..

**Comment by seonim-ryu** [comment]
@sangeunnn Can you handle image resizing through the server? If that's possible, you could think of a way to upload an image using the `hooks.addImageBlobHook` option and add it to the editor after resizing when a hook occurs.
