### ISSUE TITLE
jquery object doesn't have expected methods.

### ISSUE THREAD

**Issue by jjangga0214** [nhn/tui.editor#129]
## Version
1.0.5

## Test Environment
ubuntu 16.04, chrome. 64 bits. chrome browser v.65.0.3325.181

## Current Behavior
jquery object doesn't have expected methods.

```js
const editor = new tui.Editor({
            el: document.querySelector('#foo'),
            //other options...
        });
editor.getHtml(); //works fine
```

```js
const $editor = $('#bar');
$editor.tuiEditor({
            //options...
        });
$editor.getHtml(); //fails. Because the jquery object doesn't have the method
```

## Expected Behavior
I expect jquery object works just like a plain javascript object does, at least support useful methods, such as `getHtml`, as shown above.

**Comment by kyuwoo-choi** [comment]
Nice point @jjangga0214 
That's a reasonable improvement I think.

I'll look into what the other jquery plugin does on this.

**Comment by Artistan** [comment]
+1
