### ISSUE TITLE
Why window instance is required on the server.

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1291]
related issue https://github.com/nhn/tui.editor/issues/1222

Window instance is required for this editor, this is not a big problem. But, why window instance is also required in the `Viewer` component. I am using **NextJs with ReactJs**, i need to render markdown content on the server. Because of this problem, i am not able to render markdown content on the server. 

Although i can use `dynamic` provided by **nextJs** to render content on the client-side. But, we are not using a server-side rendering feature.

**Comment by seonim-ryu** [comment]
@ats1999 I have a question. You said that accessing the `window` object is a problem when using `Viewer`. Can you tell me where to access the `window` object? It also tells you whether the problem is when you render or when you build.

**Comment by ats1999** [comment]
> Can you tell me where to access the window object?

I know the server does not have any window object. So, we can't use the window on the server. 

My question is **Why window instance is required in the viewer component?** I can guess, this editor might be using any function to convert markdown text into **HTML** content. 

> If I can get access to that function anyhow then also I can render content on the server. 

Until a window object is required, I can not use the server-side rendering feature.
