### ISSUE TITLE
Question: How would I retrieve images behind an authorization API?

### ISSUE THREAD

**Issue by thraizz** [nhn/tui.editor#1293]
## Summary
I am currently searching for a way to proxy the requests for uploaded images, as these requests require an `Authorization` header.

## Screenshots
Does not apply.

## Version
```
├─ @toast-ui/editor@2.5.0
├─ @toast-ui/vue-editor@2.5.0
│  └─ @toast-ui/editor@^2.5.0
```

## Additional context
I am really happy with the editor and this is more a general question than editor specific, but maybe you can help me anyway. I've already implemented the `addImageBlobHook` to post the image to our server, but can't request it since it requires an `Authorization` header. This can't be done in plain HTML if i am correct, so I was looking for some alternative and found the customHTMLSanitizer, which allows me to modify the html before it gets displayed. I was thinking about using a kind of parser for every image, fetch its url with the right header and then replace the image src with the base64 data.
Do you have another, more obvious approach to this?

Thank you for the hard work on the editor and the other tools in the tui toolbox, its very much appreciated.

**Comment by thraizz** [comment]
For the reference, if one might stumble upon this issue: I adapted the API receiving and serving the images to a cookie-based authentication method. By that, I POST the image over the `addImageBlobHook` and receive a cookie as response. The GET request for the embedded image will then send the cookie to the server, allowing me to authenticate the request.

**Comment by juokavom** [comment]
For anyone reading who still haven't solved this issue, you can load your image in base64 format. By using that you can fetch your image from authorized endpoint (etc. using XMLHttpRequest with credentials header), convert it to base64 and pass it to LoadImage > path. Here's my code:


    const [imgContents, setImgContents] = useState<string | null>(null)
    function toDataURL(url: string, callback: (response: any) => void) {
        var xhr = new XMLHttpRequest();
        xhr.onload = function () {
            var reader = new FileReader();
            reader.onloadend = function () {
                callback(reader.result);
            }
            reader.readAsDataURL(xhr.response);
        };
        xhr.open('GET', url);
        xhr.responseType = 'blob';
        xhr.withCredentials = true;
        xhr.send();
    }

    useEffect(() => {
        toDataURL(ENDPOINTS.FILE.streamWithFileId(id), (response) => {
            setImgContents(response)
        })
    }, [])

    if (imgContents) {
        return (
            <div className="container">
                <ImageEditor
                    includeUI={{
                        loadImage: {
                            path: imgContents,
                            name: title,
                        },
                        ...

**Comment by valekask** [comment]
I did a custom plugin for Toast UI Editor that adds Authorization header on image loading:

```js
function customImageLoaderPlugin() {
  const toHTMLRenderers = {
    image(node, context) {
      const { origin } = context;
      const { destination, id } = node;
      const result = origin();
      const serverUrl = window.location.origin + "/rest/";
      const token = authService.getToken();

      // Skip custom image loading for images outside my domain
      if (!destination.startsWith(serverUrl)) {
        return result;
      }

      fetch(destination, {
        headers: {
          Authorization: "Bearer " + token,
        },
      })
        .then((response) => response.blob())
        .then((blob) => {
          const reader = new FileReader();
          reader.onloadend = function () {
            // Find image by id and replace src with base64
            const nodeId = `[data-nodeid="${id}"]`;
            const img = document.querySelector(nodeId);
            if (img) {
              img.src = reader.result;
            }
          };
          reader.readAsDataURL(blob);
        });

      // Dump image src to prevent loading protected image
      result.attributes.src = "";
      return result;
    },
  };

  return { toHTMLRenderers };
}
```
