### ISSUE TITLE
How to disable HTML rendering?

### ISSUE THREAD

**Issue by IntinteDAO** [nhn/tui.editor#1295]
Hello. HTML is a language that I think is difficult to verify - hence the various XSS attacks.

My idea is to block the rendering of HTML code in TUI Editor so only Markdown can be rendered. Markdown, in my opinion, is much easier to parse, so the website could be safe.

While I have different ideas, I don't know how to start - I am thinking about using my own Convertor, but according to my tests, it disable Markdown not HTML.

Is there any way (preferably an example, because I'm not an expert on Javascript) to disable rendering of HTML code and allow Markdown to work?

**Comment by seonim-ryu** [comment]
@IntinteDAO It looks like you want to block rendering `<strong>foo</strong>` typing in the Markdown editor. First of all, the TOAST UI Editor is sanitizing html and properties that might be the problem of XSS (e.g. `<script />`, `javascript:`).

> Default Sanitizer : https://github.com/nhn/tui.editor/blob/master/apps/editor/src/js/htmlSanitizer.js

If you want to add additional sanitization, you can use the options below.

```js
const editor = new Editor({
  customHTMLSanitizer: html => {
    return DOMPurify.sanitize(html);
  }
});
```
> Example : https://nhn.github.io/tui.editor/latest/tutorial-example22-using-custom-sanitizer
