### ISSUE TITLE
TypeError: Cannot read property 'Range' of null when using TUI in Laravel Livewire component

### ISSUE THREAD

**Issue by gavinhewitt** [nhn/tui.editor#1297]
## Summary
I'm trying to integrate TUI into Laravel Livewire/AlpineJS component (https://laravel-livewire.com/, https://github.com/alpinejs/alpine), which works, but I get this error _after_ successfully posting the markdown to the component. Somehow some value is cleared I think? Not sure what it precisely means and how to resolve it.

## Screenshots
![image](https://user-images.githubusercontent.com/1969103/101693917-99720000-3a72-11eb-993f-6561cca3a6b2.png)

## Version
version 2.2.0

**Comment by seonim-ryu** [comment]
@gavinhewitt Just by looking at the images, I can't figure out exactly where or what problems are occurring. I would appreciate it if you reproduce the situation where the error occurs when running using something like a code sandbox.

**Comment by gavinhewitt** [comment]
Hi @seonim-ryu,

Thanks for the reply. I did some more investigating and traced it back to livewire/alpine doing some kind of clearing of the values. It (most likely) doesn't have anything to do with TUI. I just didn't think of closing this issue, sorry.

**Comment by nfhh** [comment]
@gavinhewitt Hello! Can you show me your TUI AlpineJS component? Thanks!
