### ISSUE TITLE
Provide content on https version of plantuml. 

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1310]
## Version
latest

## Current Behavior
uml code block generates an image, which is delivered over http.

One of the image URL is 
http://www.plantuml.com/plantuml/png/HOsn2iCm34HtVONH6c7iTFEKGF-YT118Gulh1jifAS7_tjGTUjFTFOwhjnhLSCxyDhhnOuaAKwcSwxqy4-nW3k7yvHX-gJSlZgjYk7WQwKHehKN2TH6kAeTBWqVQsvN-2nR9MWe6TCxFtfsnimOD9atIxpu0

Although, there is **HTTPS** version available.
https://www.plantuml.com/plantuml/png/HOsn2iCm34HtVONH6c7iTFEKGF-YT118Gulh1jifAS7_tjGTUjFTFOwhjnhLSCxyDhhnOuaAKwcSwxqy4-nW3k7yvHX-gJSlZgjYk7WQwKHehKN2TH6kAeTBWqVQsvN-2nR9MWe6TCxFtfsnimOD9atIxpu0

## Expected Behavior
serve plantuml contents over HTTPS, because this is generating mixed-content-warning. Some, times it blocks requests or it removes the SSL lock icon from the address bar.

**Comment by seonim-ryu** [comment]
@ats1999 First of all, you can change the default image path using the options below. I'll discuss and let you know about changing the protocol.
> https://github.com/nhn/tui.editor/tree/master/plugins/uml#optional-use-plugin-with-options

**Comment by ats1999** [comment]
thanks, it worked.
