### ISSUE TITLE
Are you planning to support for vue 3?

### ISSUE THREAD

**Issue by youngpark17** [nhn/tui.editor#1325]
Itoastui-vue-editor.js?4ede:7 Uncaught (in promise) TypeError: Cannot read property '_c' of undefined
    at Proxy.i (toastui-vue-editor.js?4ede:7)
    at renderComponentRoot (runtime-core.esm-bundler.js?5c40:710)
    at componentEffect (runtime-core.esm-bundler.js?5c40:4193)
    at reactiveEffect (reactivity.esm-bundler.js?a1e9:42)
    at effect (reactivity.esm-bundler.js?a1e9:17)
    at setupRenderEffect (runtime-core.esm-bundler.js?5c40:4176)
    at mountComponent (runtime-core.esm-bundler.js?5c40:4134)
    at processComponent (runtime-core.esm-bundler.js?5c40:4094)
    at patch (runtime-core.esm-bundler.js?5c40:3715)
    at mountChildren (runtime-core.esm-bundler.js?5c40:3897)

This is an error message I got. It seems because of the version of vuejs.
There already have the same issue(#1226 ), but No answer, so I post again.

and Is there a way to apply vue3 for this editor?

`<script>
import 'codemirror/lib/codemirror.css';
import '@toast-ui/editor/dist/toastui-editor.css';

import { Editor } from '@toast-ui/vue-editor';

export default {
  name: 'Write',
  components: {
    editor: Editor,
  },
  data() {
    return {
      source: '# Hello World!',
    };
  },
};
</script>
{
  "name": "front",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@toast-ui/editor": "^2.5.1",
    "@toast-ui/vue-editor": "^2.5.1",
    "codemirror": "^5.59.0",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-airbnb": "^5.0.2",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-vue": "^7.0.0-0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "@vue/airbnb"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

`

**Comment by seonim-ryu** [comment]
@youngpark17 There are plenty of plans to update to Vue 3. However, the Editor 3.0 is currently under development, and it is necessary to check what issues there are when updating to Vue 3, so we plan to apply it after the major version update.

**Comment by playsthisgame** [comment]
There is still currently no support for Vue 3. I think this should be addressed, Vue 3 has been out for 2 years and is considered the standard going forward.
