### ISSUE TITLE
I want to change the fontFamily in TOASTUI image editor... I'm working in react js. Anyone has an example :(

### ISSUE THREAD

**Issue by JhosepGC14** [nhn/tui.editor#1341]
## Version
Write the version that you are currently using.

## Development Environment
Write the browser type, OS and so on.

## Current Behavior
Write a description of the current operation. You can add sample code, 'CodePen' or 'jsfiddle' links.

```js
// Write example code
```

## Expected Behavior
Write a description of the future action.

**Comment by seonim-ryu** [comment]
@JhosepGC14 This is where TOAST UI Editor issues are registered. For issues of TOAST UI ImageEditor, please register on GitHub below. I'll close this issue.

> https://github.com/nhn/tui.image-editor
