### ISSUE TITLE
Do not change id of heading, when the color changed, because it prevents us from creating TOC.

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1345]
I have used customHTMLRenderer in order to give id attributes to the heading tags. This is required to create **TOC**.
I am changing id like this.
```js
let id = node.firstChild && node.firstChild.literal?node.firstChild.literal:""
id = id.replace(/[^\w\s]/gi, " ")
        .trim()
        .replace(/ +/g, " ")
        .split(" ").join("-");
 if (context.entering) {
        return {
          type: "openTag",
          tagName,
          attributes: {
            id: id
          }
        };
      }

  return { type: "closeTag", tagName,
        attributes: {
            id: id
        }
    };
```
## Current Behavior
**Md in editor**
```js
# This is h2
```
**Result html**
![Screenshot (526)](https://user-images.githubusercontent.com/54087826/104796306-28f49680-5809-11eb-8b2d-1f10e6236993.png)

When we change text color using the plugin provided by the editor.
![Screenshot (527)](https://user-images.githubusercontent.com/54087826/104796321-4e81a000-5809-11eb-94d3-09fc46507a50.png)

## Expected Behavior
The id should not change after we change color.

**Comment by seonim-ryu** [comment]
@ats1999 Can you make it an example CodeSandbox? And why do you want to use id?

**Comment by ats1999** [comment]
@seonim-ryu 
Go to https://bdevg.com/articles/write and paste the code below
```js
# [go-there](#go-there)
# [I'll not go](#i-will-not-go)

# Heading levels

> This is a fixture to test heading levels

<!-- toc -->

## Heading

This is an h1 heading

### Sub-heading

This is an h2 heading

#### Sub-sub-heading

This is an h3 heading

## Heading

This is an h1 heading

### Sub-heading

This is an h2 heading

#### Sub-sub-heading

This is an h3 heading

# go there
# <span style="color:#e71717">i will not go</span>
## Heading

This is an h1 heading

### Sub-heading

This is an h2 heading

#### Sub-sub-heading

This is an h3 heading
```
You can see clicking on go there will work `go-there`, but clicking on `I'll not go` will not work. The reason is, when we change the color of `h1` then it's id becomes `span-style-color-e71717` instead of `i-will-not-go`
