### ISSUE TITLE
How to add MathJax support?

### ISSUE THREAD

**Issue by wwwagusw** [nhn/tui.editor#136]
How to add mathjax support on viewer with inline equation $x^2$ or display equation $$x^2$$?

**Comment by kyuwoo-choi** [comment]
We don't have mathjax support for now.

I think you can try to create a extension for it. If you want.

[Writing your own extension](https://github.com/nhnent/tui.editor/blob/master/docs/writing-your-own-extension.md)
[Example](http://nhnent.github.io/tui.editor/api/latest/tutorial-example12-writing-extension.html)

**Comment by Ray-Eldath** [comment]
request for this feature either =-=

**Comment by dolphin0618** [comment]
我比较屎办法的实现你的需求，我使用了比较轻量级的katex，过程遇到各种坑，tui.editor扩展并不友好,API很多不知该如何下手。我尝试了各种方案。

首先我们不能使用create a extension的方案。因为他是用``[name] x^2```，而我们需要用$$x^2$$来包裹。

然后我想在markdown传递数据给view的时候，拦截手动转换$$表达式，但是我并没有找到相关的钩子。

我的最终方案在change事件中，替换了获取getHtml用katex整体转换我需要的html，然后`editor.preview.$el.html(html)。`现在看起来似乎成了，但我又发现原本自动更新的操作会影响到我的替换。我索性这样做`editor.preview.$el.html('<div class="tui-editor-contents">' + html+ '</div>'); `it's ok。

这样做完全可以不用它自带的preview组件，我只是期望保留他的左右布局功能markdown and WYSIWYG

虽然这种方案不是很好，但它可以工作。期望更好的解决方案
