### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by KeyC0de** [nhn/tui.editor#1368]
I get error `lerna ERR! npm run build exited 1 in '@toast-ui/squire'`
when running `npm run setup:libs`

**Comment by seonim-ryu** [comment]
@KeyC0de Currently, when building Squire, you have to run it with the `make` command, but it is not in your Windows, so a build error occurs. The solution to this problem is to install a package that can run the `make` command on Windows.

> http://gnuwin32.sourceforge.net/packages/make.htm

**Comment by tasty0tomato** [comment]
And it will be a better idea to build it in [Cygwin](https://www.cygwin.com/)
