### ISSUE TITLE
indentation not work in WYSIWYG Mode

### ISSUE THREAD

**Issue by panjiangyi** [nhn/tui.editor#1376]
## To Reproduce
1. go to [Editor With WYSIWYG Mode](https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-with-wysiwyg-mode)
2. click the Indent button
3. text didn't indent

## Expected behavior
Indent a line of text.

## Desktop 
- OS:MacOS Big Sur Version 11.1
- Browser : Version 88.0.4324.96 (Official Build) (x86_64)
- Version:Lastest.

**Comment by seonim-ryu** [comment]
@panjiangyi The indent and outdent buttons on the toolbar are for lists. So this is not a bug.

**Comment by AndrewDavis** [comment]
> @panjiangyi The indent and outdent buttons on the toolbar are for lists. So this is not a bug.

Should say "List Indent", or something along those lines then; otherwise, it kinda is a bug because many users, myself included, will think it's general indentation, which is why we're here in the first place.
