### ISSUE TITLE
plugin wrapper not creating

### ISSUE THREAD

**Issue by Yongjun042** [nhn/tui.editor#1378]
## Summary
I'm trying to make some plugin but the plugin cannot create a wrapper.
On perview side it shows blank box.
el from renderYoutube returns null.
I have no idea what is wrong.

## Version
    "@toast-ui/react-editor": "^2.5.1",
using react ts
## Additional context
`

export default class edit extends Component {

    editorRef = React.createRef<Editor>();
    youtubePlugin = (editor) => {
        const { codeBlockManager } = Object.getPrototypeOf(editor).constructor
        codeBlockManager.setReplacer('youtube', (youtubeId) => {
            const wrapperId: string = `yt${Math.random()
                .toString(36)
                .substr(2, 10)}`;
            console.log(youtubeId);
            setTimeout(this.renderYoutube.bind(null, wrapperId, youtubeId), 0);
            return `<div id="${wrapperId}></div>`;
        }
        )
    };

    renderYoutube = (wrapperId, youtubeId) => {
        const el = document.querySelector(`#${wrapperId}`);
        console.log(el);
        if (el != null) {
            el.innerHTML = `<iframe width="420" height="315" src="https://www.youtube.com/embed/${youtubeId}"></iframe>`;
        }
    }
    render() {
        return (
            <Editor
                previewStyle="vertical"
                height="400px"
                initialEditType="markdown"
                plugins={[this.youtubePlugin]}
                ref={this.editorRef}
            />
        )
    }
}

`

**Comment by seonim-ryu** [comment]
@Yongjun042 There is an example that someone else made before, and I think you can refer to this.

> https://github.com/nhn/tui.editor/issues/1169#issue-686251015

**Comment by Yongjun042** [comment]
Thak you. @seonim-ryu . Solved by moving function out of class.
