### ISSUE TITLE
Custom Render in Preview

### ISSUE THREAD

**Issue by INFLCR-Kalyn** [nhn/tui.editor#1379]
## Summary
I am trying to render a youtube video with a custom pattern that doesn't exist in a codeblock as in the custom plugin example. If I have the pattern in the markdown view, can I render this in the preview as an iframe?

## Screenshots
If applicable, add screenshots to help explain your question.

## Version
Write the version of the Editor you are currently using.

**Comment by seonim-ryu** [comment]
@INFLCR-Kalyn From what I understand, it seems that you are trying to develop using custom syntax without using code blocks. If this is correct, it is difficult in the current version. Instead, v3 will provide custom syntax.

**Comment by INFLCR-Kalyn** [comment]
> @INFLCR-Kalyn From what I understand, it seems that you are trying to develop using custom syntax without using code blocks. If this is correct, it is difficult in the current version. Instead, v3 will provide custom syntax.

That is correct! I think I can work with this in the meantime while I wait for v3. Thanks!
