### ISSUE TITLE
Heading tags are not escaped when used alone.

### ISSUE THREAD

**Issue by 960813** [nhn/tui.editor#1380]
## Describe the bug
Heading tags are not escaped when used alone.

## To Reproduce
1. Go to WYSIWYG Tab
2. Type #
3. Change to Markdown Tab
4. Change to WYSIWYG Tab
5. see error

## Expected behavior
I wanted the #, ##, ... to remain in WYSIWYG, but it doesn't. Replaced with \<h1\>, \<h2\>, etc. 

## Screenshots
![cap](https://user-images.githubusercontent.com/44586666/107158078-064e3b80-69cb-11eb-9523-05caaad40b1c.gif)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox
 - Version: 85.0.1 (64-bit)

**Comment by seonim-ryu** [comment]
@960813 First of all, this is a spec, not a bug. In WYSIWYG, markdown's delimiters (eg `#`, `*`) used and the markdown syntax is completed, it is escaped when converted to markdown.
