### ISSUE TITLE
Inserting a simple html element in WYSIWYG (current 'solution' inside)

### ISSUE THREAD

**Issue by thraizz** [nhn/tui.editor#1384]
## Versions
Editor: 2.5.1
Vue Editor: 2.5.1
Vue: 2.6.12
## Development Environment
Firefox 83.0b1
Arch Linux, Kernel 5.10.13

## Current Attempt
We use the WYSIWYG mode only and use html. This works really great, especially the ability to create tables is something unique and cant be found in other WYSIWYG editors.
We use a modal to allow the upload of PDFs. These need to be linked in the document we create at the cursor position of the user. So I am trying to insert a simple `<a href="locationOfThePDF">filename.pdf</a>` at the cursor position.  
Currently I am able to create a widget outside of the editor that does exactly what we want:
The code for this looks like this:
```js
      insertURL: function (link) {
        const range = this.$refs.editor.invoke('getRange')
        const aElement = document.createElement('a')
        aElement.innerHTML = `<a href="${link.url}">${link.name}</a>`
        this.$refs.editor.invoke('addWidget', range, aElement)
      },
```

## Expected Outcome
How do I do this _IN_ the editor? I tried to get the HTML with `editor.invoke('getHTML')` but I cant find a way to determine the current cursor position. If I had this, i could split the text returned by `getHTML`, insert our tag, and then set the HTML with `setHTML`.

**Comment by seonim-ryu** [comment]
@thraizz First of all, in the current situation, I can't predict what type of widget you are going to put. `addWidget` is usually used when handling the following UI. So, can you explain in more detail what features you want to implement?

And I think you can use the `change` event in the link below for the cursor position.

> https://github.com/nhn/tui.editor/issues/968#issuecomment-625706640

**Comment by thraizz** [comment]
Thanks for tour answer. 
Widget is definetly the wrong approach. I wish to insert into the data of the editor, not to modfiy the ui.

I have a modal where the user can upload a file. This modal tries to insert a link into the editors data, so that when the user saves the and the application invokes `getHtml` on the editor the data should contain the link.
