### ISSUE TITLE
What's a good way to insert Markdown text anywhere, regardless of mode (Markdown, WYSIWYG)? 

### ISSUE THREAD

**Issue by 960813** [nhn/tui.editor#1386]
I am using the editor.setmarkdown method, but when I use it in WYSIWYG, unwanted results occur.

![녹화_2021_02_15_02_37_34_589](https://user-images.githubusercontent.com/44586666/107884185-d5c05180-6f36-11eb-876b-f0c998334ff3.gif)
The text is inserted in WYSIWYG as it is. 

So, I check the mode before setmarkdown (using if condition), switch the mode to markdown, and then return to WYSIWYG. Is there a more efficient way? 

```javascript
 if (editor.isMarkdownMode()) {
      editor.setMarkdown(markdown);
  } else {
      editor.changeMode('markdown', true);
      editor.setMarkdown(markdown);
      editor.changeMode('wysiwyg', true);
  }
```

**Comment by seonim-ryu** [comment]
@960813 When I look at the screenshot, in the WYSIWYG mode, when you add an image, the Markdown syntax is added to the WYSIWYG editor. In what situations does that happen? Is it a function you implemented yourself? Seeing that you used `setMarkdown`, it seems that you implemented this function yourself. I think I can know the problem in detail only by looking at that part.
