### ISSUE TITLE
How to resize an image after adding it?

### ISSUE THREAD

**Issue by HANYUNSEONG** [nhn/tui.editor#1391]
## Summary
Is there a way for users to adjust the size(width, height) after adding an image?

## Screenshots
Can you do it like adjusting the size of the picture on the drawing board?

*ex)*
![image](https://user-images.githubusercontent.com/58321856/108174671-168cb600-7143-11eb-9412-df68f9a880b2.png)

## Version
TOAST UI Editor 2.5.1

## Additional context
No matter how much I searched, I couldn't find the answer. help me...

**Comment by seonim-ryu** [comment]
@HANYUNSEONG This feature is not supported.
