### ISSUE TITLE
How do I force editor to produce <br/> instead <br> tags?

### ISSUE THREAD

**Issue by jcimoch** [nhn/tui.editor#1397]
Current default behaviour is on new line editor adds ```<br> tags```, but some markdown parsers require ```<br/>``` to handle it properly. 
I would like to enforce such behaviour on editor level without manual parsing the result on my side. Is it possible?

**Comment by seonim-ryu** [comment]
@jcimoch There is currently no way to change. But can't you convert `<br>` to `<br />` when you put the result of the editor in another markdown parser?

**Comment by jcimoch** [comment]
I can, there was also some issue with \n, was just wondering if such thing could be part of editor configuration, maybe potential feature for 3.0 version?
