### ISSUE TITLE
How to manually add html element to the editor

### ISSUE THREAD

**Issue by filigreti** [nhn/tui.editor#1399]
## Summary
I want to be able to add custom element to the editor, like an href tag based on where the cursor is. or better yet how to access the { linkText, url } in addLink

**Comment by seonim-ryu** [comment]
@filigreti Just looking at this, I'm not sure what exactly you're trying to implement. It looks like you want to add an element using `addWidget`. Would you like to check it?

> https://github.com/nhn/tui.editor/issues/1191#issuecomment-690932913
