### ISSUE TITLE
How to replace markdown text without setMarkdown method?

### ISSUE THREAD

**Issue by takumi-n** [nhn/tui.editor#1401]
## Summary

I've customized TUI Editor to upload image like GitHub comment markdown editor.

1. Drag and drop image to the editor
2. Inserting a progress message like `![Uploading image...]()`
3. Replace the message with a real url like `![foo.png](https://example.com/foo.png)`

To implement this, I've written the following code:

```js
const current = editor.getMarkdown();
const replaced = current.replace('![Uploading image...]()', '![foo.png](https://example.com/foo.png)');
editor.setMarkdown(replaced);
```

It works good, but has a problem.

The editor area is forced to scroll to the bottom after calling setMarkdown if the content in the editor is long.
For example, if I insert some images near the top of the content, the editor will scroll to the bottom.
But I want to keep editing around the top, so this scroll bothers me.

I understand this behavior has no probelm. It is natural the area scrolls to the bottom after setting new content.
So I want to know the other way to replace text without scrolling.

## Version
`@toast-ui/vue-editor 2.3.1`

**Comment by seonim-ryu** [comment]
@takumi-n I think you can use the `addImageBlobHook` option.

> https://github.com/nhn/tui.editor/blob/8e31e3a076805078636eac18be988ae00466ab1f/apps/editor/src/js/editor.js#L114

```js
{
  // ...
  hooks: {
    addImageBlobHook: (fileOrBlob, callback, source) => {
      // ...
      const customDescription = `${description}_foo`;

      callback(imgUrl, customDescription);
    }
  }
}
```

**Comment by takumi-n** [comment]
@seonim-ryu 

I've known `addImageBlobHook` option, but the hook cannot handle drag and drop for multiple files.
So I've handled drag and drop event on myself.

By the way, I looked into the way to do that, then I found `cursorToEnd` parameter of `setMarkdown`. Setting `true` as `cursorToEnd` solved my problem.

Thanks!
