### ISSUE TITLE
Can't install 4058 Error

### ISSUE THREAD

**Issue by AbrahamZak** [nhn/tui.editor#1413]
## Describe the bug
I am getting a 4058 error when trying to install this package for a project I am working on.
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/seonim-ryu/Squire.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

## To Reproduce
1. Running 'npm install --save tui-editor'

## Expected behavior
Installation of the package

## Desktop (please complete the following information):
 - OS: Windows 10
 - Node Version: v14.16.0

**Comment by tyuqing** [comment]
Trying to install the latest version(1.4.10) of tui-editor, I encountered similar problems at version 1.4.4-alpha.1. My problem was fixed in version 1.4.10

**Comment by seonim-ryu** [comment]
@AbrahamZak It is due to GitHub's protocol problem, and it is currently a bit difficult to support version 1. If possible, it would be nice to update to version 2 and use it.

> https://docs.npmjs.com/cli/v7/configuring-npm/package-json#git-urls-as-dependencies
