### ISSUE TITLE
toast ui editor size more low 

### ISSUE THREAD

**Issue by chanhos0626** [nhn/tui.editor#1427]
I'm Salesforce Developer.
Today. Lightning Web Component(lwc) used Develop.
I'm used toastui-editor-all.min.js library.
but I don't Using be cause babel's size limit.
Please. Is there any measure for capacity?

message:
[BABEL] Note: The code generator has deoptimised the styling of c:\Users\guest1\chikpale-lwc\toastui-editor-all.min.js as it exceeds the max of 500KB.

**Comment by seonim-ryu** [comment]
@chanhos0626 When I see the error message you gave me, I think you can change your [bundling configuration options](https://stackoverflow.com/questions/29576341/what-does-the-code-generator-has-deoptimised-the-styling-of-some-file-as-it-e). And I have one question: `toastui-editor-all.min.js` This is a file provided by CDN. Isn't it being developed in a node environment? Looking at this, I don't know in what state (bundling or development) the error occurs.
