### ISSUE TITLE
Let me know the reason and solution for text.replacetext.replace error when calling callback

### ISSUE THREAD

**Issue by DKTaehoonPark** [nhn/tui.editor#1438]
hi
I am using it in a REACT environment.
It's a simple code, so I'll show it as a capture screen
![image](https://user-images.githubusercontent.com/76200254/111103642-3ec8d280-8592-11eb-8bc6-1efdbce1a557.png)

Let me know the reason and solution for text.replacetext.replace error when calling callback

thanks.

**Comment by seonim-ryu** [comment]
@DKTaehoonPark Can you make an example in the [CodeSandbox](https://codesandbox.io/)? It's hard to see the problem just by looking at this.
