### ISSUE TITLE
dblclick event on <img> tag inside Toast UI Editor not working

### ISSUE THREAD

**Issue by Teolone88** [nhn/tui.editor#1444]
## Summary
I am using JQuery to set an event listener to the <img> tag within the document, which cause the cursor to be a pointer and with a dblclick, the wrapping division can be resized using interactJS. However, this is not happening inside the Toast UI Editor and I am not sure why. I am a total n00b with JS and if you could explain me why this is not happening would be great.

## Screenshots
Inside the editor nothing is happening.
![image](https://user-images.githubusercontent.com/36920983/111488147-47a7d880-8739-11eb-96ce-81cf52afed8f.png)
Outside the Editor, the wrapping div of the img can be resized.
![image](https://user-images.githubusercontent.com/36920983/111488371-7625b380-8739-11eb-9aa4-0f38a066760e.png)

## Additional context

**CSS**

```
.resize-drag {width: 120px;border-radius: 8px;padding: 20px;margin: 1rem;background-color: #29e;color: white;font-size: 20px;font-family: sans-serif;touch-action: none;box-sizing: border-box;}
img {width: 100%; height:100%; }
img:hover {cursor: pointer;}
```

**JQuery** (https://code.jquery.com/jquery-3.5.0.min.js)
Dblclick to assign class 'resize-drag' to the closest wrapping div.
```
var selected;
$('img').on('dblclick', function(){
selected = this;
$(selected).closest( 'div' ).toggleClass( 'resize-drag' );
});
```

**JS Vanilla** (https://unpkg.com/interactjs/dist/interact.min.js)
From InteractJS to dynamically assign width and height to class 'resize-drag'
```
interact('.resize-drag')
.resizable({
  // resize from all edges and corners
  edges: { left: true, right: true, bottom: true, top: true },
  
  listeners: {
    move (event) {
      var target = event.target
      var x = (parseFloat(target.getAttribute('data-x')) || 0)
      var y = (parseFloat(target.getAttribute('data-y')) || 0)
      
      // update the element's style
        target.style.width = event.rect.width + 'px'
        target.style.height = event.rect.height + 'px'

        // translate when resizing from top or left edges
        x += event.deltaRect.left
        y += event.deltaRect.top

        target.style.webkitTransform = target.style.transform =
          'translate(' + x + 'px,' + y + 'px)'

        target.setAttribute('data-x', x)
        target.setAttribute('data-y', y)
      }
    },
    modifiers: [
      // keep the edges inside the parent
      interact.modifiers.restrictEdges({
        outer: 'parent'
      }),

      // minimum size
      interact.modifiers.restrictSize({
        min: { width: 100, height: 50 }
      })
    ],

    inertia: true
  })
```

**Comment by js87zz** [comment]
@Teolone88 
Sorry for late replying.
First of all, binding events to editing elements within an our editor is not a recommendation. If this is to be done, something that can be controlled within the editor is needed. 
Anyway, I think it should be possible to control the image, but I don't know exactly what the problem is. Can you give me more detail code in code sandbox or jsfiddle?

**Comment by Teolone88** [comment]
Hi js87zz,

Here the jsfiddle that works with click and resize.
However, this does not work within the toastUI environment.
https://jsfiddle.net/o95v0Lmc/

Best,

Teo
