### ISSUE TITLE
The plugin use in vue-tui

### ISSUE THREAD

**Issue by zhuzhehao1999** [nhn/tui.editor#1446]
## Summary
The plugin use in vue-tui

## Version
v2.5.1

## Additional context
I am a beginner of vue, I want to use the all plugins by use @toast-ui/vue-editor, but I don't know how to input it. In the document, it use
plugins: [[codeSyntaxHighlight, { hljs }]]

but when i type it in
```vue
export default {
  components: {
    editor: Editor,
  },
  data() {
    return {
      editorText: "This is initialValue.",
      editorOptions: {
        hideModeSwitch: false,
      }, 
      plugins: [[codeSyntaxHighlight, { hljs }]]
    };
  },
};
```
it was not success.
Hope that someone can help me. Thanks a lot

**Comment by js87zz** [comment]
@zhuzhehao1999 
The `plugins` option should changed as below.
```js
import 'highlight.js/styles/github.css';

export default {
  // ...
  data() {
    return {
      editorText: "This is initialValue.",
      editorOptions: {
        hideModeSwitch: false,
        plugins: [[codeSyntaxHighlight, { hljs }]]
      }
    };
  },
```

**Comment by Coder-Iro** [comment]
I'm trying to use plugin in nuxt.js.
```vue
<template>
  <client-only>
    <ToastuiEditor initial-edit-type="wysiwyg" :options="editoroption" />
  </client-only>
</template>

<script>
import 'tui-color-picker/dist/tui-color-picker.css'
import tableMergedCell from '@toast-ui/editor-plugin-table-merged-cell'
export default {
  name: 'Admin',
  layout: 'adminpage',
  data() {
    return {
      editoroption: {
        language: 'ko',
        usageStatistics: false,
        plugins: [tableMergedCell],
      },
    }
  },
}
</script>

<style scoped></style>
```
If I use code like this, there would be error because '@toast-ui/editor-plugin-table-merged-cell' is not ssr-friendly.
![image](https://user-images.githubusercontent.com/15701568/112748709-8884d480-8ff8-11eb-8219-43f023613106.png)
How can I solve this?

**Comment by js87zz** [comment]
@Coder-Iro 
It can be a problem in SSR because that plugin directly manipulates the DOM internally. Currently, the 2.x version does not consider this issue, but we will consider the solution in the next 3.x. Thanks!

**Comment by Coder-Iro** [comment]
May I know the release schedule for the 3.x version?

**Comment by zhuzhehao1999** [comment]
thanks
