### ISSUE TITLE
how to use addImageBlobHook in vue? I cannot make it work

### ISSUE THREAD

**Issue by djbicycle** [nhn/tui.editor#1449]
## Summary
addImageBlobHook hook is not working.
No matter what it returns,(true / false/ blob etc)
only the console works and image is not inserted at last.

- HTML -
`<editor  :options="editorOptions" />`

- data definition -
editorOptions: {
     hooks: {
          addImageBlobHook: (blob, callback) => {
               console.log("?");
               return true;
          },
      },
},

## Expected Behavior
"?" is printed on developer console,
and the image is inserted

## What is really happening
"?" is printed on developer console,
and the image is **NOT** inserted

## Version
@toast-ui/editor":  2.5.1
@toast-ui/vue-editor":  2.5.1

**Comment by js87zz** [comment]
@djbicycle 
Can you give your code in code sandbox or jsfiddle?
When i tested it, there was no problem.

**Comment by ezawadzki** [comment]
@js87zz 

I have the same question:

How could I do these two line of codes in VueJs:

```
editor.removeHook('addImageBlobHook'); // remove the default hook
editor.addHook('addImageBlobHook', (blob, callback) => { ... });
```

**Comment by ezawadzki** [comment]
Okay, found [here](https://github.com/nhn/tui.editor/issues/1280)

**Comment by rkddbs1031** [comment]
> Okay, found [here](https://github.com/nhn/tui.editor/issues/1280)

Hello. If it's not rude, can you tell me how to apply it in Vue.js??

this one... 
```
editor.removeHook('addImageBlobHook'); // remove the default hook
editor.addHook('addImageBlobHook', (blob, callback) => { ... });
```

**Comment by rkddbs1031** [comment]
> Okay, found [here](https://github.com/nhn/tui.editor/issues/1280)

Hello. If it's not rude, can you tell me how to apply it in Vue.js??

this one...

```
editor.removeHook('addImageBlobHook'); // remove the default hook
editor.addHook('addImageBlobHook', (blob, callback) => { ... });
```
