### ISSUE TITLE
TypeError: Cannot read property 'nextElementSibling' of null

### ISSUE THREAD

**Issue by cs-ajay-chakkar** [nhn/tui.editor#1456]
## Describe the bug
@seonim-ryu 
Throwing error while setting markdown content with *setMarkdown* method.

## To Reproduce
Using taost ui version - 2.4.0
I am using the below content to set editor and calling *getHTML* method to display content on my page.
Using *setMarkdown* method with below content.

```
<div class="font-size-17 padding-left-sm"><strong>VirusTotal</strong></div> 
<div class="card-container-body" style="width: 200px;">
<div class="card-number  padding-bottom-md">    
 <div class="line-height-1"><a href="https://www.virustotal.com/#/ip-address/{{vars.record}}" target="_blank" rel="noopener noreferrer" class="font-size-8em">5</a></div>
 
<div class="font-size-14 font-weight-normal padding-top-sm">Detected URLs: 20</div>
</div>
</div> 
<p>&nbsp;</p>
```

it's throwing error as - 
angular.js:15635 TypeError: Cannot read property 'nextElementSibling' of null
    at MarkdownPreview.replaceRangeNodes (toastui-editor.js:5431)
    at toastui-editor.js:5400
    at Array.forEach (<anonymous>)
    at MarkdownPreview.update (toastui-editor.js:5399)
    at toastui-editor.js:5555
    at forEachOwnProperties (toastui-editor.js:2408)
    at EventManager.emit (toastui-editor.js:5554)
    at MarkdownEditor._emitMarkdownEditorContentChangedEvent (toastui-editor.js:11113)
    at MarkdownEditor._refreshCodeMirrorMarks (toastui-editor.js:11140)
    at toastui-editor.js:11010

## Expected behavior
The error should not be thrown while parsing HTML content.

## Screenshots
<img width="802" alt="Screenshot 2021-03-26 at 12 01 26 AM" src="https://user-images.githubusercontent.com/51313835/112525041-7d4a6280-8dc6-11eb-8456-fb8e1bf6fcdd.png">

## Desktop (please complete the following information):
 - OS: MAC, Windows
 - Browser - chrome , firefox

## Additional context
It works fine if I paste content in the editor and see preview, only throwing an error if I am using it to parse Html or markdown content to get HTML content to display in another wrapper.

**Comment by js87zz** [comment]
@cs-ajay-chakkar 
Can you give us the detail code?

**Comment by cs-ajay-chakkar** [comment]
Using setMarkdown method with below content.

```
<div class="font-size-17 padding-left-sm"><strong>VirusTotal</strong></div> 
<div class="card-container-body" style="width: 200px;">
<div class="card-number  padding-bottom-md">    
 <div class="line-height-1"><a href="https://www.virustotal.com/#/ip-address/{{vars.record}}" target="_blank" rel="noopener noreferrer" class="font-size-8em">5</a></div>
 
<div class="font-size-14 font-weight-normal padding-top-sm">Detected URLs: 20</div>
</div>
</div> 
<p>&nbsp;</p>
```

**Comment by otariidae** [comment]
faced same issue too

minimal reproduction:

```html
<!DOCTYPE html>
<html>
  <head>
    <link
      rel="stylesheet"
      href="https://uicdn.toast.com/editor/2.5.1/toastui-editor.min.css"
    />
    <meta charset="utf-8">
  </head>
  <body>
    <div id="editor"></div>
    <script src="https://uicdn.toast.com/editor/2.5.1/toastui-editor-all.min.js"></script>
    <script>
      const markdown = "<div>\n\n</div>"
      const editor = new toastui.Editor({
        el: document.getElementById("editor"),
        initialValue: markdown
      });
      editor.setMarkdown(markdown);
    </script>
  </body>
</html>

```

**Comment by js87zz** [comment]
@cs-ajay-chakkar @otariidae 
Why do you set the `initialValue`( or `setMarkdown` API) to HTML text?
`toast-ui/editor` is based on markdown editor. We recommend that configure `InitialValue` to markdown text.
