### ISSUE TITLE
Resizing imageObject crops the image

### ISSUE THREAD

**Issue by kemach** [nhn/tui.editor#1471]
## Version
Latest version (loaded from https://uicdn.toast.com/tui-image-editor/latest/tui-image-editor.js)

## Test Environment
Same issue with al browsers
## Current Behavior
After loading an image object using imageEditor.addImageObject, I try to resize the object using imageEditor.setObjectProperties. The object get resized but the image is croped (and not resized)

## Expected Behavior
Image should be untouched only resized

**Comment by js87zz** [comment]
@kemach 
The wrong place. Raise the issue [here](https://github.com/nhn/tui.image-editor/issues) :)
