### ISSUE TITLE
URL link should be clickable after typed the URL and clicked enter

### ISSUE THREAD

**Issue by kelvinkoko** [nhn/tui.editor#1476]
## Version

2.5.2

## Test Environment

Chrome browser in MacOS (the issue is platform independent)

## Current Behavior

With Editor option set to
      linkAttribute: {
        target: "_blank",
        contenteditable: false
      }
When typing url in WYSIWYG mode
e.g. https://www.google.com
After clicking enter, it will converted to a "link",  however, it is not clickable.

If add link through toolbar, it is clickable

## Expected Behavior

Should also apply "linkAttribute" when converting user input url to "link" by clicking enter same as adding through toolbar

**Comment by js87zz** [comment]
@kelvinkoko 
I checked the issue.
However, the priority is not high compared to 3.0 major update, so it will not be resolved immediately.

**Comment by kelvinkoko** [comment]
@js87zz 
thanks for confirming that. I am also looking forward to 3.0 release :)
