### ISSUE TITLE
Image baseurl, homepage resolve

### ISSUE THREAD

**Issue by kirevdokimov** [nhn/tui.editor#1480]
## Summary
How to make editor to resolve image defined like `![20210419213629.png](20210419213629.png)` 
from `/mybaseurl/20210419213629.png`, not `/20210419213629.png`

## Additional context
I have a markdown like this
```
# Test Case 0
This is plain text
![/api/read/20210419213629.png](/api/read/20210419213629.png)
![20210419213629.png](20210419213629.png)
```
I can serve my images only from `/api/read/:filename`, therefore first image discoverable, second does not. I want to be able to markdown images like `![20210419213629.png](20210419213629.png)` not `![/api/read/20210419213629.png](/api/read/20210419213629.png)`. What is a proper way to make TUIEditor to resolve my own baseurl for relative urls?

Good to know how to do this for every link-like node.

**Comment by kirevdokimov** [comment]
Discovered solution while scrolling through all relevant issues: #1344 

I use react-editor and Typescript so this is the solution:
```jsx
import { Editor as TUIEditor } from '@toast-ui/react-editor';
...
<TUIEditor
    initialValue={text}
    previewStyle="vertical"
    height="600px"
    initialEditType="wysiwyg"
    useCommandShortcut={true}
    ref={editor}
    customHTMLRenderer={{
        "image": (node, context) => {
            const { destination } = node as object as { destination: string};
            const { getChildrenText, skipChildren } = context;
            skipChildren()
            console.log(node, destination)
            return {
                type: "openTag",
                tagName: "img",
                selfClose: false,
                attributes: {
                    src: `/api/read/${destination}`, // <-- url substitution take place here
                    alt: getChildrenText(node),
                }
            }
        }
    }}
/>
```

Looks clear enough for me.

**Comment by musiccow** [comment]
Cool
