### ISSUE TITLE
how can I import code-syntax-highlight in vue wrapper?

### ISSUE THREAD

**Issue by paxmiler** [nhn/tui.editor#1483]
## Summary
How can I  import 'highlight.js/styles/github.css' in vue.js correctly?

## Screenshots
my project import tui-editor in 'editor.js' and import again 'main.js'
like this.
![Screen Shot 2021-04-27 at 0 02 02](https://user-images.githubusercontent.com/49383027/116105237-16350c00-a6ec-11eb-8522-2728a6926707.png)

editor.js
![Screen Shot 2021-04-26 at 23 55 00](https://user-images.githubusercontent.com/49383027/116105339-2f3dbd00-a6ec-11eb-84d1-eb3dc9081218.png)

main.js
![Screen Shot 2021-04-27 at 0 05 26](https://user-images.githubusercontent.com/49383027/116105590-6c09b400-a6ec-11eb-9943-4920cbf81d56.png)

so, i already imported table-merged-cell plugin successfully but code-syntax-highlight is different...
![Screen Shot 2021-04-27 at 0 08 52](https://user-images.githubusercontent.com/49383027/116106065-db7fa380-a6ec-11eb-98bb-993023d1e0c0.png)

I think my problem is importing css...
because it look like working right on console, but nothing change visually...
![Screen Shot 2021-04-27 at 0 11 44 (2)](https://user-images.githubusercontent.com/49383027/116106647-4630df00-a6ed-11eb-9099-45199a99ddca.png)

.bind() and { hljs } has same result.

## Version
tui-editor 2.x

## Additional context
I'm newb on web coding
so, this question looks like foolish or code reviewing.

full package of my code is here, https://github.com/paxmiler/personal_site
and I hope this help to helping me... 😇

**Comment by js87zz** [comment]
Can you try as below?
```js
import codeSyntaxHighlight from '@toast-ui/editor-plugin-code-syntax-highlight';

import hljs from 'highlight.js';

const editor = new Editor({
  // ...
  plugins: [[codeSyntaxHighlight, { hljs }]]
});
```

**Comment by paxmiler** [comment]
> Can you try as below?
> 
> ```js
> import codeSyntaxHighlight from '@toast-ui/editor-plugin-code-syntax-highlight';
> 
> import hljs from 'highlight.js';
> 
> // ...
> options: {
>   // ...
>   plugins: [[codeSyntaxHighlight, { hljs }]]
> };
> ```

thanks to your answer.
actually I already do this before but it doesn't work for me as same as that time... 🥲

my browser console look like 'highlight.js' work correctly,
but why 'highlight.js/styles/github.css' doesn't applying?

**Comment by js87zz** [comment]
When I look at your screenshot again, I think that the code is highlighted. 
The highlighting is only applied to preview area(not editing area)

**Comment by paxmiler** [comment]
oh, I think example picture was little complicate(with swift).

![Screen Shot 2021-04-28 at 14 32 51 (2)](https://user-images.githubusercontent.com/49383027/116351449-a9765a80-a82e-11eb-811c-97112672b0f2.png)

this is compare with toast ui plugin document.
that's why I'm saying 'css doesn't applying'...
same code on code block but not same output on preview.

if your opinion was correct that mean same output like tui document right?

**Comment by js87zz** [comment]
@paxmiler 
Hm...No, the code should be highlighted as same.
There doesn't seem to be a problem with the configuration code. It would be better to check if the css is properly imported as a bundle result.

**Comment by paxmiler** [comment]
how can I check css imported properly as a bundle result?
can you advice for me?

**Comment by paxmiler** [comment]
ahha, i edited tui-editor's css before because of dark mode.
that code made this happen.
thanks for your advice.
