### ISSUE TITLE
Uncaught TypeError: e.replace is not a function

### ISSUE THREAD

**Issue by SeaRoll** [nhn/tui.editor#1489]
## Describe the bug
When starting a website with Toast UI Editor from the CDN. the following text appears `Uncaught TypeError: e.replace is not a function`. It also appears that no button works either

## To Reproduce
1. put everything inside from this [example](https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic) to a new HTML file.

## Expected behavior
No error and pressing on headers/image should work

## Screenshots
![image](https://user-images.githubusercontent.com/26680151/117415517-b1ae5400-af18-11eb-80f8-c5c2f94bbf23.png)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Firefox
 - Version 88.0 (64-bit)

## Additional context
Django templating is also used

**Comment by js87zz** [comment]
@SeaRoll 
Can you give us your detail code? 
There seems to be no problem with the existing example code. It works well for Fire Fox, too.

**Comment by jkamzi** [comment]
The problem is copy paste without looking at what is being copied.

[the example](https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic) contains this snippet under JavaScript:

```js
const editor = new toastui.Editor({
  el: document.querySelector('#editor'),
  previewStyle: 'vertical',
  height: '500px',
  initialValue: content // <--- Here is the issue
});
```

If `content` is not defined you get the error message `Uncaught TypeError: e.replace is not a function`

**Comment by js87zz** [comment]
@SeaRoll 
It's just a snippet of code for an example. 
This is not a bug.
