### ISSUE TITLE
🚨 Potential Cross-site Scripting (XSS) - Stored (CWE-79)

### ISSUE THREAD

**Issue by huntr-helper** [nhn/tui.editor#1491]
👋 Hello, @shiren, @kyuwoo-choi, @seonim-ryu - a potential medium severity Cross-site Scripting (XSS) - Stored (CWE-79) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/2-other-nhn/tui.editor** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by js87zz** [comment]
@huntr-helper 
We will fix it. Thanks!

**Comment by JamieSlome** [comment]
@js87zz - if you could visit https://huntr.dev/bounties/2-other-nhn/tui.editor to validate the advisory, that would be helpful!

**Comment by JamieSlome** [comment]
@js87zz - was this valid and/or fixed?
