### ISSUE TITLE
Is there to permit an option about 'iframe' tag in Toast UI?

### ISSUE THREAD

**Issue by vEduardovich** [nhn/tui.editor#1493]
I am using vue-toast ui.
I cannot show youtube preview to our users in present because Toast UI always remove iframe tags.
How can I solve this, especially Viewer component?

Thanks in advance.

**Comment by js87zz** [comment]
@vEduardovich 
Our default sanitizer remove `iframe` tag. 
So you can override the sanitizer through `customHTMLSanitizer` option.

```js
import DOMPurify from 'dompurify';

// just example
const purifyOptions = { ... };
const editor = new Editor({
  // ...
  customHTMLSanitizer: html => {
    return DOMPurify.sanitize(html, purifyOptions) || ''
  }
});
```
