### ISSUE TITLE
Dark mode code highlighting

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1510]
## Describe the bug
We are not able to apply dark mode.

If we apply this `css` to editor then background of `pre` wont change.
```js
import 'highlight.js/styles/atom-one-dark.css';
```

## To Reproduce
Use this code to render editor.
```js
import React from "react";
import 'codemirror/lib/codemirror.css';
import '@toast-ui/editor/dist/toastui-editor.css';
import { Editor } from '@toast-ui/react-editor';

// highlights
import codeSyntaxHighlight from '@toast-ui/editor-plugin-code-syntax-highlight';
import 'highlight.js/styles/atom-one-dark.css';
import hljs from 'highlight.js';
import java from 'highlight.js/lib/languages/java';
hljs.registerLanguage('java', java);

function App() {
  return (
    <div>
       <Editor
        previewStyle="vertical"
        height="400px"
        initialEditType="markdown"
        initialValue={`
\`\`\`java
public static void main(String[] args){
  System.out.println("Hello World!");
}
\`\`\`
        `}
        plugins = {[[codeSyntaxHighlight,{hljs}]]}
      />
    </div>
  );
}

export default App;
```

## Expected behavior
Background should be dark.

## What is the problem
`highlight.js` apply `background` css property on `hljs` class, and in our case this class is not persent on `pre` tag.

See: https://github.com/highlightjs/highlight.js/blob/2b9ca9f1cae701cc5f2dec2ba4b74f94a975390e/src/styles/a11y-dark.css#L10

This is the default styling of `pre`
***
```css
.tui-editor-contents pre {
    margin: 2px 0 8px;
    padding: 18px;
    background-color: #f5f7f8; 
}
```
We need to remove background color from here, so `hljs` color can applied.

**Comment by js87zz** [comment]
@ats1999 
It's not the bug.
You can change the style by overriding the background of code block.

**Comment by ats1999** [comment]
Ok
