### ISSUE TITLE
Whether to support vue3.0

### ISSUE THREAD

**Issue by gaoxinke88888888** [nhn/tui.editor#1520]
## Summary
I can't use it in vue3.0 project，I don’t know if vue3.0 is supported, if so ，
Could you please teach me how to use it in vue3.0 project

**Comment by codingcn** [comment]
Nuxtjs support for vue3 is really slow！

**Comment by js87zz** [comment]
@gaoxinke88888888 
It is currently supported based on vue2.0. I know there is no compatibility problem with vue3, is there a problem?

**Comment by gaoxinke88888888** [comment]
> @ gaoxinke88888888
> 当前基于vue2.0受支持。我知道vue3没有兼容性问题，有问题吗？

我在vue3的<script setup>语法糖里使用@toast-ui/vue-editor出现了报错

**Comment by gaoxinke88888888** [comment]
> @gaoxinke88888888
> It is currently supported based on vue2.0. I know there is no compatibility problem with vue3, is there a problem?

**Comment by gaoxinke88888888** [comment]
> @ gaoxinke88888888
> 当前基于vue2.0受支持。我知道vue3没有兼容性问题，有问题吗？

我在vue3的<script setup>语法糖里使用@toast-ui/vue-editor出现了报错

**Comment by gaoxinke88888888** [comment]
> @gaoxinke88888888
> It is currently supported based on vue2.0. I know there is no compatibility problem with vue3, is there a problem?

I used @toast-ui/vue-editor in vue3's <script setup> syntactic sugar and there was an error
