### ISSUE TITLE
Height of the rendered content

### ISSUE THREAD

**Issue by DellaMoraWalter** [nhn/tui.editor#1526]
Is there a way to retrieve the height of the rendered text in viewer and/or in the editor?

Thanks

**Comment by js87zz** [comment]
@DellaMoraWalter 
Currently, we don't provide the API to get the height of text.
Thanks!

**Comment by DellaMoraWalter** [comment]
@js87zz
I've tried some ways to solve but without success.
The scenario is that I need to render the toast ui viewer in a WebView that is a xamarin form control, pratically an embedded browser, so the problem to solve is resize the control from the content height.
The better result I've founded is creating a function that retrieve the scrollHeoght of the boby that contain the toast viewer.
In chrome the result seems coerent but in xamarin webview the height is three or four times.
I'm not a javascript expert so I ask you if you can suggest me a better way.
Thanks!
