### ISSUE TITLE
How can I disabled the editor by variable

### ISSUE THREAD

**Issue by becory** [nhn/tui.editor#1554]
## Summary
I use Vue wrapper to create editor.
I want disable editor in some status.
I can't found the disabled options in editor API document.
Could you help me how to disabled the editor by variable?

## Version
2.5.1

## Additional context
The original html tag <textarea disabled></textarea> has disabled attribute to prohibit the user key in data.

**Comment by js87zz** [comment]
@becory 
We don't provide any `disabled` option. Instead of providing the [viewer](https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/viewer.md).

**Comment by becory** [comment]
@js87zz 
Does it feature has any possible to add in new version?
or 
how can I toggle the viewer and editor mode by button in vue?

thank you very mush.
