### ISSUE TITLE
TOAST UI 2.5.2+ - Paste from office support enhancements/bug fixes

### ISSUE THREAD

**Issue by JackHammond** [nhn/tui.editor#1559]
## Version
2.5.2

## Test Environment
Chrome

## Current Behaviour
Content from word does not import accurately in WYSIWYG editor. To replicate, create a word doc with the following contents:

1. Create 3x3 table (Once you paste into editor you will notice that a heading row is always added, despite the fact that the table I am pasting from word already has a heading row for the table)

2. Create a bulleted list of 3 items (Once you paste into editor you will notice that it replaces actual bullets with a full stops '.' , instead of '*' to signify markdown bullet)

3. Add image (The image does not convert to base 64 but instead tries to add local system file path to markdown)

4. Copy all of these contents together and paste them all into the WYSIWYG editor in a single paste command

5. You should now see the contents not pasting correctly, this then leads them to not be converted to markdown.

## Expected Behaviour
Converting word document content to the WYSIWYG editor and then subsequently to accurate Markdown is an extremely valuable feature that many companies require.

The ideal expected behaviour is that pasted content should more accurately be parsed into the WYSIWYG editor. This should make TOASTUI the default editor and make competitors like CKEditor obsolete as this paste from word feature is arguably the deciding factor for many companies. 

Word Template Example:
![Capture](https://user-images.githubusercontent.com/36892914/121167963-5985ad00-c84a-11eb-8dfa-6fde7d6a42b2.PNG)

**Comment by js87zz** [comment]
@JackHammond 
After the `v3.0` official release, we will improve the compatibility with Word. However, it will only be supported to the extent that it is compatible with Markdown. Thank you!
