### ISSUE TITLE
Pasting various content results in 'textNode.parentNode is null' error

### ISSUE THREAD

**Issue by fastloris** [nhn/tui.editor#1561]
## Describe the bug
Pasting different content results in content being cut off and an exception being thrown in the console.

## To Reproduce
1. Go to http://www.columbia.edu/~fdc/sample.html
2. Copy the whole page
3. Go to https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic
4. Click on WYSIWYG
5. Paste the content

## Expected behavior
Exception is thrown in console and content is cut off after table of contents, expect the full content to be shown and no exception.

```
TypeError: textNode.parentNode is null
    _replaceNewLineToBr https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:21198
    _replaceNewLineToBr https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:21196
    _onWillPaste https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:21217
    _onWillPaste https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:21215
    _executeHandler https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:21110
    init https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:21089
    emit https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:27753
    forEachOwnProperties https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:10303
    emit https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:27752
    _initSquireEvent https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:26578
    fireEvent https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:12413
    insertHTML https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:12414
    it https://nhn.github.io/tui.editor/latest/dist/cdn/toastui-editor-all.js:12413
toastui-editor-all.js:12413:27742
```

## Desktop (please complete the following information):
 - OS: XUbuntu
 - Browser Firefox
 - Version 89.0

## Additional context
I am getting this error pasting various content in, but the linked page does it reliably. So does copying the content from https://github.com/mxstbr/markdown-test-file/blob/master/TEST.md. I am not sure what is triggering the error as there isn't any strange HTML tags being generated at that point.

If you skip the point where the error happens in your copy/paste, another similar error happens further down in the file on a different element.

I can't say for sure, but this seems to maybe be correlated with random `<br>`s being returned from the getMarkdown() function that don't really seem to need to be there. Or that may be more related to https://github.com/nhn/tui.editor/issues/1349.

**Comment by js87zz** [comment]
@fastloris 
I checked the issue as you mentioned, but no script errors occurred when running on Chrome and Firefox. 
Is there anything else I missed?
![2021-06-09 12-44-44 2021-06-09 12_45_26](https://user-images.githubusercontent.com/37766175/121289844-97550500-c920-11eb-91bb-838a78ca8753.gif)

**Comment by fastloris** [comment]
Really interesting @js87zz, no doesn't look like you missed anything. Maybe it's something to do with Linux, in which case it's more niche.

Here's a video of it happening to me in case there's something subtle I'm doing differently.

https://user-images.githubusercontent.com/3529318/121301817-0c144900-c8f9-11eb-83f7-ab43002eb737.mp4
