### ISSUE TITLE
@toast-ui/editor-plugin-code-syntax-highlight is not wokring in react

### ISSUE THREAD

**Issue by SeoHyunDeock** [nhn/tui.editor#1564]
@toast-ui/editor-plugin-code-syntax-highlight 해당 라이브러리가 리액트에서 정상 동작 하지 않습니다.

실행 버전은 다음과 같습니다.

```
"@toast-ui/editor-plugin-code-syntax-highlight": "^3.0.0-alpha.0",
"@toast-ui/editor-plugin-color-syntax": "^1.0.1",
"@toast-ui/react-editor": "^2.5.3",
"highlight.js": "^11.0.1",
```

@toast-ui/editor-plugin-color-syntax 또한 버전 3의 알파에서 정상 실행되지 않아 

하위 버전으로 설치후 실행시 정상 동작하는 것을 확인하여 @toast-ui/editor-plugin-code-syntax-highlight 또한 버전을

하위 버전으로 낮춘후 실행했으나 정상 동작하지 않습니다.

관련해서 [해당이슈](https://github.com/nhn/tui.editor/issues/909)를 참고했고

highlight.js 설치 및 bind를 통해서 바인딩 후 실행했으나 콘솔상 에러 없이 적용이 되지 않습니다.

아래는 실행 결과입니다.

<img width="1195" alt="스크린샷 2021-06-09 오후 3 31 55" src="https://user-images.githubusercontent.com/26263255/121304861-d6428500-c937-11eb-84b6-013ee1b351b9.png">

**Comment by js87zz** [comment]
@SeoHyunDeock 
Alpha version will not work with existing plugin because the way it is used has changed completely.
Can you upload your source code in code sandbox or jsfiddle?

**Comment by SeoHyunDeock** [comment]
[package.json]
```json
{
    "@toast-ui/editor-plugin-code-syntax-highlight": "^3.0.0-alpha.0",
    "@toast-ui/editor-plugin-color-syntax": "^1.0.1",
    "@toast-ui/react-editor": "^2.5.3"
}
```

[code]
```ts
import { Editor } from "@toast-ui/react-editor";
import "codemirror/lib/codemirror.css";
import "tui-color-picker/dist/tui-color-picker.css";
import "@toast-ui/editor/dist/toastui-editor.css";
import "highlight.js/styles/github.css";

import colorSyntaxPlugin from "@toast-ui/editor-plugin-color-syntax";
import hljs from "highlight.js";
import codeSyntaxHighlightPlugin from "@toast-ui/editor-plugin-code-syntax-highlight";


const CustomEditor = () => {
  return (
        <Editor
          placeholder="title"
          previewStyle="vertical"
          height="100%"
          initialEditType="markdown"
          useCommandShortcut={true}
          hideModeSwitch={true}
          useDefaultHTMLSanitizer={true}
          plugins={[codeSyntaxHighlightPlugin.bind(hljs), colorSyntaxPlugin]}
        />
  )

}


```
@toast-ui/editor-plugin-code-syntax-highlight의 알파버전이 아닌 1.0을 설치해도 위와 같은 문제가 발생합니다.

인라인 코드블록에서만 하이라이팅이 적용되고 코드블록에서는 정상 동작하지 않습니다.

**Comment by js87zz** [comment]
@SeoHyunDeock 
Can you try as below?
```jsx
// ...

const CustomEditor = () => {
  return (
        <Editor
          placeholder="title"
          previewStyle="vertical"
          height="100%"
          initialEditType="markdown"
          useCommandShortcut={true}
          hideModeSwitch={true}
          useDefaultHTMLSanitizer={true}
          plugins={[[codeSyntaxHighlightPlugin, { hljs }]]}
        />
  )
}
```
If it is not operated, Please upload the example code in code sandbox or jsfiddle to solve the issue quickly.

**Comment by SeoHyunDeock** [comment]
확인 감사합니다.

말씀해주신대로 하면 정상 동작하는 것을 확인했습니다.

하지만 타입스크립트에서는 플러그인을 제안해주신 방식대로 연결할 수 없네요.

추가적으로 관련 이슈를 해당 레포에서 찾아보니 bind로 연결하도록 되어있는데 해당 부분 확인 가능할까요?

자바스크립트 기반으로 제안해주신 부분을 적용한 [코드샌드박스](https://codesandbox.io/s/keen-pine-n4b88?file=/src/App.js)입니다.

**Comment by js87zz** [comment]
@SeoHyunDeock 
I'm sorry for the late response. This issue is old, so if you have any issues, please post a new one! Thank you!
