### ISSUE TITLE
Certain attributes for video tag are missing

### ISSUE THREAD

**Issue by fzlee** [nhn/tui.editor#157]
## Version
1.0.5 or 1.1.0

you may reproduce this issue here:
https://nhnent.github.io/tui.editor/

## Current Behavior
Insert the following code into markdown editor

```js
<video width="400" controls name="123" autoplay>
    <source src="" type="video/mp4">
</video>
```
And inspect element with developer tools in the preview field, you will see the two attributes,`controls` and `autoplay` are missing from the HTML, but the other two attributes are still there.

**Comment by kyuwoo-choi** [comment]
Hi. @fzlee 

It currently filters out attributes according to attr whitelist.
I need time to review the whitelist and maybe including the logic.

I'm afraid there's no workaround at this moment.

**Comment by sohee-lee7** [comment]
@fzlee This issue does not occur In the latest version.

**Comment by fzlee** [comment]
@sohee-lee7 Many thanks for your help on this.
I just want to make sure the issue is resolved in the latest version, `1.3.1`, right?

I asked cause i tried 1.3.1 locally, the two tags are still missing

**Comment by sohee-lee7** [comment]
@fzlee Sorry, my reproduce is not right. I try again it and this issue still occur.
I think this issue need to discussion with my team member. Please wait util discussion.

**Comment by HunterXuan** [comment]
Hi, any progress?
