### ISSUE TITLE
Custom tooltips

### ISSUE THREAD

**Issue by Yeongjae-Shin** [nhn/tui.editor#1573]
## Summary
Hi, Is there any way to changing tooltips?

I want to change these tooltips to Korean but I can't find how to do.

How can I do?

## Screenshots
![스크린샷 2021-06-15 오전 10 44 14](https://user-images.githubusercontent.com/60685930/121980406-d8d52c80-cdc6-11eb-8c5a-c098a9795226.png)
![스크린샷 2021-06-15 오전 10 44 30](https://user-images.githubusercontent.com/60685930/121980415-dd99e080-cdc6-11eb-8a0e-8a86d473ef9f.png)

## Version
```
"@toast-ui/editor-plugin-table-merged-cell": "^1.3.2",
"@toast-ui/react-editor": "^2.5.3"
```

## Additional context
-

**Comment by ustacryptact** [comment]
You can import the locale for korean:
```typescript
import '@toast-ui/editor/dist/i18n/ko-kr';
```

Then you can pass `language="ko"` prop to the React editor component.

More info here: https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/i18n.md

**Comment by Yeongjae-Shin** [comment]
> You can import the locale for korean:
> ```typescript
> import '@toast-ui/editor/dist/i18n/ko-kr';
> ```
> 
> Then you can pass `language="ko"` prop to the React editor component.
> 
> More info here: https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/i18n.md

Thank you!!!

**Comment by js87zz** [comment]
@ustacryptact 
Great!! :) Thanks
