### ISSUE TITLE
TOAST UI Editor 3.0.0 is released!

### ISSUE THREAD

**Issue by js87zz** [nhn/tui.editor#1580]
🎊TOAST UI Editor 3.0.0 is released!🎊
## Release Note
* https://github.com/nhn/tui.editor/releases/tag/v3.0.0
## Migration Guide
 * English: https://github.com/nhn/tui.editor/tree/master/docs/v3.0-migration-guide.md
 * Korean: https://github.com/nhn/tui.editor/tree/master/docs/v3.0-migration-guide-ko.md
## Tutorial
 * English: https://github.com/nhn/tui.editor/tree/master/docs/en
 * Korean: https://github.com/nhn/tui.editor/tree/master/docs/ko

**Comment by ats1999** [comment]
@js87zz  is `react` wrapper updated?

**Comment by jung-han** [comment]
@ats1999 
I think this is. 😀
* https://www.npmjs.com/package/@toast-ui/react-editor
