### ISSUE TITLE
setHTML not support breakline tag

### ISSUE THREAD

**Issue by jbjumbojb** [nhn/tui.editor#1582]
## Describe the bug
setHTML not support tags ```<br/>``` ```<br>``` ```\n```

## To Reproduce
1. call ```setHTML('<p>a<br/>b</p>')``` or ```setHTML('<p>a<br>b</p>')```
2. no newline insert

## Expected behavior
new line insert between a and b
el.setHTML(el.getHTML()) should not change the content

## Screenshots
![image](https://user-images.githubusercontent.com/682524/122409438-56f32800-cfad-11eb-8ede-2d71443023f6.png)

## Desktop (please complete the following information):
 - OS: Windows
 - Browser: Edge
 - Version: 92

**Comment by js87zz** [comment]
@jbjumbojb 
We will fix it. Thanks for reporting!

**Comment by js87zz** [comment]
@jbjumbojb 
The bug has been fixed and released in [v3.0.1](https://github.com/nhn/tui.editor/releases/tag/editor%403.0.1).
