### ISSUE TITLE
Set "File Upload" Button type to "button"

### ISSUE THREAD

**Issue by subicura** [nhn/tui.editor#1584]
## Describe the bug

Most browsers the default type of button is submit.
If click "File upload" button, form will submit.

## To Reproduce

![image](https://user-images.githubusercontent.com/67347/122485356-9f443180-d011-11eb-8042-d8c2f04fe963.png)

1. Click 'Choose a file'
2. See "form submit"

## Expected behavior

Not form submit.

## Desktop (please complete the following information):
 - OS: macOS
 - Browser chrome

**Comment by js87zz** [comment]
@subicura 
Oh..I missed this part. I will change it to the `button` type.
Thanks!!
