### ISSUE TITLE
is code block editor removed?

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1590]
# Previous editor
> We are getting this after we hover over here

![Screenshot from 2021-06-19 13-10-39](https://user-images.githubusercontent.com/54087826/122635153-e3156480-d0ff-11eb-8d23-cab57763da81.png)

## How can i open this editor in my application
![Screenshot from 2021-06-19 13-12-07](https://user-images.githubusercontent.com/54087826/122635173-03ddba00-d100-11eb-8592-e9a69f6de56d.png)

**Comment by js87zz** [comment]
@ats1999 
Yes. It was removed because it was inconvenient to use.
Instead, it was changed to enter or select a language within the WYSIWYG code block.
