### ISSUE TITLE
How can i add button to the toolbar in new version?

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1591]
## Summary
Currently we have following buttons
![Screenshot from 2021-06-19 13-36-28](https://user-images.githubusercontent.com/54087826/122635786-6a180c00-d103-11eb-8ea2-85784f1363df.png)

I want to add one more button to it.

How can i do this?

**Comment by devshot-dotcom** [comment]
[This Documentation Link](https://nhn.github.io/tui.editor/latest/ToastUIEditor#insertToolbarItem) might be useful

**Comment by js87zz** [comment]
@ats1999 
The below links will be helpful to you.
* https://nhn.github.io/tui.editor/latest/tutorial-example15-customizing-toolbar-buttons
* https://github.com/nhn/tui.editor/blob/master/docs/en/toolbar.md
