### ISSUE TITLE
is editor suport toggle feature?

### ISSUE THREAD

**Issue by DoGukKim** [nhn/tui.editor#1594]
## Summary
is editor suport toggle feature?

## Screenshots
![image](https://user-images.githubusercontent.com/59882993/122861780-fb34f000-d35a-11eb-900b-9f017c21b050.png)

## Version
3.0

## Additional context
is editor suport toggle feature?

**Comment by js87zz** [comment]
@DoGukKim 
`details`, `summary` tag can be used in editor, but it will be not worked properly.
Maybe this feature will be made in the new plugin format.
