### ISSUE TITLE
How to prevent GFM inline HTML destroying content in setMarkdown() call?

### ISSUE THREAD

**Issue by obonac** [nhn/tui.editor#1595]
Hi,

Toast UI is supercool! We are trying to integrate it for our physicians at https://projectvikram.github.io

Which version should we use for the given fix #998  ?

We are facing an issue importing GFM markdown with inline HTML! On encountering any HTML tag other than bold the entire content vanishes. Verified by switching between markdown and wysiwyg modes manually too.

      const Editor = toastui.Editor;
      const wysiwyg = new Editor({
        el: document.querySelector('#editor'),
        height: '500px',
        initialValue: 'Loading...',
        initialEditType: 'wysiwyg'
      });
 
       mycont = '# Head 1\\n### Head 3\\nPara       <b>Word</b>'; // works
       //mycont = '# Head 1\\n### Head 3\\nPara       <b>Word</b><br>'; //does not work - entire content vanishes
       wysiwyg.setMarkdown(mycont,0);

We are using toastui-editor.min.css with toastui-editor-all.min.js from "latest". Meanwhile I will experiment with the custom renderer example above.

Regards,
Abhishek

**Comment by js87zz** [comment]
@obonac 
Sorry for late replying. 
This is a bug, not an intended result. 
I have checked the same problem in `v3.0`.
I'll fix it at the next bug-fix release. Thank you!

**Comment by js87zz** [comment]
@obonac 
The bug has been fixed in `v3.0.2`. Thanks!
