### ISSUE TITLE
EditorOptions.toolbarItems type definition is incorrect

### ISSUE THREAD

**Issue by lucaslcode** [nhn/tui.editor#1596]
## Describe the bug
The new nested array stated in the v3.0 docs is not reflected in the type definitions.

## To Reproduce
1. use this code:
 
    new ToastUIEditor({
      el: myEl,
      toolbarItems: [
        ["heading", "bold", "italic"],
        ["hr", "quote", "ul", "ol"],
        ["link"],
      ],
    });

2. The type is incorrect

## Expected behavior
Type is correct

**Comment by js87zz** [comment]
@lucaslcode 
Thanks! I will fix it.

**Comment by js87zz** [comment]
@lucaslcode 
The bug has been fixed and released in [v3.0.1](https://github.com/nhn/tui.editor/releases/tag/editor%403.0.1).
