### ISSUE TITLE
LaTeX equation not rendering properly

### ISSUE THREAD

**Issue by 2klm** [nhn/tui.editor#1600]
## Bug

LaTeX equations are not rendering properly. I thought it was due to a missing "UTF8 statement" in my HTML but it's not

## Behavior

This is what I'm getting :

https://i.ibb.co/hCFk59b/rendered.png

## Expected behavior

This is what I should get :

https://i.ibb.co/Lh9frf7/render.png

What I already did :

Add 
`<script src="https://cdn.jsdelivr.net/npm/latex.js/dist/latex.js"></script>`

Add 
```
const renderers = {
    latex(node) {
        const generator = new latexjs.HtmlGenerator({ hyphenate: false });
        const { body } = latexjs.parse(node.literal, { generator }).htmlDocument();

        return [
            { type: 'openTag', tagName: 'div', outerNewLine: true },
            { type: 'html', content: body.innerHTML },
            { type: 'closeTag', tagName: 'div', outerNewLine: true }
        ];
    },
}
```

Add 
`customHTMLRenderer: renderers` in the `new Editor({... ` array

**Comment by js87zz** [comment]
@2klm 
I think It looks not the bug.
Can you add the below css link?
```html
<link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css"
>
```

**Comment by 2klm** [comment]
fixed! thx
