### ISSUE TITLE
Is there a way to increase the maximum capacity of the attached image?

### ISSUE THREAD

**Issue by geniushyeon** [nhn/tui.editor#1609]
## Summary
I think the maximum image capacity that can be attached through the editor is 1MB.
But I need to attach an image that exceeds 1MB.
Is there a way to increase the maximum capacity of the attached image?

## Version
2.5.3 (react-editor)

**Comment by js87zz** [comment]
@geniushyeon
Currently, there is no option for it. 
There's probably no capacity limit, but it's weired.
