### ISSUE TITLE
Upload file to server instead of base 64 conversion

### ISSUE THREAD

**Issue by 2klm** [nhn/tui.editor#1614]
I would like the image button to allow server file upload instead of just converting the image to base 64.
I also need this url to be Markdown compatible ( !_[ ]_(path/to/image.png)

Issue #57 and #127 can't seem to help me with that.

**Comment by 2klm** [comment]
> 
> 
> https://nhn.github.io/tui.editor/latest/addImageBlobHook/
> 
> This link is supposed to help me but it's dead

@js87zz

**Comment by js87zz** [comment]
@2klm 
I got a few issues related to this. I will fix it and add a description to the example page..
Thank you!

**Comment by 2klm** [comment]
@js87zz 
Somehow, in `addImageBlobHook: function(blob, callback){` ,
the "blob" value is weird. If I log it, it returns something like that :   

`File { name: "foo.png", lastModified: 1607252347900, webkitRelativePath: "", size: 2587, type: "image/png" }`

And I can't use this to upload the file into the server
Is it normal?
