### ISSUE TITLE
Module parse failed: Unexpected token (2:922)

### ISSUE THREAD

**Issue by mtoloon** [nhn/tui.editor#1615]
Using the component as described, I faced the following error:
```
ERROR  Failed to compile with 1 errors                                           1:41:34 PM

error  in ./node_modules/@toast-ui/vue-editor/dist/toastui-vue-editor.js

Module parse failed: Unexpected token (2:922)
You may need an appropriate loader to handle this file type.
```
The character at 2:922 is
```js
const e={...this.options,initialEditType
        ^
```

## To Reproduce
```
npm install --save @toast-ui/vue-editor
```
In my vue component:
```js
import '@toast-ui/editor/dist/toastui-editor.css';
import { Editor } from '@toast-ui/vue-editor';

components: {editor: Editor}
```
And then try to run/build:
```
npm run dev
npm run build
```

 - OS: Ubuntu 20.04
 - Node: 10.19 and then 14.17.1

At first I thought the problem is old version of node (10.19), so I updated it to 14.17.1 using this solution: https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04 (Option 2). But nothing changed after update!

**Comment by js87zz** [comment]
@mtoloon 
I need to more information to solve the issue like your configuration code, editor version.

**Comment by js87zz** [comment]
@mtoloon 
I fixed similar issues and released the editor.
Can you check the issue in the new version(`v3.0.3`)?

And the installation order is shown [here](https://github.com/nhn/tui.editor#setup), so check it out. 
Sorry for the delay in resolving the issue!
