### ISSUE TITLE
How can i disable additional button in preview mode

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1619]
## Summary
I have added few button ad `toolBarItems`. When i click on `preview` button then native button are being disabled, but custom not.
## Screenshots

![Screenshot from 2021-07-01 08-45-45](https://user-images.githubusercontent.com/54087826/124059445-c0147a00-da48-11eb-8db1-8ac67a7abf27.png)

## live
https://codesandbox.io/s/still-night-0feor?file=/src/App.js

**Comment by ats1999** [comment]
How can i disable all buttons?

**Comment by js87zz** [comment]
@ats1999 
In the case of the customized toolbar, it was not considered regarding `disabled` state. 
I'll fix it and let you know. Thanks!

**Comment by js87zz** [comment]
@ats1999 
This feature has been fixed in `v3.0.1`
You can see the tutorial [here](https://github.com/nhn/tui.editor/blob/master/docs/en/toolbar.md#change-toolbar-item-state)
