### ISSUE TITLE
plugins is not working

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1622]
## Summary
I want to use plugins like, uml,chart,etc. But, it's not working

## Screenshots
![Screenshot from 2021-07-01 14-07-24](https://user-images.githubusercontent.com/54087826/124093657-ae959700-da75-11eb-8f08-f144a63e68d2.png)

## Version
Write the version of the Editor you are currently using.
Latest

### Live
https://codesandbox.io/s/still-night-0feor?file=/src/App.js:2207-2214

**Comment by js87zz** [comment]
Try as below in `v3.0`~!
```js
$$uml
( * ) -> rahul
$$
```

**Comment by ats1999** [comment]
@js87zz It's not working
![Screenshot from 2021-07-06 08-22-46](https://user-images.githubusercontent.com/54087826/124535215-64286780-de33-11eb-8772-022093dc5a94.png)
![Screenshot from 2021-07-06 08-22-41](https://user-images.githubusercontent.com/54087826/124535219-65f22b00-de33-11eb-9257-1892f1084c08.png)

**Comment by js87zz** [comment]
@ats1999 
It's worked well in your sandbox.
![스크린샷 2021-07-06 오전 11 57 53](https://user-images.githubusercontent.com/37766175/124535662-76b19980-de51-11eb-969e-d3781f3a241a.png)

**Comment by ats1999** [comment]
In My sandbox
![Screenshot from 2021-07-06 08-34-29](https://user-images.githubusercontent.com/54087826/124536115-0432c080-de35-11eb-8356-104df91b6dac.png)

**Comment by ats1999** [comment]
# My System
Ubuntu 20.04 LTS

**Comment by ats1999** [comment]
Wrong `src`
![Screenshot from 2021-07-06 08-37-04](https://user-images.githubusercontent.com/54087826/124536315-67bcee00-de35-11eb-8975-fccfe9697f48.png)

**Comment by ats1999** [comment]
With
```js
const umlOptions = {
  rendererURL: "https://www.plantuml.com/plantuml/svg/"
};
```
Url becomes
![Screenshot from 2021-07-06 08-48-23](https://user-images.githubusercontent.com/54087826/124537132-f0885980-de36-11eb-8505-77b1d8a9d4ac.png)


But, image is not showing.
