### ISSUE TITLE
Toolbar dropdowns are placed outside of the default view

### ISSUE THREAD

**Issue by bobvandevijver** [nhn/tui.editor#1627]
## Describe the bug
Toolbar dropdowns are placed outside of the default view: see the screenshot

![image](https://user-images.githubusercontent.com/1835343/124140161-89f6ea80-da88-11eb-9d13-1db060960b8d.png)

## To Reproduce
Use a small screen and click any toolbar button that shows a dropdown.

## Expected behavior
It should be snapped to the side of the available space

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Edge
 - Version: 91

**Comment by js87zz** [comment]
@bobvandevijver 
I will fix in v3.0.2. Thanks for reporting!

**Comment by js87zz** [comment]
@bobvandevijver 
The bug has been fixed in `v3.0.2`. Thanks!

**Comment by bobvandevijver** [comment]
@js87zz Thank you for this fix, I just confirmed the submitted case is indeed fixed.

However, when the screen is a bit smaller (arguably too small for this editor), the following happens:
![image](https://user-images.githubusercontent.com/1835343/128319522-29c20316-1853-4070-885c-0f40f116abce.png)

This was captured on a 444px screen width.

**Comment by ats1999** [comment]
This editor doesn't support mobile devices

https://github.com/nhn/tui.editor/issues/1735

Read comments
