### ISSUE TITLE
npm run serve failed in v3.0.0

### ISSUE THREAD

**Issue by zjzshb** [nhn/tui.editor#1628]
## Describe the bug
I forked this repository days ago. (v3.0.0)

and i run these commands
```shell
npm install
npm run serve editor
```
it told me 

```
[snowpack] We resolved "@toast-ui/toastmark" to /tui.editor/libs/toastmark/dist/esm/index.js, but the file does not exist on disk.
```

I'm sure there are really no such files and dirs. I want to know how could i solve this problem. Thank you.

## To Reproduce
git pull 
npm install
npm run serve editor

## Desktop
 - OS: macOS 10.15.7
 - npm: 7.18.1 (I followed the readme and upgraded my npm version)
 - node: 16.4.0

**Comment by js87zz** [comment]
@zjzshb 
The process is missing in our README.md. 
It'll work if you do it like below. 
```sh
npm install
npm run build toastmark
npm run serve editor
```
Thank you!

**Comment by zjzshb** [comment]
@js87zz 

when i run 
```shell
npm run build toastmark
```

error appeared
```
[!] Error: Cannot find module '@rollup/plugin-commonjs'
```

Should I enter some path in order to run this command?
Or any other commands I need?

Thanks~

**Comment by js87zz** [comment]
@zjzshb 
Well, that's missing our dependency setting. 
First of all, if there is a dependency error related to `rollup`, you should install it explicitly and serve the editor. 
I'm so sorry for the trouble and it will be fixed!

**Comment by zjzshb** [comment]
@js87zz 

I ran it successed!
After I ran these commands

```shell
cd libs/toastmark
npm install @rollup/plugin-commonjs
npm install @rollup/plugin-node-resolve
npm install @rollup/plugin-json
```

Waiting for your good news~

Thanks u~

**Comment by clichedmoog** [comment]
@zjzshb @js87zz With all npm commands and dependency installing I've successfully installed v3.0.0
Thank you, and I hope settings would be updated in the next release.

**Comment by js87zz** [comment]
@zjzshb @clichedmoog 
I added missing dependencies in our `packge.json`. Thanks!
