### ISSUE TITLE
file upload button is Not type='button'

### ISSUE THREAD

**Issue by devToroko** [nhn/tui.editor#1631]
## Describe the bug
I download the toastui-editor-all.min.js file by entering 'https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js' on the browser url.
but i got some problem when i use toast editor with `<form>` tag.
when i click **file upload button (파일 선택)**, the form **submits**.
soon i knew that the file upload button's type attribute was missing.

## To Reproduce
![image](https://user-images.githubusercontent.com/51431766/124226117-87a59680-db43-11eb-866a-b81f07f50565.png)
1. Click '파일 선택'
2. the form submits

## Expected behavior
dont submit form.

## Screenshots
![image](https://user-images.githubusercontent.com/51431766/124225841-11a12f80-db43-11eb-83d5-5770ee4d2fe3.png)

## Desktop (please complete the following information):
 - OS: [Window10]
 - Browser: [Chrome]
 - Version [91.0.4472.114]

**Comment by js87zz** [comment]
@devToroko 
It will be fixed in next release.
