### ISSUE TITLE
Popups rendered outside the visible area

### ISSUE THREAD

**Issue by JakubGIT** [nhn/tui.editor#1633]
## Describe the bug
When the browser window is narrow or for example when the editor is inside a SharePoint webpart, the popups (insert a link, insert an image) activated in the toolbar are rendered partly outside of the visible area

## To Reproduce
1. Go to https://nhn.github.io/tui.editor/latest/tutorial-example17-placeholder
2. make the browser window small
3. click on 'insert an image'

## Expected behavior
Popups rendered in the visible area

## Screenshots
![image](https://user-images.githubusercontent.com/49392205/124428263-c23e4780-dd6c-11eb-8602-4f069692685d.png)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Chrome
 - Version 91.0.4472.124 (Official Build) (32-bit)

**Comment by js87zz** [comment]
@JakubGIT 
I will fix in `v3.0.2`. Thanks for reporting!

**Comment by js87zz** [comment]
@JakubGIT 
The bug has been fixed in `v3.0.2`. Thanks!

**Comment by JakubGIT** [comment]
thank you!
