### ISSUE TITLE
How to style toolbar with smaller icons

### ISSUE THREAD

**Issue by tafel** [nhn/tui.editor#1638]
## Summary
With Toast UI Editor v3, the toolbar icons are much bigger than previously. Changing certain styles may help a bit, but it seems the image used for toolbar buttons is bigger than in v2.

Is there any simple way to reduce this new toolbar size, without adding custom buttons for each standard functions (bold, italic, etc.)?

## Screenshots
[v3 toolbar style](https://user-images.githubusercontent.com/37766175/121464762-71e2fc80-c9ef-11eb-9a0a-7b06e08d3ccb.png)

[v2 toolbar style](https://user-images.githubusercontent.com/18183560/84381972-d3c62600-ac24-11ea-99e2-9640b0a2bfe8.png)

## Version
v3

**Comment by 2klm** [comment]
Unfortunately, it is not possible at the moment. The icons are a base64 map and each icon is represented by coordinates on this map.

**Comment by js87zz** [comment]
@tafel 
We created custom toolbar item because we cannot accommodate all of these requirements. 
That is the best way forward.

**Comment by tafel** [comment]
> @tafel
> We created custom toolbar item because we cannot accommodate all of these requirements.
> That is the best way forward.

Ok, no problem, custom toolbar elements with font-awesome will be enough for me. Thanks.
