### ISSUE TITLE
How can I test tui.editor with react-testing-library?

### ISSUE THREAD

**Issue by HTMLhead** [nhn/tui.editor#1642]
First of all, thank you for making such a wonderful and comfortable library.

## Summary

I want to do a rendering test by react-testing-library with react/tui-editor. but when I testing the react/tui-editor with another component, error occured with below error message.

`Error: Uncaught [TypeError: Cannot read property 'nodeType' of undefined]`

My guess is that tui-editor is not rendered because of the above error.

## Screenshots
![124559799-103f7200-de77-11eb-8a56-52b2c19bfa41](https://user-images.githubusercontent.com/40166539/127137060-0ea02d47-69a8-48bb-b7a2-4fcfe1e373d7.png)
---
![124559811-12a1cc00-de77-11eb-98fb-fae38176e60c](https://user-images.githubusercontent.com/40166539/127137131-4ad3ffd8-26f5-4e77-b990-ed9dfd5325b1.png)

and this is my toast-editor code
```javascript
import React from "react";
// Type
import { IToastEditor } from "./ToastEditor.type";
// style
import "codemirror/lib/codemirror.css";
import "tui-editor/dist/tui-editor.min.css";
import "styles/tui-editor-contents.scss";
import "styles/tui-md.scss";
import "highlightjs/styles/a11y-light.css";

import { Editor } from "@toast-ui/react-editor";
import codeSyntaxHighlight from "@toast-ui/editor-plugin-code-syntax-highlight";
// @ts-ignore
import hljs from "highlightjs";

import { videoPlugin, googleFormPlugin, ihtmlPlugin } from "lib/toastUiPlugin";

const ToastEditor: React.FC<IToastEditor> = ({ editorRef, initialValue, onChange, onDrop }) => {
  if (initialValue === undefined || initialValue === null) return null;

  return (
    <Editor
      height="100%"
      previewStyle={window.innerWidth > 900 ? "vertical" : null}
      {...{ initialValue, onDrop }}
      initialEditType="markdown"
      useDefaultHTMLSanitizer={false}
      usageStatistics={false}
      ref={editorRef}
      // @ts-ignore
      plugins={[videoPlugin, googleFormPlugin, ihtmlPlugin, [codeSyntaxHighlight, { hljs }]]}
      events={{ change: onChange }}
      toolbarItems={[
        "heading",
        "bold",
        "italic",
        "strike",
        "link",
        "divider",
        "hr",
        "quote",
        "divider",
        "ul",
        "ol",
        "task",
        "indent",
        "outdent",
      ]}
    />
  );
};

export default ToastEditor;
```

## Version
"@toast-ui/editor": "2.5.1",
"@toast-ui/editor-plugin-code-syntax-highlight": "1.0.0",
"@toast-ui/react-editor": "2.5.1",

**Comment by js87zz** [comment]
@HTMLhead 
It's hard to know the cause just by looking at this code.
Can you give me the reproducible repository link?

**Comment by HTMLhead** [comment]
Thank you for response
Sorry but, This is not possible because the repository is private.

After work, I'll create a new repository to reproduce this error.

**Comment by HTMLhead** [comment]
@js87zz Here's reproducible repository link.

[(https://github.com/HTMLhead/tui-editor-test)]

Please run
`npm i`
`npm run test`

**Comment by js87zz** [comment]
@HTMLhead 
The exact cause is hard to know, but it could be a jsdom or jest environmental problem. 
I want to see more, but I hope you understand that it is difficult to see deeply because there are many other tasks and other priority issues.

But is there a reason for writing the editor test? I'm asking because I think it's more important to test other interactions than the editor in the application.

**Comment by HTMLhead** [comment]
> But is there a reason for writing the editor test? I'm asking because I think it's more important to test other interactions than the editor in the application. 

Cause I want test case like "If editor content value is changed, The save button becomes clickable".
and other interactions are able to test when button has clickable. (Like when save button clicked, modal open...)

Like you said, I'll have to think of a different approach. Thank you for replying despite being busy with other things.
