### ISSUE TITLE
SSR Support expected date

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1645]
You can see in this issue https://github.com/nhn/tui.editor/issues/1537#issuecomment-863043854, @js87zz  told that SSR will be included in the next minor release. Although i am waiting for this feature from last year. I was using `customHtmlRenderer` to render `MD` content on the server side. But, i was having trouble while rendering `uml, chart, code syntax highlight, color syntax highlight` on server side. 

To render them i was rendering plan MD on server and the MD which require plugins on client as `<Viewer>` component. 

I would be happy to know the expected date for SSR support.
Thanks!

**Comment by js87zz** [comment]
@ats1999 
The exact schedule is hard to say. However, SSR support will be a top priority for the next minor version update. 
But for the time being, the Bugfix release will be a priority for stability.

**Comment by ats1999** [comment]
ok
