### ISSUE TITLE
Where can I find documentation for v2.x.x ?

### ISSUE THREAD

**Issue by michaltaberski** [nhn/tui.editor#1647]
## Summary
Currently I am running successfully tui.editor in version `2.2.0`. Now I have to make rather minor update on my setup. Upgrading to version `3.x` is too complex task for now and I want to avoid it. The problem I am having is missing documentation for the legacy version of the editor. Where can I find it?  I've checkout to `v2.2.0` tag on GitHub (https://github.com/nhn/tui.editor/tree/v2.2.0), but there the docs folder is basically empty.

## Version
`2.2.0`

**Comment by js87zz** [comment]
@michaltaberski 
You can find [here](https://github.com/nhn/tui.editor/tree/2.5/apps/editor/docs)

**Comment by michaltaberski** [comment]
Thanks @js87zz !!
