### ISSUE TITLE
Uncaught TypeError: t is not a function

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1648]
## Describe the bug
Getting this bug in production

## To Reproduce
Deploye it on vercel or use build version locally.

## Screenshots
![Screenshot from 2021-07-06 20-36-14](https://user-images.githubusercontent.com/54087826/124623739-d7fd5b00-de99-11eb-9039-4a6766d401cb.png)

## Platform
Vercel https://vercel.com

## Live
https://react-do-ats1999.vercel.app/

Open dev console

**Comment by js87zz** [comment]
@ats1999 
It looks the duplicate issue(#1589).

**Comment by ats1999** [comment]
@js87zz exactly, it's duplicate, but i created this because it's also appearing in production.

**Comment by js87zz** [comment]
This issue is closed because the duplicate issue is resolved.
