### ISSUE TITLE
Is it possible to render Latex content directly in the wysiwyg editor ?

### ISSUE THREAD

**Issue by ClementT3** [nhn/tui.editor#1652]
Is it possible to render Latex content directly in the wysiwyg editor ?

Matter of fact, my application doesn't even have a Markdown tab to write in (I disabled it)
So I would like to write Latex equations in the Wysiwyg editor using the usal format : 

```
$$latex

$
x^2 = 4
$

$$
```

At the moment it's not doing anything (which is normal)
Is it possible with a hack or a native method ?

(Sorry for asking a lot of questions / opening issues, I'm sure this is the last one)

**Comment by js87zz** [comment]
@2klm 
You can edit the custom block in WYSIWYG as below.
![2021-07-08 09-09-09 2021-07-08 09_09_22](https://user-images.githubusercontent.com/37766175/124850281-531a5a80-dfdb-11eb-89bc-b4f79ffd1de9.gif)

Do you want something other than this?

**Comment by 2klm** [comment]
> @2klm
> You can edit the custom block in WYSIWYG as below.
> ![2021-07-08 10-56-58 2021-07-08 10_58_35](https://user-images.githubusercontent.com/37766175/124850369-75ac7380-dfdb-11eb-9979-9849f6e52594.gif)
> 
> Do you want something other than this?

I’ll check this out and I’ll let you know.
