### ISSUE TITLE
Viewer with dark mode

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1653]
## Summary
Is viewer has dark mode?

## Version
`v3.0.0`

**Comment by 2klm** [comment]
Yes, it does have a dark mode. To enable it, add these lines to your editor config : 

```
// ...
import '@toast-ui/editor/dist/toastui-editor.css';
import '@toast-ui/editor/dist/theme/toastui-editor-dark.css';

const editor = new Editor({
  // ...
  theme: 'dark'
});
```

Please read documentation before posting an issue :)

**Comment by ats1999** [comment]
@2klm I think you have misunderstood the question, i am talking about `Viewer` not `Editor`. 

https://codesandbox.io/s/still-night-0feor?file=/src/App.js

Have a look  at the above sandbox. You'll not see any text on the screen, because `bg` is white and `text-color` is also white.

**Comment by 2klm** [comment]
Oh my bad, I did misunderstood.
If you set the editor theme to dark, does the viewer stays in light theme ?
Have you tried adding the theme: 'dark' option in the viewer instanciation ?

Anyways if you have time, you can still make the dark theme yourself, it's only a few CSS rules.

**Comment by js87zz** [comment]
@ats1999 
The dark mode css rules are applied to `Viewer`.
However, in this case, the background color of the viewer is not specified separately, so it follows the parent element. it seems to need some improvement.

**Comment by ats1999** [comment]
@js87zz in my comment you can see a code sandbox link.

I used to write everything in English.

**Comment by js87zz** [comment]
@ats1999 
Yes, I checked the sandbox and will review it and work on our viewer's background color. 
I was asking you to respect our basic issue template~ :)

**Comment by ats1999** [comment]
@js87zz I used to follow issue template, but i this was a simple question, so i didn't follow this time. Sorry for that!
