### ISSUE TITLE
While using customHTMLRenderer with returning <p> or <div> tag, its block keeps duplicating (react)

### ISSUE THREAD

**Issue by yulimshin-tatum** [nhn/tui.editor#1657]
## Summary

While using customHTMLRenderer with image func returning `<p>` or `<div>` tag, its block keeps duplicating in preview section.
But when I get editor's markdown data, it goes fine. it is working weird with only preview section.

+) I think duplicating is triggered by onChange, but I don't know why.

Is there something wrong with my code?

My code
```
customHTMLRenderer={{
        image(node, context) {
          const { destination } = node;
          const { getChildrenText, skipChildren } = context;
          const desc = getChildrenText(node)
          skipChildren();
    
          return [
            { type: 'openTag', tagName: 'p',  classNames: ['img-block'], },
            { type: 'openTag', tagName: 'img', selfClose: true,
              attributes: {
                src: destination,
              }},
            { type: 'html', content: `<em>${desc}</em>` },
            { type: 'closeTag', tagName: 'p'}
          ];
        },
```
## Screenshots
If applicable, add screenshots to help explain your question.

https://user-images.githubusercontent.com/79494605/124850361-73e2b000-dfdb-11eb-96b1-0a50fdf91328.mov

- first duplicating triggered by input ENTER
- second duplicating triggered by adding new image

## Version
3.0.1 react-editor

**Comment by yulimshin-tatum** [comment]
I just follow the example here https://github.com/nhn/tui.editor/blob/master/docs/en/custom-html-renderer.md#controlling-newlines
and same issue appears. It is something related with traversing?

**Comment by js87zz** [comment]
@yulimshin-tatum 
Because the `image` node is an inline node, it is essentially wrapped in a `paragraph` node, which is a block node.
Then, the preview will have the following DOM structure.
```html
<p><img src"..."/></p>
```
Let's look at the renderer you define. It will be rendered as below, but it is impossible.
```html
<p><p><img src"..."/><em>...</em></p></p>
```
The `paragraph` element represents a paragraph. **It cannot contain block-level elements (including P itself)**.
This is why rendering is broken, and in order to customize the image node correctly, it must be configured only with **inline nodes** as shown below.

```js
customHTMLRenderer={
  image(node, context) {
    const { destination } = node;
    const { getChildrenText, skipChildren } = context;
    const desc = getChildrenText(node)
    skipChildren();

    return [
      { type: 'openTag', tagName: 'img', selfClose: true,
        attributes: {
          src: destination,
        }},
      { type: 'html', content: `<em>${desc}</em>` },
    ];
  },
}
```

**Comment by yulimshin-tatum** [comment]
@js87zz Why I add p tag outside img was to add a class to its block.
What I eventually wanted to try was making image-caption with text-align:center, but I can't find a way to add class to its parent or just assign center attribute to caption. I think it would be nice to have features like customizing whole block:)

Thanks for your explanaiton!
