### ISSUE TITLE
Wysiwyg editor does not correctly escape input 

### ISSUE THREAD

**Issue by J-avery32** [nhn/tui.editor#1658]
## Describe the bug

The Wysiwyg editor does not correctly escape input. 

## To Reproduce
1. Go to https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-with-wysiwyg-mode
2. Enter in any html tag such as: \<b\>test\</b\>. Or enter in \_Test\_. 
3. Click on the markdown tab on bottom right corner of editor.
4. Click back on the Wysiwyg editor.
5. Observe that the tag is gone and the corresponding format is applied to the inner text.

## Expected behavior
I expect for the Wysiwyg editor to display exactly what I typed in originally. Is this expected behavior or a bug?

## Desktop (please complete the following information):
 - OS: Ubuntu
 - Browser: Firefox

**Comment by js87zz** [comment]
@J-avery32 
Oh..It's not intended operation. I will fix it.

**Comment by js87zz** [comment]
@J-avery32 
The bug has been fixed in `v3.0.2`. Thanks!

**Comment by J-avery32** [comment]
Great. I will close this issue.
