### ISSUE TITLE
Rendering inline math

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1660]
## Summary
I want to have math equation inline, just like below image.
![Screenshot from 2021-07-08 15-48-36](https://user-images.githubusercontent.com/54087826/124905749-fb441980-e003-11eb-8878-6f13607fe815.png)

## Version
Latest

## Additional context
I have tried `htmlInline` as
```js
htmlInline: {
            var(node, { entering }) {
              console.log(node);
              return entering
                ? { type: "openTag", tagName: "big", attributes: node.attrs }
                : { type: "closeTag", tagName: "big" };
            }
          }
```
I typed `<var>abc` in editor and got below in the console.
![Screenshot from 2021-07-08 15-51-56](https://user-images.githubusercontent.com/54087826/124906311-8fae7c00-e004-11eb-9910-d52f224ef914.png)

It has no data which was entered in the editor.

## What i want
I want to parse the math equations inline.

Suppose i  have markdown `And here is some in-line math: $k_{n+1} = n^2 + k_n^2 - k_{n-1}$` where `$` is starting and ending point of inline math. It should produce below output.
![Screenshot from 2021-07-08 15-48-36](https://user-images.githubusercontent.com/54087826/124906687-f59b0380-e004-11eb-8a80-290720fe46e3.png)

**Comment by js87zz** [comment]
@ats1999 
Currently, we support only block customization. The customization syntax for inline nodes is not yet officially supported.😂
The plan for this feature is a priority, but I am not yet clear exactly when I can do the work.

**Comment by ats1999** [comment]
@js87zz 
>The plan for this feature is a priority,

Let me know once it's done.

Thanks!
