### ISSUE TITLE
Select , cut is not working in custom block

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1661]
## Describe the bug
When i try  to select and cut some text from custom block, then all content of the block is being selected. When i release mouse then the same content is pasted. 
## To Reproduce
Try  to select `latex` code in `WYSIWYG` mode from dragging mouse.

**Comment by js87zz** [comment]
@ats1999 
In the case of a custom block, it is selected on a block node basis because it is a single selection unit.
If it is another issue, I would appreciate it if you could show me the image or gif.

**Comment by ats1999** [comment]
https://user-images.githubusercontent.com/54087826/125270148-0316fd00-e327-11eb-8595-5094be7a129d.mp4


## Video
See, the content is pasted when we release the mouse.

**Comment by js87zz** [comment]
@ats1999 
The bug has been fixed in `v3.1.2`. Thanks!
