### ISSUE TITLE
How to call `insertText()` from plugin level?

### ISSUE THREAD

**Issue by michaltaberski** [nhn/tui.editor#1662]
Hi, I have successfully created a most of simple plugin I want to use in tui.editor `3.0.1`. Plugin doesn't do much but it suppose to inserts a simple predefined string. The problem is that when I execute the command I have no access to editor instance, therefore I can't call `editor.insertText(placeholderString)`. So here is my question - how to insert such text?

## Code snippet explaining the issue
```ts
const insertPlaceholderCommand: CommandFn<{
  placeholderString: string;
}> = ({ placeholderString }, state, dispatch, view) => {
  // 
  // HERE IS THE QUESTION:
  // HOW TO INSERT TEXT `placeholderString` IF
  // I HAVE NO ACCESS TO EDITOR INSTANCE ??
  // 
  return false;
};

const newPlaceholderPlugin: PluginFn = (
  pluginCtx: PluginContext,
  pluginOptions: PlaceholderPluginOptions
): PluginInfo => {
  return {
    toolbarItems: [
      {
        // quite artificial number, but the purpouse is to push it to the every end of toolbar
        groupIndex: 10,
        itemIndex: 10,
        item: {...}, // this works
      },
    ],
    markdownCommands: {
      insertPlaceholder: insertPlaceholderCommand,
    },
    wysiwygCommands: {
      insertPlaceholder: insertPlaceholderCommand,
    },
  };
};
```

## Version
`3.0.1`

## Additional context
I am using `'@toast-ui/react-editor'` version, so I have no access to editor instance until el is mounted.

**Comment by michaltaberski** [comment]
I will answer myself. Maybe it will be useful for someone. The solution that works for me is:
```
const insertPlaceholderCommand: CommandFn<{
  placeholderString: string;
}> = ({ placeholderString }, { tr, selection }, dispatch) => {
  tr.insertText(placeholderString, selection.to);
  dispatch(tr);
  return true;
};
```

**Comment by js87zz** [comment]
@michaltaberski 
Great! You can insert the text like you wrote it. 
But if you're adding the placeholder string, I think it's better to use the `placeholder` option as below.
```js
const editor = new Editor({
  // ...
  placeholder: placeholderString
});
```

**Comment by michaltaberski** [comment]
@js87zz understand, but my case is different. I have created a custom menu where I can pick one of few placeholders which later I process to different content. eg:
```
# Hey {authorName},
```

in this case what I call placeholder is `{authorName}`.
