### ISSUE TITLE
editor is not making scroll  in table with wysiwyg mode

### ISSUE THREAD

**Issue by devToroko** [nhn/tui.editor#1664]
## Describe the bug
I am using editor inside [ table > tr > td ] and knew there is some bug.
if i use markdown editor it works fine with height option i give and make scroll when overflow.
but if i use in wysiwyg  mode, it doesn't make scroll.
it just get bigger and bigger.

## To Reproduce

```javascript
<body>
    <!-- <div id="editor"></div> -->
    <table>
        <tr>
            <th>content</th>
            <td id='editor'></td>
        </tr>
    </table>
    <script>
        const editor = new toastui.Editor({
            el: document.querySelector('#editor'),
            height: '100px',
            initialEditType: 'markdown',
            previewStyle: 'vertical',
            language: 'ko-KR',
            plugins: [toastui.Editor.plugin.colorSyntax]
        });
    </script>
</body>
```
1. make table and use td as editors container.
2. enter several time.
3. editor doesnt make scroll.

## Expected behavior
want scroll when using editor in table with wysiwyg mode.

## Screenshots
![image](https://user-images.githubusercontent.com/51431766/125011553-a657e000-e0a3-11eb-9d30-46f248babaa9.png)

## Desktop (please complete the following information):
 - OS: [Window10]
 - Browser [chrome]
 - Version [91.0.4472.124]

**Comment by js87zz** [comment]
@devToroko 
The bug has been fixed in `v3.0.2`. Thanks!
