### ISSUE TITLE
How to create a custom markdown markup?

### ISSUE THREAD

**Issue by michaltaberski** [nhn/tui.editor#1667]
I would like to add support for markdown custom markup like `{color:#ff0000/}red text{color}` which should be translated to `<span style="color: #ff0000;">red text</span>` in html mode.
Also I am using `colorSyntaxPlugin` which evaluates picked color to `<span style="color: #a72929">cool</span>`. Can I make it dynamically translated also to `{color:#a72929/}cool{color}` syntax?

## Summary
Looking for resources to learn how to add support for custom markdown syntax.

## Version
`3.0.1`

### EDIT
From what I read and understood I am looking for something what was called convertor in version 1.x: https://nhn.github.io/tui.editor/1.4.10/tutorial-example14-custom-convertor right?

**Comment by michaltaberski** [comment]
@js87zz correct me if I am wrong, but the architecture looks more or less like so, correct?

<img width="989" alt="Screenshot 2021-07-11 at 22 42 20" src="https://user-images.githubusercontent.com/202033/125209512-8ab62a80-e299-11eb-9361-99b74bd5e7d7.png">

**Comment by js87zz** [comment]
@michaltaberski 
You can find the custom markdown syntax in [this tutorial](https://github.com/nhn/tui.editor/blob/master/docs/en/custom-block.md). 
However, currently, only block customization is supported, and customization syntax for inline nodes is not yet officially supported. Your example is also an inline node, so it is not yet supported.😂

The plan for this feature is a priority, but I am not yet clear exactly when I can do the work.

**Comment by vin-ni** [comment]
@michaltaberski  have you found any solution?
