### ISSUE TITLE
Get editor contents in POST

### ISSUE THREAD

**Issue by AlirezaIvaz** [nhn/tui.editor#1676]
## Summary
Most wysiwyg editors use `textarea` and with the `name` attribute you can get the value entered through the `$_GET` variable and perform the operation, but in TUI `div` is used and its content can not be obtained in PHP.

## Version
3.0.0

**Comment by js87zz** [comment]
@AlirezaIvaz 
Our Editor only uses `contenteditable` for editing. If you want text data, we recommend using `getMarkdown()` or `getHTML()` API.
