### ISSUE TITLE
No options parameters for ToastUIEditor class are listed in the documentation

### ISSUE THREAD

**Issue by J-avery32** [nhn/tui.editor#1680]
## Describe the bug
No options parameters are listed in the documentation

## To Reproduce
Go to https://nhn.github.io/tui.editor/latest/ToastUIEditor

Observe that there are no options listed in the table with the title: "new ToastUIEditor(options)"
## Expected behavior
I expect that all of the available options with types and descriptions would appear on this table.

**Comment by jack9603301** [comment]
see https://nhn.github.io/tui.editor/latest/ToastUIEditorCore

**Comment by J-avery32** [comment]
OK then I think what needs to be fixed is the link under this heading: https://github.com/nhn/tui.editor/tree/master/apps/editor#default-options

**Comment by js87zz** [comment]
@J-avery32 
Thanks for reporting!
