### ISSUE TITLE
How to Image Upload not Base64??

### ISSUE THREAD

**Issue by DongJu-Na** [nhn/tui.editor#1686]
## Summary
How to Image Upload not Base64??

## Version
using the latest version.

## Additional context
When uploading an image using addImageBlobHook, is it possible to preview and upload in a way other than base64? I'd appreciate it if you could tell me how.

**Comment by JakubGIT** [comment]
I've made:

```typescript
editorInstance.removeHook('addImageBlobHook');
editorInstance.addHook('addImageBlobHook', callback);
```

`editorInstance` is an object, which is returned by `<reference to the editor>.current.getInstance()`
`callback` becomes `blob` as argument - then you can do your stuff.

My callback is
```typescript
const callback = async (blob) =>
    {
        ...
    }
```

**Comment by DongJu-Na** [comment]
Is there a callback function that I can edit even when the image is deleted?
