### ISSUE TITLE
Running classifyToolbarItems () in the Window resizing event, but I want you to run classifyToolbarItems () in the toastui-editor-defaultUI resizing event

### ISSUE THREAD

**Issue by HiroyukiNIshimura** [nhn/tui.editor#1687]
## Describe the bug
Running classifyToolbarItems () in the Window resizing event, but I want you to run classifyToolbarItems () in the `.toastui-editor-defaultUI` resizing event.
Window resizing does not occur, side menus etc. are displayed and menus are not redrawn when the size of toastui-editor-defaultUI is changed.

window.addEventListener("resize",this.handleResize)};
↓
~~document.querySelector('.toastui-editor-defaultUI').addEventListener("resize",this.handleResize)};~~
Is this not good if you have two or more editors 😓

**Comment by js87zz** [comment]
@HiroyukiNIshimura 
The bug has been fixed in `v3.0.3`.
