### ISSUE TITLE
How to use custom css for markdown in editor and viewer

### ISSUE THREAD

**Issue by JakubGIT** [nhn/tui.editor#1688]
## Summary
I would like to use custom css file for the markdown elements. i.e. only to change, how the markdown content is displayed - in both editor and viewer. I'd moreover like to exchange the css file dynamically as the program runs. Is it possible?
Thank you!

## Version
3.0.0

**Comment by ats1999** [comment]
yes, override the CSS by manually targeting classes,

**Comment by js87zz** [comment]
@JakubGIT 
Sorry for late replying.
As mentioned above, I think it's the best way to override CSS class.
Thanks!

**Comment by JakubGIT** [comment]
Thank you both for the replies.

I'm not 100% sure, how to do it though. Let's say I have these components:

```TypeScript
import React from 'react';
import {Editor, Viewer} from '@toast-ui/react-editor';
// Import language file
import '@toast-ui/editor/dist/i18n/de-de';
import '@toast-ui/editor/dist/toastui-editor.css';

export const MyEditor = (reference: React.LegacyRef<Editor>, content: string): JSX.Element => (
    <Editor
        ref={reference}
        height="600px"
        initialEditType="markdown"
        initialValue={content}
        language="de"
        previewStyle="tab"
        useCommandShortcut

    />
);

export const MyViewer = (reference: React.LegacyRef<Editor>, content: string): JSX.Element => (
    <Viewer
        ref={reference}
        initialValue={content}
    />
);
```
and let's say I add a property `cssFile: string`, which contains the css code I want to use. The signatures would look like that:
```TypeScript
export const MyEditor = (reference: React.LegacyRef<Editor>, content: string, cssFile: string): JSX.Element
export const MyViewer = (reference: React.LegacyRef<Editor>, content: string, cssFile: string): JSX.Element
```

if I understand correctly what you say, the `cssFile` should contain thing like

```css
.toastui-editor-md-heading1 {
  font-size: 666px;
}
```

with <kbd>666px</kbd> being different to the value in `@toast-ui\editor\dist\toastui-editor.css`, which is <kbd>24px</kbd>

How do I tell the ToastUI Editor and Viewer to prefer `cssFile` to `@toast-ui\editor\dist\toastui-editor.css`?

thank you very much!

**Comment by ats1999** [comment]
See
```css
.toastui-editor-contents h2 {
  border-bottom: 0px;
}

.toastui-editor-contents a{
  text-decoration: none;
}

// ... so  on
```

**Comment by JakubGIT** [comment]
OK, thanks - still - how to tell the editor and viewer to prefer my values to the values in the `@toast-ui\editor\dist\toastui-editor.css`file?

**Comment by ats1999** [comment]
If the above dose't worked, then force it to use your css by `!important`

```css
.toastui-editor-contents a{
  text-decoration: none !important;
}
```

**Comment by boussou** [comment]
Hi, what is the best way to change the font? 
Or just the font size globally within the editor?

**Comment by boussou** [comment]
ok, for the record, auto answer:

```html
    <style>

        .toastui-editor-contents,.ProseMirror {
            font-family:  "YourFont Sans", ... ; 
            font-size: 14px;
        }

    </style>
```
