### ISSUE TITLE
Is there a callback function that I can call when deleting an image?

### ISSUE THREAD

**Issue by DongJu-Na** [nhn/tui.editor#1690]
Is it possible to call an event that occurs when an image is deleted?
Is there an opposite function of addImageBlobHook as an example??

**Comment by ats1999** [comment]
I think currently it's not there

**Comment by js87zz** [comment]
@DongJu-Na 
Sorry for late replying.
Currently, we don't provide the event for it.
Is it because of deleting the image uploaded on the server? I'll think about this later.

**Comment by ats1999** [comment]
@DongJu-Na 
Can you fill this form for this editor https://docs.google.com/forms/d/e/1FAIpQLSdhPRNZlEknQcx0V9Ww5U2sAbN_wv3WTmFeWIOIX21LRjFd7Q/viewform

**Comment by Ben-Mack** [comment]
@js87zz This is quite an important feature, please consider adding it. I need this to delete unused uploaded image.
