### ISSUE TITLE
how to set preview tab default? activeTab not work

### ISSUE THREAD

**Issue by halcyonone** [nhn/tui.editor#1691]
## Summary
how to set preview tab default? activeTab not work?

## Version
2.5.3

## Additional context
options:
minHeight: '200px',
  previewStyle: 'tab',
  useCommandShortcut: true,
  useDefaultHTMLSanitizer: true,
  usageStatistics: false,
  hideModeSwitch: false,
  language: "zh-CN",
 hideModeSwitch: "true", 
 previewHighlight: false
  toolbarItems: [
    'heading',
    'bold',
    'italic',
    'strike',
    'divider',
    'hr',
    'quote',
    'divider',
    'ul',
    'ol',
    'task',
    'indent',
    'outdent',
    'divider',
    'table',
    'image',
    'link',
    'divider',
    'code',
    'codeblock'
  ]

**Comment by js87zz** [comment]
@halcyonone 
Sorry for late replying.
Currently, we don't provide the option for setting initial tab(`write` or `preview` tab) in markdown.
