### ISSUE TITLE
Editor v3 breaks when tables have invalid list HTML

### ISSUE THREAD

**Issue by KirilSoshnin** [nhn/tui.editor#1692]
## Describe the bug
When a table has a list in HTML, but the HTML is invalid, switching between editor modes breaks the editor and all content is erased. Switching back to markdown does not resolve the issue, as content will be gone from there too.

## To Reproduce
1. Go to https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic
2. Enter markdown mode
3. Enter the following markdown content:
(notice the missing `\` in the closing `ul`)
 ```
|  |  |
| --- | --- |
| <ul><li>Hello</li><ul>  |  |
```
4. Switch editor mode to WYSIWYG
5. See bug

## Expected behavior
The HTML should be re-parsed and fixed, like in V2.5.3

## Desktop (please complete the following information):
 - OS: MacOS, latest
 - Browser: Chrome
 - Version: latest

**Comment by ats1999** [comment]
@KirilSoshnin 
Can you give some information about this editor: 
  https://docs.google.com/forms/d/e/1FAIpQLSdhPRNZlEknQcx0V9Ww5U2sAbN_wv3WTmFeWIOIX21LRjFd7Q/viewform

**Comment by js87zz** [comment]
@KirilSoshnin 
The bug has been fixed in `v3.1.0`. Thanks for waiting!
