### ISSUE TITLE
Bugs exposed using getHTML on blur

### ISSUE THREAD

**Issue by m-f-home** [nhn/tui.editor#1693]
first: write content on the markdown page，like this：
![image](https://user-images.githubusercontent.com/51625532/126584009-69b5515c-fb65-4844-8649-7ff80b203ad8.png)

then: switch to the ww page, and then switch back to the md page, preview will always stay in the state before the switch(markdown page), like this: 
![image](https://user-images.githubusercontent.com/51625532/126584132-d1e22184-d9de-4936-99d6-3da6029e60e8.png)

**Comment by js87zz** [comment]
@m-f-home 
Sorry for late replying.
Can you explain the detail? I cannot reproduce it.
It's very helpful to give us your configuration code or demo in code sand box
