### ISSUE TITLE
How to rename Markdown & WYSIWYG tabs? 

### ISSUE THREAD

**Issue by callumbuttery** [nhn/tui.editor#1694]
## Summary
Looking to see if it is possible to change the markdown & wysiwyg tab text?

## Screenshots
![image](https://user-images.githubusercontent.com/46718195/126641183-a3ba9205-d32d-4b3a-a596-1ac7b0c6aca8.png)

**Comment by js87zz** [comment]
@callumbuttery 
[This tutorial(2.x)](https://github.com/nhn/tui.editor/blob/2.5/apps/editor/docs/i18n.md) will be helpful to you~!
