### ISSUE TITLE
Pie chart in editor

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1707]
## Summary
Documentation of [tui.chart](https://ui.toast.com/tui-chart) says about the uses with javascript, but i did't found any documentation to render different chart in the editor.

### How can i render pie chart in the editor?

Using JS
```js
import Chart from '@toast-ui/chart';

const chart = Chart.pieChart({el, data, options});
```

Here, `Chart.pieChart` defines pie chart,how can we do this in editor.

**Comment by js87zz** [comment]
@ats1999 
We cannot support all chart type with editor's csv format. I need to check it with the toastui chart.
I will check it!

**Comment by ats1999** [comment]
@js87zz  most of the `tui.chart` have  the same data format, we can support all types of chart by just taking parameter of in yaml format from markdown.

```js
---
chart-type:line
 series-names : rahul, kumar,..
.....
...
---
```
