### ISSUE TITLE
video html element will be dropped when i use the setHTML method

### ISSUE THREAD

**Issue by Znuoya** [nhn/tui.editor#1710]
## Describe the bug
As the title, video tag will be dropped in the setHTML method

## To Reproduce
1. set the initial html string:
```
<div>
<h2>视频示例</h2>
<video controls="controls" width="500" height="250">
<source src="https://xxxx.mp4" type="video/mp4" /></video>
</div>
```
2. Render Editor with
```
<Editor
    height="auto"
     language="zh-CN"
     hideModeSwitch={true}
     ref={fileEditorRef}
     onChange={handleMarkdownChange}
/>
```
3. use the setHTML method: fileEditorRef.current?.getInstance().setHTML(the above html string)
4. render result will only show the H2 ELEMENT, but the video ELEMENT IS DROPPED.

## Expected behavior
can show the video tag

## Desktop (please complete the following information):
 - OS: [iOS]
 - Browser [chrome]
 - Version [3.0.1]

**Comment by js87zz** [comment]
@Znuoya 
The bug has been fixed in `v3.1.0`. Thanks for wating.
You can use video as below.

```js
const customHTMLRenderer = {
  htmlBlock: {
    video(node) {
      return [
        { type: 'openTag', tagName: 'video', outerNewLine: true, attributes: node.attrs },
        { type: 'html', content: node.childrenHTML },
        { type: 'closeTag', tagName: 'video', outerNewLine: true },
      ];
    }
  }
}

<Editor
    height="auto"
    customHTMLRenderer={customHTMLRenderer}
    // ...
/>
```
