### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'PluginKey' of undefined" when using /dist/toastui-editor.js from current NPM package

### ISSUE THREAD

**Issue by MoritzGiessmann** [nhn/tui.editor#1715]
First of all: Thank you for your amazing work! 
Second: I am not sure if what I tried to do was intended by the authors, but it looked like this should work. Please correct me if I’m wrong.

## Describe the bug
When using `toastui-editor.js` from the [current NPM package (3.0.1)](https://www.npmjs.com/package/@toast-ui/editor/v/3.0.1) directly in HTML, the browser console throws an error `Uncaught TypeError: Cannot read property 'PluginKey' of undefined`. This does not happen when I use the [CDN version](https://uicdn.toast.com/editor/latest/toastui-editor-all.js). Using just the viewer (dist/toastui-editor-viewer.js) works as intended.

## To Reproduce
1. Install the [current NPM package (3.0.1)](https://www.npmjs.com/package/@toast-ui/editor/v/3.0.1) in your project
2. Use the JS-file from `node_modules` in your HTML like `<script src="node_modules/@toast-ui/editor/dist/toastui-editor.js"></script>`
3. Open HTML file in browser
4. Error visible in browser console (Chrome).

## Expected behavior
No JS error occurs, editor loads.

See demo: 
https://moritzgiessmann.de/toast-test/

HTML looks like this:

```HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editor test</title>
    <link rel="stylesheet" href="node_modules/@toast-ui/editor/dist/toastui-editor.css">
</head>
<body>
<div id="editor">EDITOR</div>
<!-- <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.js"></script> -->
<script src="node_modules/@toast-ui/editor/dist/toastui-editor.js"></script>
<script>
const editor = new toastui.Editor({
    el: document.querySelector('#editor'),
    height: '500px',
    initialEditType: 'wysiwyg',
    usageStatistics: false,
  });
</script>
</body>
</html>
```

**Comment by js87zz** [comment]
@MoritzGiessmann 
The `@toast-ui/editor/dist/toastui-editor.js` file has no information about external dependencies. This bundle is suitable for esm or other build with bundler in node environments. It is recommended to use CDN link in the above case.

**Comment by realLiangshiwei** [comment]
Hi @js87zz 

> The @toast-ui/editor/dist/toastui-editor.js file has no information about external dependencies

So, if I want to use the NPM package instead of CDN link, I need to add dependencies manually, right?

If yes, but I don't know what to add and which dependencies, because the document does not explain.

Should it be explained on the documentation, what do you think?

**Comment by yuseok** [comment]
@realLiangshiwei Though this is an old and closed issue, I found a way re-packing source for usage in browser by webpack. Please refer following steps. 

Note that I use `express` server.


### project structure
```
- project root/
    ├ build_toastui/
    │    └ toast_generator.js # temporary script for generating toastui.js
    │
    ├ public/
    │    ├ css/
    │    │    └ toastui-editor.css # css from dist directory
    │    │
    │    ├ js/
    │    │    └ toastui.js # it will be created from webpack
    │    │
    │    └ index.html
    │
    ├ app.js
    ├ package.json
    ├ webpack.config.js
    │
```

### toast_generator.js
```javascript
import * as Editor from "@toast-ui/editor";

export default Editor;
```

### webpack.config.js
```javascript
const path = require("path");

module.exports = {
    mode: "production",
    entry: "./build_toastui/toast_generator.js",
    output: {
        path: path.join(__dirname, "public", "js"),
        filename: "toastui.js",
        library: {
            name: "toastui",
            type: "var",
            export: "default"
        },
    },
};
```

### index.html
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" href="/css/toastui-editor.min.css" />

        <title>Editor</title>
    </head>
    <body>
        <div>
            <div id="editor"></div>
        </div>

        <script src="/js/toastui.js"></script>
        <script>
            var editor = new toastui.Editor({
                el: document.querySelector("#editor"),
                initialEditType: "markdown",
                previewStyle: "vertical",
            });

            editor.getMarkdown();
        </script>
    </body>
</html>
```


```
$ npx webpack build
$ npm run start
```

### output
![image](https://user-images.githubusercontent.com/7038876/155483440-a1ae48eb-4294-4066-a2cc-b78306ab0a4a.png)


---
@js87zz 
 위에 적은대로 사용하면 동작은 원 질문자의 의도되로 되는 것으로 보입니다. 다만, nhn에서 의도한 사용법과는 다소 거리가 있지 않을까 하여 멘션드렸습니다. 의견 부탁드립니다.
