### ISSUE TITLE
UML plugin is not working

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1716]
## Describe the bug
UML plugin is not working, but it is generating correct image.

## To Reproduce
1. Go to https://www.dsabyte.com/editor-dark
2. paste below code
```js
$$uml
(*)->rahul
$$
```
You'll not see any UML diagram. 

When you'll inspect then you'll see that image has correct `src`
![Screenshot from 2021-07-31 17-15-39](https://user-images.githubusercontent.com/54087826/127738906-d09e4f40-93fa-40e3-9930-450c7b5b3bbd.png)

Generated image https://www.plantuml.com/plantuml/svg/qz3IrBKhIimepU420000

**Comment by js87zz** [comment]
@ats1999 
Hmm..I can see the diagram well.. It doesn't look like a plug-in problem.
Did you check the your network env?
![스크린샷 2021-08-02 오전 11 23 07](https://user-images.githubusercontent.com/37766175/127796248-0fdb426a-254a-4a8c-afbd-e11f2cf15774.png)

**Comment by ats1999** [comment]
I don't know why this is working, but i have tried too many time in my browser and the same hapens.

**Comment by ats1999** [comment]
Network is perfectly fine

**Comment by js87zz** [comment]
@ats1999 
This seems to be a problem unrelated to the editor. I close this issue.
