### ISSUE TITLE
a bug in browser env with @toast-ui/editor-plugin-code-syntax-highlight

### ISSUE THREAD

**Issue by www159** [nhn/tui.editor#1718]
## Describe the bug
I just want to decorate it but not too be familiar with it.
when I try to introduce the plugin local with tag <script> like this:
![image](https://user-images.githubusercontent.com/40891547/127761831-cc0e2340-c1b6-446e-ab74-cf9c70f1bde9.png)

my chrome reports as below:
![image](https://user-images.githubusercontent.com/40891547/127761813-ed5dff69-8273-4933-939f-d96265db0246.png)

I am a little white. please help me if possible.

**Comment by js87zz** [comment]
@www159 
Try to use CDN link in your case~!
Please refer [this lilnk](https://github.com/nhn/tui.editor/tree/master/plugins/code-syntax-highlight#-usage-cdn)
