### ISSUE TITLE
a suggestion for red underlines

### ISSUE THREAD

**Issue by www159** [nhn/tui.editor#1725]
## Version
3.0.0

## Development Environment
window 10

## Description
why chrome has spellcheck? ????
It makes me crazy when faced numerous red underlines my chrome adding automaticly especially in wysiwyg mode.
It's would be better to avoid some 'smart' browsers~~~

**Comment by Bistard** [comment]
see #1655 , you can do like this:
```
const md = document.getElementById('md')
md.setAttribute('spellcheck', 'false')
```

**Comment by js87zz** [comment]
@www159 
You can control the issue as above comment. 
It seems that there is no reason to prevent such basic operation in WYSIWYG Editor.

**Comment by www159** [comment]
thx, issue is closed
