### ISSUE TITLE
mermaid diagram is not perfectly rendering in markdown mode

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1727]
## Describe the bug
I am trying to render [mermaid](https://mermaid-js.github.io/mermaid/#/) diagram. It's only rendering in wyswyg mode and not in viewer/markdown mode.

## To Reproduce
1. Go to https://www.dsabyte.com/write/sa
2. paste 
```js
$$mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
$$
```
3. Open markdown mode
3. Open  wyswyg mode
4. Spot the difference

### Directly edit code
https://stackblitz.com/edit/react-43hudd?file=src%2FApp.js

### Markdown Mode
![Screenshot from 2021-08-03 01-27-23](https://user-images.githubusercontent.com/54087826/127916523-205cfd50-0b5d-4f89-a9ca-901af444a4d8.png)

### WYSWYG Mode
![Screenshot from 2021-08-03 01-28-02](https://user-images.githubusercontent.com/54087826/127916598-32bf25e6-a2d1-4341-bc06-1e4c8f466695.png)

**Comment by ats1999** [comment]
Any update??

**Comment by zsanhong** [comment]
Any update??

**Comment by 464884492** [comment]
new Editor({ 
customHTMLSanitizer: function (html) {
        return html;
      }})

**Comment by kabachello** [comment]
The links above are dead. Could anyone please share the code to make mermaid work at least in WYSIWYG mode?
