### ISSUE TITLE
How to cancel auto focus after initialization?

### ISSUE THREAD

**Issue by big-dream** [nhn/tui.editor#1730]
## Summary
Now that the TOAST UI Editor instance is created, it will automatically focus the browser on the editor, which will affect the user experience. This is not the case with the v2 version. How can I cancel the auto focus? 

## Screenshots
![c0ef40d3-0eff-48f8-84fb-8a5ba3256dad](https://user-images.githubusercontent.com/9215157/128108939-0d63ee5c-9540-40bb-877c-f74f403d58d4.gif)

## Version
3.0.1

## Additional context
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css" />
    <style>
        #content {
            text-align: center;
            font-size: 10em;
            background-color: #eee;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div id="content">1<br/>2<br/>3<br/>4<br/>5<br/>6<br/>7<br/>8<br/>9<br/>10</div>
    <div id="editor"></div>
    <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
    <script>
        window.onload = function() {
            const editor = new toastui.Editor({
                el: document.querySelector('#editor'),
                previewStyle: 'vertical',
                height: '500px',
                initialValue: 'hello world'
            });
        }
    </script>
</body>
</html>
```

**Comment by ats1999** [comment]
Use this API, https://nhn.github.io/tui.editor/latest/ToastUIEditorCore#blur

**Comment by big-dream** [comment]
> Use this API, https://nhn.github.io/tui.editor/latest/ToastUIEditorCore#blur

I tried to use it in this way, but it couldn't achieve the expected effect. Although the focus is cancelled, the page has scrolled to the position of the editor instead of staying at the top of the page. I don't know if it is used incorrectly. 

```
const editor = new toastui.Editor({
    el: document.querySelector('#editor'),
    previewStyle: 'vertical',
    height: '500px',
    initialValue: 'hello world'
});
editor.blur();
```

**Comment by ats1999** [comment]
I think it can not be solved via API because we can only call `.blur()` method after initialization of the editor. But, then page might have been scrolled. 

@js87zz  It needs to be solved via props, like `autoFocus`

**Comment by ar4ipers** [comment]
SetTimeout(() => {
   editor.blur();
}, 0)

**Comment by js87zz** [comment]
@big-dream @ats1999 
I checked it. 
I'll think about how to fix this operation. It does look good to control as an option. 
Thank you!

**Comment by azmeuk** [comment]
This issue is a blocker for me, since it prevents toast-ui editor to integrate with the rest of my UI, as it steals the focus.

**Comment by js87zz** [comment]
@big-dream 
The `autofocus` option has been added in `v3.1.0`. Thanks for @azmeuk.

**Comment by seanwang1998** [comment]
@js87zz 
![image](https://user-images.githubusercontent.com/65933570/145787725-dc60d2e9-8d64-475b-bf28-dbf6068b9d2d.png)
I set autofocus to false, but the cursor remains in the editor after the page loads

**Comment by azmeuk** [comment]
Can you try #2030 to see if it fixes your problem?

**Comment by seanwang1998** [comment]
> 

So the authorities are still working on it? I am currently using NPM install V3.1.0 is there a temporary fix?

**Comment by seanwang1998** [comment]
@azmeuk

**Comment by n3storm** [comment]
This is working per version 3.2.1, though I could not find it documented
