### ISSUE TITLE
3.0.2 missing graphics

### ISSUE THREAD

**Issue by kjeldflarup** [nhn/tui.editor#1734]
## Describe the bug
I was using latest in a simple demo.

This gave me this output
![image](https://user-images.githubusercontent.com/30384076/128269745-0a92610a-d8b2-4858-b8c3-a5f1d200a265.png)

Changing to 3.0.2 was the same, but 3.0.1 made it go away.

I just fix to 3.0.1 to get ahead.

```
<html>
<head>
        <link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css" />
        <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
</body>
</head>
<body>
        <div id="editordiv">Hello <b>World</b></div>
        <script>
const Editor = toastui.Editor;
const editor = new Editor({
  el: document.querySelector('#editordiv'),
  height: '500px',
  initialEditType: 'markdown',
  previewStyle: 'vertical'
});

editor.getMarkdown();

function Save() {
        alert(editor.getHTML())
}
        </script>

<input type="button" onClick="Save();" value="Save">

</body>
</html>

```

## Desktop (please complete the following information):
 - Ubuntu 20.04
 - Chrome Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by js87zz** [comment]
@kjeldflarup 
I fixed it. There was a problem in the cdn bundle. Thank you!
