### ISSUE TITLE
Popup rendered outside visible area in v3.0.2 also

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1735]
## Describe the bug
The issue https://github.com/nhn/tui.editor/issues/1633 was fixed in `3.0.2`, but it is still there. 
## To Reproduce
1. Go to https://stackblitz.com/edit/react-2ajz1z
2. Open in mobile device (not dev tools)
3. or open this in mobile device https://react-2ajz1z.stackblitz.io

## Screenshots

https://user-images.githubusercontent.com/54087826/128279591-29b474ea-335f-4081-b6d9-b5a1e7a0b41e.mp4

## Device dimensions
![Screenshot_20210805-085218](https://user-images.githubusercontent.com/54087826/128285870-d5da5837-1579-4b51-83b5-9aa70ff8a1a2.png)

**Comment by js87zz** [comment]
@ats1999 
Thanks for letting me know. 
But the editor's width is narrower than the basic pop-up. In general, it is unlikely to be used in such situations.

**Comment by ats1999** [comment]
See the dimensions of my mobile, i have added an image above.

Width is 360 px, and height is 684

**Comment by js87zz** [comment]
@ats1999 
As mentioned above, mobile usability has not yet been considered.

**Comment by ats1999** [comment]
Ohh, got it, thanks
