### ISSUE TITLE
[VueJS][3.0.2] CSS weird behaviour without codemirror.css

### ISSUE THREAD

**Issue by ezawadzki** [nhn/tui.editor#1738]
## Describe the bug

I upgraded toastUI Vuejs wrapper from previous version (sorry, I don't remember exactly if it was 2.7.... the last one before 3.0.2) to **3.0.2**.
Before it was using codemirror.css, and worked fine about width displaying. But in new version, I have weird style behaviour, my tabs are shifter toward the left, but if I click on the last tab, everything goes alright after. So I guess there's an issue with width at initialization.

![image](https://user-images.githubusercontent.com/4253915/128365741-8e0556fb-c7ba-42bd-bbe8-f5cf77544b4a.png)

Also, every second browser reload, the toolbar is not appearing completely :

![image](https://user-images.githubusercontent.com/4253915/128365865-d5d8ee9b-3d01-432a-a1d8-eab3be4179d0.png)

![image](https://user-images.githubusercontent.com/4253915/128365928-f1695e96-82a5-4aa7-9068-f2b9581a61b2.png)

Any idea ?

Thanks for this awsome editor !!! I am really happy to use it !

**Version:**
    "vue": "2.6.11",
    "@toast-ui/vue-editor": "^3.0.2",

**Comment by js87zz** [comment]
@ezawadzki 
You're saying the toolbar layout isn't rendered properly?
In this case, I will provide an API to re-layout the toolbar.

**Comment by js87zz** [comment]
@ezawadzki 
The issue has been resolved in `v3.0.3`, so can you check it out?

**Comment by ezawadzki** [comment]
Alright! I will check this this week! Thank you very much for your reactivity!!
