### ISSUE TITLE
How can I get it to work in IE?

### ISSUE THREAD

**Issue by Kyung-A** [nhn/tui.editor#1739]
I'm asking because I can't find any relevant documentation anywhere.
The editor does not load at all in IE. 
The first reason was that loading the colorSyntax plugin with curly braces was incompatible, 
so I removed it
Then the editor was loaded in IE, but writing was blocked. what's the reason?

**Comment by js87zz** [comment]
@Kyung-A 
The editor works in IE. 
If it doesn't work, please provide more information on how it doesn't work with detailed code and some screenshots.
