### ISSUE TITLE
convertor.toMarkdownText do not work properly

### ISSUE THREAD

**Issue by dghg** [nhn/tui.editor#1741]
## Describe the bug
`convertor.toMarkdownText` function can not convert multiple `<br>` tag

## To Reproduce
1. with wysiwyg mode, write a multiple `<br>` content
2. Invoke a `convertor.toMarkdownText` 

## Expected behavior
work properly

## Screenshots
1. with wysiwyg mode, write a multiple 'br' tag

![image](https://user-images.githubusercontent.com/44010625/128638354-b7a69171-ad18-4d03-aa1f-fa5af5359604.png)

2. Invoke a `convertor.toMarkdownText` ( using `console.log(convertor.toMarkdownText(..))`)

![image](https://user-images.githubusercontent.com/44010625/128638384-9b6f6c00-4e0a-4849-94c2-50b07af92121.png)

## Desktop (please complete the following information):
 - OS: macOS 11.4
 - Browser Chrome 92

**Comment by js87zz** [comment]
@dghg 
Sorry for late replying. 
This is not a bug. In Markdown, we deal with the blank line as hard break, so `br` only needs to be added once.

**Comment by ats1999** [comment]
@dghg 
Can you give some information about this editor: 
  https://docs.google.com/forms/d/e/1FAIpQLSdhPRNZlEknQcx0V9Ww5U2sAbN_wv3WTmFeWIOIX21LRjFd7Q/viewform
