### ISSUE TITLE
Customise toolbar items

### ISSUE THREAD

**Issue by anuj9196** [nhn/tui.editor#1743]
## Describe the bug
I want to only show the bold, italic toolbar items. To customise the list of toolbar items, an array of string is passed to the constructor
```
this.editor = new Editor({
        el: this.editorWrapper.nativeElement,
        height: '300px',
        toolbarItems: [
          'bold',
          'italic'
        ] as any
      });
```

Without `as any`, it gives error as 
```
TS2322: Type 'string' is not assignable to type '(string | ToolbarItemOptions)[]'.
```

With `as any`, the error in the editor is gone, but the editor is not working and gives the following error in the console.
```
ERROR TypeError: item.map is not a function
    at index.js:22316
    at Array.reduce (<anonymous>)
    at groupToolbarItems (index.js:22315)
    at new Toolbar (index.js:22654)
    at createComponent (index.js:21464)
    at buildVNode (index.js:21470)
    at render (index.js:21576)
    at new ToastUIEditor (index.js:22921)
    at editor.component.ts:146
    at ZoneDelegate.invoke (zone.js:372)
```

## Expected behavior
It should accept an array of string as options.

## Desktop (please complete the following information):
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 92.0.4515.107 (Official Build) (x86_64)
 - tui.editor version -- 3.0.2

**Comment by ats1999** [comment]
Bro, try this
```js
toolbarItems:[
   [ 'bold', 'italic' ]
]
```

**Comment by anuj9196** [comment]
@ats1999 Thanks 😊
