### ISSUE TITLE
How to align text using Toast UI Vue Editor Text Alignment?

### ISSUE THREAD

**Issue by justirva09** [nhn/tui.editor#1748]
Hi Maintainers! my question same as above, how to align text using toast UI editor in Vuejs? after [reading master docs](https://github.com/nhn/tui.editor/blob/master/docs/en/toolbar.md), the editor provides a total of 16 toolbar items and there are no options for text alignment and font size.

**Comment by js87zz** [comment]
@justirva09 
Our editor does not provide that functionality because it is based on markdown and markdown syntax can't support that kind of functionality.
If you want to use the feature in wysiwyg, it needs to be implemented directly.

**Comment by justirva09** [comment]
@js87zz 
Can u give me an example, if I need to implement it directly with **wysiwyg editor**?
