### ISSUE TITLE
image upload resize and bug

### ISSUE THREAD

**Issue by kasumil** [nhn/tui.editor#1764]
## Summary
There is a bug in the Markdown scroll button, and if the picture is small after uploading my picture, 
the text is not aligned below the picture.

How do I align text under a photo?

How can I resize the image upload edit?
I'm using addImageBlobHook and url, but it returns an Image, but it's large.
I want to set the image width size up to 1000px.

## Screenshots
![화면 캡처 2021-08-20 142748](https://user-images.githubusercontent.com/64586771/130184419-38a00220-5c87-4f28-897e-cbc3b03d6106.png)
![화면 캡처 2021-08-20 142829](https://user-images.githubusercontent.com/64586771/130184459-93ae11e1-576d-41fc-8fed-5392166676af.png)

## Version
sorry, I don't know it
I'm using php and jquery.
`<script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>`

**Comment by js87zz** [comment]
@kasumil 
Currently, the editor does not provide the resizing functionality for image.
It's hard to reproduce the bug for markdown scroll sync toolbar, can you give me the example on the code sandbox?

**Comment by kasumil** [comment]
I apologize.
It was a problem with my css and the cause of the problem was display: inline-block.
The original setting was default p {display:block}, which was a side effect because I was touching other settings.
