### ISSUE TITLE
How can I get types in Typescript

### ISSUE THREAD

**Issue by cary-hu** [nhn/tui.editor#1765]
## Summary
I use tui.editor(3.0.3) in typescript(4.2.3), and at past times, I defined the editor type as any, that was so confused.

and now, I try to import tui.editor types to my project, I didn't find any article to explain how to import types in typescript, and I tried below code:

```typescript
import Viewer from "@toast-ui/editor/dist/toastui-editor-viewer";
import Editor from "@toast-ui/editor/dist/toastui-editor";
```
and a extra d.ts:
```typescript

declare module  "@toast-ui/editor/dist/toastui-editor-viewer" {
    import { Viewer } from "@toast-ui/editor/types/editor";
    export default Viewer;
}

declare module "@toast-ui/editor/dist/toastui-editor" {
    import { Editor } from "@toast-ui/editor/types/editor";

    export default Editor;
}
```

the type worked fine, but when I try to build project, there was a error says:

```
ERROR in ./src/component/xxx.tsx 60:23-70
Module not found: Error: Package path ./dist/toastui-editor is not exported from package C:\...\node_modules\@toast-ui\editor (see exports field in C:\...\node_modules\@toast-ui\editor\package.json)
```

any ideas lead me work with tui.editor types?

so much thanks for your help

## Version
tui.editor: 3.0.3
typescript: 4.2.3
webpack: 5.28.0
ts-loader: 8.0.18

If you need more information, let me know.

**Comment by cary-hu** [comment]
typescript config
```json
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es5",
    "jsx": "react",
    "jsxFactory": "h",
    "allowJs": true,
    "lib": ["ESNext", "DOM"]
  }
}
```

**Comment by cary-hu** [comment]
Seems `import Editor from '@toast-ui/editor';` worked for me

**Comment by cary-hu** [comment]
Sorry for this, but it worked not correct, could you please tell me how to import types..

thanks

**Comment by js87zz** [comment]
@cary-hu 
There is no problem with the definition of the editor's type, so you don't need to do additional work. 
However, the viewer type has not been properly inferred, so it will be fixed later.

**Comment by cary-hu** [comment]
@js87zz  is there any configuration error? I can't get any intelligent tips on typescript, the editor is `any` type.

**Comment by cary-hu** [comment]
@js87zz 
https://codesandbox.io/embed/lucid-wind-vgroj?fontsize=14&hidenavigation=1&theme=dark&view=preview

**Comment by js87zz** [comment]
@cary-hu 
Does this issue happen in the latest version(`v3.1.3`)?

**Comment by cary-hu** [comment]
No, When I upgrade to V3.1.3, the type definition is works well. thanks for your awesome fix 🎉
