### ISSUE TITLE
Uncaught TypeError: Cannot read property of undefined for $$...$$

### ISSUE THREAD

**Issue by Aaron-Hu** [nhn/tui.editor#1768]
## Describe the bug
Input $$e=mc2$$ in the editor will cause the undefined error

## Screenshots
![image](https://user-images.githubusercontent.com/19277713/130400991-91e62cc9-e516-43dd-b437-6623fc66e91e.png)

**Comment by js87zz** [comment]
@Aaron-Hu 
Currently, only block-type custom syntax is supported and custom inline nodes are not yet supported.
However, there seems to be a problem with throwing the error. Can you give me the editor configuration code?

**Comment by Aaron-Hu** [comment]
I can reproduce this issue on the example page  https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic

**Comment by js87zz** [comment]
@Aaron-Hu 
Aha, I got it wrong. I checked the issue and I'll let you know after I fix it.

**Comment by js87zz** [comment]
@Aaron-Hu 
The bug has been fixed in `v3.1.0`.
