### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by Aaron-Hu** [nhn/tui.editor#1770]
## Describe the bug
Input plain text html in the markdown editor, then click WYSIWYG to switch WYSIWYG mode. This cause the TypeError

## Screenshots
![image](https://user-images.githubusercontent.com/19277713/130406299-052ae504-cd6b-46dc-a9a6-357a5983bacb.png)

**Comment by js87zz** [comment]
@Aaron-Hu 
Is there a reason to use it like this? 
Using the html document itself is unlikely to be good for security.
