### ISSUE TITLE
onBlur triggers when user click in the toolbox.

### ISSUE THREAD

**Issue by rrjanbiah** [nhn/tui.editor#1790]
## Describe the bug

https://github.com/nhn/toast-ui.react-editor/issues/17 issue got missed out.

## To Reproduce

1. Go to https://ui.toast.com/tui-editor
2. In WYSIWYG mode, select any text (say, "You can create an instance") and choose bold option from the toolbox. It doesn't work due to onBlur handling.

## Desktop
 - OS: Ubuntu
 - Browser Chrome 93.0.4577.63
 - Version Latest in https://ui.toast.com/tui-editor (3.0.3)

**Comment by js87zz** [comment]
@rrjanbiah 
It's not the bug.
The `focus`, `blur` events are triggered based on the editing area.
Can you tell me why you want to control the `blur` event in the whole area?

**Comment by rrjanbiah** [comment]
@js87zz Looks like you misunderstood the issue. Please check the below video to understand the toolbar issue, that seems to occur due to the `onBlur` handling:

![tuieditor-toolbar](https://user-images.githubusercontent.com/4907427/132298081-9c06e914-f97a-4220-a55d-928d0ca5d6bf.gif)

**Comment by js87zz** [comment]
@rrjanbiah 
Your example is not the WYSIWYG mode and I think it's not the bug.
The command is executed on latest cursor position of the editing area regardless of the blur event.

**Comment by rrjanbiah** [comment]
@js87zz Thanks for your clarification

**Comment by Darthmaul** [comment]
Hi @js87zz sorry to tag on an old issue -- I am having this exact issue right now and I'm not sure how to fix. Clicking the bold in the toolbox triggers the onblur. Some other options seem to work, but bold, italic, strike and underline have the issue reported here. 

Let me know if I should submit a new issue. Thanks.

**Comment by js87zz** [comment]
@Darthmaul 
I'd appreciate it if you could make it a new issue!
