### ISSUE TITLE
Youtube video embedding problem

### ISSUE THREAD

**Issue by JunChulKwon** [nhn/tui.editor#1795]
## Summary
I am trying to put a youtube video in toast ui editor.
There are several examples on the internet, so I made some code.
But I'm having a problem with codeBlockManager.
No further progress due to this issue.

## Version
It is implemented in jsp.
toast ui editor 3.1.0 version.

**Comment by js87zz** [comment]
@JunChulKwon 
The `codeBlockManager` has been removed in `v3.x`.
You can implement it as below(just example).

```js
const customHTMLRenderer = {
  htmlBlock: {
    iframe(node) {
      return [
        { type: 'openTag', tagName: 'iframe', outerNewLine: true, attributes: node.attrs },
        { type: 'html', content: node.childrenHTML },
        { type: 'closeTag', tagName: 'iframe', outerNewLine: true },
      ];
    }
  }
}

const content = '<iframe width="420" height="315" src="https://www.youtube.com/embed/XyenY12fzAk"></iframe>';

const editor = new Editor({
  el: document.querySelector('#editor'),
  previewStyle: 'vertical',
  height: '400px',
  initialEditType: 'markdown',
  useCommandShortcut: true,
  extendedAutolinks: true,
  frontMatter: true,
  customHTMLRenderer,
  initialValue: content,
});
```

reference link: https://github.com/nhn/tui.editor/blob/master/docs/ko/custom-block.md

**Comment by nlevasseur-ix** [comment]
Hi, there is a bug if you call after insert `iframe` in content variable this method : ` editor.getHTML()`
