### ISSUE TITLE
how to write a customHTMLRenderer?

### ISSUE THREAD

**Issue by zsanhong** [nhn/tui.editor#1797]
if I write a codeBlock like this
![image](https://user-images.githubusercontent.com/5259153/132873956-7947b391-9232-4f52-8dbd-c98cfd71ed25.png)

in WYSIWYG mode the code is

![image](https://user-images.githubusercontent.com/5259153/132875040-53ef215e-565f-4144-aedf-467674f80650.png)

I want to write a customHTMLRenderer when I enter the code ,
the result html will be:

```
<div class="meimaid">graph LR
    A[Hard edge] -->|Link text| B(Round edge)
    B --> C{Decision}
    C -->|One| D[Result one]
    C -->|Two| E[Result two]
</div>
```
how can I get the result  I wanted?

**Comment by zsanhong** [comment]
any one can help?

**Comment by js87zz** [comment]
@zsanhong 
In v2, It's very difficult to create the custom plugin. 
If you can see the [UML plugin package](https://github.com/nhn/tui.editor/blob/2.x/plugins/uml/src/js/index.js), It will be a little helpful.

This usability has improved much in 3.x, so updates are recommended if possible.

**Comment by zsanhong** [comment]
@js87zz  I wite the mermaid Plugin like this:
```
 function mermaidPlugin() {

            const MERMAID_LANGUAGES = ['meimaid'];
            Editor.setCodeBlockLanguages(MERMAID_LANGUAGES);
            MERMAID_LANGUAGES.forEach(mermaidLanguage => {
            
                Editor.codeBlockManager.setReplacer('mermaid', function (content) {
                    var mermaidId = 'mermaid-' + Math.random().toString(36).substr(2, 10);
                    setTimeout(renderMermaid.bind(null, mermaidId, content), 0);
                    return '<div style="text-align:center" id="' + mermaidId + '"></div>';
                });
            });


            function renderMermaid(mermaidId, content) {
                var el = document.querySelector('#' + mermaidId);
                const cb = function (svgGraph) {
                    el.innerHTML = svgGraph;
                };
                const id = mermaidId + "-svg"
                mermaid.render(id, content, cb);
            }
        };
```
but the wrong msg is:
```
Editor.setCodeBlockLanguages is not a function
```
the tui.editor is v3.1.0
