### ISSUE TITLE
Bold and Italic intersection incorrect Markdown

### ISSUE THREAD

**Issue by Tiberiusss** [nhn/tui.editor#1806]
## Describe the bug
If you use bold and italic at the intersection of a word, then the output markdown will be incorrect

## To Reproduce
1. Go to "Wysiwyg" tab
2. Enter text "boldanditalic"
3. Make phrase "boldand" bold, then phrase "anditalic" italic
4. Go to "Markdown" tab. 
5. Incorrect result is preview. Extra asterisks appeared.

![image](https://user-images.githubusercontent.com/8930952/134575623-3b97fe88-4753-4deb-93dd-244d00fb75bd.png)

## Expected behavior
Markdown will be `**bold*****and***&#8203;*italic*` or `**bold*****and***_italic_` and preview:
![image](https://user-images.githubusercontent.com/8930952/134576328-831ca41b-449f-491f-bd8b-e642e4f869f6.png)

Editor version: 3.1.0

**Comment by js87zz** [comment]
@Tiberiusss 
Thanks for reporting. I will fix it.

**Comment by js87zz** [comment]
@Tiberiusss 
Sorry for late repsonse. 
When I checked this issue again, I confirmed that it was not a bug. 
This is the normal operation according to the [commonmark specification](https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis).

* commonmark playground: https://spec.commonmark.org/dingus/
![스크린샷 2022-02-04 오전 11 53 45](https://user-images.githubusercontent.com/37766175/152464600-d6a1845e-1b43-4f7d-abbf-2bb7ce5fc348.png)

**Comment by michpalm** [comment]
I believe this I've come across the same or a similiar issue, or related at least (perhaps something about the regex in Markdown marks?). Here I've reproduced it in the example page:
![2022-08-09 16 07 17](https://user-images.githubusercontent.com/18511803/183670793-a0b41a6e-991c-421a-87b9-ae2ff684c059.gif)

It seems like it only matches part of the syntax and ends up in a limbo state with part html/part markdown 🤔 
Output after switching to markdown:
```
<strong>This text is bold and the last word is also *italic***
```
And then once again after switching to markdown once again:
```
<strong>This text is bold and the last word is also <em>italic</em>\*\*</strong>
```

---------
Looking at the regex expression in the [strong.ts](https://github.com/nhn/tui.editor/blob/65c4983a2721729d36e1986d05b17ad30ab87e7c/apps/editor/src/markdown/marks/strong.ts) file, it seems like it only matches the starting asterisks for example, if I understand it correctly (checked on regex101 website):
<img width="2052" alt="Screenshot 2022-08-09 at 16 16 12" src="https://user-images.githubusercontent.com/18511803/183672546-bc21b6a8-1c46-44a4-873d-7d96651b6af8.png">
