### ISSUE TITLE
onLoad not firing in @toast-ui/react-editor

### ISSUE THREAD

**Issue by HeikoMueller** [nhn/tui.editor#1808]
Not sure if npm package @toast-ui/react-editor directly belongs to this Git repository or if it is just an external wrapper, but it is linking to this Issue section, therefore: 

## Describe the bug
In the description: All the events of TOAST UI Editor are supported in the form of on[EventName] props. This works for onChange and other events. 

However, onLoad={(e) => {console.log("onLoad")}} is not firing. 

Is this intentional (e.g., shall setup functions be called with react hooks) ? 

## Expected behavior
onLoad is supposed to fire after initial loading for calling setup functions such as insertToolbarItem ...

## Desktop (please complete the following information):
 - OS: OSX 12.0 Beta
 - Browser Chrome
 - Version 93.0.4577.82

**Comment by js87zz** [comment]
@HeikoMueller 
I checked the issue. It will be fixed.
Thanks!

**Comment by dojun-hoztec** [comment]
is it solved?

**Comment by js87zz** [comment]
@HeikoMueller @dojun-hoztec 
The bug has been fixed in `v3.1.2`. Thanks!
