### ISSUE TITLE
Unable to center align text

### ISSUE THREAD

**Issue by jason-gu** [nhn/tui.editor#1904]
## Describe the bug
There isn't a way left/right/center align text using the editor. Align text to the left/right/center is a very basic feature, but I'm not sure how to enable it.

## Expected behavior
To be able to align text.

## Screenshots
![align](https://user-images.githubusercontent.com/2045134/137612772-5eeb1fbd-14cc-4751-8a8d-f6bab34ea74b.png)

## Desktop (please complete the following information):
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 94

**Comment by wh1t3h47** [comment]
Can't that feature be implemented using divs? This works for markdown
```html
<div align="right"> Deprecated </div>

<div style="text-align: justify;"> Not Deprecated </div>
```
