### ISSUE TITLE
Adding an hyphen, on the WYSIWYG mode, add a line and transform the text in a header

### ISSUE THREAD

**Issue by infiniweb** [nhn/tui.editor#1924]
## Describe the bug
In WYSIWYG mode, when you add an hyphen in a separate line, it will transform the hyphen in a ligne when retrieving the html, and the previous line with transform to a header.

## To Reproduce
1. Go in the WYSIWYG mode
2. Add the following text :
```
test
-
```
3. Get the HTML (`.getHtml()`) OR go to the markdown mode
4. You will see in the html or in the markdown preview the first paragraph before an `h2` and a line is added in replacement of the hypen

This can be reproduced in the basic editor test : https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic

## Expected behavior
In WYSIWYG mode, an hyphen should not act as a new line, the previous text should not become an header

**Comment by js87zz** [comment]
@infiniweb 
The bug has been fixed in `v3.1.2`.
