### ISSUE TITLE
Span exceeding the width of the viewer

### ISSUE THREAD

**Issue by JakubGIT** [nhn/tui.editor#1925]
## Describe the bug
Wenn a `<span />` element is used in markdown and length of its content is bigger than the size of the Toast UI Viewer, the span is kept in one line, its content exceeding the width of the viewer.

## To Reproduce
1. create a markdown file with 
```markdown
<span>123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890</span>
```
2. open the file in Toast UI Viewer

## Expected behavior
line break or horizontal slider

## Screenshots
![grafik](https://user-images.githubusercontent.com/49392205/138244799-de587c53-47d3-4d32-b1d4-01289e5ec11c.png)
leads to
![grafik](https://user-images.githubusercontent.com/49392205/138244864-fd189337-2b07-47bf-b7b0-47d382ffc48c.png)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome
 - Version 94.0.4606.81 (Official Build) (32-bit)

**Comment by js87zz** [comment]
@JakubGIT 
The bug has been fixed in `v3.1.2`. Thanks!
