### ISSUE TITLE
editor is still getting focused after autofocus=false

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1945]
## Describe the bug
```js
<Editor autofocus={false}/>
```
Then also editor is getting focused after load
## To Reproduce
Clone this repo https://github.com/ats1999/editor-no-chakra-UI and run the example.

## Expected behaviour
Editor should not get focused

## Screenshots

https://user-images.githubusercontent.com/54087826/138985006-ef62f51f-c222-4c82-a44a-4049a346fae2.mp4

**Comment by js87zz** [comment]
@ats1999 
Sorry for late replying. I will check it in your repo.

**Comment by volkflo** [comment]
This is the same like: https://github.com/nhn/tui.editor/issues/1802
