### ISSUE TITLE
Wrong escaping when converting from WYSWIG to Markdown

### ISSUE THREAD

**Issue by andrewsali** [nhn/tui.editor#1964]
## Describe the bug

If the markdown contains an <a> tag with a URL that has "_", it is incorrectly escaped.

## To Reproduce
1. Create a markdown file that contains:

```
<a href="test_">test</a>
```
2. Open with WYSWIG editor
3. See that URL is escaped to 

```
<a href="test\_">test</a>
```

## Expected behavior

URL should not be escaped when opening in WYSWIG mode. If opened in Markdown only, the issue is not there.

## Desktop (please complete the following information):
 - OS: Windows
 - Browser: Chrome
 - Version 96

## Additional context

Probably related to #1719

**Comment by js87zz** [comment]
@andrewsali 
Sorry for late replying.
I checked the issue and it will be fixed. Thanks!

**Comment by js87zz** [comment]
@andrewsali 
The bug has been fixed in `v3.1.2`. Thanks!
