### ISSUE TITLE
Can WYSIWYG be disabled completely?

### ISSUE THREAD

**Issue by dehghani-mehdi** [nhn/tui.editor#1967]
## Summary
I want to disable WYSIWYG, is there anyway to do that?

## Version
`3.1.1`

**Comment by js87zz** [comment]
@dehghani-mehdi 
Sorry for late replying.
You can hide switch button for converting WYSIWYG.
```js
new Editor({
  ...
  hideModeSwitch: true,
  initialEditType: 'markdown'
})
```
