### ISSUE TITLE
Error: There is no event type keyPress

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#1973]
## Describe the bug
`onKeyPress` is not working in react.

```js
<Editor
onKeyPress={()=>console.log("pressed..")}
/>
```
## To Reproduce
Use the editor in react and pass `onKeyPress={()=>console.log("pressed..")}`

The same is with `onKeyDown`
## Expected behaviour
It should work

**Comment by js87zz** [comment]
@ats1999 
We do not provide the `keypress` event.
I'll add this event if necessary. 
When I checked, `onKeydown` works well. 
```js
ReactDOM.render(
  <>
    <Editor
      previewStyle="vertical"
      initialValue={content}
      height="400px"
      onKeydown={() => console.log("pressed..")}
    />
  </>,
  document.getElementById('editor')
);
```
![2021-11-08 15-11-30 2021-11-08 15_11_49](https://user-images.githubusercontent.com/37766175/140692782-e833eb0b-edcf-4cdc-a802-d9fb0475e8a6.gif)



Is there any other reason?

**Comment by ats1999** [comment]
@js87zz thanks
