### ISSUE TITLE
how can i customize inserting video link not a tag but iframe?

### ISSUE THREAD

**Issue by kiwwwwwy** [nhn/tui.editor#1975]
## Summary
hi. i used your editor in my project. thank you for this.

i just have one  question.
how can i customize when inserting video link like youtube not a tag but iframe tag in wysiwyg ?

when i searching for this, i found codeblockmanager for used when inserting link to convert iframe tag from atag in tui v2.x
but i can't find this simmilar function v3.x

i use tui editor v3.1.0 on javascript and jquery.

Any other way to do this?

or is it possible to using customHTMLRenderer?

it is my source.
thank you for read.

## Screenshots
![20211101_182729](https://user-images.githubusercontent.com/93512518/139650959-4da80759-38d9-4768-b142-89e2eb0dd2f1.jpg)

**Comment by js87zz** [comment]
@kiwwwwwy 
Sorry for late replying.
The link below will be helpful. Let me know if it doesn't work.
* en: https://github.com/nhn/tui.editor/blob/master/docs/en/custom-block.md#html-node
* ko: https://github.com/nhn/tui.editor/blob/master/docs/ko/custom-block.md#html-%EB%85%B8%EB%93%9C
