### ISSUE TITLE
`factory` constructor isn't compliant with linters

### ISSUE THREAD

**Issue by pierredarrieutort** [nhn/tui.editor#1992]
## Describe the bug
Following multiple linter's rules _(ex: standardJS, ESLint, ...)_ the `factory` constructor isn't compliant with good practices.

## To Reproduce
![image](https://user-images.githubusercontent.com/25182438/140481927-f8dff2e7-e05b-4acd-af11-9332536c07b5.png)

You only have to instantiate the WYSIWYG `factory` contructor and use a linter as cited as above.

![image](https://user-images.githubusercontent.com/25182438/140481708-dccd4068-f201-42ee-b177-7cd04ae730ec.png)

## Expected behavior
Reffering to [ESLint documentation](https://eslint.org/docs/rules/new-cap), the `factory` constructor must use a capital letter.

## A little background :
> Native JavaScript functions begin with an uppercase letter to distinguish those functions that are to be used as constructors from functions that are not. Many style guides recommend following this pattern to more easily determine which functions are to be used as constructors.

**Comment by js87zz** [comment]
@pierredarrieutort 
It's not the bug. 
You should use as below. The `factory` method cannot be used as `constructor`
```js
this.viewer = Editor.factory({
  ...
});
```
