### ISSUE TITLE
Please review pull request with updated info

### ISSUE THREAD

**Issue by mattlevine** [nhn/tui.editor#2024]
## Summary
I submitted a pull request and didn't not see your reply for more information until I saw that it was closed because I didn't respond.

I'm sorry for missing your original response, but I truly appreciate it you review the updated description.  I believe it fixes a real issue.

[Fix for toggling between custom plugin popups #1801](https://github.com/nhn/tui.editor/pull/1801)

**Comment by js87zz** [comment]
@mattlevine 
Oh..I'll review the problem based on your PR. Thank you!

**Comment by js87zz** [comment]
@mattlevine 
I think that your issue may be resolved in #2029
