### ISSUE TITLE
Image preview 

### ISSUE THREAD

**Issue by seanwang1998** [nhn/tui.editor#2026]
## Version
3.1.0

## Development Environment
Chrome win10

## Expected Behavior
I want to be able to preview images by clicking on them

for example：
click the img
![image](https://user-images.githubusercontent.com/65933570/142364351-be0c1f39-108d-4208-aa34-c8d3daec3ec9.png)
then:
![image](https://user-images.githubusercontent.com/65933570/142364471-18b6a28f-8366-4a99-8d93-9ae79bebcc43.png)

**Comment by js87zz** [comment]
@seanwang1998 
We don't support this customization yet. Markdown may be possible now, but it's not possible at WYSIWYG.

**Comment by seanwang1998** [comment]
> @seanwang1998 We don't support this customization yet. Markdown may be possible now, but it's not possible at WYSIWYG.

All right, but thank you all the same
