### ISSUE TITLE
Cell merge occasionally fails

### ISSUE THREAD

**Issue by Morton-Freer** [nhn/tui.editor#2027]
## Describe the bug

Cell merge occasionally succeeds, occasionally fails, the console throws an exception, I try to use the table plug-in V3.0.2 version and V3.0.0 version, this error occurs

# Below is my code
import Editor from '@toast-ui/editor';
import '@toast-ui/editor/dist/toastui-editor.css';
import '@toast-ui/editor/dist/i18n/zh-cn.js' ;

import chart from '@toast-ui/editor-plugin-chart';
import uml from '@toast-ui/editor-plugin-uml';

import Prism from 'prismjs';
import 'prismjs/themes/prism.css';
import '@toast-ui/editor-plugin-code-syntax-highlight/dist/toastui-editor-plugin-code-syntax-highlight.css';
import codeSyntaxHighlight from '@toast-ui/editor-plugin-code-syntax-highlight';

import 'tui-color-picker/dist/tui-color-picker.css';
import '@toast-ui/editor-plugin-color-syntax/dist/toastui-editor-plugin-color-syntax.css';
import colorSyntax from '@toast-ui/editor-plugin-color-syntax'

import '@toast-ui/editor-plugin-table-merged-cell/dist/toastui-editor-plugin-table-merged-cell.css';
import tableMergedCell from '@toast-ui/editor-plugin-table-merged-cell';

const chartOptions = {
  minWidth: 100,
  maxWidth: 600,
  minHeight: 100,
  maxHeight: 300
};

const editor = new Editor({
        el: document.querySelector('#editor'),
        previewStyle: 'vertical',
        height: '800px',
        initialValue: '你大爷的',
        language: 'zh-CN',
        initialEditType: 'wysiwyg',
        plugins: [[chart, chartOptions], [codeSyntaxHighlight, { highlighter: Prism }], tableMergedCell, colorSyntax,  uml]
      });

## Screenshots
![image](https://user-images.githubusercontent.com/82444336/142557009-268e2b3f-52fb-4823-a925-0290d330c720.png)

## Desktop (please complete the following information):
 - Windows10
 - chrome
 - 95.0.4638.69

**Comment by js87zz** [comment]
@Morton-Freer 
I checked the issue. It will be fixed.

**Comment by js87zz** [comment]
@Morton-Freer 
Sorry for the late response. 
Since this issue has been resolved in `editor@3.1.3` and `merged-table@3.0.2`.
