### ISSUE TITLE
opening two different customPopupBlocks after each other results in wrong rendering

### ISSUE THREAD

**Issue by PaulSchult** [nhn/tui.editor#2028]
## Describe the bug
If you have two plugins using two different customPopupBlocks and open the second popup after you opened the first, the first popup will be displayed again. The body used is not updated. 

## To Reproduce
1. Have two plugins that use a customPopupBlock (I used the color plugin + a custom own one)
2. Click on the first plugin toolbar item. Notice correct body.
3. Click on the second plugin toolbar item. Notice body from plugin one is displayed.

## Expected behavior
The body of the customPopupBlock should be updated. 

## Desktop (please complete the following information):
 - OS: manjaro linux
 - Browser chrome
 - Version v3.1.1

## Additional context
Problem is fixed locally, will open a pull request soon.

**Comment by js87zz** [comment]
@PaulSchult 
I checked the issue. I'll review the PR tomorrow.
Thanks!! :)
