### ISSUE TITLE
Can't select text by draging empty part when editing customBlock in wysiwyg mode

### ISSUE THREAD

**Issue by z-950** [nhn/tui.editor#2048]
## Describe the bug
Can't select text by draging empty part when editing customBlock in wysiwyg mode. Draging empty part will emit drag event so that text can't be selected.

## To Reproduce
1. Change mode to wysiwyg
2. Click the customBlock's edit button
3. Draging the empty part in the customBlock's editable area.
4. Text can not be selected, but dragging whole element.

## Expected behavior
Text can be selected.

## Additional context
version: 3.1.1

**Comment by js87zz** [comment]
@z-950 
I checked the issue. I'll review the PR tomorrow. Thank you!! :)
