### ISSUE TITLE
How do I render KaTex equations?

### ISSUE THREAD

**Issue by hsb-tonmoy** [nhn/tui.editor#2051]
As demonstrated here: https://ui.toast.com/weekly-pick/en_20210617
How do I add the ability to render KaTex like that?

**Comment by ats1999** [comment]
You can see https://github.com/ats1999/md-byte/blob/1310be8356937aab9c764097bfe90f3bf179239a/mde10/src/customHTMLRenderer.js#L118

**Comment by js87zz** [comment]
@hsb-tonmoy 
[This document](https://github.com/nhn/tui.editor/blob/master/docs/en/custom-block.md) is helpful to you

**Comment by hsb-tonmoy** [comment]
> @hsb-tonmoy [This document](https://github.com/nhn/tui.editor/blob/master/docs/en/custom-block.md) is helpful to you

> You can see https://github.com/ats1999/md-byte/blob/1310be8356937aab9c764097bfe90f3bf179239a/mde10/src/customHTMLRenderer.js#L118

Thanks a lot guys. It was really helpful. I'm using the custom rendered that @ats1999 referenced but I'm getting this broken output:

![image](https://user-images.githubusercontent.com/35843150/143496674-2acdf64a-9fb2-4228-bd21-e9cec7948cf8.png)

**Comment by ats1999** [comment]
@hsb-tonmoy import the CSS properly
```js
import 'katex/dist/katex.min.css'
```

**Comment by ats1999** [comment]
## In CSS file
```css
@import url("katex/dist/katex.min.css");
```

**Comment by ats1999** [comment]
You can opt anyonne of them

**Comment by hsb-tonmoy** [comment]
> You can opt anyone of them
> 
> Let me know if this resolved your issue?

This resolved the issue. Thank you very much.
