### ISSUE TITLE
How to turn off Wysiwyg mode, or to cancel showing Wysiwyg mode, I just want to keep markdown mode.

### ISSUE THREAD

**Issue by seanwang1998** [nhn/tui.editor#2071]
## Summary
How to turn off Wysiwyg mode, or to cancel showing Wysiwyg mode, I just want to keep markdown mode.

## Screenshots
If applicable, add screenshots to help explain your question.

## Version
3.1.0
![Snipaste_2021-12-01_18-30-56](https://user-images.githubusercontent.com/65933570/144218451-5511f0eb-d53b-46eb-bf70-a63dce3012fc.png)

**Comment by seanwang1998** [comment]
i use css code resolved this q;

.toastui-editor-mode-switch .tab-item:last-child {
  display: none;
}

**Comment by seanwang1998** [comment]
![image](https://user-images.githubusercontent.com/65933570/144221577-e51eba6a-be1c-4ad0-be9c-42e01f8a96ac.png)

**Comment by ats1999** [comment]
use parameter 
```js
hideModeSwitch:true
```
