### ISSUE TITLE
<details /> and <summary /> tags will remove from wysiwyg mode

### ISSUE THREAD

**Issue by cary-hu** [nhn/tui.editor#2075]
## Summary
Insert details tag and summary tag in markdown mode will show correctly:
![image](https://user-images.githubusercontent.com/41052104/144347741-8f69c4f5-888a-4308-b284-46114ef9dd8a.png)

but if change mode to wysiwg mode, the detail and summary tag will remove:

![image](https://user-images.githubusercontent.com/41052104/144347798-bf074f3a-171b-44ac-be67-fa3d5b4d2fea.png)
![image](https://user-images.githubusercontent.com/41052104/144347806-350b6ff6-bce1-4c28-b5d1-918546c8e23a.png)

## Version
V3.1.1

## Additional context
I tried:
```js
customHTMLSanitizer: content => {
            return content;
        },
```
```js
this._editor.addHook('beforePreviewRender', (html) => {
            return html || "";
        });
```

Both method not take effect

any ideas?

**Comment by js87zz** [comment]
@cary-hu 
Our editor now does not support this syntax(`details`, `summary`) properly. I think this feature should be developed by adding it as a separate plug-in later on. It's a little bit of a future story, but I want you to wait.

**Comment by cary-hu** [comment]
Ok, Before got your update, I will use html block as workaround for this. thanks for your reply.
