### ISSUE TITLE
Replace suggestion text at cursor position

### ISSUE THREAD

**Issue by seanwang1998** [nhn/tui.editor#2080]
## Summary
Replace suggestion text at cursor position  ，The ultimate goal is to do @ mention function
#968 There is already a "change event" in it, but I failed to call the API mentioned in it. I wonder if the version has been updated

## Version
3.1.0

## Additional context
#968

**Comment by js87zz** [comment]
@seanwang1998 
Can you refer [this link](https://github.com/nhn/tui.editor/blob/master/docs/en/widget.md)?

**Comment by seanwang1998** [comment]
> @seanwang1998 你能参考[这个链接](https://github.com/nhn/tui.editor/blob/master/docs/en/widget.md)吗？

Thank you ever so much !!!
