### ISSUE TITLE
Gets the character/string you just typed

### ISSUE THREAD

**Issue by seanwang1998** [nhn/tui.editor#2084]
## Summary
如标题所说，我想获取最后输入的内容是不是"@"符号，这是我提出的问题。 
我要解决的需求：@输入后，弹出一个列表选取人员，就像github的@那样，如果有碰到过相关的需求，能贴出代码来得，更是不胜感激！！！ 
As the title says, I want to know if the last thing I typed was the "@" sign, which is my question.
Requirements I want to solve: @ input, pop up a list to select people, just like github @, if you have encountered relevant requirements, you can post the code, I would be very grateful!!

## Screenshots
If applicable, add screenshots to help explain your question.

## Version
3.1.0 chrome

**Comment by js87zz** [comment]
@seanwang1998 
It looks the same as #2080, right?
