### ISSUE TITLE
Placeholder will be get as HTMLCONTENT

### ISSUE THREAD

**Issue by cary-hu** [nhn/tui.editor#2096]
## Describe the bug
If not type anything in editor, Call editor.getHTML() and editor.getMarkdown(), 

editor.getHTML() will return:

```
<p><span class="placeholder ProseMirror-widget" contenteditable="false">Type here to compose Document</span><br></p>
```
editor.getMarkdown() will return ""

## Screenshots
![image](https://user-images.githubusercontent.com/41052104/144963431-56552853-92f1-4dfa-b1e7-5837ef3950a9.png)

![image](https://user-images.githubusercontent.com/41052104/144963396-f84f243e-d107-437c-a0c7-90913e25f70b.png)

## Desktop (please complete the following information):
 - OS: Windows 11
 - Browser chrome
 - Version 96.0.4664.45 
 - Editor Version: 3.1.1

## Additional context

I tried in clean env, reproduced

**Comment by cary-hu** [comment]
sample gist here: https://gist.github.com/cary-hu/585960fc9b34eb336dbc49012d7f4159

**Comment by js87zz** [comment]
@cary-hu 
Thanks for reporting. I will fix it.

**Comment by cary-hu** [comment]
any update? @js87zz

**Comment by js87zz** [comment]
@cary-hu 
It will be fixed in next release. Thanks!

**Comment by cary-hu** [comment]
Update to 3.1.5, then it fixed, thanks for your work.
