### ISSUE TITLE
@toast-ui/editor-plugin-color-syntax   Uncaught TypeError: Cannot read properties of undefined (reading 'setLanguage')

### ISSUE THREAD

**Issue by kwdd** [nhn/tui.editor#2097]
vue3.0 vite@latest
dependencies:
    "@toast-ui/editor": "^2.5.4",
    "@toast-ui/editor-plugin-chart": "^3.0.1",
    "@toast-ui/editor-plugin-code-syntax-highlight": "^3.0.0",
    "@toast-ui/editor-plugin-color-syntax": "^3.0.2",
    "@toast-ui/editor-plugin-table-merged-cell": "^3.0.1",
    "@toast-ui/editor-plugin-uml": "^3.0.1",

![image](https://user-images.githubusercontent.com/15699551/144987508-19967c03-6bf9-4e5a-ad0c-dda23b30b036.png)
![image](https://user-images.githubusercontent.com/15699551/144987533-016324f4-83fa-4715-95f2-360902dfeb9d.png)
![image](https://user-images.githubusercontent.com/15699551/144987556-3bd4d9d5-c7eb-4213-b4da-d01860d71185.png)

**Comment by js87zz** [comment]
@kwdd 
You should update `@toast-ui/editor` to `v3.1.1`
