### ISSUE TITLE
get keyup word

### ISSUE THREAD

**Issue by seanwang1998** [nhn/tui.editor#2098]
## Summary
how to get keyup word?

## Screenshots
![image](https://user-images.githubusercontent.com/65933570/145004844-f7f84952-ef6c-43b1-bdff-541c4e3c9f73.png)
![1111](https://user-images.githubusercontent.com/65933570/145004858-711e68b7-98b2-46f3-8a77-f5e93a0895b2.gif)

## Version
Write the version of the Editor you are currently using.

**Comment by js87zz** [comment]
@seanwang1998 
Can you try as below?
```js
events: {
  keyup(editorType, ev) {
    console.log(ev)
  }
}
```

**Comment by seanwang1998** [comment]
@js87zz   ok,i'll try it
