### ISSUE TITLE
Auto-escaping in WYSIWYG mode causes issues

### ISSUE THREAD

**Issue by kkstoklund** [nhn/tui.editor#2099]
## Describe the bug
When using WYSIWYG mode it auto-escapes _ and * characters.
This means that links will break if it contains underscore (which is pretty common for links)

## To Reproduce
1. Go to https://ui.toast.com/tui-editor
2. In the demo editor on this page there is already a link - add '_test' somewhere in the linke (while in markdown mode)
for example:
![Screen Shot 2021-12-07 at 16 35 10](https://user-images.githubusercontent.com/29021651/145059248-6627d7e2-ff51-4dcb-b5e1-2e140a4a41d7.png) 

3. Switch to WYSIWYG mode
4. Switch back to markdown mode
5. Now the link looks like this:
![Screen Shot 2021-12-07 at 16 37 47](https://user-images.githubusercontent.com/29021651/145059499-a29b76b2-b3da-4d53-a41c-47c3005b668c.png)

## Expected behavior
I would expect that WYSIWYG mode does not auto-escape the content at all.
Is there a way to completely disable this?

## Desktop (please complete the following information):
 - OS: macOS
 - Browser: Chrome
 - Version: 3.1.1

**Comment by js87zz** [comment]
@kkstoklund 
This issue will be fixed in next release.

**Comment by js87zz** [comment]
@kkstoklund 
The bug has been fixed in `v3.1.2`. Thanks!
