### ISSUE TITLE
How to rewrite the image upload method

### ISSUE THREAD

**Issue by a1b2c5** [nhn/tui.editor#2110]
## Summary
Hi, there. I noticed that when uploading or copying an image, it automatically transcodes (it's too long) and I was wondering how to rewrite the uploaded image method (I process the image myself and return a URL).

## Screenshots
![image](https://user-images.githubusercontent.com/57167177/145667299-08011855-bc0e-4229-a008-a54a03b15c18.png)

## Version
![image](https://user-images.githubusercontent.com/57167177/145667406-eb81a1a2-f7b3-438b-bcf2-4c119fc561b7.png)

**Comment by js87zz** [comment]
@a1b2c5 
You can use `addImageBlobHook`
```js
const editor = new Editor({
  // ...
  hooks: {
    addImageBlobHook(imgeBlob, callback) {
      // write your code
      // ...
      callback(your imageUrl, your altText)
    }
  }
})
```

**Comment by a1b2c5** [comment]
Thanks for getting back to me. I'll give it a try.

**Comment by a1b2c5** [comment]
> @a1b2c5 You can use `addImageBlobHook`
> 
> ```js
> const editor = new Editor({
>   // ...
>   hooks: {
>     addImageBlobHook(imgeBlob, callback) {
>       // write your code
>       // ...
>       callback(your imageUrl, your altText)
>     }
>   }
> })
> ```

It works, but how do I get the value of description(altText)?

**Comment by MihailoSepsinac** [comment]
Please, can you give me an example how to find imageUrl from imgeBlob, sometimes it works fine for me, but sometimes it won't?

**Comment by a1b2c5** [comment]
> Please, can you give me an example how to find imageUrl from imgeBlob, sometimes it works fine for me, but sometimes it won't?


      this.editor = new Editor({
        el: document.getElementById(this.id),
        ...this.editorOptions,
        hooks: {
          addImageBlobHook(imgeBlob, callback) {
            const formData = new FormData()
            formData.append('file', imgeBlob)
            uploadApi.uploadOssFileCms(formData).then(res => {
              callback(res.result, '')
            }).catch(error => {
              console.log(error)
            })
          }
        }
      })

"uploadApi.uploadOssFileCms" is a method I defined to store an image in the cloud and return a link to it.

**Comment by MihailoSepsinac** [comment]
Thanks for response, is it possible to explain to me how you did it uploadApi.uploadOssFileCms?

**Comment by a1b2c5** [comment]
> Thanks for response, is it possible to explain to me how you did it uploadApi.uploadOssFileCms?

This can be uneasy to achieve. I used the separation of front-end and backend, and the backend was developed in Java(SpringCloud+OssBrowser). One word or two words is not clear, you can learn from my project.[gitee](https://gitee.com/ChrisPhantom/cyzx-rear/blob/master/service/service_oss/src/main/java/xyz/zhzby/cyzx/oss/service/impl/OssServiceImpl.java)
