### ISSUE TITLE
javascript XSS when using MD links

### ISSUE THREAD

**Issue by ET-CS** [nhn/tui.editor#2114]
## Describe the bug
There is potential XSS issue when using MD links.

## To Reproduce
1. Open editor
2. Add the following: `To read more [click here](javascript:alert(localStorage["key"]))`
3. When displaying the result MD created by the component - there is clickable link which alert a key from localStorage

## Expected behavior
javascript should be sanitized, or at least should have a way to disable the support of it.

**Comment by js87zz** [comment]
@ET-CS 
What is your editor version?
I cannot reproduce it in the latest version.
![2021-12-14 14-12-14 2021-12-14 14_12_27](https://user-images.githubusercontent.com/37766175/145937200-8896447f-f855-4587-bc14-b7744a393e03.gif)
