### ISSUE TITLE
The style of the hyperlink in the widget

### ISSUE THREAD

**Issue by seanwang1998** [nhn/tui.editor#2115]
## Summary
I want to implement the function in the document GIF
[like this](https://github.com/nhn/tui.editor/blob/master/docs/en/widget.md)

this is my code：
```js
 ul.addEventListener('mousedown', (ev) => {
   const text = ev.target.textContent;
   var member;
   for (let m=0;m<me.rdMembers.length;m++) {
     if (me.rdMembers[m].searchKey == text) {
       member = me.rdMembers[m];
       break ;
     }
   }
   const [start, end] = me.myEditor.getSelection();
   me.myEditor.replaceSelection(`[@${member.name}](rdportal-member-${member.value})`, [start[0], start[1] - 1], end);
 });
 me.myEditor.addWidget(div, 'bottom');
```

## Screenshots
my result:
![image](https://user-images.githubusercontent.com/65933570/145740158-aae41ab9-0ce9-4667-b514-261b7f5db957.png)

I want this result：
![11](https://user-images.githubusercontent.com/65933570/145739779-f03b97eb-2ed3-4cc8-b292-fa4c34164503.gif)

## Version
V 3.1.0

**Comment by js87zz** [comment]
@seanwang1998 
Can you give your code in code sand box?

**Comment by seanwang1998** [comment]
@js87zz https://codesandbox.io/embed/cool-leaf-pbbku?fontsize=14&hidenavigation=1&theme=dark

**Comment by seanwang1998** [comment]
@js87zz  ![image](https://user-images.githubusercontent.com/65933570/145942169-fbb37d1c-31de-41c6-b856-48c1c603ad73.png)
