### ISSUE TITLE
Version 3.1.2 release date?

### ISSUE THREAD

**Issue by kkstoklund** [nhn/tui.editor#2117]
Hi. Version 3.1.2 contains some bug fixes that I'm very much looking forward to.
When do you expect to release this version? 😄 
Keep up the good work 🥇 

Regards,

Klaus

**Comment by js87zz** [comment]
@kkstoklund 
It is scheduled to be release within this week.

**Comment by js87zz** [comment]
@kkstoklund 
`v3.1.2` is released. Thanks!
