### ISSUE TITLE
How to support some fenced code syntax (like markdown-it-container) or to use custom block to achieve that?

### ISSUE THREAD

**Issue by CarrotB** [nhn/tui.editor#2127]
## Summary
Thank you guys for this awesome editor!
Our doc site uses tui.editor for online doc editing, and saves doc to md then uses markdown-it for doc site generation. Recently I was working on changing our doc site generator to vue-press, we want to use some extension syntax it provides, like: 
``` 
::: warning
This is a warning
:::
```

This will be rendered as:
![20211213151643737](https://user-images.githubusercontent.com/23547642/145768814-0770ab69-2656-41f6-8627-cb881f014b03.png)

see at [vuepress](https://vuepress.vuejs.org/guide/markdown.html#custom-containers) 

Inside vue-press, [markdown-it-container](https://github.com/markdown-it/markdown-it-container) is used. So I was thinking if I can extend tui.editor to support the same syntax. After searching through google and read tui docs, there seems no way to add custom markdown block syntax, but there's a custom block functionaly, though not quite working as I thought it'd be. 

Say, give a custom block like this: 
``` 
$$ warning
This is a warning, please be **careful**!
$$
```

We want it to be rendered like this:
``` html
<div class="warning">
<p>This is a warning, please be <strong>careful<strong>!</p>
</div>
```

I could write some custom block handler to render the outer div, but inside custom block, all content (including markdown) will be rendered as if it's plain text, guess that's "literal" in `node.literal` means. 

Tried to find if there's quicker way to render some markdown to html than to create a new instance of `Editor` then invoke `setMarkdown()` and `getHTML()`, or to use other libs like markdown-it to render. I couldn't find an good solution, so here I am. Any suggestion?

## Version
3.1.1

## Aditional context

Say we found a way to solve the problem above, there's another question, is there anyway we can change custom block delimiter? Last time I checked, markdown-it-container can change delimiter character to something else so I can change `:` to `$`, but it also requires at least 3 of delimiter there.  I can change this behavior if I simply fork their code to customize a little, but is there a better way?
I found there's an issue filed #1675 about custom delimiter, but no discussion continues.

**Comment by js87zz** [comment]
@CarrotB 
1. markdown paring in custom block
The Custom Block is functionality for rendering various nodes. Therefore, parsing text to markdown is not considered.
If you want to use it as the markdown syntax in your custom block, you can change it using the `markdown-it` as you said.

```js
customHTMLRenderer: {
  warning(node) {
    const md = new MarkdownIt();

    return [
      { type: 'openTag', tagName: 'div', attributes: { class: 'warning' }, outerNewLine: true },
      { type: 'html', content: md.render(node.literal) },
      { type: 'closeTag', tagName: 'div', outerNewLine: true }
    ];
  }
}
```

It would be appropriate to use the renderer used internally by our editor, but this is the best way because there is currently no API that provides our renderer to the outside. If the API is added, I will let you know.

2. custom block syntax
As you said, there is no progress yet to add the symbol of the custom block. There are other priority features, so it will take some time.

**Comment by CarrotB** [comment]
@js87zz Ok, I'll use `markdown-it` for rendering. Look forward to APIs for rendering markdown.  Thanks!
