### ISSUE TITLE
Copy link from editor, paste to other side, link url lost

### ISSUE THREAD

**Issue by cary-hu** [nhn/tui.editor#2128]
## Describe the bug
Copy link from editor, paste to whatever side (except editor), link url will lost

## To Reproduce

https://ui.toast.com/tui-editor

![image](https://user-images.githubusercontent.com/41052104/145933310-afb6a63a-de1f-4e67-a9cf-2a7dece1ba47.png)

copy the editor link

paste here:

Editor

## Desktop (please complete the following information):
 - OS: windows
 - Browser chrome
 - Version latest

**Comment by js87zz** [comment]
@cary-hu 
It's not the bug. 
The WYSIWYG contents is normally pasted only in the area where the `contenteditable` is activated. 
In the plain text area, only text is pasted.

**Comment by cary-hu** [comment]
got that, thank you
