### ISSUE TITLE
Expected release data of v3.2.0

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#2130]
Hi, thank you for providing an amazing editor. 

Can you tell me what is the expected date of `v3.2.0`

I am waiting for https://github.com/nhn/tui.editor/issues/1803

Thanks again :)

**Comment by js87zz** [comment]
@ats1999 
There's a lot of other work to do in next minor version. So it's hard to say exactly, and the rough goal is to release it within January next year. Thank you.

**Comment by ats1999** [comment]
Thanks for letting me know :)
