### ISSUE TITLE
Ability to *not* wrap codeblock content in Markdown Editor

### ISSUE THREAD

**Issue by dpatra** [nhn/tui.editor#2131]
## Describe the bug
Codeblock is wrapping content to next line.

## To Reproduce
1. Copy lengthy lines and paste it into codeblock in markdown editor

## Expected behavior
Should not wrap content, and should present a horizontal scrollbar at the end of codeblock. Not necessarily a default option but an option to overcome default behaviour. (Users keep requesting us to provide the no-wrap option) 

## Desktop (please complete the following information):
 - Any platform
 - Chrome
 - Version 3.x

**Comment by js87zz** [comment]
@dpatra 
The operation is not the bug. It is the intended for visual unity with the editing area. 
If you want to change this, you can control through overriding the css.

**Comment by dpatra** [comment]
> @dpatra The operation is not the bug. It is the intended for visual unity with the editing area. If you want to change this, you can control through overriding the css.

I was able to handle the wrap content from css, but not sure about the horizontal scroll, could you please guide!

**Comment by dpatra** [comment]
@js87zz could you guide me to show a scrollbar for the codeblock content using css

**Comment by js87zz** [comment]
@dpatra 
You can override css as below.
```css
.toastui-editor-md-preview code {
    overflow-x: auto;
    white-space: pre;
    display: block;
}
```

**Comment by dpatra** [comment]
Hey @js87zz , Thanks for the reply. I think I was not clear in my question.
The solution you have provided is for the preview I think, what I want is the editor itself.

1. Disable wrapping content in editor.

```
.toastui-editor-md-code,
.toastui-editor-md-code-block {
  font-family: Consolas, Courier, 'Lucida Grande', 'Nanum Barun Gothic', 'Malgun Gothic', sans-serif;
  white-space: pre; //This disables the wrapping
}
```

2. Show a horizontal scrollbar for the overflown codeblock content
**The above solution does not work, as it is intended for preview**

**Comment by js87zz** [comment]
@dpatra 
It is not recommended to control the `white-space` in the editing area.
