### ISSUE TITLE
Document example suggestion

### ISSUE THREAD

**Issue by HTMLhead** [nhn/tui.editor#2136]
## Version
v3.1.1

## Expected Behavior
First of all thanks to make this wonderful library.

Reason that I create this issue is I have waste much time the Internationalization (i18n) is doesn't work well.
It's my fault. I only saw the [example](https://nhn.github.io/tui.editor/latest/tutorial-example16-i18n) and mistakenly thought that it didn't work well.
After seeing [this](https://github.com/nhn/tui.editor/blob/master/docs/en/i18n.md) document I found that I don't import source file of i18n.

If it's not rude, can you put the phrase of the import file in the example as well? or can I PR about this?

like this
![스크린샷 2021-12-16 오후 5 42 18](https://user-images.githubusercontent.com/40166539/146337539-bffa9ddd-10dd-4f64-9292-74904630d31b.png)

**Comment by js87zz** [comment]
@HTMLhead 
I agree with you! Can you write the PR for this?
