### ISSUE TITLE
Add Link With Selection TEXT

### ISSUE THREAD

**Issue by realLiangshiwei** [nhn/tui.editor#2139]
## Describe the bug
I tried to add link for the selection text but I need to enter the text again.

## To Reproduce
1. Open https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic
2. Select text
3. click toolbar add link btn
4. insert link

## Expected behavior
Add link with selection text

## Screenshots
![ng](https://user-images.githubusercontent.com/16813853/146377790-d5293813-2e97-4afc-9163-d05353a6c61f.gif)

**Comment by js87zz** [comment]
@realLiangshiwei 
This issue is same as #2106. It will be fixed in this week.

**Comment by realLiangshiwei** [comment]
Thank you.

**Comment by js87zz** [comment]
@realLiangshiwei 
The bug has been fixed in `v3.1.2`. Thanks!
