### ISSUE TITLE
Multiple newlines in the text are copied to the editor, leaving no empty newlines

### ISSUE THREAD

**Issue by songwone** [nhn/tui.editor#2144]
## Describe the bug
When I copy text from a website or document into an editor, Multiple newlines in the text are copied to the editor, leaving no empty newlines

## To Reproduce
1. Go to '[[...](https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-with-wysiwyg-mode)](https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-with-wysiwyg-mode)'
2. Copy text from '[[...](https://www.sfchronicle.com/projects/2021/jessica-simulation-artificial-intelligence)](https://www.sfchronicle.com/projects/2021/jessica-simulation-artificial-intelligence)' 
3. Empty lines between paragraphs are no longer visible in the editor

## Expected behavior
 keep the empty lines

**Comment by js87zz** [comment]
@songwone 
It's not the bug. It seems that the data is being pasted normally.
There is a margin style between sentences in your example page, so there seems to be an empty sentence. 
![스크린샷 2021-12-22 오전 10 34 08](https://user-images.githubusercontent.com/37766175/147019927-6ab238bf-4502-454f-99ba-ee5d99629c59.png)

**Comment by songwone** [comment]
> @songwone It's not the bug. It seems that the data is being pasted normally. There is a margin style between sentences in your example page, so there seems to be an empty sentence. ![스크린샷 2021-12-22 오전 10 34 08](https://user-images.githubusercontent.com/37766175/147019927-6ab238bf-4502-454f-99ba-ee5d99629c59.png)

Ok, thank you very much
