### ISSUE TITLE
Hopefully there is no edit toolbar in read-only mode

### ISSUE THREAD

**Issue by l54808821** [nhn/tui.editor#2156]
## Version
"@toast-ui/vue-editor": "^3.1.1",

## Current Behavior
The functionality is now complete

There is a function that requires editing markdown text. Then someone else needs to read only the view. Hopefully there is no edit toolbar in read-only mode, thank you very much

**Comment by js87zz** [comment]
@l54808821 
Our editor provides viewer mode.
* [tutorial](https://github.com/nhn/tui.editor/blob/master/docs/en/viewer.md)
* [example](https://nhn.github.io/tui.editor/latest/tutorial-example04-viewer)
