### ISSUE TITLE
Is it possible to add a pop up on a custom added button?

### ISSUE THREAD

**Issue by anaggithub** [nhn/tui.editor#2158]
## Summary
Hi all!! First of all thanks so much for this awesome Editor!!!

I have worked on the editor for it to support latex and added a new button:
![image](https://user-images.githubusercontent.com/47753872/147253713-ab7174f2-61ea-4600-829d-7e609960bb74.png)

Whay my client wants is that when you click the button a pop up appears with some information for the user, explaining how to use the latex sintax, with a link to some documentation ooutside the app. Thing is that the pop up should looks like the other pop ups on the editor, like this one for example:

![image](https://user-images.githubusercontent.com/47753872/147253838-f4fea2ec-199d-4cc4-92ea-256e49513416.png)

And of course it should appear just below the button.

Does tui editor have a feature to add a pop up on a custom button? Or does anyone worked on something similar before? Have checked the issues on this repo but haven't found anything so far.

Not sure if you need the code but here it is:

```
function createLatexButton() {
    const el = document.createElement('button');

    el.innerHTML = 'Σ';
    el.className = 'tui-latex'
    el.onclick = (e) => {
      console.log("Yay")
    };
    return el;
  }

  const toolbarItems = [
    'heading',
    'bold',
    'italic',
    'strike',
    'divider',
    'hr',
    'quote',
    'divider',
    'ul',
    'ol',
    'task',
    'indent',
    'outdent',
    'divider',
    'table',
    'link',
    'image',
    'divider',
    'code',
    'codeblock',
    {
      type: 'button',
      options: {
        tooltip: 'Latex',
        el: createLatexButton(),
      },
    },
  ];
```
 

Thank you so much!!

## Version
"@toast-ui/react-editor": "^2.5.4",

**Comment by seanwang1998** [comment]
Leave a message and follow up. I need the same thing😂
