### ISSUE TITLE
when invoke getHTML  parse text `$$xxx$$` error

### ISSUE THREAD

**Issue by SurprisedTao** [nhn/tui.editor#2167]
## Describe the bug
Type in the editor `$$xxx$$`, Then invoke getHTML.
![image](https://user-images.githubusercontent.com/29747441/147453574-47be300a-98b9-4cf6-ae86-6c01add1d5ad.png)

## Desktop (please complete the following information):
 - OS:  windows
 - Browser: edge
 - Version: 96.0.1054.62

**Comment by js87zz** [comment]
@SurprisedTao 
I checked the issue. It will be fixed. Thanks!

**Comment by js87zz** [comment]
@SurprisedTao 
Thanks for long wating.
The bug has been fixed in `v3.1.3`(#2275)
