### ISSUE TITLE
Ampersands ("&") in link URLs are converted to "&amp;" and single tildes ("~") are escaped (to "\~")

### ISSUE THREAD

**Issue by Alyw234237** [nhn/tui.editor#2168]
## Describe the bug

I noticed that ampersand symbols (`&`) in link URLs are converted to `&amp;`. For example, the following:

`[Cat pics](https://www.google.com/search?q=cats&tbm=isch)`

Becomes:

`[Cat pics](https://www.google.com/search?q=cats&amp;tbm=isch)`

This is a common URL character and I don't think it has syntactic importance here so I don't think it should be converted.

I think that this bug may have been introduced in the latest version (3.1.2) as it doesn't seem to happen with TUI Editor 3.1.1.

I also noticed that single tilde symbols (`~`) in general are escaped (to `\~`). For example, `Pi is ~3.14` becomes `Pi is \~3.14`. Only two or more tildes in a row constitute CommonMark syntax I believe, so I think that single tildes don't need to be escaped.

## To reproduce

Enter the above markdown examples into the editor and they will be converted as described.

## Expected behavior

`&` in link URLs won't be converted into `&amp;` and single tildes (`~`) won't be escaped (to `\~`).

## Desktop

 - OS: Microsoft Windows 10
 - Browser: Google Chrome 
 - Version: 96.0.4664.110 (Official Build) (64-bit)

## TUI Editor
 - Version: 3.1.2 (latest—Mon., Dec. 27th, 2021)

**Comment by unikaive** [comment]
Additionally, There is another problem.
When upload image and url is returned. this url also change.

For example. If i upload image and return url?key=abc&attribute=abc.
'&' in there, also change to '&amp;'
So fail to load Image.

This need to be fixed.
I think this need to be fixed.

**Comment by ibedarev** [comment]
It's related to this [commit](https://github.com/nhn/tui.editor/commit/bc6f31b0ad81f377db69a5e9b66ce6c1af59b646)

**Comment by js87zz** [comment]
It has been fixed and will be included in the next release. Thanks for wating!

**Comment by js87zz** [comment]
@Alyw234237 
The bug has been fixed in `v3.1.3`(#2267)

> Note: `~`(tilde) is escaped to conflict the [strike specification of GFM](https://github.github.com/gfm/#strikethrough-extension-) when converting wysiwyg to markdown. Therefore, this logic has not been modified. If this becomes a problem later, we will fix it then.
