### ISSUE TITLE
WYSIWYG escaping characters issue

### ISSUE THREAD

**Issue by kkstoklund** [nhn/tui.editor#2176]
## Describe the bug
The issue described here [2099](https://github.com/nhn/tui.editor/issues/2099), is still present in version 3.1.2.

I also find that it occasionally escapes '.', '(' and ')' characters in headers too.

Please see issue [2099](https://github.com/nhn/tui.editor/issues/2099) for additional details.

See screen recording demonstrating the issue (version 3.1.2)

https://user-images.githubusercontent.com/29021651/147930211-771de4f7-6972-4214-9ffc-bec4ba7216a9.mov

**Comment by js87zz** [comment]
@kkstoklund 
Oh, I checked the issue. There's a problem with the conversion to link text.
I will fix it.

**Comment by kkstoklund** [comment]
@js87zz any idea of when this will be fixed? :)

**Comment by js87zz** [comment]
@kkstoklund 
It has been fixed and will be included in the next release. Thanks for wating!
