### ISSUE TITLE
Downloading Version 2.5.1 of TOAST-UI Editor via NPM serves the incorrect CSS files

### ISSUE THREAD

**Issue by briochie** [nhn/tui.editor#2215]
## Describe the bug
A few months ago in our app, the styling for our markdown fields suddenly stopped working, leaving them unusable. Upon investigating the issue, I discovered it was because the CSS class names used had changed to the 3.0 names in the dist css file, rather than the names they should be.

## To Reproduce
This should replicate the behavior:
1. Create a new empty project
2. Use npm to install TOAST-UI Editor 2.5.1
3. Create a markdown field for the page
4. Load the page

## Expected behavior
The markdown field displays properly.

## Screenshots
![image](https://user-images.githubusercontent.com/4731407/149798371-21c9c700-b8af-42f2-939a-128b62d4e1f8.png)

## Desktop (please complete the following information):
 - OS: macOS Big Sur 11.6
 - Browser: Chrome

**Comment by js87zz** [comment]
@briochie 
When I installed that version, it was installed as a `dist` folder of `v2.5.1` version. And your screenshot looks like the `v3.x` version. Can you try to remove the cache and reinstall it?

**Comment by briochie** [comment]
> @briochie When I installed that version, it was installed as a `dist` folder of `v2.5.1` version. And your screenshot looks like the `v3.x` version. Can you try to remove the cache and reinstall it?

I did, just to check, and the same thing happened. It SAYS it should be 2.5.1, but that's not the case. Something is mismatched, as the classnames don't match the elements the javascript for 2.5.1 creates:

<img width="853" alt="Screen Shot 2022-01-19 at 9 24 18 AM" src="https://user-images.githubusercontent.com/4731407/150161536-2a3502a9-9d4a-4e00-8b1a-3539e8891642.png">

The stylesheets and the javascript are both loaded correctly in the page, but the CSS we include names the classes like this:
```
/* tui editor */
.tui-editor:after,
.tui-editor-defaultUI-toolbar:after {
  content: '';
  display: block;
  height: 0;
  clear: both;
}

.tui-editor {
  position: absolute;
  line-height: 1;
  color: #222;
  width: 100%;
  height: inherit;
}

.te-editor-section {
  min-height: 0px;
  position: relative;
  height: inherit;
}

.te-md-container {
  display: none;
  overflow: hidden;
  height: 100%;
}

.te-md-container .te-editor {
  line-height: 1.5;
}

.te-md-container .te-editor,
.te-md-container .te-preview {
  box-sizing: border-box;
  padding: 0;
  height: inherit;
}
```

There is some mismatch happening. I'm assuming it may SAY it's the `2.5.1` version in the top of the file, but it's actually the 3.0 version. It could be the other way, and the 2.5.1 version of the npm package is serving 3.0 javascript. The lack of consistency is the issue we're struggling with.

**Comment by js87zz** [comment]
@briochie 
2.x and 3.x files do not get mixed up because they are bundled separately in completely different packages. I think it could be a problem with npm itself. 
If you give me the code sandbox or repository to check the issue, I'll check it out in more detail.

**Comment by briochie** [comment]
@js87zz Unfortunately, I can't share the code. It's a private repo. I can provide you with any information you need from it in regards to how we're using the package, or what files NPM is serving us.

**Comment by briochie** [comment]
@js87zz I found the issue after digging some more. You're right, it's using the ver3 version of the editor. I found we're loading the javascript via CDN, despite actually loading the CSS from the npm.

This can be closed. Thank you so much, I don't think I'd have noticed without you pointing that out. 🙏
