### ISSUE TITLE
Bullet indent is not work properly

### ISSUE THREAD

**Issue by HTMLhead** [nhn/tui.editor#2216]
## Describe the bug
bullet mark indent is not work properly

## To Reproduce
1. write bullet mark 
2. press enter and press spacebar once(WYSIWYG is weird)
3. press enter and press spacebar twice

## Expected behavior
work properly markdown when press spacebar twice 

## Screenshots
![head](https://user-images.githubusercontent.com/40166539/150048109-f230083f-995d-46fa-8af3-972b28f8a98b.gif)

## Desktop (please complete the following information):
 - OS: macOS Big Sur 11.5.2
 - Browser: chrome

## Smartphone (please complete the following information):
unuse

## Additional context
toast-editor version: 3.1.1

**Comment by js87zz** [comment]
@HTMLhead 
I cannot reproduce it in [our example page](https://nhn.github.io/tui.editor/3.1.1/tutorial-example01-editor-basic).
![2022-01-19 11-55-57 2022-01-19 11_56_28](https://user-images.githubusercontent.com/37766175/150055421-7dfab448-f775-40ac-82a0-6683453c3b4b.gif)

Is there anything else that could be the problem?

**Comment by HTMLhead** [comment]
If the css file provided in the example is applied, it works correctly.
Sorry, that was my mistake, not a bug.

But I confirmed that the above works when the file below is imported.
`import "@toast-ui/editor/dist/toastui-editor-only.css";`
I was using a custom tui-editor-only.css file because of font size, and I wonder if it's the wrong way.

Thanks for your quick reply
