### ISSUE TITLE
Widget position wrong when page is scrolled

### ISSUE THREAD

**Issue by munettt** [nhn/tui.editor#2220]
## Describe the bug
The widget positioning is bugged if the page is scrolled.

## To Reproduce
https://codepen.io/munzir/pen/MWENRzW

## Expected behavior
It should stick to the caret positioning regardless if page is scrolled or not

## Screenshots

![image](https://user-images.githubusercontent.com/4035110/150684285-7510a8b8-1567-4d27-bd20-5d0f6806bfc8.png)

**Comment by js87zz** [comment]
@munettt 
I checked issue. It will be fixed.
Thanks!

**Comment by js87zz** [comment]
@munettt 
Thanks for long wating.
The bug has been fixed in `v3.1.3`(#2271)
