### ISSUE TITLE
conflict with the code's backticks

### ISSUE THREAD

**Issue by m-alaiady** [nhn/tui.editor#2235]
## Version
I'm using CDN with the latest version

## Test Environment
Chrome  version 97.0.4692.99 64-bit, Windows 10

## Current Behavior
I'm using laravel for the backend 

1 - make some input with code tag in the editor.
2 - save markdown code to the database.
3 - retrieve markdown from database to $article->content ( now this variable contains backticks for code tag ).

```js
const { Editor } = toastui;
const { codeSyntaxHighlight } = Editor.plugin;

const viewer = Editor.factory({
  el: document.querySelector('#viewer'),
  viewer: true,
  height: '500px',
  initialValue: ` {!! $article->content !!}`,
});
```

## Expected Behavior
I expected to see the code tag on the screen, but the backticks conflict with the backticks in the code tag.

I tried to use single and double quotations but they will not work since article content contains multiple lines.

Console shows unexpected identifier on line 130
![‏‏لقطة الشاشة (499)](https://user-images.githubusercontent.com/84629651/150903431-3c9b013e-a11f-4b3d-bdc9-a44a9eb39482.png)

toastUI viewer script with the content value you can clearly see the code tag (line 130) conflict and causing this problem.
![‏‏لقطة الشاشة (498)](https://user-images.githubusercontent.com/84629651/150903440-2b93424c-0ca6-4521-89b6-6445b64f4b58.png)

**Comment by m-alaiady** [comment]
I found Laravel helper for rendering markdown code directly.

**Comment by hilmanski** [comment]
HI @m-alaiady can you ellaborate how do you deal with this issue?
I found a problem when retreiving old content from  database
that has something like
<script> text</script>
