### ISSUE TITLE
Question: Toolbar too big

### ISSUE THREAD

**Issue by topse** [nhn/tui.editor#2239]
Hi,
I am sorry -- this is more a question. I need to reduce the width of the Toolbar. I already removed unneeded buttons -- but it is still too large. Is there a possibility to split it in rows (in 2018 this was not possible -- there was already a question here)? Or is it possible to hide some Buttons "under a more-button"? Or make the buttons smaller?

Any hint would be appreciated very much :-)

Best Regards,
         Tobias

**Comment by js87zz** [comment]
@topse 
Sorry for late replying.
Can you show me the toolbar UI you want, with an image?

**Comment by topse** [comment]
@js87zz 
Hi no problem...

No I am very sorry ... I found more problems with the TuiEditor (see [https://github.com/nhn/tui.editor/issues/2248](https://github.com/nhn/tui.editor/issues/2248), so that I changed to another library -- so sorry, I cant provide a picture...

Sorry and Best Regards,
Tobias
