### ISSUE TITLE
Skip next Node in toHTMLRenderers

### ISSUE THREAD

**Issue by topse** [nhn/tui.editor#2241]
Hi,
I need a custom render plugin to process not only the current text node but also the next. How can I mark the next node in the tree (not the children) as to be skipped?

I found the skipChildren function -- but I need a "skipNext" :-/

Thanks anyone for help and Best Regards,
         Tobias

**Comment by js87zz** [comment]
@topse 
Sorry for late response.
Could you tell me why you need it(`skipNext`)? 
It may be annoying, but I think it will be a good opinion if you let me know. Thank you!

**Comment by topse** [comment]
Hi,
to parse a latex formular between $...$ in my obervation it could happen, that it gets distributed to multiple nodes... so the next nodes with parts of the formular need to be skipped.

Best Regards,
       Tobias
