### ISSUE TITLE
Problem with Plugins: toHTMLRenderers

### ISSUE THREAD

**Issue by topse** [nhn/tui.editor#2248]
Hi,
sorry to bother again... I am trying to create a plugin -- but I dont see any result. Here is my test-code:

```
export default function mathjaxPlugin(
  context: PluginContext,
  options?
): PluginInfo {
  return {
    toHTMLRenderers: {
      text(node) {
        return [
          {
            type: "text",
            content: " *** ",
          },
        ];
      },
    },
  };
}
```

Expectation would be, that I can only see "***" in WYSIWYG-Mode of the Editor -- but I dont. I still see the "real" text.

But:
- When Debugging out of my function, I can see some command "this.buffer.push(...)" where my three stars *** seems to be worked on -- but I still dont see them in the Editor :-/

Thanks again,
          Tobias

**Comment by js87zz** [comment]
@topse 
Sorry for late response.
I don't know what you want exactly, but it's not recommended to customize the text node like an above. 
It could be a problem for both Markdown and WYSIWYG.
