### ISSUE TITLE
Page jumps to and focuses editor on load

### ISSUE THREAD

**Issue by AlecRust** [nhn/tui.editor#2295]
## Describe the bug

We use Toast Editor as part of a larger form. The editor is at the bottom of the form.

When the page loads (and Toast initialises) the user is scrolled to the editor at the bottom of the page and it becomes focused.

Is there a way to disable this behaviour? We have fields above the editor we would like the user to see/fill in first.

## To Reproduce

Steps to reproduce the behaviour:
1. Add Toast in a form with fields above the Toast editor
2. Load the page, note how user is scrolled down to Toast editor (away from the fields above) and the editor is focuses
3. User must scroll back up to fields above the editor in order to fill them in

## Expected behaviour

Personally I would have expected _by default_ Toast not to focus or scroll to the editor.

**Comment by js87zz** [comment]
@AlecRust 
Can you try to create the editor with `autofocus` option?
```js
const editor = new Editor({
  el: document.querySelector('#editor'),
  ...
  autofocus: false
});
```

**Comment by AlecRust** [comment]
Thanks @js87zz I guess I didn't ready documentation carefully enough!

Still, I would have expected this to be opt-in behaviour (like `autofocus` on a a normal text input) instead of opt-out.
