### ISSUE TITLE
Not able to keep front-matter tag inside markdown

### ISSUE THREAD

**Issue by ats1999** [nhn/tui.editor#2304]
https://www.npmjs.com/package/front-matter

## Reproduce 
Paste the following snippet in the editor
```js
---
title: Just hack'n
description: Nothing to see here
---
```

## SS
![Screenshot from 2022-02-13 07-12-59](https://user-images.githubusercontent.com/54087826/153734707-7fb1dd2c-a7aa-417a-bc17-b7c79e7754f9.png)

You'll see unexpected things on the preview side?

**Comment by ats1999** [comment]
```
rahul
-
```

This will also trigger the behaviour

**Comment by jwlee1108** [comment]
@ats1999 

Thank you for the issue.
There is an option called `frontMatter`. Set it to `true` and tell me again.

Please refer to the [link](https://nhn.github.io/tui.editor/latest/ToastUIEditorCore) and the example code.


```
const editor = new Editor({
  // others option..
  frontMatter: true,
});
```
