### ISSUE TITLE
Any update on this issue(2303)?

### ISSUE THREAD

**Issue by rahul-adpushup** [nhn/tui.editor#2323]
Issue 

https://github.com/nhn/tui.editor/issues/2303

I have  seen a lot of request regarding SSR. As we just have to provide an way  convert markdown to html on server(Node/Next.js), then the problem will be automatically  solved.

Anyway, thanks for  providing such an editor.

**Comment by jwlee1108** [comment]
@rahul-adpushup 

Thank you for the issue. 

SSR support is a task we need to do. but I have to research into supporting SSR.
There are no exact milestones yet. If I have a plan, I will update it on related issues.

**Comment by rahul-adpushup** [comment]
@jwlee1108 Is there any way to render markdown into HTML outside of the browser. 

https://www.npmjs.com/package/marked can not work in case of custom blocks and plugins/

**Comment by jwlee1108** [comment]
@rahul-adpushup 

When using additional features, there are quite complex converting logics, so I don't think it can be covered with a single library.

I understand your discomfort, but it's not something I can solve in a short term. Sorry. 🙏

**Comment by rahul-adpushup** [comment]
Hi, @jwlee1108 
I am trying to use https://github.com/nhn/tui.editor/blob/master/docs/en/custom-html-renderer.md

How can i use https://github.com/nhn/tui.editor/blob/master/docs/en/custom-block.md here. 

It's not working with  new `$$` syntax.
