### ISSUE TITLE
Extract links from markdown

### ISSUE THREAD

**Issue by akashchopra** [nhn/tui.editor#2340]
Is there any API for parsing the markdown and extracting information from it? My use case is that I want to get a list of the links that are in the markdown. The closest issue I could find (https://github.com/nhn/tui.editor/issues/1900) suggests that this is not possible, but might be in the future. Has there been any progress on this?

**Comment by jwlee1108** [comment]
@akashchopra 
Thank you for searching for other issues. There is no work for this yet. I'm sorry.
