### ISSUE TITLE
동적, 멀티 editor 에 대한 질문 ( Dynamic, multi-editor questions )

### ISSUE THREAD

**Issue by NamSeonw** [nhn/tui.editor#2342]
안녕하세요.

저는 현재 에디터를 사용하여 개발 하고 있는 사용자 입니다. 개발자 분들이 한국분들인거 같아 한국어로 먼저 써놓겠습니다.

현재 막힌 부분이 코드로 예를 들자면

```
const editor = new toastui.Editor({
      el: document.querySelector('#editor'),
      previewStyle: 'vertical',
      height: '500px'
});

console.log( editor.getHtml() )
```
이런 식으로 해당 내용을 가져와 쓰던데

만약 동적으로 toast ui editor가 추가 된다면 어떻게 처리 할 수 있을까요?

editor.getHtml() 이런식의 코드 또는 editor 라는 변수에 담지 않고 editor의 값을 가져 올 수 있을 까요..?

한 함수에서 이뤄지는 부분이 아니다 보니 전역으로 동적변수를 만들기도 애매하고 또 이미 저장되어있는 데이터가 toast ui editor를 3개의 editor로 나누어서 사용했다면 그에 대한 관리 또한 애매하여 문의 드립니다.

감사합니다.

Hello.

I am a user currently developing using the editor. Since the developers are Korean, I will write in Korean first.

If the currently blocked part is the code, for example,

```
const editor = new toastui.Editor({
      el: document.querySelector('#editor'),
      previewStyle: 'vertical',
      height: '500px'
});

console.log( editor.getHtml() )
```
This is how I got it and wrote it.

If the toast ui editor is dynamically added, how can it be handled?

editor.getHtml() Is it possible to get the editor's value without putting it in this type of code or editor variable..?

Since it is not a part of one function, it is ambiguous to create a global dynamic variable, and if the data that is already stored is used by dividing the toast ui editor into three editors, the management of it is also ambiguous, so we will ask you.

thank you.

**Comment by jwlee1108** [comment]
@NamSeonw 
> We basically use English for developers in other countries.

Can you tell me in more detail what you want to implement?  It is difficult to know the issue just by looking at the current blockage. Do you mean you want to create multiple instances?
