### ISSUE TITLE
Using custom block with @toast-ui/toastmark

### ISSUE THREAD

**Issue by rahul-adpushup** [nhn/tui.editor#2344]
## Summary
v3 custom block syntax is not working when using custom html renderer on server side.

## Related issues
- https://github.com/nhn/tui.editor/issues/1337

## Live Demo
> `Converting heading` will never logged

https://replit.com/join/vqldkkwzia-rahul-kumar1

**Comment by jwlee1108** [comment]
@rahul-adpushup 
Sorry. We haven't officially supported SSR yet.

**Comment by rahul-adpushup** [comment]
@jwlee1108 which parser or code do you use to parse new custom block syntax `$$`. Can you give me that?
