### ISSUE TITLE
Pasting text with new lines - New lines are omitted on editor

### ISSUE THREAD

**Issue by marskop** [nhn/tui.editor#2360]
## Version
3.1.3

## Description
When pasting text in the wysiwyg editor copied from vscode or from another text editor, the new lines are ommitted.
(**Note**: On toast ui editor version 2.5.2 this behavior does not exist)

Picture from Toast UI editor version 3.1.3: 

![newToastEditor](https://user-images.githubusercontent.com/11446441/157689501-43e77135-c081-4951-95aa-63a446ffd110.png)

Picture from Toast UI editor version 2.5.2: 
![oldToastEditor](https://user-images.githubusercontent.com/11446441/157689503-be3f69c2-5f68-4baf-a4b4-e00e6e66201b.png)

## Steps To Reproduce

1. Go to [Editor with WYSIWYG mode](https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-with-wysiwyg-mode) 
2. Delete example's content
3. Paste the following text with new lines in wysiwyg mode (or any text that includes multiple empty lines):  
<br>
Dummy text
<br>
<br>
after one new line
<br>
<br>
<br>
after two new lines
<br>
<br>
<br>
<br>
<br>
more new lines.

## Current behavior
Empty lines disappear

## Expected Behavior
Empty lines should be preserved.

**Comment by jwlee1108** [comment]
Sorry for the late reply. I'll check it.
