### ISSUE TITLE
Overwrite Editor Mark

### ISSUE THREAD

**Issue by PaulSchult** [nhn/tui.editor#2374]
Is it possible to overwrite an exisiting mark? E.g when inserting an image, the resulting html is `<img src="/files/test.png" alt="test.png" data-nodeid="12">`. In my use-case I would like to add an `<a>`-tag around the `<img>`-tag. Is there any way to do this?

**Comment by jwlee1108** [comment]
I think you can use [customHTMLRenderer](https://github.com/nhn/tui.editor/blob/master/docs/en/custom-html-renderer.md#-custom-html-renderer)
