### ISSUE TITLE
How to set the position and size of the inserted picture

### ISSUE THREAD

**Issue by better-pz** [nhn/tui.editor#2379]
![WO4nQ9YBii4ShjD61AR7tg==](https://user-images.githubusercontent.com/68367439/158921652-0ae9d1c4-cad0-4900-ac5a-7940edf4f529.png)

As shown in the picture, I want to set the position where I paste the image (I want it to be centered) or increase the size, what should I do

**Comment by jwlee1108** [comment]
@pzheng98 

We don't support it. but I think it is a good feature. so, we'll try to research it to make.

**Comment by pzheng98** [comment]
@jwlee1108 thanks

**Comment by pzheng98** [comment]
@jwlee1108 When can you repair it? thanks
