### ISSUE TITLE
Fix typo in german translation

### ISSUE THREAD

**Issue by MBWebTechMariusz** [nhn/tui.editor#2380]
## Describe the bug
There is a typo in the german translation. "datei" is written in lowercase, where it should be uppercase.
```
    'Choose a file': 'Wähle eine datei',
    'No file': 'Keine datei',
```

## Expected behavior
```
    'Choose a file': 'Wähle eine Datei',
    'No file': 'Keine Datei',
```

**Comment by jwlee1108** [comment]
@MBWebTechMariusz 

Do you have any thoughts to contribute by revising this issue yourself? It's simple, but I think it'll be a good experience for you.

**Comment by MBWebTechMariusz** [comment]
Is this the right way? https://github.com/nhn/tui.editor/pull/2391

**Comment by jwlee1108** [comment]
Thank you for your contribution!
