### ISSUE TITLE
i cannot install

### ISSUE THREAD

**Issue by JackDeng666** [nhn/tui.editor#2383]
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
npm ERR! Error while executing:
npm ERR! D:\program\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/seonim-ryu/Squire.git
npm ERR!
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

**Comment by jwlee1108** [comment]
@JackDeng666 I need your detailed development environment. What commands did you execute?

**Comment by JackDeng666** [comment]
PS D:\MySourceCode\MyProjects\home_crm_admin> node --version
v14.19.0
PS D:\MySourceCode\MyProjects\home_crm_admin> npm --version
6.14.16
PS D:\MySourceCode\MyProjects\home_crm_admin> npm i
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b 2.2.0-c https://github.com/nhn/raphael.git C:\Users\15563\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-013b548c --config core.longpaths=true
npm ERR! warning: templates not found in C:\Users\15563\AppData\Local\Temp\pacote-git-template-tmp\git-clone-2ea58d7e
npm ERR! fatal: unable to access 'https://github.com/nhn/raphael.git/': OpenSSL SSL_read: Connection was reset, errno 10054
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\15563\AppData\Roaming\npm-cache\_logs\2022-03-24T01_45_22_827Z-debug.log
PS D:\MySourceCode\MyProjects\home_crm_admin>

**Comment by JackDeng666** [comment]
win11
