### ISSUE TITLE
@toast-ui/react-editor autofoucs props is ignored

### ISSUE THREAD

**Issue by caias** [nhn/tui.editor#2389]
## Describe the bug
autofoucs props is ignored in @toast-ui/react-editor

## To Reproduce
related issue in https://github.com/nhn/tui.editor/issues/1802
@toast-ui/react-editor has same issue but not solved

## Expected behavior
According to that issue, i know that the problem has been solved in tui-editor 1.3.2 . but now tui-editor dependency version is 1.3.0 in @toast-ui/react-editor. so request version update latest tui-editor version

also what is correct dependency? tui-editor? or @toast-ui-editor??

it is my package.json
<img width="468" alt="image" src="https://user-images.githubusercontent.com/14008805/159621583-cdf39267-3d06-4920-ae2e-6b11f72fc7d6.png">

 @toast-ui/react-editor package.json
<img width="322" alt="image" src="https://user-images.githubusercontent.com/14008805/159621615-9d7c4b65-d681-4ca5-b451-fe46afe39f09.png">

**Comment by jwlee1108** [comment]
Thank you for the issue.

We'll check it

**Comment by jajugoguma** [comment]
@caias 
The repository [toast-ui/react-editor](https://github.com/nhn/toast-ui.react-editor) is deprecated️️️️️. Currently, the wrapper is managed in this repository(mono-repo). So, you can use react wrapper for toast ui editor by using this repository or installing [package with npm](https://www.npmjs.com/package/@toast-ui/react-editor). Please read [it](https://github.com/nhn/tui.editor/tree/master/apps/react-editor) to use.

If the issue occurs again, please comment here with mentioned me. Thanks!
