### ISSUE TITLE
Where can I see the documentation to use the UML plugin?

### ISSUE THREAD

**Issue by curiosport** [nhn/tui.editor#2405]
I already saw the UML example, but that's all this plugin can do or there are more features? because if there are I can't find the documentation.

**Comment by jwlee1108** [comment]
@curiosport 

I'm sorry. but, this is all you can see now.

https://nhn.github.io/tui.editor/latest/tutorial-example11-editor-with-uml-plugin

FYI. we have the [plantuml-encoder](https://github.com/markushedvall/plantuml-encoder) dependency
