### ISSUE TITLE
Will this editor support katex or mathJax

### ISSUE THREAD

**Issue by df19900725** [nhn/tui.editor#2408]
## Version
I haven't use it yet

## Development Environment
chrome, suse

## Current Behavior
I am developing a website which can help people to record their ideas. I build it for who are someone writing CS papers. So, there are many math expressions. So I need an editor with support both markdown and latex. I am using Editor.md right now, it has lots of features while I think it is too old and too large. So I am trying to find a new one. I think tui.editor is very proper for me. However, it does not support any latex plugin. As I am not an expert for developing javascript, so I find it is diffult for me to add the feature

## Expected Behavior
I am wondering that whether the tui.editor will support katex or mathjax, or is there any plan to support latex functions?

**Comment by jwlee1108** [comment]
@df19900725 I misunderstood that you must use `katex`. But I think it'll be fully applicable.

**Comment by df19900725** [comment]
@jwlee1108 Fine, katex is fast I think. The most important is the `latex` feature for me.
