### ISSUE TITLE
Color-syntax plugin always focus the first editor when using several editors on the same page

### ISSUE THREAD

**Issue by SvetlanaTselikova** [nhn/tui.editor#2413]
## Describe the bug
I have three Toast UI editors on the same page and using color-syntax plugin in each of them. When I pick color and press "ok" button in second or third editor, the page scrolls to the first editor and focus on it.  

## To Reproduce
1. Add two editors on the same page and use color color-syntax plugin on the second editor.
2. Pick the color in the color-syntax tab of the second editor and press "ok" button.
3. The first editor will be focused.

## Expected behavior
The second editor will be focused (the editor, which color pick tab was pressed)

## Additional context
Looks, that the reason of issue is that querySelector: https://github.com/nhn/tui.editor/blob/master/plugins/color-syntax/src/index.ts#L88 selects the first .ProseMirror div in document and after press "ok"  focus on it https://github.com/nhn/tui.editor/blob/master/plugins/color-syntax/src/index.ts#L98.

**Comment by jwlee1108** [comment]
@SvetlanaTselikova Thank you for the issue.

Recently, We are checking an issue similar to this. I think one of my colleagues can help. (@jajugoguma)
