### ISSUE TITLE
using Existing Prose mirror Plugins

### ISSUE THREAD

**Issue by kishorethecoder** [nhn/tui.editor#2423]
## Summary
I would like to integrate Prosemirror Find-Replace [plugin](https://www.npmjs.com/package/prosemirror-find-replace) into the toast UI editor. But, I'm not able to find the way of adding the find command into the command set given in the description as it is not exposed. can you please guide me through it?

## Screenshots
![image](https://user-images.githubusercontent.com/3882978/161921731-e5337576-ec62-4484-aba4-2bceae7530b9.png)

## Version
latest

**Comment by jwlee1108** [comment]
@kishorethecoder 
I want to help with this question, I don't think it's a simple problem because we have to consider an MD and WYSIWYG.
We'll check it later. Sorry.

**Comment by jwlee1108** [comment]
@kishorethecoder 

Sorry for the late reply. 

I think you can make a new plugin for tui-editor.
please refer to this [link](https://github.com/nhn/tui.editor/blob/master/apps/editor/types/plugin.d.ts#L37)

We can give the interface markdown and wysiwyg command.
