### ISSUE TITLE
Missing library in examples ?

### ISSUE THREAD

**Issue by nlevasseur-ix** [nhn/tui.editor#2427]
Hello, 

After downloading the project on Git when I try to launch the following page: example01-editor-basic.html in the folder: apps/editor/examples. I get the following error: 

`Uncaught ReferenceError: toastui is not defined` 

The script tag `<script src="../dist/cdn/toastui-editor-all.js"></script>` try to retrieve the file that does not exist in folder!

Thanks

**Comment by jwlee1108** [comment]
@nlevasseur-ix 
Would you like to try the build first? If you still have a problem, please leave a comment.

**Comment by nlevasseur-ix** [comment]
@jwlee1108 thanks the problem must come from there, I thought that the sources were compiled in the project.

**Comment by jwlee1108** [comment]
@nlevasseur-ix Sorry for the late reply.

```
cd tui.editor
npm run build:all
```

**Comment by nlevasseur-ix** [comment]
@jwlee1108 Thanks ! It's will be great if this command is indicate on the documentation.
