### ISSUE TITLE
how to get the "command" list of toolbar?

### ISSUE THREAD

**Issue by seongto** [nhn/tui.editor#2428]
I can see only 'bold' examples. 
I'm trying to add "H1" toolbar button, but I can't find how to do.
Is there any way?

**Comment by jwlee1108** [comment]
Do You want to make a customized toolbar button with a heading feature?

**Comment by cary-hu** [comment]
https://github.com/nhn/tui.editor/blob/master/apps/editor/src/__test__/unit/wysiwyg/wwCommand.spec.ts#L64

hope to help you @seongto
