### ISSUE TITLE
Is there a way to upload any file like txt or PDF? (Vue)

### ISSUE THREAD

**Issue by tomaszmac** [nhn/tui.editor#2429]
I want to add a possilibity to add any file. Something like git has. It may be done as icon or as additional button. Even with drag&drop would be perfect. 

Even writing an issue in the github you can add any other file:
![image](https://user-images.githubusercontent.com/64752217/162737484-7d5876ff-5f03-4307-ae44-0d1daaf70e2d.png)

And check it how it looks in the preview: 
![image](https://user-images.githubusercontent.com/64752217/162737605-cc460c05-e263-461e-887c-a371fe42f96d.png)

Is there  a way to achive something like that in an Editor and a Viewer in Vue?

**Comment by jwlee1108** [comment]
@tomaszmac 

This is not just a matter for editors. I think you need to develop a custom toolbar button or plugin. 

1. When the Custom toolbar button is clicked, upload the file to the server
2. Get a link. 
3. Then add a link to the body of the editor or outside of the editor.

FYI, I think D&D can use `handleDrop`, but I can't help you right away because I'm working on something else.

**Comment by nlevasseur-ix** [comment]
I hook this function `addImageBlobHook` : 

```
hooks: {
            addImageBlobHook: function (blob, callback, source) {

                fileName = blob.name;
                var reader = new FileReader();

                reader.onload = function (_a) {s

                    var data = {};
                    var content = reader.result;

                    data.fileName   = fileName;
                    data.content    = content;
                    data.extension  = fileName.split('.').pop();

                    $.ajax({
                        type: 'POST',
                        data: data,
                        url: '/uploadFile,
                        success: function (data) {
                            var res = JSON.parse(data);
                            $('.toastui-editor-close-button').trigger('click');
                            var isImage   = new RegExp("(\\.(webp|jpg|jpeg|gif|bmp|png))$", "i"); // /(\.(webp|jpg|jpeg|gif|bmp|png))$/
                            if (isImage.test(res.title)) {
                                editor.insertText('!['+altText+']('+res.url+')')
                            } else {
                                editor.insertText('['+altText+']('+res.url+')')
                            }
                        },
                        error: function () {
                            alert('error to insert file');
                        }
                    });
                };
                reader.readAsDataURL(blob);
            }
        }
```

In PHP you can do this to write this file : 

```
// Decode base64 data
    $fileName               = $_POST['fileName'];
    $extension              = $_POST['extension'];
    list($typeFile, $data)  = explode(';', $_POST['content']);
    list(, $data)           = explode(',', $data);
    $file_data              = base64_decode($data);
    file_put_contents('my path', $file_data);
   // todo return url path of file
```

**Comment by tomaszmac** [comment]
> I hook this function `addImageBlobHook` :
> 
> ```
> hooks: {
>             addImageBlobHook: function (blob, callback, source) {
> 
>                 fileName = blob.name;
>                 var reader = new FileReader();
> 
>                 reader.onload = function (_a) {s
> 
>                     var data = {};
>                     var content = reader.result;
> 
>                     data.fileName   = fileName;
>                     data.content    = content;
>                     data.extension  = fileName.split('.').pop();
> 
>                     $.ajax({
>                         type: 'POST',
>                         data: data,
>                         url: '/uploadFile,
>                         success: function (data) {
>                             var res = JSON.parse(data);
>                             $('.toastui-editor-close-button').trigger('click');
>                             var isImage   = new RegExp("(\\.(webp|jpg|jpeg|gif|bmp|png))$", "i"); // /(\.(webp|jpg|jpeg|gif|bmp|png))$/
>                             if (isImage.test(res.title)) {
>                                 editor.insertText('!['+altText+']('+res.url+')')
>                             } else {
>                                 editor.insertText('['+altText+']('+res.url+')')
>                             }
>                         },
>                         error: function () {
>                             alert('error to insert file');
>                         }
>                     });
>                 };
>                 reader.readAsDataURL(blob);
>             }
>         }
> ```

> ```

 editor.insertText('['+altText+']('+res.url+')'). This kinda works but when I'm using WYSIWYG it's escaping all of the signs like dots and so on :(



> @tomaszmac
> 
> This is not just a matter for editors. I think you need to develop a custom toolbar button or plugin.
> 
> 1. When the Custom toolbar button is clicked, upload the file to the server
> 2. Get a link.
> 3. Then add a link to the body of the editor or outside of the editor.
> 
> FYI, I think D&D can use `handleDrop`, but I can't help you right away because I'm working on something else.

It all works until step 3. When I use the example above with editor.insertText it's not always inserting it or is escaping special sings.

**Comment by nlevasseur-ix** [comment]
Hi, I updated code, try to send Ajax return with this `echo json_encode($myArray);` and it's should be good.

editor is the name of variable which contain Editor class, like this :

```
editor = new Editor({
        el: document.querySelector('#div'),
        previewStyle: 'vertical',
        height: '400px',
        },
```

**Comment by tomaszmac** [comment]
Problems I have right now are:

1) When I use WYSIWYG and I add a link (for tests it's static) it gives me wierd output:

Code:
```
editor.insertText('[testPDF](https://www.howtogeek.com/downloads/4/file/2020/05/PC_Building_Demystified.pdf)');
```
Output:

**Comment by tomaszmac** [comment]
Problems I have right now are:

1) When I use WYSIWYG and I add a link (for tests it's static) it gives me wierd output:

Code:
```
editor.insertText('[doggo](https://www.howtogeek.com/downloads/4/file/2020/05/PC_Building_Demystified.pdf)');
```
Output WYSIWYG:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/64752217/163993052-3edc9e66-5713-4a9f-a797-0d45e12734b8.png">

Output markdown:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/64752217/163993212-b93f8429-9e25-4e88-a751-b293b6915bbf.png">

2) When I click on a link it opens in the same tab. How to add `target="_blank"`?

**Comment by nlevasseur-ix** [comment]
1. Yes I don't now how to fix it ! you can share solution if you find it.
2. try this : https://github.com/nhn/tui.editor/issues/527

**Comment by tomaszmac** [comment]
> 1. You can use this
>    `editor.exec('addLink', { linkUrl: 'mytext', linkText: 'https://picsum.photos/200' });`
>    a search in repo like this, could help you : https://github.com/nhn/tui.editor/search?q=insertText&type=issues
> 2. try this : [linkAttribute in Viewer #527](https://github.com/nhn/tui.editor/issues/527)

Thanks a lot.

The first one I did like that ` editor.wwEditor.commands.addLink(payload);` but i think your solution is better.

The second one doesn't seem to work in the Preview tab.
