### ISSUE TITLE
addImageBlobHook Cannot read properties of undefined

### ISSUE THREAD

**Issue by hejunrex** [nhn/tui.editor#2453]
`  data() {
    return {
      qiniuToken: '',
      editorOptions: {
        usageStatistics: false,
        toolbarItems: [
          ['bold', 'italic'],
          ['image']
        ],
        hooks: {
          addImageBlobHook(blob, callback) {
            if (this.qiniuToken === '' || this.episodeInfo.content_id == null) {
              return
            }`

Uncaught TypeError: Cannot read properties of undefined (reading 'qiniuToken')

How to use this

**Comment by jwlee1108** [comment]
@hejunrex Could you leave a little more detail?
