### ISSUE TITLE
Add quote in wysiwyg mode

### ISSUE THREAD

**Issue by nlevasseur-ix** [nhn/tui.editor#2462]
Hello, 

Is-it possible to add quote with a command in  wysiwyg mode ? 

As command 'addImage' below :
```
editor.exec('addImage', {
                        altText: altText,
                        imageUrl: res.url
                      });
```

I see this function, but I don't know how to use it : 

![image](https://user-images.githubusercontent.com/66420970/164641386-cae028db-e122-4659-a8ef-3989914f2d23.png)

Thanks

**Comment by nlevasseur-ix** [comment]
I find and alternative with :

`editorEdit.setMarkdown('> ' + content)`

**Comment by jwlee1108** [comment]
@nlevasseur-ix It's a markdown command. so I think your way is a kind of solution. You don't want a shortcut, do you?
