### ISSUE TITLE
Failed to load resource:https://uicdn.toast.com/editor/latest/purify.js.map

### ISSUE THREAD

**Issue by ConanJordan** [nhn/tui.editor#2470]
## Summary
Failed to load resource:https://uicdn.toast.com/editor/latest/purify.js.map

## Screenshots
> source
<img width="908" alt="image" src="https://user-images.githubusercontent.com/40572164/165013330-6f2df03f-3063-4351-86de-1e6370cf4870.png">

> browser result
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/40572164/165013400-1dd05197-bef6-4102-b326-0496f945c2e2.png">

## Version
As we can see in source image, it was the latest version at 2022/04/25.

## Additional context
It seems to be a resource accessing problem. But I just have no idea how to get it. 
Very appreciate if anyone can give me a hand.

**Comment by jwlee1108** [comment]
@ConanJordan Where did you get the sample code? please check this [link](https://nhn.github.io/tui.editor/latest/tutorial-example04-viewer).

**Comment by jwlee1108** [comment]
@ConanJordan I was confused and I just deleted the comment I wrote because I thought it would confuse you.

Is this problem still happening again? There is no particular problem when I made a simple HTML file and tested the code below.

```html
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <meta charset="UTF-8" />
    <script src="https://uicdn.toast.com/editor/latest/toastui-editor-viewer.js"></script>
    <link
      rel="stylesheet"
      href="https://uicdn.toast.com/editor/latest/toastui-editor-viewer.min.css"
    />
  </head>

  <body>
    <div id="viewer"></div>

    <script>
      const Viewer = toastui.Editor;
      const viewer = new Viewer({
        el: document.querySelector("#viewer"),
        height: "600px",
        initialValue: "[Google](https://google.com)"
      });
    </script>
  </body>
</html>

```

**Comment by ConanJordan** [comment]
@jwlee1108 

**Sorry** to reply so lately.
Still have no idea how the problem happened. 
But it was OK when I took a test on **other device.**

Anyway, it is appreciate to have your comment.
