### ISSUE TITLE
How to prevent the @toast-ui/vue-editor from focusing when mounted?

### ISSUE THREAD

**Issue by radiorz** [nhn/tui.editor#2474]
## Summary
  I dont want to focus on this editor when the component mounted, What should I do.
  I try to put autofocus in options or  just put it  in <editor :autofocus="false"> but nothing works.
  

## Screenshots
If applicable, add screenshots to help explain your question.

## Version
Write the version of the Editor you are currently using.
@toast-ui/vue-editor 3.1.5

**Comment by jwlee1108** [comment]
@radiorz We have `autofocus` options. Please try it.

**Comment by radiorz** [comment]
How to make it work? I try to add `autofocus:false` into options like this,but it still focus on the editor when component mounted.
```
  <editor
    ref="editor"
    preview-style="vertical"
    class="markdown-editor"
    :options="{
        ...otherOptions,
        autofocus:false
    }"
    @blur="onEditorChange"
    initialEditType="wysiwyg"
  />
```

**Comment by jwlee1108** [comment]
@radiorz Sorry for the late reply. I think the autofocus operation was strange when I reproduced it in codesandbox. I'll check the code.

**Comment by mladen-orsolic** [comment]
This issue still persists in latest version. Its easily reproducible when you have multiple instances (that contain some text) in a vertically scrollable div. It will auto scroll to the end of text in last editor, and it will cause to containing div to scroll to the last editor. Autofocus has no effect here and i'm unable to prevent this behaviour using css and/or javascript.

css:
```
  overflowAnchor: 'none', // on the container
  '& *': {
    overflowAnchor: 'none', // apply to all child editors and its children too
  },
```

react:
```
  // Force blur after mount or value change if autoFocus is false
  useEffect(() => {
    if (!autoFocus && editable && editorRef.current) {
      const editorInstance = editorRef.current.getInstance();
      const { mdEditor, wwEditor } = editorInstance.getEditorElements();

      // Blur both markdown and WYSIWYG editors
      if (mdEditor instanceof HTMLElement) {
        mdEditor.blur();
        mdEditor.scrollTop = 0;
      }
      if (wwEditor instanceof HTMLElement) {
        wwEditor.blur();
        wwEditor.scrollTop = 0;
      }
    }
  }, [editorRef, autoFocus]);
```

none of this helps preventing the focus and autoscroll

edit: it works fine when initialEditType is "markdown", which i dont want, i want initialEditType to be "wysiwyg"
