### ISSUE TITLE
How to override the Ctrl+S command in Markdown mode?

### ISSUE THREAD

**Issue by swordow** [nhn/tui.editor#2476]
The "Ctrl+S" command in toast editor is used to add "strike" and how to override it for "Save" usage?
And  how to add any new command in right click context menu?

**Comment by kmhari** [comment]
set `useCommandShortcut={false}`
This will remove all keyboard shortcuts and then you can override them using onKeydown event.

**Comment by HichamDz38** [comment]
hello, the solution will stop the whole shortcut, i want just to prevent the Ctrl+S an keep the rest, there is a configuration for that?

**Comment by swordow** [comment]
> hello, the solution will stop the whole shortcut, i want just to prevent the Ctrl+S an keep the rest, there is a configuration for that?

I think you should open a new issue? And have you solved this?

**Comment by umitnrodemund** [comment]
I have the same problem, I need Ctrl+s for the "save" command, please reopen issue

Workaround:

```
document.addEventListener("keydown", function(event) {
    if (event.ctrlKey && event.key === "s") {
        event.preventDefault();
        event.stopPropagation();
    }
}, true);
```

**Comment by swordow** [comment]
> I have the same problem, I need Ctrl+s for the "save" command, please reopen issue
> 
> Workaround:
> 
> ```
> document.addEventListener("keydown", function(event) {
>     if (event.ctrlKey && event.key === "s") {
>         event.preventDefault();
>         event.stopPropagation();
>     }
> }, true);
> ```

I dont have permission to reopen this issue...
