### ISSUE TITLE
How to make the toolbar stick to the top?

### ISSUE THREAD

**Issue by LogeshG5** [nhn/tui.editor#2478]
For lengthy documents the toolbar is not visible as you scroll down. So to access toolbar you have to scroll up to the top. 

How can I make the toolbar stick to the top? 

With my limited knowledge, I tried `position: fixed` and `position: sticky` with toastui-editor-toolbar with no luck.

**Comment by mornslit** [comment]
My css looks like this, and it works.
/deep/ .toastui-editor-toolbar {
  --top: 0;
  position: sticky;
  top: var(--top);
  z-index: 50;
}

**Comment by LogeshG5** [comment]
Thanks! It works for me too.
