### ISSUE TITLE
Module not found: @toast-ui/editor tried to access prosemirror-transform, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

### ISSUE THREAD

**Issue by JeongTaehwan** [nhn/tui.editor#2490]
## Summary

I'm going to use @toast-ui/react-editor for typescript + react project.    
From the top of the code after installing the library,
`import "@toast-ui/editor/dist/toastui-editor.css";
import { Editor } from "@toast-ui/react-editor";`
Attempted to use Editor after loading code.    
I wonder why the error does not occur on the code, but only on the terminal. Also, I wonder why that error appears.

## Screenshots

<img width="505" alt="스크린샷 2022-05-03 13 54 20" src="https://user-images.githubusercontent.com/68889258/166406080-2772e89c-b651-49ce-81a4-1206f82cfae4.png">
<img width="280" alt="스크린샷 2022-05-03 13 54 29" src="https://user-images.githubusercontent.com/68889258/166406086-8bd236d9-ae38-4fa2-afc4-6c2df47bda4a.png">
<img width="867" alt="스크린샷 2022-05-03 13 54 36" src="https://user-images.githubusercontent.com/68889258/166406090-bff0b735-1cf5-441a-8e3f-d018b251a57e.png">
<img width="361" alt="스크린샷 2022-05-03 13 55 09" src="https://user-images.githubusercontent.com/68889258/166406091-c984c49a-2d3f-4ee3-8843-dd63fa7b30fe.png">

## Version
^3.1.5

**Comment by JeongTaehwan** [comment]
Here's my code

```ts
/** @jsxImportSource @emotion/react */
import React, { useRef, useState } from "react";
import Button from "../Button/Button";
import * as S from "./Style";
import { useBeforeunload } from "react-beforeunload";
import Input from "../Input/Input";
import { useNavigate } from "react-router-dom";
import "@toast-ui/editor/dist/toastui-editor.css";
import { Editor } from "@toast-ui/react-editor";

interface WriteProps {
  onClick?: Function;
  data?: {
    contents: string;
    fieldList: string[];
    fileUrlList: any;
    languageList: string[];
    purpose: string[];
    status: string[];
    title: string;
  };
}

const WriteTextForm: React.FC<WriteProps> = () => {
  const [title, setTitle] = useState("");
  const [value, setValue] = useState("");
  const navigate = useNavigate();
  const innerRef: any = useRef(null);

  useBeforeunload((e: any) => {
    e.preventDefault();
  });

  const handleSubmit = (e: any) => {
    e.preventDefault();
  };

  return (
    <div css={S.Positioner}>
      <Input
        type="text"
        theme="WritePageInput"
        fontSize="h1"
        placeholder="프로젝트 이름을 입력하세요"
        fontWeight="600"
        width="100%"
        onChange={(currentTarget) => {
          setTitle(currentTarget.target.value);
        }}
        value={title}
      />
      <Editor
        initialValue={value}
        previewStyle="vertical"
        height="600px"
        initialEditType="markdown"
        useCommandShortcut={true}
      />
      <div css={S.ButtonContainer}>
        <Button
          theme="GrayButtonWithBlackTextNoHover"
          children="취소"
          size="Regular"
          fontSize="h5"
          fontWeight="400"
          isShadow="No"
          onClick={() => navigate("/main")}
        />
        <Button
          theme="BlackButtonWithWithTextNoHover"
          children="글 등록"
          size="Regular"
          fontSize="h5"
          fontWeight="600"
          isShadow="No"
          onClick={() => {}}
        />
      </div>
    </div>
  );
};

export default WriteTextForm;
```

**Comment by chinesedate** [comment]
> ## Summary
> I'm going to use @toast-ui/react-editor for typescript + react project. From the top of the code after installing the library, `import "@toast-ui/editor/dist/toastui-editor.css"; import { Editor } from "@toast-ui/react-editor";` Attempted to use Editor after loading code. I wonder why the error does not occur on the code, but only on the terminal. Also, I wonder why that error appears.
> 
> ## Screenshots
> <img alt="스크린샷 2022-05-03 13 54 20" width="505" src="https://user-images.githubusercontent.com/68889258/166406080-2772e89c-b651-49ce-81a4-1206f82cfae4.png">
> 
> <img alt="스크린샷 2022-05-03 13 54 29" width="280" src="https://user-images.githubusercontent.com/68889258/166406086-8bd236d9-ae38-4fa2-afc4-6c2df47bda4a.png">
> 
> <img alt="스크린샷 2022-05-03 13 54 36" width="867" src="https://user-images.githubusercontent.com/68889258/166406090-bff0b735-1cf5-441a-8e3f-d018b251a57e.png">
> 
> <img alt="스크린샷 2022-05-03 13 55 09" width="361" src="https://user-images.githubusercontent.com/68889258/166406091-c984c49a-2d3f-4ee3-8843-dd63fa7b30fe.png">
> 
> ## Version
> ^3.1.5

aaa

**Comment by chinesedate** [comment]
> @JeongTaehwan Sorry for the late reply.
> 
> Can you show your code in detail? I tried to reproduce the error, but I can't do it. ([ref link](https://codesandbox.io/s/react-editor-ts-m003tu?file=/src/App.tsx))

444

**Comment by chinesedate** [comment]
> @JeongTaehwan Sorry for the late reply.
> 
> Can you show your code in detail? I tried to reproduce the error, but I can't do it. ([ref link](https://codesandbox.io/s/react-editor-ts-m003tu?file=/src/App.tsx))

啊啊啊啊啊啊

**Comment by youknowhat** [comment]
I have the same problem in yarn berry

**Comment by jiwon-mun** [comment]
If you are using Yarn2, you can avoid the problem with the following settings.

.yarnrc.yml
```yml
packageExtensions:
  '@toast-ui/editor@*':
    dependencies:
      prosemirror-transform: '*'
```

https://yarnpkg.com/configuration/yarnrc#packageExtensions

**Comment by leewp14** [comment]
> If you are using Yarn2, you can avoid the problem with the following settings.
> 
> .yarnrc.yml
> 
> ```yaml
> packageExtensions:
>   '@toast-ui/editor@*':
>     dependencies:
>       prosemirror-transform: '*'
> ```
> 
> https://yarnpkg.com/configuration/yarnrc#packageExtensions

@jiwon-mun it works beautifully, thanks!
