### ISSUE TITLE
addimageblobhook 

### ISSUE THREAD

**Issue by AtroxEzerel** [nhn/tui.editor#2495]
Will the addimageblobhook event in hooks be triggered when I paste pictures when using the copy and paste function?

**Comment by jwlee1108** [comment]
@AtroxEzerel 
yes. it works. ([link](https://codesandbox.io/s/editor-js-oq3t7r?file=/src/index.js))

**Comment by AtroxEzerel** [comment]
@jwlee1108 Thank you very much. The problem has been solved.
