### ISSUE TITLE
tui toolbaritems color issue, when using tailwind

### ISSUE THREAD

**Issue by baesumin** [nhn/tui.editor#2511]
## Summary
ToolbarItems lose color when using tailwind. Is there any way to set the toolbaritems color?

## Screenshots
![image](https://user-images.githubusercontent.com/52240990/169327137-735134ed-5649-4c2f-9811-d71ee6dd99fb.png)
![image](https://user-images.githubusercontent.com/52240990/169327495-f7a0f7ae-bfd4-43be-90cf-e8b0cd3c4459.png)

## Version
"@toast-ui/editor": "^3.1.3",
"@toast-ui/react-editor": "^3.1.3",

## Additional context
/

**Comment by baesumin** [comment]
i remove 

button,
[type='button'],
[type='reset'],
[type='submit'] {
  background-image: none;
}

**Comment by OnkelTem** [comment]
@baesumin How can he remove something from tailwind? :)

**Comment by vimkim** [comment]
This situation was driving my teammates and me nuts, but we found an elegant solution.

```ts
// main.ts
import React from 'react';
import './index.css';

import App from './App.tsx';
```
basically it gets fixed when you reorder the imports... In my case vscode's 'auto-organizing imports by alphabetical order' caused the problem.

https://velog.io/@dkvlg/TOAST-UI-Editor%EC%99%80-Tailwind%EC%97%90%EC%84%9C-toolbar-icon%EC%9D%B4-%EB%82%98%ED%83%80%EB%82%98%EC%A7%80-%EC%95%8A%EB%8A%94-%EB%AC%B8%EC%A0%9C

I wrote a blog post (in Korean) about solving this issue...
