### ISSUE TITLE
Customize List Icon

### ISSUE THREAD

**Issue by SeogJongYu** [nhn/tui.editor#2527]
# Translated
1. I want to create a List Plugin that imports the list function as it is and replaces only the front bullet icon with an SVG image.
I referred to the [plugin doc](https://github.com/nhn/tui.editor/blob/master/docs/ko/plugin.md),
Can I make a new list command by referring to the bulletList command in markdownCommands or wysiwygCommands?

2. toHTMLRenderers works in Markdown mode, but not in Wysiwyg mode.
What's the problem?

![image](https://user-images.githubusercontent.com/63091064/170653075-830277ea-98bd-49cf-93cd-14c81c0889d1.png)

# Origin

## Summary
1. List 기능을 그대로 가져오면서 앞의 글머리 아이콘만 SVG 이미지로 대체하는 List Plugin을 만들려고 합니다.
[plugin doc](https://github.com/nhn/tui.editor/blob/master/docs/ko/plugin.md)을 참고했는데,
markdownCommands나 wysiwygCommands에서 bulletList 커맨드를 참조하여 새로운 리스트 커맨드를 만들수 있나요?

2. toHTMLRenderers가 Markdown mode에선 동작하는데, Wysiwyg mode에선 동작하지 않습니다.
무엇이 문제인가요?

![image](https://user-images.githubusercontent.com/63091064/170653075-830277ea-98bd-49cf-93cd-14c81c0889d1.png)

**Comment by jwlee1108** [comment]
@SeogJongYu 

First, I translate it into English to share with others.

1. I think that is possible. but, you need to check CSS.
2. If you're making a plug-in now, you'll also need a `wysiwygPlugins`
