### ISSUE TITLE
Norwegian translations are terrible

### ISSUE THREAD

**Issue by AbstractionsAs** [nhn/tui.editor#2549]
## Describe the bug
Norwegian translations are a mix of bad and just plain wrong

## Additional context
Theese are better:

Editor.setLanguage(['nb', 'nb-NO'], {
        Markdown: 'Markdown',
        WYSIWYG: 'WYSIWYG',
        Write: 'Skriv',
        Preview: 'Forhåndsvisning',
        Headings: 'Overskrift',
        Paragraph: 'Avsnitt',
        Bold: 'Fet skrift',
        Italic: 'Kursiv',
        Strike: 'Stryk',
        Code: 'Sett inn kodelinje',
        Line: 'Linje',
        Blockquote: 'Sitat',
        'Unordered list': 'Usortert liste',
        'Ordered list': 'Sortert liste',
        Task: 'Oppgave',
        Indent: 'Innrykk',
        Outdent: 'Utrykk',
        'Insert link': 'Sett inn lenke',
        'Insert CodeBlock': 'Sett inn kodeblokk',
        'Insert table': 'Sett inn diagram',
        'Insert image': 'Sett inn bilde',
        Heading: 'Overskrift',
        'Image URL': 'Bildeadresse',
        'Select image file': 'Velg bildefil',
        'Choose a file': 'Velg en fil',
        'No file': 'Ingen fil',
        Description: 'Beskrivelse',
        OK: 'OK',
        More: 'Mer',
        Cancel: 'Angre',
        File: 'Fil',
        URL: 'URL',
        'Link text': 'Lenketekst',
        'Add row to up': 'Legg til rad ovenfor',
        'Add row to down': 'Legg til rad nedenfor',
        'Add column to left': 'Legg til kolonne til venstre',
        'Add column to right': 'Legg til kolonne til høyre',
        'Remove row': 'Fjern rad',
        'Remove column': 'Fjern kolonne',
        'Align column to left': 'Venstrejuster',
        'Align column to center': 'Sentrer',
        'Align column to right': 'Høyrejuster',
        'Remove table': 'Fjern diagram',
        'Would you like to paste as table?': 'Ønsker du å lime inn som en tabell?',
        'Text color': 'Tekstfarge',
        'Auto scroll enabled': 'Auto-scroll aktivert',
        'Auto scroll disabled': 'Auto-scroll deaktivert',
        'Choose language': 'Velg språk',
    });

**Comment by jwlee1108** [comment]
@AbstractionsAs 

Thank you for the issue. 
Why don't you contribute? Norwegian was created by the contribution of others.
