### ISSUE TITLE
이미지 사이즈 조절 문제

### ISSUE THREAD

**Issue by sonCream** [nhn/tui.editor#2554]
## Summary
에디터에 이미지 첨부 후 사이즈 조절이 가능한지요
## Screenshots
[사이즈 조절 전](https://drive.google.com/file/d/1xyU3twSBfaaDTTzf5ZrXI9rJtthHFDku/view?usp=sharing)
[사이즈 조절 후](https://drive.google.com/file/d/1LG2OitECSLfLCWcF1prOmyQxRbm_u9zt/view?usp=sharing)

## Version
3.0

## Additional context
첨부한 예시 이미지처럼 에디터에 이미지를 첨부한 후 사이즈를 조절할 수 있는 방법이 있는지 문의드려요.

**Comment by jwlee1108** [comment]
@sonCream Sorry, We don't support it.
