### ISSUE TITLE
How to make the text editor expandable?

### ISSUE THREAD

**Issue by larzuk91** [nhn/tui.editor#2595]
Hi, thanks for this excellent text editor. I've been trying to make the text area expandable, just like a regular text-area field (there is a little icon at the bottom right corner that you can drag), but I couldn't find anything related in the documentation. Is there a way to accomplish it? 

![image](https://user-images.githubusercontent.com/3451985/177846392-562356ba-583d-4412-9302-5e21d1da111f.png)

## Version
3.1.7

**Comment by senthil88** [comment]
TUI editor rendering in "div" element.
You can acheive similar behaviour for div element using css

#editor {
  resize: vertical;
  overflow: hidden;
}

**Comment by bocharsky-bw** [comment]
@senthil88 Thanks for this tip! Is there any chance to make it work out of the box with TUI editor? Or enable it with a special config option?

**Comment by larzuk91** [comment]
Thank you @senthil88 it works like a charm.! Didn't know it was so simple to make an element expandable. Also, Victor's suggestion sounds great
