### ISSUE TITLE
Upgrade peerDependencies

### ISSUE THREAD

**Issue by murdockcrc** [nhn/tui.editor#2665]
## Version
3.2.0

## Current Behavior
The code sets a peerDependency value of ^2.5.0 for `vue`.

![image](https://user-images.githubusercontent.com/4062119/183615067-3412d1c5-b281-40b0-8a26-c4ff414b1cd0.png)

We need to upgrade our vue package to 2.6.x and above, due to security vulnerabilities in other dependencies which has a higher version of vue as a peer dependency. 

## Expected Behavior
Upgrade the peer dependency so that it supports vue versions higher than 2.5.0 (~2.5.0 instead of ^2.5.0).

**Comment by whendon** [comment]
Im using @toast-ui/editor 3.2.0 in vue 2.6.11 successfully (with only one issue related to adding links)

What issue is it that you are facing exactly?

**Comment by murdockcrc** [comment]
Yes, there are no breaking changes that I can see, should work fine. Thx.
