### ISSUE TITLE
Self is not defined on Next JS with Next/Dynamic

### ISSUE THREAD

**Issue by dukesx** [nhn/tui.editor#2686]
## Describe the bug
I am using React Tui Editor on NextJS 12.2.5 and Loading it through Dynamic Import using next/dynamic package. When i navigate to the page using client routing of Next JS, it works but if i reload the same page manually (the page on which editor is , present),  the editor throws error of "self is not defined"
## To Reproduce
Steps to reproduce the behaviour:
1. Use Next JS 12.2.5]
2. Start Dev Server
3. Install TUI Editor @latest
4. Load the editor using next/dynamic
5. Reload the page using refresh button of browser
6. See the error

## Expected behavior
There should be no error

## Desktop (please complete the following information):
 - OS: MAC OS Montenery
 - Browser Microsoft Edge

I cant attach a codesandbox since i am working on a different branch than "main". If there is any other alternative which can use my branch to showcase the bug, will be glad to share it.

**Comment by joniel** [comment]
same error msg too... T_T: 
what's the problem? can you share your howto?

**Comment by dukesx** [comment]
There seemed to be issue with my node_modules and sudden verisoning in package.json. I use Vscode. So I just deleted the node modules folder, reinstalled everything. Then closed vscode window and folder and restarted. It started working again.
