### ISSUE TITLE
How to avoid pasting selected text from clipborad without images?

### ISSUE THREAD

**Issue by leochiu-a** [nhn/tui.editor#2719]
## Summary
How to avoid pasting selected text from clipborad without images? Because images pasted from clipborad will become base64 encoding, but generally do not want the database to store base64 encoding images, so I hope to avoid pasting text exclude images.

## Version

3.1.3

**Comment by jwlee1108** [comment]
I guess you could make an plugin for this issue. We did open plugin interface for keymap ([#2647](https://github.com/nhn/tui.editor/pull/2647))

**Comment by williamsun1993** [comment]
You can add a hook and it will be called the hook when uploading or pasting this image to OSS. This is my code.

```
// ~ template
// ==================

<Editor
  ref="toastuiEditor"
  height="500px"
  :options="editorOptions"
  initial-edit-type="markdown"
></Editor>

// ~ script
// ==================

export default {
  data() {
    ...
    return {
      editorOptions: {
        hooks: {
          addImageBlobHook: (blob, callback) => {
            // upload image
            UploadApi.uploadImg(blob).then(res => {
              callback(res.data.data, 'img')
            })
          },
        },
      },
    }
  },
}
```

**Comment by leochiu-a** [comment]
@williamsun1993 Thank you for your reply. It is seams like the way to upload image, but what I want is prevent pasting text from clipboard which maybe includes images. These images will be transformed to base64 encoding even doesn't trigger addImageBlobHook.
