### ISSUE TITLE
Error when setting initial value of Editor to a markdown link or html <a> tag

### ISSUE THREAD

**Issue by spencerpowell** [nhn/tui.editor#2730]
## Describe the bug
Error when setting initial value of Editor to a markdown link or html <a> tag. I'm using "@toast-ui/react-editor": "^3.2.0", and it is a Next.js application

Additionally when I click the "Insert Link" button from the Editor that functionality does not work for my production app.

## To Reproduce
1. Add code such as this 

```
const test = "<a>Testing</a>"
<Editor
        placeholder={props.placeholder}
        initialValue={test}
        previewStyle="vertical"
        height="400px"
        hideModeSwitch={true}
        initialEditType="wysiwyg"
        useCommandShortcut={true}
        onChange={handleChange}
        onBeforePreviewRender={handleBeforePreviewRender}
        onBeforeConvertWysiwygToMarkdown={handlBeforeConvertWysiwygToMarkdown}
        onCaretChange={handleCursorChange}
        onKeyup={handleKeyup}
        onKeydown={handleKeydown}
        ref={editorRef}
      />
```
3. Go to page with editor 

## Expected behavior
I should be able to add links to the wysiwyg editor

## Screenshots
<img width="737" alt="Screen Shot 2022-09-12 at 8 17 07 PM" src="https://user-images.githubusercontent.com/2447847/189780605-1800081f-6ed0-4fea-9190-626ca9219cff.png">
<img width="563" alt="Screen Shot 2022-09-12 at 8 17 34 PM" src="https://user-images.githubusercontent.com/2447847/189780608-b079a824-2cbc-4f99-b583-386dfca60580.png">

**Comment by spencerpowell** [comment]
I think this is related to https://github.com/nhn/tui.editor/pull/2729#pullrequestreview-1105989640

**Comment by jwlee1108** [comment]
@spencerpowell Sorry, We don't fully support SSR. It's our todos.

**Comment by spencerpowell** [comment]
@jwlee1108 This doesn't have to do with SSR.  It is related to this bug https://github.com/nhn/tui.editor/pull/2729#pullrequestreview-1105989640

https://github.com/nhn/tui.editor/issues/2687

Reverting to version  3.1.8 fixed the bug for me
```
"@toast-ui/editor": "3.1.8",
"@toast-ui/react-editor": "3.1.8",
```

**Comment by jwlee1108** [comment]
@spencerpowell We'll check it. Thank you for the issue.

**Comment by benderillo** [comment]
I have the same issue and it is not SSR. And I can reproduce it by simply running the editor with "markdown" as being default mode.
Then typing the `[text](https://google.com)` in the editor and switching tab to WYSIWYG mode. And  the same error pops up that the `getCustomAttrs` is not defined.

**Comment by benderillo** [comment]
@jwlee1108  안녕하세요!

Your codesandbox works fine but I created a sample repo that exposes the error.

It is a vanilla NextJS app that I added toast-ui react editor to.

Here is the shared workspace on codesandbox that you can open to see it running [codesandbox](https://codesandbox.io/p/github/benderillo/nextjs-toastui-editor/draft/wizardly-rain?import=true&file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A20%2C%22endLineNumber%22%3A26%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A25%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8420t8z000clojhe27zhf5a%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522cl8420wiu000x3b6ibt8d8ekq%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl8421473006y3b6i281znbom%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl84213oe00503b6ivwoe6ld7%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

And github repo: https://github.com/benderillo/nextjs-toastui-editor 

Steps:
1. Editor loads in markdown mode
2. type in [text](link)
3. Switch to wysiywg mode
4. Tada! Exception is thrown saying `getCustomAttrs` is not defined.

**Comment by jwlee1108** [comment]
@benderillo 

Thank you for doing your best for reproducing. When I checked, the function(`getCustomAttrs`) in the module wasn't connected properly when I bundled it. I haven't found the cause yet, but I'll check it whenever I can. Our team is currently working on several projects other than TOAST UI, so it is difficult to process them quickly. Please use the previous version that works.

**Comment by jwlee1108** [comment]
check [v3.2.1](https://github.com/nhn/tui.editor/releases/tag/editor%403.2.1) please, if you use react or vue wrapper, you need to use v3.2.2
