### ISSUE TITLE
怎么改变文字提示？(How to change the text prompt?)

### ISSUE THREAD

**Issue by hexiaochen666** [nhn/tui.editor#2731]
我现在有个海外版本的网站，想把提示改成英文，怎么改？（I now have an overseas version of the website. I want to change the prompts to English. How do I change them?）
![image](https://user-images.githubusercontent.com/52769073/189836401-315ee5e3-9c71-4c37-a2a2-adb6008011d3.png) false
![image](https://user-images.githubusercontent.com/52769073/189836454-6e3197ae-adac-4217-a432-9cdbdb2daacf.png) true

**Comment by jwlee1108** [comment]
@hexiaochen666 

Please check this [line](https://github.com/nhn/tui.editor/blob/master/apps/editor/src/ui/components/toolbar/imagePopupBody.ts#L151)
Can you show your language setting? This is our [example](https://nhn.github.io/tui.editor/latest/tutorial-example16-i18n)

**Comment by hexiaochen666** [comment]
> @hexiaochen666
> 
> Please check this [line](https://github.com/nhn/tui.editor/blob/master/apps/editor/src/ui/components/toolbar/imagePopupBody.ts#L151) Can you show your language setting? This is our [example](https://nhn.github.io/tui.editor/latest/tutorial-example16-i18n)
I use tui-editor,but no I18n.The version is 1.4

**Comment by jwlee1108** [comment]
@hexiaochen666 Are you using [tui 1.4](https://nhn.github.io/tui.editor/1.4.0/) now?

**Comment by hexiaochen666** [comment]
> 
yes.1.4.6

**Comment by hexiaochen666** [comment]
> @hexiaochen666 Are you using [tui 1.4](https://nhn.github.io/tui.editor/1.4.0/) now?
Is there any solution?

**Comment by jwlee1108** [comment]
@hexiaochen666 Sorry, Unfortunately, it is not customized ([ref](https://github.com/nhn/tui.editor/blob/1.4/src/js/ui/popupAddImage.js#L28)). I think you can fork this repository and modify the code ([example](https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/)). We have no plans to modify v1. Sorry.

**Comment by hexiaochen666** [comment]
> @hexiaochen666 Sorry, Unfortunately, it is not customized ([ref](https://github.com/nhn/tui.editor/blob/1.4/src/js/ui/popupAddImage.js#L28)). I think you can fork this repository and modify the code ([example](https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/)). We have no plans to modify v1. Sorry.

Thank you very much!
