### ISSUE TITLE
How to switch editor to viewer after clicking button?

### ISSUE THREAD

**Issue by chagadoll** [nhn/tui.editor#2734]
## Summary
I would like to switch editor mode to viewer mode after clicking a button. If ```props.mode``` changes, the html will show viewer mode and let user disable to edit. Now, I can only get the editor but not viewer after clicking the button. 
My code as below:

```
<template>
      <div :id="id"></div>
</template>
```
```
onMounted(() => {
    editor = new Editor.factory({
        el: document.querySelector(`#${props.id}`),
        height: "300px",
        initialEditType: 'wysiwyg',
        initialValue: 'text.value',
        viewer: isViewer.value,
        events: {
          change() {
            emit('update:modelValue', editor.getHTML())
          } 
        }
    })
})
watch(() => props.mode, (newVal) => {
   editor.reset()
})
```

## Version
3.1.10

**Comment by jwlee1108** [comment]
I guess you need to reload to create new instance from factory. please check this [code](https://github.com/nhn/tui.editor/blob/master/apps/editor/src/editor.ts#L57)
