### ISSUE TITLE
Unable to add text after table in WYSIWYG mode

### ISSUE THREAD

**Issue by tdittmar** [nhn/tui.editor#2735]
## Describe the bug
Then you insert a table at the end of your document, you can not append any text after that table or even place the cursor there.

## To Reproduce
1. [Go to Demo Page for WYSIWYG editor](https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-with-wysiwyg-mode)
2. Remove all content from the demo editor
3. Add a new table using the toolbar button
4. Try to place the cursor after the table/add text after the table
5. => Doesn't work

## Expected behavior
The user should be able to place the cursor behind the table to add more content.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome
 - Version: 105.0.5195.102

**Comment by jwlee1108** [comment]
That's right. I think it's one of the inconveniences of TOAST UI Editor. But it's quite tricky to fix because we have to consider the markdown spec as well. Now we have no plans or milestones to fix this.

**Comment by jwlee1108** [comment]
But, If you want to escape to table, you can use 'Mod+Enter'

**Comment by tdittmar** [comment]
Thanks for your response. The "Mod + Enter" (on Windows: Ctrl + Enter) hint did the trick. We're going to document this on our end internally, but maybe it might be a good idea to have it in the official documentation as well (at least I didn't find it at a first glance).
