### ISSUE TITLE
 After Header & List tag new line/break not working properly.

### ISSUE THREAD

**Issue by senthil88** [nhn/tui.editor#2736]
## Summary
As we can see it in the screeshot, If we enter trailing new lines are not considered. Is there any way to considering the trailing new lines into "br" tag?

```
customHTMLRenderer: {
            table(node, context) {
              return { type: 'openTag', tagName: 'table', classNames: ['table-responsive'], outerNewLine: true, attributes: node.attrs };
            },
            link(node, context) {
                return { type: 'openTag', tagName: 'a', attributes: {target: '_blank', rel: 'noopener'}, outerNewLine: true };
            },
            linebreak(node, context) {
                return { type: 'html', content: '<br>' };
            },
        };
```

`linebreak` event is not triggering consistently

## Screenshots
<img width="1060" alt="Screenshot 2022-09-19 at 12 19 05 PM" src="https://user-images.githubusercontent.com/1169064/190963129-9b449d81-fc3d-4e73-b5a9-68ddf50442f4.png">

## Version
All version

## Additional context
N/A

**Comment by jwlee1108** [comment]
@senthil88 You can type `<br/>` directly in markdown editing area. 

```text
abcd
<br />
<br />
cdef
<br />
<br />
xyz
```
