### ISSUE TITLE
Typo in react-editor README.md file

### ISSUE THREAD

**Issue by D0Dam** [nhn/tui.editor#2743]
## Describe the bug

There is a typo in the README.md file.

## To Reproduce

The typo is in the code written in the 'Instance Methods' of 'Usage'.
<img width="731" alt="스크린샷 2022-09-20 오전 11 48 42" src="https://user-images.githubusercontent.com/51052049/191160956-d597f2ad-dc9d-4573-b3f6-faeb0da975d5.png">

handleClick function is wrong, It must be change like this.
```
  handleClick = () => {
   // type error!!
   // this.editorRef.current.getInstance().exec('Bold'); 
   // Change the first letter of 'Bold' to lowercase.
      this.editorRef.current.getInstance().exec('bold');
  };
```

Check console.log like this, we can see that '**bold**' is defined.
```
const handleClick = () => {
console.log(editorRef.current.getInstance().commandManager.wwCommands);
  };
```

<img width="551" alt="스크린샷 2022-09-20 오후 12 34 52" src="https://user-images.githubusercontent.com/51052049/191162343-5205b2f8-d655-4273-ab59-0dd2b0d22f57.png">

## Desktop (please complete the following information):
 - OS: iOS
 - Browser: chrome
 - Version: 22

**Comment by jwlee1108** [comment]
@D0Dam Thank you for the issue. I'll fix it later. Are you willing to contribute to fix it?

**Comment by D0Dam** [comment]
> @D0Dam Thank you for the issue. I'll fix it later. Are you willing to contribute to fix it?

@jwlee1108
Oh! Yes, I willing to contribute to that. Thank you for accepting issue.
And If I want to contribute, do I have to send PR?

**Comment by jwlee1108** [comment]
@D0Dam Yes. I want you to follow the template when you open the PR. Our team is busy with other projects these days, so I can't check it right away, but I'll check it as soon as possible.

**Comment by D0Dam** [comment]
Thank you for your explanation. I will send the PR according to the template as soon as possible.

**Comment by D0Dam** [comment]
Here is opened PR : https://github.com/nhn/tui.editor/pull/2746

**Comment by jwlee1108** [comment]
@D0Dam It merged. Thanks.
