### ISSUE TITLE
React.js - Error - options.el is undefined

### ISSUE THREAD

**Issue by dit-j** [nhn/tui.editor#2765]
## Describe the bug
React.js - Error - options.el is undefined

> Uncaught TypeError: options.el is undefined
>     ToastUIEditorCore index.js:22327
>     ToastUIEditor index.js:25719
>     React 14
> index.js:22327
> Uncaught DOMException: Node.removeChild: The node to be removed is not a child of this node

## To Reproduce

```
import '@toast-ui/editor/dist/toastui-editor.css';
import Editor from '@toast-ui/editor';

...

<div id={"text-editor"}>
    <Editor 
        height={'600px'}
        initialEditType="wysiwyg"
    />
</div>
```

## versions

```
    "@toast-ui/editor": "^3.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
```

## Expected behavior
...

**Comment by dit-j** [comment]
I see. I have to use @toast-ui/react-editor.

maybe you can add this information in the doc: https://github.com/nhn/tui.editor/blob/master/docs/en/getting-started.md

**Comment by jwlee1108** [comment]
Thanks.
