### ISSUE TITLE
Incompatible with Vue 3.2?

### ISSUE THREAD

**Issue by CreativeWarlock** [nhn/tui.editor#2768]
When executing
`npm install --save @toast-ui/vue-editor`

I receive the following error:

`npm ERR! While resolving: gts@0.1.0
npm ERR! Found: vue@3.2.40
npm ERR! node_modules/vue
npm ERR!   vue@"^3.2.13" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.5.0" from @toast-ui/vue-editor@3.2.2
npm ERR! node_modules/@toast-ui/vue-editor
npm ERR!   @toast-ui/vue-editor@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

Is toaster-ui not compatible with Vue 3.2.x or is it just me missing something? I ask because I saw other issues here where people reported bugs when using Vue3 which lead me to the conclusion it would work with it.

Do you guys plan to update this editor to Vue 3.2.x?

**Comment by jwlee1108** [comment]
We haven't considered the Vue 3 environment yet with @toast-ui/vue-editor. 
We'll do it later, but we don't have a milestone yet. It's because I'm participating in various projects other than this.
I think it would be better if you put @toast-ui/editor on Vue 3 yourself.
