### ISSUE TITLE
src is trimmed from img tag when URL is prefixed with "blob:" since 3.1.1

### ISSUE THREAD

**Issue by mfuruskog** [nhn/tui.editor#2772]
## Describe the bug
We are using [createObjectUrl](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) to prepare links for images that the user have uploaded in our ToastUI editor. The URL will then be prefixed by `blob:` like `blob:http://<imageurl>`. In the preview however (and also using Viewer), the `src` property is trimmed from the `img` tag. This only happens from version `3.1.1` on onward, so we must currently remain on `3.1.0`.. 

## To Reproduce
This can easily be reproduced by testing the editor in your docs.
1. Go to https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic
2. Change the image markdown to `![image](blob:https://uicdn.toast.com/toastui/img/tui-editor-bi.png)`
3. Inspect the image element in the preview
4. See that the `src` property is **missing**

## Expected behavior
Like above, but using the 3.1.0 editor
1. Go to https://nhn.github.io/tui.editor/3.1.0/tutorial-example01-editor-basic
2. Change the image markdown to `![image](blob:https://uicdn.toast.com/toastui/img/tui-editor-bi.png)`
3. Inspect the image element in the preview
4. See that the `src` property is **present**

## Desktop (please complete the following information):
 - OS: macOS 12.5.1
 - Browser: Tested and reproduced on Chrome and Safari
 - Version: Reproduced using various ToastUI versions from 3.1.1 to 3.2.1

**Comment by jwlee1108** [comment]
@mfuruskog 
I want to help you, but I don't have enough time to check this issue because of another project. If you want to solve the problem quickly, you can fork it with your Repo and change it yourself.

**Comment by mfuruskog** [comment]
I solved it by just using my own DOMPurify sanitizer, so I'll close this.
