### ISSUE TITLE
are there any heading tag restrictions?

### ISSUE THREAD

**Issue by taylous** [nhn/tui.editor#2794]
## Summary
after debugging, HTML is generated as `<h${entered level value}>...</h..>` according to the number of "#" in the markdown editor.

however, when the number of **"#" became 5**, the "h" tag no longer appeared and was replaced with a "p" tag.
it's in a limited state, is there any way I can fix it?... 🤔 i want to use it `infinity`.

> Of course, it's not really infinity. At most, up to level 10. 😅

**Comment by jwlee1108** [comment]
@taylous

Thank you for the issue.
TOAST UI Editor complies with commonmark specifications as much as possible. According to the [atxHeading](https://spec.commonmark.org/0.30/#atx-heading) specification, it is converting from h1 to h6.

And from more than six, define that it is no longer a heading.

What I don't understand is that it will be converted from h5 to <p>, so could you share the sample text?

**Comment by taylous** [comment]
@jwlee1108 

Oops... my mistake 😥

i did the wrong test.
It is converted normally up to h6. 😀

thank you for caring me
