### ISSUE TITLE
Chart & Video vanish in WYSIWYG

### ISSUE THREAD

**Issue by av1659** [nhn/tui.editor#286]
I have implemented the Youtube extension as described [here](https://github.com/nhnent/tui.editor/blob/master/docs/writing-your-own-extension.md)

The video shows up and plays in the preview of the editor. However, the video shows up only as a code block in the Viewer and in the WYSIWYG view.

The same is even true with the prebuilt chart extension! Any way to fix this issue?

**Comment by oasif** [comment]
Same problem here. even in the demo site

**Comment by sohee-lee7** [comment]
Codeblock preview is not supported in wysiwyg. The wysiwyg is also editor so need to edit content of codeblock. So rendering result of codeblock can not be shown in wysiwyg.

**Comment by h0gar** [comment]
The codeblock could be edited in the wysiwyg via the "Editor" button.
