### ISSUE TITLE
Customize rendered HTML

### ISSUE THREAD

**Issue by JayCallas** [nhn/tui.editor#289]
How can we hook into the MD to HTML rendering so we can customize the HTML. In my case I need to add classes (for example, to `table` element) and tweak code block rendering.

**Comment by kyuwoo-choi** [comment]
you can get a markdown-it using this
https://github.com/nhnent/tui.editor/blob/fcfdf0946db8b83b4d0d74f3a10ce35ae204b10c/src/js/editor.js#L850

and customize as you want. see what we're doing
https://github.com/nhnent/tui.editor/blob/fcfdf0946db8b83b4d0d74f3a10ce35ae204b10c/src/js/convertor.js#L37-L64

be aware. modifying the markdown-it can make serious effects.

**Comment by sohee-lee7** [comment]
@JayCallas I'd like to get feedback on how you tried. After you customized markdownIt, did you have any other problems with Wysiwyg?
