### ISSUE TITLE
Is it possible to disable certain shortcuts?

### ISSUE THREAD

**Issue by reynirf** [nhn/tui.editor#2975]
## Summary
Icelandic keyboards write the @ character using altKey+Q. That combination activates the "blockquote" in the tui.editor and ignores the @. I've tried disabling the blockquote from the toolbar, but the shortcut is still enabled. I've dug into the documentation but I'm yet to find a way to do this. I tried disabling "all" shortcuts, but then the cmd+z (undo) stopped working for example.

Is there any way I can manipulate this functionality? Either by disabling certain shortcuts or by preventing the blockquote from bein g emitted. Or by disabling shortcuts if options from the toolbar are not visible.

## Screenshots
<img width="518" alt="Screenshot 2023-03-16 at 10 12 12" src="https://user-images.githubusercontent.com/11130271/225585448-ba6fd174-2a66-4951-b731-6388197f5672.png">

## Version
@toast-ui/editor - 3.1.8

**Comment by AlexAndBear** [comment]
@reynirf Did you find a solution to that ?

**Comment by reynirf** [comment]
I don't remember exactly, I think I just forked the project and removed the shortcut manually.

See the relevant commit:
https://github.com/reynirf/tui.editor/commit/2aaed8c97fb1cd7d76e219d6623a147fd0448455

**Comment by reynirf** [comment]
> @reynirf Did you find a solution to that ?

I don't remember exactly, I think I just forked the project and removed the shortcut manually.

See the relevant commit:
https://github.com/reynirf/tui.editor/commit/2aaed8c97fb1cd7d76e219d6623a147fd0448455
