### ISSUE TITLE
How to prevent selecting base 64 code when pasting image?

### ISSUE THREAD

**Issue by taylous** [nhn/tui.editor#2982]
## Summary
how to prevent selecting base 64 code when pasting image into editor?

## Version
- react: 17.0.2
- @toast-ui/react-editor: 3.2.3

## Additional context

hello?

as you know, images are base64 encoded when copied and pasted.
since the value is very long, usually save the image to the server and get the url.

**But in my case,** company policy doesn't allow me to store images on the server.
> this means that the base64 code is exposed to the editor as it is.

so, **`i want to prevent the user from typing "enter" or any character in the base64 code.`**
> i gave options such as "pointer-events: none" and "user-select: none" to the css, but they didn't apply.

Is there any good way?

**Comment by taylous** [comment]
i solved it

**Comment by magimenon** [comment]
@taylous , how did you solved ?
