### ISSUE TITLE
Print rendered output as PDF

### ISSUE THREAD

**Issue by rickywu** [nhn/tui.editor#303]
I want to print the WYSIWYG result as pdf use browser print as pdf function, 

Preview#getHTML can get html result, but how can I call browser print function?

**Comment by ashutoshsaboo** [comment]
Hi, seeing a few commits above for this request. Was it shipped or what's the status of this currently? @js87zz @seonim-ryu @sohee-lee7 @kyuwoo-choi

**Comment by js87zz** [comment]
@ashutoshsaboo 
We don't have any plan for this feature yet.

**Comment by fkdp06** [comment]
I think you can read this: https://dev.to/covydev/designing-html-pages-for-printing-2jnj

It must be very easy to add some basic CSS which would result in the printable version of the md document.
