### ISSUE TITLE
Paste string with &lt;

### ISSUE THREAD

**Issue by Shadowz3n** [nhn/tui.editor#3035]
## Describe the bug
Processing too high, crashing the window when paste a string starting with "<something ... bla bla bla"

## To Reproduce
Paste this text on WYSIWYG editor:

Lorem Ipsum <ou = is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with deskto

**Comment by okeefm** [comment]
We're seeing this issue as well

**Comment by Shadowz3n** [comment]
Thanks!!
