### ISSUE TITLE
self is not defined (vue3 + nuxt3)

### ISSUE THREAD

**Issue by snowdream** [nhn/tui.editor#3188]
## Describe the bug
I want to import tui editor into my project(vue3 + nuxt3),but failed.

errors:
self is not defined

## To Reproduce
1. import
```
npm install --save @toast-ui/vue-editor
```
2. define componet

```
<template>
  <editor
    :initial-value="editorText"
    :options="defaultEditorOptions"
    height="500px"
    initial-edit-type="wysiwyg"
    preview-style="vertical"
  />
</template>

<script setup lang="ts">
import { reactive, ref, onMounted, onUnmounted, nextTick } from 'vue'

import '@toast-ui/editor/dist/toastui-editor.css'

import { Editor } from '@toast-ui/vue-editor'

const editorText = ref('This is initialValue.')

const defaultEditorOptions = reactive({
  minHeight: '200px',
  language: 'en-US',
  useCommandShortcut: true,
  usageStatistics: true,
  hideModeSwitch: false,
  toolbarItems: [
    ['heading', 'bold', 'italic', 'strike'],
    ['hr', 'quote'],
    ['ul', 'ol', 'task', 'indent', 'outdent'],
    ['table', 'image', 'link'],
    ['code', 'codeblock'],
    ['scrollSync']
  ]
})
</script>
```

4. build and run

## Expected behavior
It works！

## Screenshots
![image](https://github.com/nhn/tui.editor/assets/737958/09f7b089-0125-4782-a8ff-88affe2c2055)

## Desktop (please complete the following information):
 - OS: [e.g. Windows 10] Windows 10 
 - Browser [e.g. chrome, safari] Microsoft Edge
 - Version [e.g. 22] Microsoft Edge
版本 115.0.1901.188 (正式版本) (64 位)

**Comment by XiaoRongwen** [comment]
博主解决了么

**Comment by snowdream** [comment]
https://github.com/snowdreamtech/vue-tui-editor
