### ISSUE TITLE
Insert list in the table.(5MD)

### ISSUE THREAD

**Issue by ikan88** [nhn/tui.editor#321]
Hello. Thanks for your hardworking.
It would be great if it can insert list in the table.

**Comment by sohee-lee7** [comment]
tui.editor follows GFM(https://github.github.com/gfm/#table), so can't insert list in the table.

**Comment by ikan88** [comment]
Thanks for answering my question. 
Is there no way to insert list in the table until GFM specification changed?

**Comment by cybaek** [comment]
@ikan88 
Among the various specifications of markdown, there is no implementation that allows lists in the table.
