### ISSUE TITLE
remove highlight.js

### ISSUE THREAD

**Issue by PanJiaChen** [nhn/tui.editor#335]
[link](https://bundlephobia.com/result?p=tui-editor)

![image](https://user-images.githubusercontent.com/8121621/49197746-0a35aa80-f3cb-11e8-802b-1f5e49dee06d.png)

You can see that the size of the highlight.js is very large, but I don't really need to use the highlight.js. How can I remove it?

**Comment by fjanevski** [comment]
Highlight.js also exceed the call stack size when building Angular project with the TUI editor. One of the main cause as I have seen is the string concatenation they are using for different programming languages (as for SQL syntax, they are using string concatenation of 109 lines of text - https://github.com/highlightjs/highlight.js/blob/master/src/languages/sql.js#L23.

**Comment by sohee-lee7** [comment]
Currently, highlight.js can not be removed. We will consider the option of choosing highlight.js later.

**Comment by seonim-ryu** [comment]
In v2.0, hightlight.js has been separated into the [code-syntax-highlight](https://github.com/nhn/tui.editor/tree/master/plugins/code-syntax-highlight) plugin. So this issue is closed.
