### ISSUE TITLE
alttext as addImageBlobHook parameter

### ISSUE THREAD

**Issue by m4sk1n** [nhn/tui.editor#349]
I think addImageBlobHook should receive parameter with alttext, so we could be able to call the callback with alttext instead of defaulting it, not sure why adding a hook makes tui.editor ignore the alttext…

**Comment by sohee-lee7** [comment]
@m4sk1n I investigate about this issue. 
```js
editor.on('addImageBlobHook', function(blob, callback) {
   const reader = new FileReader();
   reader.onload = event => {
      callback(event.target.result, 'custom alt text')
   };
  reader.readAsDataURL(blob);
});
```
I think that overriding alt text could be possible but it does not work.

https://github.com/nhnent/tui.editor/blob/a883a3550efc969488ceef49a5cc5e605e06d459/src/js/ui/popupAddImage.js#L133

When choose alt text, always use default text that is file name.
So I think if alt text is passed by callback, replace alt text.
