### ISSUE TITLE
data-tomark-pass attr only work once. (3MD)

### ISSUE THREAD

**Issue by LinFeng1997** [nhn/tui.editor#366]
## Version

1.2.6
## Test Environment

Chorme,Mac OS
## Current Behavior

put the code in editor:
```js
<table data-tomark-pass><tbody><tr><td>123</td></tr><tr><td>123</td></tr><tr><td>123</td></tr><tr><td>123</td></tr></tbody></table>
```
![image](https://user-images.githubusercontent.com/16188742/51180825-7da46480-1904-11e9-951c-cb47595e07c2.png)

change mode from markdown to wysiwyg:
![image](https://user-images.githubusercontent.com/16188742/51180847-872dcc80-1904-11e9-9f9d-ee3738ca99ef.png)

then back to markdown mode:
![image](https://user-images.githubusercontent.com/16188742/51180882-990f6f80-1904-11e9-9797-edbc1109f2e3.png)

## Expected Behavior

data-tomark-pass attribute never be remove.

**Comment by sohee-lee7** [comment]
@LinFeng1997 Sorry for late reply. We tried to maintain html tag that is inserted in markdown. So if the tag maintain while change mode, you don't need to use `data-tomark-pass`. Also I recommend not to use `data-tomark-pass` because it is for internal implement.
