### ISSUE TITLE
Togglable tasks in WYSIWYG

### ISSUE THREAD

**Issue by MCGods** [nhn/tui.editor#388]
## Version
v1.3.0

## Test Environment
Windows 10, Firefox & Chrome

## Current Behavior
Tasks can be toggle in wysiwyg mode.

Tasks correctly keep state in markdown preview.

## Expected Behavior
The task to stay in one state

**Comment by sohee-lee7** [comment]
@MCGods I think markdown preview only needs to function as a preview. It is needed more discussion.

**Comment by MCGods** [comment]
The markdown preview works as expected - the tasks cannot be toggled.
However in WYSIWYG mode the task can be toggled which is not what I expect

**Comment by sohee-lee7** [comment]
@MCGods Wysiwyg mode is also editor so the task can be modified in Wysiwyg. Therefore the task should be toggled in Wysiwyg.
