### ISSUE TITLE
Unexpected new table appears

### ISSUE THREAD

**Issue by vadamk** [nhn/tui.editor#394]
## Version:
1.3.0
## Test Environment:
Mac OS Mojave 10.14.2, Chrome 72.0.3626.96
## Current Behavior
  1. I am creating table in the editor ( WYSIWYG mode ).
  2. Add value to any cell
  3. Highlight this text and copy (cmd+c)
  4. Go to other cell and paste (cmd+v)
  
 **Result**: Unexpected new table appears.
 
![image](https://user-images.githubusercontent.com/20296237/52656542-46bf6f80-2eff-11e9-8354-e96e63a8ea46.png)

## Expected Behavior

  ..Same steps 1-4
  
 **Result**: When we pasted value it should insert to another cell.

![image](https://user-images.githubusercontent.com/20296237/52657041-673bf980-2f00-11e9-837b-d7ac0e7f1c58.png)

**Comment by sohee-lee7** [comment]
@vadamk This issue is a duplicate issue (#365). #365 issue was fixed v1.3.1. Please check again using v1.3.1.

**Comment by sohee-lee7** [comment]
This issue was fixed so close it.
