### ISSUE TITLE
Feature request: Allow typing markdown in WYSIWYG mode

### ISSUE THREAD

**Issue by koliyo** [nhn/tui.editor#41]
It is very powerful to be able to type markdown directly in the WYSIWYG mode. Examples of such editors:
- http://typora.io/
- https://paper.dropbox.com/

**Comment by kyuwoo-choi** [comment]
May be or may be not as It already has a markdown mode.
feel free to discuss about it more here.

**Comment by CosmoMyzrailGorynych** [comment]
It is always quicker to write `###` then to navigate to a tiny button on a toolbar and find a needed heading style. Other codes are better at writing too.

If you aim to 'productivity', it is a must-have feature, imho.
