### ISSUE TITLE
Reduce size of hightlight.js

### ISSUE THREAD

**Issue by fzlee** [nhn/tui.editor#415]
## Version
1.3.1

## Current Behavior

`require('hightlightjs')` will import over more than 150 language js files, and which will finally results in a hugs js bundle, most of them are not commonly used though.

Recently I was working on a project, and I tried to minimize the build size.
I modified `hightlight.js/index.js` to selectively enable 5 most used languages, and here is the comparison:

| |stat size | parsed size| gzipped size |
|---|---|---|---|
|require('hightlightjs')|3.07MB|1.45MB|471.7KB|
| selectively enabled(5 languages) |2.22MB|845.25KB|251.72KB| 

Can we do something like
```js
editor  =Editor({
    languageSupport: ['all', 'javascript', 'java']
})
``` 
to choose language needed?

**Comment by sohee-lee7** [comment]
@fzlee That's good idea. We have plan to reduce the size of bundle file by optionally including highlight.js in the bundle. We consider your idea and this feature may be released version 2.0 or 1.4.

**Comment by sohee-lee7** [comment]
#335 similar issue.

**Comment by seonim-ryu** [comment]
In v2.0, hightlight.js has been separated into the [code-syntax-highlight plugin](https://github.com/nhn/tui.editor/tree/master/plugins/code-syntax-highlight). So this issue is closed.
