### ISSUE TITLE
Markdown-it attributes with wysiwyg editor doesn't add attributes

### ISSUE THREAD

**Issue by suomiton** [nhn/tui.editor#417]
## Version
1.3.1

## Test Environment
Google Chrome 72.0.3626.119, Windows 10, Asp.Net MVC Razor page, Parcel bundler JS-component

## Current Behavior
We are trying to add markdown-it-attr extension to our editor to support HTML element attributes. It works in the markdown editor now. The only issue we have with it is that need to support Wysiwyg editors in our app and the plugin does not go well with that. Example below

In markdown editor the following ```# Title {.section-title}``` translates correctly to 
```<h1 class="section-title">Title</h1>``` but when switched to Wysiwyg editor it shows ```Title {.section-title}``` so the attribute part is rendered raw. Should it work like this? Is there a way we could fix this? I tried to create a custom converter for this but it turned out to quite a burden. 

This is how we add markdownItAttrs plugin. 
```js
const markdownItAttrs = require("markdown-it-attrs");
const tuiEditor = require("tui-editor");
tuiEditor.markdownitHighlight.use(markdownItAttrs);
```

## Expected Behavior
I would expect Wysiwyg render the attributes to HTML and not display the markdown code for them.

Cheers!

**Comment by sohee-lee7** [comment]
@suomiton Currently there is no way to not display markdown code in Wysiwyg. When use markdown extension, I'm sorry to not support every case. 

In this cause, you can use 'wysiwygSetValueAfter' event. This event occur when convert to Wysiwyg from markdown. So when this event occur, you can remove `{.section-title}` in Wysiwyg. For removing `{.section-title}`, you need a root element of Wysiwyg. You can obtain Wysiwyg instance by calling `getSquire` of editor instance API and then get the root element by `getRoot` Squire instance API. I hope this method will help you. 

If you have a problem, please leave a question or suggest a more comfortable one. Currently, I am thinking about making API that is more convenient for this situation.
