### ISSUE TITLE
Support Underline in tui.editor

### ISSUE THREAD

**Issue by leowujs** [nhn/tui.editor#422]
Just want to say if we can support underline in the editor, that would be great

**Comment by rwlaschin** [comment]
This seems like a standard editor feature.  Please add ...

**Comment by masoudtahmasebi93** [comment]
Sorry for reopening this issue, is there any activity on this issue? if not, can you help me in the best direction for implementing this feature?

**Comment by C-likethis123** [comment]
@masoudtahmasebi93 I have a custom fork that implements the underline feature, but I am thinking of refactoring this into a plugin. Perhaps we can discuss further about how to refactor it into a plugin? 
For your reference, this is the PR for the code that implements the underline feature in my custom fork: https://github.com/C-likethis123/tui.editor/pull/1

**Comment by masoudtahmasebi93** [comment]
> @masoudtahmasebi93 I have a custom fork that implements the underline feature, but I am thinking of refactoring this into a plugin. Perhaps we can discuss further about how to refactor it into a plugin?
> For your reference, this is the PR for the code that implements the underline feature in my custom fork: [C-likethis123#1](https://github.com/C-likethis123/tui.editor/pull/1)

Thank you so much, if we could make it a plugin it would be fantastic and handy. How can I help?

**Comment by C-likethis123** [comment]
@masoudtahmasebi93 I have created a separate repository so we can discuss on this plugin: https://github.com/C-likethis123/nhn-underline-plugin

I've included some resources in there that might be useful to you. Looking forward to working together!

**Comment by azmeuk** [comment]
@js87zz This seems a legit feature request to me. Would you consider to reopen the ticket?

**Comment by livevsonline** [comment]
bump
