### ISSUE TITLE
Suggestion: Plugin for Visual Studio Code

### ISSUE THREAD

**Issue by FSharpCSharp** [nhn/tui.editor#44]
The WYSIWYG editor is really great. This helps a lot of people who are used to creating texts visually.

For exactly this reason, it would be great if there was a plugin for Visual Studio code for this editor. Since this is also completely written in type and JavaScript, this should not be a big act. But I think this would help a lot of people to create Markdown documents in the future.

**Comment by de1ck** [comment]
good idea

**Comment by kyuwoo-choi** [comment]
I really have no idea what should be done to make VSCode extension.
If anyone have experience creating VSCode extensions, please leave a comment.

**Comment by ryanmcalister** [comment]
see https://marketplace.visualstudio.com/items?itemName=ryanmcalister.Unotes

**Comment by sohee-lee7** [comment]
@ryanmcalister Thank you for implement VSCode extension. I inserted UNOTES link at README. :)
