### ISSUE TITLE
yarn add error on dependency eve@git://github.com/adobe-webplatform/eve.git#eef80ed

### ISSUE THREAD

**Issue by thiagozb** [nhn/tui.editor#446]
## Test Environment

Windows 10
Yarn v. 1.15.2
node v. 11.8.0
npm v. 6.5.0

## Current Behavior

When I try to install the tui-editor v. 1.3.3 package, yarn can not resolve the dependency of the package eve@git://github.com/adobe-webplatform/eve.git#eef80ed. I saw that the dependency is locked in a commit of 01/30/2013, is this correct? I tested it on other computers and the error also occurs.

```js
yarn add tui-editor
```

## Expected Behavior

The expected behavior is that the installation is complete. 

Thanks for listening.

**Comment by sohee-lee7** [comment]
@thiagozb I try to install the tui-editor by yarn but there is not error. I need more information about the error you that happened to you. Currently tui-editor use `tui-chart` for chart extension and `tui-chart` has dependency `raphael` that use `eve`. It would also be a good clue to make sure that there are other modules in your project that use `raphael` or `eve`. If you use `npm ls ${module name}`, you can find which module use that.
![image](https://user-images.githubusercontent.com/42666492/54973651-18d84b00-4fd4-11e9-91f5-6da8604ad8e8.png)

**Comment by jippy89** [comment]
Hello, I had the same problem, however when I was installing `vue-element-admin`'s dependency. This thing came up. I have made an [issue](https://github.com/PanJiaChen/vue-element-admin/issues/1773) there, but apparently it's not from their app.
```
ERROR  Could not resolve eef80ed to a commit of git://github.com/adobe-webplatform/eve.git.
at resolveRefFromRefs  /home/jippy98/.nvm/versions/node/v10.15.3/pnpm-global/2/node_modules/.registry.npmjs.org/pnpm/3.0.1/node_modules/pnpm/lib/node_modules/@pnpm/git-resolver/lib/index.js:91  
at resolveRef          /home/jippy98/.nvm/versions/node/v10.15.3/pnpm-global/2/node_modules/.registry.npmjs.org/pnpm/3.0.1/node_modules/pnpm/lib/node_modules/@pnpm/git-resolver/lib/index.js:79  
at _tickCallback       internal/process/next_tick.js:68
```
When I was trying to do `npm ls eve`, this came up in my terminal:
```
vue-element-admin@3.10.0 /home/jippy98/git-repositories/templates/vue-element-admin
└── (empty)
```
Anything else should I provide?

**Comment by sohee-lee7** [comment]
@jippy89 If you use `npm install`, there is no problem. `pnpm` can not handle short hash. (https://github.com/pnpm/git-resolver/issues/15)
We have dependency `tui-chart` that has dependency `raphael` that has dependency `eve` by short hash (https://github.com/nhnent/raphael/blob/master/package.json#L20)
I recommend using `npm install`

**Comment by jippy89** [comment]
Thanks! a lot @sohee-lee7! I've just managed to tried it today. And it works!

**Comment by Gilles-GitHub** [comment]
I have the same issue !
I did made a `npm install` but got the same error.
The pb comes from the git protocol: `https://github.com/DmitryBaranovskiy/raphael/issues/993`

Using `git config --global url."https://".insteadOf git://` solved the problem on my local environment but I still got the issue when I need to build my app on a distant server which don't allow me to modify the git config :(

**Comment by gebin** [comment]
```
yarn add git://github.com/adobe-webplatform/eve.git#eef80ed
yarn add tui-editor
```
It is work. But I don't think is good solution.

**Comment by onrdmr** [comment]
```
yarn cache clean
yarn set version stable

```
This make my yarn latest version i have same error. Giving commit hash isn't enough. i made

```
yarn add eve@git://github.com/adobe-webplatform/eve.git#eef80ed8d188423c2272746fb8ae5cc8dad84cb1
yarn add tui-editor
```
