### ISSUE TITLE
Property initialValue not showing merged cells

### ISSUE THREAD

**Issue by NetDefender** [nhn/tui.editor#447]
## Version
1.3.3

## Test Environment

Opera / Google Chrome
Windows 10
## Current Behavior

First, thanks for the work done with the editor. The following is a problem that i faced when i tried to display a table.
If i load the following markdown with the table extension

```
| @cols=3:TITLE |
| :----- | --- | --- |
| AAA| @rows=2:BBB| CCC|
| DDD| EEE|
``` 
in the initialValue it displays incorrectly not merging the cells, but if i load later with the method *setMarkdown* then it displays correctly as showing in the following code:

```js

var md = $('#E').val(); // the previous markdown
var contenidoToastEditor = new tui.Editor({
                        el: document.getElementById('editor'),
                        language: 'es_ES',
                        previewStyle: 'vertical',
                        height: '400px',
                        initialEditType: 'wysiwyg',
                        initialValue: md,//<-- NOT SHOWING CORRECTLY
                        exts: ['table']
                    });
                    //IF I LOAD LATER IT WORKS
                    contenidoToastEditor.setMarkdown(md);
```
I send a capture of the problem:

![Test](https://user-images.githubusercontent.com/2451916/54871855-3383a780-4dbb-11e9-853a-c1b2c0299a75.PNG)

## Expected Behavior

If i set the property initialValue with merged cells then it must be displayed correctly.

**Comment by sohee-lee7** [comment]
@NetDefender Sorry for late replay. I can not reproduce this issue. http://nhnent.github.io/tui.editor/api/latest/tutorial-example07-table.html
This example is same condition that use table extension and initialValue. It works well.
If you still have the same problem, give me more detail information.
