### ISSUE TITLE
gfm table remove html tag and insert slash automatically

### ISSUE THREAD

**Issue by rickywu** [nhn/tui.editor#454]
I use pandoc's output which is gfm format table like this:

```
<table>
<tbody>
<tr class="odd">
<td><strong>要素</strong></td>
<td><strong>生成方式</strong></td>
<td><strong>说明</strong></td>
</tr>
<tr class="even">
<td>需求编号</td>
<td>自动生成</td>
<td>与xxx生成需求编号保持一致或产生对应关系，建议与xxx编号规则一致。</td>
</tr>
<tr class="odd">
<td>需求类别</td>
<td>下拉选择</td>
<td>选项：项目需求、系统维护需求</td>
</tr>
<tr class="even">
<td>需求模板</td>
<td>下拉选择</td>
<td><p>需求类别选择项目需求时，选项：业务原始需求、</p>
<p>建设需求书、业务需求书、需求规格说明书（项目）</p>
<p>需求类别选择任务需求时，选项：业务原始需求、需求规格说明书（系统维护）</p></td>
</tr>
<tr class="odd">
<td>需求名称</td>
<td>手输</td>
<td></td>
</tr>
<tr class="even">
<td>需求提出部门</td>
<td>选择</td>
<td>业务部门</td>
</tr>
<tr class="odd">
<td>需求负责人</td>
<td>手输</td>
<td>姓名、联系方式</td>
</tr>
<tr class="even">
<td>受理人</td>
<td>手输</td>
<td>业务条线、姓名、联系方式</td>
</tr>
</tbody>
</table>
```

The first time load from markdown mode render correct, but if I switch to visual mode and switch back to markdown mode, the html tag removed, then switch to visual mode and switch to markdown mode again, the table becomes:

```
\| **要素** \| **生成方式** \| **说明** \|  
\|  
\| 需求编号 \| 自动生成 \| 与xxx生成需求编号保持一致或产生对应关系，建议与xxx编号规则一致。 \|  
\| 需求类别 \| 下拉选择 \| 选项：项目需求、系统维护需求 \|  
\| 需求模板 \| 下拉选择 \| 需求类别选择项目需求时，选项：业务原始需求、

建设需求书、业务需求书、需求规格说明书（项目）

需求类别选择任务需求时，选项：业务原始需求、需求规格说明书（系统维护） \|

\| 需求名称 \| 手输 \| \|  
\| 需求提出部门 \| 选择 \| 业务部门 \|  
\| 需求负责人 \| 手输 \| 姓名、联系方式 \|  
\| 受理人 \| 手输 \| 业务条线、姓名、联系方式 \|
```

Is this pandoc's problem or both?

**Comment by sohee-lee7** [comment]
@rickywu Sorry for late reply. If you insert table using `<table>` in markdown, our editor change to markdown syntax while change mode. So if you want to maintain `<table>`, you could use `data-tomark-pass`. But there is a problem. #366 `data-tomark-pass` only work once. 😢 We plan to fix the problem about `data-tomark-pass` that maintain a html element.

**Comment by rickywu** [comment]
I use pandoc convert docx to markdown, if there is no heading row in the table, then the gfm markdown missing header element then will cause this problem:
<thead>
<tr class="header">
<th><strong>T1</strong></th>
<th><strong>T2</strong></th>
<th><strong>...</strong></th>
</tr>
</thead>

So I used one vba macro add heading row in docx or use python add header thread after convert to markdown
