### ISSUE TITLE
Custom Renderer is not working

### ISSUE THREAD

**Issue by LIFOsitory** [nhn/tui.editor#455]
## Version

1.3.3
## Test Environment

Whale Browser(Windows 10)

## Current Behavior

```js
const taskList = function(markdownit) {
    // your plugin codes here
};

tui.Editor.markdownItRenderer.use(taskList); 
```
![cusotmRendererUse](https://user-images.githubusercontent.com/26114165/55216409-0104ff00-5240-11e9-88dd-1e8327178aad.jpg)

[커스텀 렌더러](https://github.com/nhnent/tui.editor/wiki/Getting-Started-Korean#%EC%BB%A4%EC%8A%A4%ED%85%80-%EB%A0%8C%EB%8D%94%EB%9F%AC%EC%9D%98-%EC%A0%81%EC%9A%A9)의 예시가 전부 동작하지 않습니다.

## Expected Behavior

특정 태그나 스코프를 컨버팅 하지 못하게 커스텀 렌더러를 적용하고 싶습니다.

**Comment by sohee-lee7** [comment]
@LIFOsitory Sorry for late reply. API is wrong in Getting-Started-Korean wiki.
```
tui.Editor.markdownitHighlight.use(taskList); // for preview of markdown
tui.Editor.markdownit.use(taskList); // for wysiwyg
```
