### ISSUE TITLE
`addButton` function of toolbar can not add button in the end of toolbar

### ISSUE THREAD

**Issue by sohee-lee7** [nhn/tui.editor#458]
## Version
v1.3.3

## Test Environment
Chrome

## Current Behavior
`addButton` function of toolbar can not add button at the end of the toolbar

## Expected Behavior
It should be able to add a button at the end to the toolbar.

**Comment by seonim-ryu** [comment]
As `Button` class was removed, `addButton()` method was also removed. And replaced by `insertItem()` method.
