### ISSUE TITLE
Request moving list like Workflowy

### ISSUE THREAD

**Issue by kerlingcode** [nhn/tui.editor#461]
How about making lists as movable items in WYSIWYG mode, like Workflowy

So that moving something from a list to another will be easier comparing to copy/paste. It would be better to support multi-select, expand/collapse and zoom in/out. It can be added as extension.

**Comment by sohee-lee7** [comment]
It's a good idea. It can be implemented as an extension. But we can't afford to implement this. We wait for PR for this feature.
