### ISSUE TITLE
Support draw.io embeded in editor

### ISSUE THREAD

**Issue by rickywu** [nhn/tui.editor#462]
Can you please consider support embed [draw.io](https://github.com/jgraph/drawio) in iframe or as a plugin option

see this https://github.com/jgraph/drawio-html5

**Comment by rickywu** [comment]
Is that possible to support?

**Comment by seonim-ryu** [comment]
@rickywu 
I think It's hard to take the default option. Instead, the editor provides a [custom extension](https://nhn.github.io/tui.editor/latest/tutorial-example10-make-new-extension). How about using it?

**Comment by rickywu** [comment]
@seonim-ryu  Yes I already used this feature, if it's hard to take default option, then we can close it
