### ISSUE TITLE
`getHtml` converts a table to markdown

### ISSUE THREAD

**Issue by ParkSB** [nhn/tui.editor#463]
## Version

v1.3.3

## Test Environment

OSX, Firefox Developer Edition 67

## Current Behavior

I created an editor with [table extension](https://github.com/nhnent/tui.editor/wiki/Extensions#table) and set body of the editor to html string(`htmlContent`) containing table tags through `setHtml`. Finally, I got the content using `getHtml`.

```js
this.editor.setHtml(htmlContent);
return this.editor.getHtml();
```

Here is `htmlContent`:

```html
<table style="width:900px; border-collapse:collapse;">
  <tbody>
    <tr>
      <th style="border:1px solid black;">Header 1</th>
      <th style="border:1px solid black;">Header 2</th>
    </tr>
    <tr>
      <td style="border:1px solid black; padding:10px;">item 1-1</td>
      <td style="border:1px solid black; padding:10px;">item 2-1</td>
    </tr>
    <tr>
      <td style="border:1px solid black; padding:10px;">item 1-2</td>
      <td style="border:1px solid black; padding:10px;">item 2-2</td>
   </tr>
   </tbody>
</table>
```

I'd like to get an only html string, but `getHtml` returns a string including markdown and html both:

```html
<p>
  | Header 1 | Header 2 |<br>
  | item 1-1 | item 2-1 |<br>
  | item 1-2 | item 2-2 |
</p>
```

## Expected Behavior

`getHtml` should return only html string like this:

```html
<table>
  <thead>
    <tr>
      <th>Header 1</th>
      <th>Header 2</th>
    </tr>
  <thead>
  <tbody>
    <tr>
      <td>item 1-1</td>
      <td>item 2-1</td>
    </tr>
    <tr>
      <td>item 1-2</td>
      <td>item 2-2</td>
    </tr>
  </tbody>
</table>
```

**Comment by sohee-lee7** [comment]
@ParkSB Sorry for late reply. `getHtml` return html of current mode so when you use wysiwyg, `getHtml` return only html string. If you want to get only html regardless mode, you use api of our wysiwyg editor, Squire like this:
```js
editor.getSquire().getHTML();
```

**Comment by sohee-lee7** [comment]
@ParkSB I was guided wrong. `getHTML` return html that is rendered result of markdown. So `getHTML` don't return markdown syntax in the html. 
Your example code don't have `<thead>` in `htmlContent`. If `htmlContent` have  `<thead>`, `getHtml` return html string.

**Comment by ParkSB** [comment]
@sohee-lee7 Thank you :) It was my mistake.
