### ISSUE TITLE
how to rendering database content in toast ui editor

### ISSUE THREAD

**Issue by mingming38** [nhn/tui.editor#477]
## Version
TOAST UI Editor v1.3.3

## Test Environment

jsp , javascript

## Current Behavior
i'm developing bulletin boards using the toast-ui editor. When submit a form, the value of contents is stored in db in html format. 
I want to load the contents stored in html in the database, but I do not know how to bind it. If you know, please help me.

```js
// Write example code
// Article registration page
<script>
var frm = document.getElementById("writeform");
var formSubmitButton = document.querySelector("#save");
formSubmitButton.addEventListener('click', function() {
    var contents = document.querySelector("#content");
   document.getElementById("content").value = editor.getHtml();
   frm.submit();
});
</script>

// Article edit page
<div id=editSection></div>
<script class="code-js">
    var editor = new tui.Editor({
            el: document.querySelector('#editSection'),
            initialEditType: 'wysiwyg',
	    previewStyle: 'vertical',
	   height: '500px'
          initialValue: how to binding?
</script>
```

**Comment by sohee-lee7** [comment]
@mingming38 Sorry for late reply. I don't understand your question. 🙄 If you want to input content to editor, you can use `initialValue` or `setValue`.
