### ISSUE TITLE
Why don't you maintain your to-mark library as open source on github page of nhn ?

### ISSUE THREAD

**Issue by dragmove** [nhn/tui.editor#487]
## Version
1.4.0

## Test Environment
Chrome browser

## Current Behavior
This is a question about 'to-mark' library that you have been using in tui.editor.
Why don't you maintain your 'to-mark' library as open source on github page of nhn ?

## Expected Behavior
I'm looking forward to using unminified 'to-mark' library and seeing it on github page of nhn.

**Comment by sohee-lee7** [comment]
`to-mark` is already open source. https://github.com/nhn/to-mark

**Comment by dragmove** [comment]
Thanks millions for your kind comment. 
I couldn't find github url and detail description in this npm page. [https://www.npmjs.com/package/to-mark](https://www.npmjs.com/package/to-mark)

Would your 'to-mark' page of npm be updated soon?

**Comment by sohee-lee7** [comment]
We don't have a plan to write detail description. 😥
