### ISSUE TITLE
tags is changed when deleting heading contents

### ISSUE THREAD

**Issue by seong954t** [nhn/tui.editor#493]
## Version
tui-editor version 1.4.0

## Test Environment
Windows 10, Chrome Browser

## Current Behavior

There seems to be a problem using the heading of the tui editor.
현재 tui editor의 Heading을 사용하는데 문제가 있는것 같습니다.

### 1. When heading is first created, the tag is generated as shown below. (처음 Heading을 만들면 아래와 같이 태그가 생성됩니다.)
```html
<h1>
    <div>
        <br>
    </div>
</h1>
```
![screen_1](https://user-images.githubusercontent.com/19300604/57746606-dfd37180-770c-11e9-83c0-a3fc5b079523.PNG)

### 2. At this time, if you write inside the heading, the results are as follows: (이 때 Heading내부에 글을 작성하게되면, 아래와 같은 결과가 나오게 됩니다.)
```html
<h1>
    <div>가나다라</div>
</h1>
```
![screen_2](https://user-images.githubusercontent.com/19300604/57746675-35a81980-770d-11e9-80c5-5e7e23067e03.PNG)

### 3. However, if you erase the created text one by one with Backspace, the tag is generated as shown below. (그러나 작성된 글을 하나씩 Backspace로 지우게 되면 아래와 같이 태그가 생성됩니다.)
```html
<h1>
    <br>
</h1>
```
![screen_3](https://user-images.githubusercontent.com/19300604/57746725-71db7a00-770d-11e9-9ad1-3ada34a3bc33.PNG)

### 4. So if you write the contents in heading in that state, the tag will be created in the following form which is different from the one when you write an existing article (write the letters in the div tag). (그래서 해당 상태에서 Heading에 내용을 작성하게 되면 기존의 글을 작성할 때(div태그 내 글자가 작성)와 다른 아래와 같은 형태로 태그가 생성됩니다.)
```html
<h1>가나다라2</h1>
```
![screen_4](https://user-images.githubusercontent.com/19300604/57746756-946d9300-770d-11e9-9afa-fb5b1d9465e3.PNG)

## Expected Behavior
If all the characters are deleted in the tag,  I expect the following results. (해당 태그 내에서 글자를 모두 지웠을 경우에도 아래와 같은 결과가 나오길 기대합니다.)
```html
<h1>
    <div>
        <br>
    </div>
</h1>
```

However, the actual behavior results in the following:
```html
<h1>
    <br>
</h1>
```
In this case, the non-regular tags cause problems with the desired behavior and leave an issue. Please check and answer my opinion.
이러한 경우 규칙적이지 않은 태그들로 인해 원하고자 하는 동작에 문제가 발생하여 이슈를 남깁니다. 확인해주시고 저의 의견에 대한 답변 부탁드립니다.

**Comment by sohee-lee7** [comment]
이슈 관리 정책 상 이슈 제목과 본문을 영어로 번역하였습니다. 양해 부탁드립니다. 해당 이슈는 확인하였고, 분석 후 답변 드리겠습니다.

**Comment by seong954t** [comment]
tui에서 사용하는 Squire에서도 이와 유사한? 이슈가 있어서 등록을 해두었습니다.

해당 이슈는 <br>태그가 적절히 생성되지 않아 줄바꿈을 인식하는데 어려움이 있는 것입니다.
해당 이슈도 링크로 남겨두겠습니다.

https://github.com/neilj/Squire/issues/353

감사합니다.
