### ISSUE TITLE
BackSlash that inserted in wysiwyg disappear in markdown (2MD)

### ISSUE THREAD

**Issue by sohee-lee7** [nhn/tui.editor#501]
## Version
v1.4.0

## Test Environment
Chrome

## Current Behavior

``` text
/\/
'\'
"\"
(\_)
```

rendering in markdown like this

![image](https://user-images.githubusercontent.com/42666492/57851210-f2d46780-781a-11e9-956b-cfcf90481807.png)

## Expected Behavior

If backslash is inserted in Wysiwyg, it should not disappear.

**Comment by parthshah31** [comment]
On current latest (2.3.1). This issue still occurs on the latest version (2.3.1) and on the online demo. If I do:
```
foo\
bar
```
in WYSIWYG, and then switch to markdown and back to WYSIWYG it drops the `\`.
