### ISSUE TITLE
Redo is not work in table (Wysiwyg)

### ISSUE THREAD

**Issue by sohee-lee7** [nhn/tui.editor#503]
## Version
v.1.4.0

## Test Environment
Chrome

## Current Behavior

1. Write text in table
2. Copy the text
3. Paste the text in same cell or other cell
4. CMD(or Ctrl) + Z => undo
5. CMD(or Ctrl) + Shift + Z => redo

Text is not appear again in Step 5.

## Expected Behavior

The text should be appear when redo.

**Comment by seonim-ryu** [comment]
## Cause
Squire does not support the `undo` and `redo` action for each cell in the table. So, the editor's table manager clearly calls logic to save on undo stack of Squire. This logic is called when combined modifier key(e.g. `SHIFT+META+Z`) is pressed, so the `undo` and `redo` action in the table does not work correctly.
