### ISSUE TITLE
In Safari, list item is removed by backspace key when it has one character

### ISSUE THREAD

**Issue by sohee-lee7** [nhn/tui.editor#507]
## Version
v1.4.0

## Test Environment
Safari

## Current Behavior

![Screen Recording 2019-05-17 at 11 46 07 AM mov](https://user-images.githubusercontent.com/42666492/57899918-d3c8ea80-7899-11e9-979f-489ffef81f2b.gif)

List item is removed by backspace key when it has one character

## Expected Behavior

Should not remove list item.

**Comment by seonim-ryu** [comment]
Currently not reproduced. Close the issue.
