### ISSUE TITLE
switch from the editor to the viewer

### ISSUE THREAD

**Issue by nicolasvahidzein** [nhn/tui.editor#510]
Hello,

i loe your editor.

I had a question though, i don't see a variable to go from the viewer to the editor and vice versa.

Obviously we load the editor code because it contains the most but i don't see a a variable that would disable the toolbar and remove it. Can you please explain how it would be done aside from removing all the elements in the toolbar? It would leave a blank toolbar and people can still go in and delete the text. 

Thanks.

**Comment by sohee-lee7** [comment]
There is no way to switch from the editor to the viewer and vice versa. The editor and the viewer is independent component so we do not provide switching feature. Switching between the editor and the viewer is something that people using tui.editor should implement.
