### ISSUE TITLE
Usage with Rollup/ES Modules

### ISSUE THREAD

**Issue by KayakinKoder** [nhn/tui.editor#512]
TUI Editor looks fantastic. I'm wondering if anyone has gotten it successfully set up with Rollup/ES modules? We can't seem to get things bundled up correctly.  Should we be looking here for what packages we need to pull in: https://github.com/nhn/tui.editor/wiki/Getting-started-with-bower

Or is there any easier way? Thanks!

## Version
1.4.1

## Test Environment
Chrome latest, Windows latest

## Current Behavior
Can't import as ES module

```js
import Editor from 'tui-editor';
```

## Expected Behavior
Package is usable as an ES module

**Comment by sohee-lee7** [comment]
We provide a bundle file that has all dependency. That is `tui-editor-Editor-full`.
So if you import tui.editor like below, you can bundle by Rollup.
```js
import Editor from 'tui-editor/dist/tui-editor-Editor-full';
```
Please try this full file and let me know if it is bundle properly.

We need more analysis on this issue, but perhaps markdown-it seems to be the cause of the problem.

**Comment by sohee-lee7** [comment]
I find problems again. When bundling markdown-it, `rollup-plugin-json` is needed. And  `rollup-plugin-node-builtins` is needed.

Please try to insert those plugin in your rollup.config.js.
If you use those plugin, ES module import is possible.

**Comment by KayakinKoder** [comment]
Thanks for the quick response, actually with `import Editor from 'tui-editor/dist/tui-editor-Editor-full';` I don't seem to need the rollup plugins you mentioned, using the latest versions of all packages. I do remember seeing error messages about those plugins yesterday when I was trying to `import Editor from 'tui-editor';` though.

I use gulp + rollup, if you guys are ever interested in an additional section of your docs for rollup usage I could probably throw something together. Thanks for the great tool.
