### ISSUE TITLE
`<br>\n` rendering result is different between preview and wysiwyg

### ISSUE THREAD

**Issue by sohee-lee7** [nhn/tui.editor#528]
## Version
v1.4.1

## Test Environment
Chrome

## Current Behavior
![image](https://user-images.githubusercontent.com/42666492/59731469-39d1d480-9281-11e9-8e76-ab345ffa5107.png)

If a new line is inserted in table of Markdown, the rendering result is not changed.

![image](https://user-images.githubusercontent.com/42666492/59731495-52da8580-9281-11e9-910e-6c74689a0bca.png)

But when mode is changed to Wysiwyg, the new line makes a new row in the table.

## Expected Behavior

The preview of markdown and Wysiwyg should be same.

**Comment by seonim-ryu** [comment]
### <br> on table
|h1|h2|
|---|---|
| |a<br>b |
||c<br>
d|

### <br> on text
1
2

<br>
3

<br>
<br>
4

<br>
<br>
<br>
5
