### ISSUE TITLE
Who uses TOAST UI Editor?

### ISSUE THREAD

**Issue by sohee-lee7** [nhn/tui.editor#532]
### Do you use TOAST UI Editor in production? 
**Please let us know so we can add you to the [Used By](https://github.com/nhn/tui.editor#-used-by) section of the README!**

![Screen Shot 2019-06-07 at 3 34 31 PM](https://user-images.githubusercontent.com/42666492/59085782-ae7c4900-893a-11e9-9b65-8094abd536ab.png)

- If you want, feel free to edit the [README.md](https://github.com/nhn/tui.editor/blob/master/README.md) file directly and send a PR.
- Otherwise, Please provide 
  -  The official name of your company/brand/service
  -  The link to your official website
  -  (optional) The logo image

**Comment by dongsik-yoo** [comment]
[TOAST Dooray! - Collaboration Service (Project, Messenger, Mail, Calendar, Drive, Wiki, Contacts)](https://dooray.com)
