### ISSUE TITLE
Catch paste event on image

### ISSUE THREAD

**Issue by seb-saletes** [nhn/tui.editor#533]
Hi,

The paste event of an image is stopped by _processBlobItems. (tui-editor-Editor.js 2239)

What is the correct way to catch this event and handle the data ?

**Comment by seb-saletes** [comment]
What I've done so far is inserting my custom listener in the first position of the map in the eventManager.
Something like that:
```

var pasteListener = (event) => {
  var cbData = event.data.clipboardData;
  var types = cbData && cbData.types;

  if (types.includes("Files")) {
    event.preventDefault();
    event.stopPropagation();
   }
  };

tuiEditor.eventManager.events.set('paste', [pasteListener, ...tuiEditor.eventManager.events.get('paste')]);
```

**Comment by sohee-lee7** [comment]
In case pasting image, we need to emit `addImageBlobHook` hook and load image using FileReader.
Why you need `paste` event for image? If you give me for more detail information, I will check it.

**Comment by robertfausk** [comment]
I think it's following use case:
The user has image data in his clipboard and simply wants to insert an image in editor by pressing ctrl+v without using buttons of editor. This would result in a huge usability improvement.
