### ISSUE TITLE
Javascript file size

### ISSUE THREAD

**Issue by gregroyal** [nhn/tui.editor#534]
## Version
1.4.1

## Test Environment
All

## Current Behavior
Large file size

## Expected Behavior
Smaller optional footprint

## Comments

I think you guys have done a fantastic job with the features of the editor, however the filesize is very large. I'm trying to compress it down as much as possible. Currently I've manually included libraries and gotten it about half the size of your full minified js file of 1.3M

Any other tips? I'm only using the table plugin and also not using the preview mode for the markdown editor

Libraries / Files I've included
* mardown-it
* to-mark
* squire-rte
* codemirrior (I manually minified this)
* highlight.js (I manually minified this)
* tui-code-snippet
* tui-editor-Editor.min.js
* tui-editor-extTable.min.js

I'm getting pushback from our other developers about pulling in such a large library. So I'd love to get it in with the bare minimum file size. I'll probably end up lazy-loading the javascript until the user needs the editor which will also significantly reduce the initial loading time.

Can any of these dependencies go? I trimmed it as much as possible before it stopped working

Thanks!

**Comment by gregroyal** [comment]
I think i unfortunately cant even lazy load it because the editor adds custom display to the markdownit render? so if i render the markdown myself in read only mode it will look different than when tui-editors wysiwyg mode renders it

**Comment by sohee-lee7** [comment]
I also want to reduce the file size. The most large size of our dependencies is highlight.js. There are already issues about file size of highlight.js (#415, #335). So I will try to reduce highlight.js size by importing only the language user want.
I think that lazy loading is possible. For example Squire is not loaded until user change mode from markdown to wysiwyg. But I do not know how it will help.
This issue is difficult to solve right away, but it will be fixed in version 1.5 or 2.0.

**Comment by seonim-ryu** [comment]
@gregroyal 
To reduce the bundle size in 2.0, the following work was done.

* jQuery has been removed.
* Each extension has been separated into a plugin.
* highlight.js has been separated into the [code-syntax-highlight](https://github.com/nhn/tui.editor/tree/master/plugins/code-syntax-highlight) plugin.
* The language files (i18n) have been separated into individual files.

![bundle-size](https://user-images.githubusercontent.com/18183560/77377612-f29be580-6db6-11ea-8085-dc90a0d54e34.png)

When I checked the issue you wrote earlier, I think you can reduce the bundle size if you disable highlight.js usage.

I'll close this issue. Please register new issues if necessary.

**Comment by gregroyal** [comment]
Awesome! is this for a later release or available right away?

**Comment by seonim-ryu** [comment]
@gregroyal 
> Awesome! is this for a later release or available right away?

TOAST UI Editor v2.0 is available now. See [here](https://github.com/nhn/tui.editor/tree/master/apps/editor).
