### ISSUE TITLE
How to change font color?

### ISSUE THREAD

**Issue by rico345100** [nhn/tui.editor#544]
## Version
Using @toast-ui/react-editor 1.0.0. From that repo, it uses @1.3.0.

## Test Environment
Chrome 74, MacOS 10.13.6

## Current Behavior
I can clearly see that some text has different color, also there's a button for change color in main front page of this repo:

https://user-images.githubusercontent.com/1215767/34356204-4c03be8a-ea7f-11e7-9aa9-0d84f9e912ec.gif

However, I can't see that button. How do I change the font color? Only I can guess is that using [this one](https://ui.toast.com/tui-color-picker), but can't see any helpful information that integrate with Toast UI Editor.

Also, all example links were broken, please fix that too.

**Comment by sohee-lee7** [comment]
Please check this [link](https://github.com/nhn/tui.editor/blob/master/docs/using-extensions.md#for-color-syntax).

**Comment by rico345100** [comment]
@sohee-lee7 Thanks, but there's missing in that link, must be import 'tui-color-picker/dist/tui-color-picker.css' also, otherwise color picker looks horrible. But still, color-picker seems weird, even your screenshot in document, "OK" text in button is totally invisible and layout seems not aligned properly. Even worse, I got this broken UI as well. Take a look at this picture:

http://photon.modernator.me:/album/rico345100@gmail.com/others//glitch.png

Here's my code:

```javascript
import 'tui-editor/dist/tui-editor-extColorSyntax';
import 'tui-color-picker/dist/tui-color-picker.css';
import React, { Component, createRef } from 'react';
import { Editor } from '@toast-ui/react-editor';

...
const editorConfig = {
  content: {
    initialEditType: 'wysiwyg',
    style: { marginBottom: 10 },
    hideModeSwitch: true,
    placeholder: 'Notice',
    height: 500,
    usageStatistics: false,
    toolbarItems: [
      'heading',
      'bold',
      'italic',
      'hr',
      'quote',
      'divider',
      'ul',
      'ol',
      'indent',
      'outdent',
      'divider',
      'table'
    ]
  }
};
...

    render() {
        return (
            <Editor {...editorConfig.content} ref={this.contentRef} />
        );
    }

    ...
```

**Comment by sohee-lee7** [comment]
@rico345100 Please refer this commit (6212d75470a5fb4c8a8dc1f61f9144eae0b3f59b).
You can override color-picker css like this commit. Try change css of those selectors.

* `.tui-popup-color .te-apply-button`
* `.tui-popup-color .tui-colorpicker-container .tui-colorpicker-palette-hex`

**Comment by rico345100** [comment]
@sohee-lee7 Thanks, however I'm using react version, so I just put them to override:

```css
:global(.tui-popup-color .te-apply-button) {
  bottom: 135px;
  color: black;
}
```

But still overall layout broken.

http://photon.modernator.me:/album/rico345100@gmail.com/others//Messed.png

Also I saw your commit but there's no change in this one: '.tui-popup-color .tui-colorpicker-container .tui-colorpicker-palette-hex'. Maybe you should forget to commit?
