### ISSUE TITLE
Placeholder cause misplaced cursor in Markdown mode

### ISSUE THREAD

**Issue by KanthWasTaken** [nhn/tui.editor#576]
## Version
1.4.2

## Test Environment
Chrome, Mac OS

## Current Behavior
Cursor isn't on the same line as the placeholder in Markdown mode. Works in WYSIWYG mode.
![giphy](https://user-images.githubusercontent.com/8203554/61274486-33654880-a7ac-11e9-988d-37f73bc1dc85.gif)

## Expected Behavior
Cursor should be on the same line as the placeholder

**Comment by sohee-lee7** [comment]
I tried to reproduce this issue, but it was not reproduced. Please let me know the editor option, and let me know if you are using CSS.
