### ISSUE TITLE
when wysiwysgEditor style button is on, setMarkdown method not work correctly

### ISSUE THREAD

**Issue by kingecg** [nhn/tui.editor#580]
## Version
1.4.4

## Test Environment

Angular and typescript
## Current Behavior
When using wysiwygEditor and with some style button on(eg. Bold), get markdown from editor and set back to it, editor will render wrong html.
for example, if I write BB and bold it. 
The markdown code is **BB**.
when I reset this code with Editor.setMarkdown method, editor render it as \*\*BB\*\*
```js
// Write example code
```

## Expected Behavior
can correct render it as **BB**

**Comment by sohee-lee7** [comment]
I try to reproduce this issue but this issue is not reproduced. `setMarkdown` and `getMarkdown` works well. Please more detail way to occur this issue.

**Comment by kingecg** [comment]
I am working on wrap this editor to an Angular component. To make the markdown content can be used as data binding, I declared an Input property 'content' and output property 'contentChange'. 
the logic are:
1. when be set value to content property, I render the content with setMarkdown method into editor.
2. when content was edited, I would get the markdown content in editor on change event and info user with my contentChange property.
3. As we know, in Angular, we can use banana expression to combine content input and contentChange output as a two-way binding([(content)]="xx"). So, every time content is edited, it will trigger 2 and then 1(render back).
with my component, this issue reproduce is:
1. input some content, for example BB.
2. Select the inputed text BB and click 'Bold' button on editor toolbar.
3. Ensure the input cursor is following BB and press and key(eg, press space).
4. the editor will render content as \*\*BB \*\*, But It should render it as **BB**

Then, I make a workaround. By listening on editor stateChange event, I can trace style button state. when any style button state is true(on), I would stop listen editor content change event. with this work around, the editor working correctly
```typescript
this.editorInstance.on('stateChange',(state)=>{
        let states = Object.keys(state).map(key => state[key])
        let index = states.findIndex(s=>{
          return s
        })
        if(index!==-1){
          this.toggleOnChange(false)
        } else {
          this.toggleOnChange(true)
        }
    })

```

**Comment by sohee-lee7** [comment]
Thank you for a detailed description. However, this issue seems to be related to your angular code. I'm sorry, but I can not reproduce this issue in the editor sample example. So I do not know how to help. 

Does your problem not cause `change` event when you manipulate the markdown with the button?

Or is it a problem to render like **BB** when the markdown is equal to **BB **?
If you think this is a problem, this is normal. This is because the markdown syntax does not allow spaces on either side of the emphasis syntax. Please refer this markdown example.
https://spec.commonmark.org/dingus/?text=a%20*%20foo%20bar*%0A

**Comment by kingecg** [comment]
Yes, The problem is about to render like BB when the markdown is equal to **BB **.
Actually, When I write some word with Bold and type space in wysiwyg editor, it means I want next word I would input also be bold. So, if I request markdown content, editor should first trailing the last blank character (that is return **BB** to me, not **BB **).
this issue also can be reproduced in http://nhn.github.io/tui.editor/api/latest/tutorial-example-e2e.html
as following steps:
1. switch to wysiwyg editor.
2. input BB. bold the text and input a blank str.
3. switch to markdown editor

**Comment by sohee-lee7** [comment]
The way to reproduce the problem is different, but it seems to be related to this issue https://github.com/nhn/tui.editor/issues/548. I will improve this issue after discussion with my team members. Thank you.

**Comment by seonim-ryu** [comment]
This issue appears to be resolved and closes.
