### ISSUE TITLE
Codeblock Highlighting not working

### ISSUE THREAD

**Issue by EzraZebra** [nhn/tui.editor#583]
## Version
Latest (CDN)

## Test Environment
Firefox 68.0.1 & Internet Explorer 11
Windows 8.1

## Current Behavior
The code highlighting isn't working in the preview, wysiwyg or viewer. In the preview and viewer (not in wysiwyg) the span tags _are_ present with the appropriate classes, font-weight is bold for keywords, but color is always `#333`.  
I've tested with PHP and JavaScript.  
I've included the CSS and JS from the CDN exactly as in the Readme.md, and I've also tried adding highlight.js. Everything is being loaded correctly according to Firefox Dev Tools.

```js
var content = document.getElementById('content_text');

var editor = new tui.Editor({
	el: document.getElementById('editSection'),
	initialEditType: 'markdown',
	previewStyle: 'tab',
	height: '500px',
	initialValue: content.value,
	usageStatistics: false
});
```

## Expected Behavior
Syntax highlighting should apply font colors.

**Comment by sohee-lee7** [comment]
Did you load below css ?
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css"></link>
```
I try to test highlighting of code block in http://nhn.github.io/tui.editor/api/latest/tutorial-example-e2e.html. But it works well.
![image](https://user-images.githubusercontent.com/42666492/61853320-98c8e000-aef6-11e9-90cd-6d898f394554.png)

If you want to another style of highlight.js, you can choose one in https://cdnjs.com/libraries/highlight.js/.
For example:
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/styles/atom-one-light.min.css">
```

**Comment by EzraZebra** [comment]
> Did you load below css ?
Yes, I did. I just tried it with Marked.js + Highlight.js instead of TUI Viewer and the same thing is happening, so it's not a problem with TUI apparently.
