### ISSUE TITLE
Editor 수정내역 디비 연동

### ISSUE THREAD

**Issue by Sanhosa** [nhn/tui.editor#584]
에디터에 저장된 내용을 DBMS에 연동하는 방법을 간단히라도 가이드 받고 싶습니다.
(DB에 저장된 내용을 불러와 에디터에 출력해 주는것 포함)

JavaScript 코드 위치는 어디쯤이 기입하는 것이 가장 좋은가요?
(예 : 하단부 or 아래 or 페이지 로딩 후..)

**Comment by sohee-lee7** [comment]
해당 문의는 저희가 가이드 드릴 영역이 아니므로 close 하겠습니다.
