### ISSUE TITLE
First Version Angular Lib available for Testing

### ISSUE THREAD

**Issue by mahmoudajawad** [nhn/tui.editor#585]
Hello.

I just came across your great editor few days back. I wanted to work further on it in my projects, but since I use Angular for my projects I wanted to have a wrapper for it. I created a quick, dirty wrapper for it that can be used as a component like:
```html
<tui-ng-tui-editor dir="rtl" height="300px" [data]="data" (change)="editorChange($event)"></tui-ng-tui-editor>
<tui-ng-tui-editor initialEditType="markdown" previewStyle="vertical" height="300px"></tui-ng-tui-editor>
<tui-ng-tui-editor initialEditType="markdown" previewStyle="tab" height="300px"></tui-ng-tui-editor>
```
I've also implemented top-level `dir` attr that's not part of `tui` originally. The reason is I work with multi-locale apps where I need the editor to have the option to have correct text direction based on the current locale.

The lib isn't yet published on npm as I still need to review it, but it's available on:
https://github.com/AjawadMahmoud/ng-tui-editor

To get started:
```bash
git clone https://github.com/AjawadMahmoud/ng-tui-editor
cd ng-tui-editor
npm i
ng build
ng serve
```
The test app has three different editors each with its own configs. This is perfect for my use case as I'm intending to have multiple instances of the editor in my apps.

I would be glad if you give this project a shot, and maybe consider it the community Angular wrapper that some previous issues asked for.

**Comment by AjawadMahmoud** [comment]
In order to keep this issue open for any future references for the project I'm posting this comment.
