### ISSUE TITLE
Cannot create custom "Header" button

### ISSUE THREAD

**Issue by GammaGames** [nhn/tui.editor#589]
## Version

1.4.4

## Test Environment

Ubuntu 18.04.2 LTS
Chrome Version 75.0.3770.142 (Official Build) (64-bit)

## Current Behavior

1. Create editor
2. Add custom header button
3. Cannot open custom button, gives `Cannot read property 'offsetTop' of undefined` error

https://jsfiddle.net/x4fh0ytp/

```js
 new tui.Editor({
  el: document.querySelector('#editSection2'),
  initialEditType: 'wysiwyg',
  previewStyle: 'vertical',
  height: "auto",
  hideModeSwitch: true,
  initialValue: "## Does not work",

  toolbarItems: [
    {type: 'button', options: {
      $el: $('<button><i class="black heading icon"></i></button>'),
      name: 'heading',
      event: 'openHeadingSelect',
    }},
  ],
});
```

## Expected Behavior
Custom button should open like a regular button

**Comment by sohee-lee7** [comment]
Button tag should have `button tui-heading` class for create Heading Popup. Please modify it as follows.
```js
  toolbarItems: [
    {type: 'button', options: {
      $el: $('<button class="button tui-heading"><i class="black heading icon"></i></button>'),
      name: 'heading',
      event: 'openHeadingSelect',
    }},
  ],
```

**Comment by GammaGames** [comment]
That worked, thank you!
