### ISSUE TITLE
Quote blocks not rendered with tui-editor-Viewer-full

### ISSUE THREAD

**Issue by EzraZebra** [nhn/tui.editor#590]
## Version
Latest (CDN).

## Test Environment
Firefox 68.0.1, Windows 8.1

## Current Behavior
With "https://uicdn.toast.com/tui-editor/latest/tui-editor-Viewer-full.min.js", quote blocks aren't rendered. They appear just as `> text`.  All other markup is rendered correctly as far as I can tell.
In the editor it works as expected, including Preview and WYSIWYG.

```js
		let value = element.innerHTML;
		element.innerHTML = null;
		new tui.Editor({
			el: element,
			initialValue: value,
		});
```

## Expected Behavior
Quote blocks should appear instead of `> text`.

**Comment by sohee-lee7** [comment]
Quote block is rendered well using `tui-editor-Viewer-full.min.js`. It is assumed that the value of `value` in your code is incorrect.

```js
new tui.Editor({
    el: document.querySelector('#editSection'),
    initialValue: '> text'
});
```
If `initialValue` set just `> text`, it rendered `<blockquote>`

**Comment by EzraZebra** [comment]
Hmm, you're right. I tested it like that and it works.  
I'm saving the text as 'text' in a mysql database, using CodeIgniter 3's database class. It looks like the `>` are being converted to `&gt;`.

**Comment by sohee-lee7** [comment]
Do you mean that when you set `&gt; test` as `initialValue` in the editor, `<blockquote>` is rendered? When I test it, editor and viewer render `> test` as same.

**Comment by EzraZebra** [comment]
Turns out the problem was that I used `.innerHTML` to set the value. It works properly using `.textContent` instead.  
Sorry for wasting your time.

**Comment by sohee-lee7** [comment]
I am glad your issue has been resolved. Then I will close this issue.
