### ISSUE TITLE
Saving crop before hitting apply, saves the image with the crop guides visible

### ISSUE THREAD

**Issue by owenallenaz** [nhn/tui.editor#592]
## Version
https://ui.toast.com/tui-image-editor

## Test Environment
Windows, Google Chrome 75.0.3770.142

## Current Behavior

https://www.screencast.com/t/iCwLRhSOfUf2

If you open up the image editor example on the website. Click on the crop tool, click one of the crop formats, and then click "download" without clicking "apply" it will result in downloading an image that still contains the crop guides. In this case it should either remove the guides prior to the download by cancelling the action or it should prevent the download. I tested some of the other tools, and they don't seem to suffer this same problem. In example rotate, flip didn't exhibit this behavior, but crop did.

**Comment by codepink** [comment]
@owenallenaz
This issue is related to the image editor. 😅
Could you re-register this issue on [the repository of `tui-image-editor`](https://github.com/nhn/tui.image-editor/issues)? Then I would appreciate it.

I'll close this issue.

**Comment by seonim-ryu** [comment]
@owenallenaz
This issue is related to the image editor. 😅
Could you re-register this issue on the repository of tui-image-editor? Then I would appreciate it.

I'll close this issue.
