### ISSUE TITLE
How to accept 2+ params in an Extension

### ISSUE THREAD

**Issue by taurenshaman** [nhn/tui.editor#593]
## Version
v1.4.4

## Test Environment
Opera 62

## Current Behavior
The following sample code only provide one param scenario.
https://github.com/nhn/tui.editor/blob/master/docs/writing-your-own-extension.md
How to accept 2+ params?

```js

tui.Editor.defineExtension('youtube', function() {
    tui.Editor.codeBlockManager.setReplacer('youtube', function(youtubeId, sid) {
        var wrapperId = 'yt' + Math.random().toString(36).substr(2, 10);
        setTimeout(renderYoutube.bind(null, wrapperId, youtubeId, sid), 0);

        return '<div id="' + wrapperId + '"></div>';
    });
});

function renderYoutube(wrapperId, youtubeId, sid) {
    console.log(sid);
    var el = document.querySelector('#' + wrapperId);
    el.innerHTML = '<div><p>Hello~</p><p>Youtube Rendered:' + youtubeId + '</p></div>';
}

```
I guess maybe the second line is another param.
So I tried:  
```
youtube
XGSy3_Czz8k
ffff44
```
in the editor, BUT the console prints `youtube`.

**Comment by taurenshaman** [comment]
Tried:
```

tui.Editor.defineExtension('youtube', function() {
    tui.Editor.codeBlockManager.setReplacer('youtube', function(youtubeId, secondId, thirdId, fouthId) {
        var wrapperId = 'yt' + Math.random().toString(36).substr(2, 10);
        setTimeout(renderYoutube.bind(null, wrapperId, youtubeId, secondId, thirdId, fouthId), 0);

        return '<div id="' + wrapperId + '"></div>';
    });
});

function renderYoutube(wrapperId, youtubeId, secondId, thirdId, fouthId) {
    console.log("youtubeId=" + youtubeId);
    console.log("secondId=" + secondId);
    console.log("thirdId=" + thirdId);
    console.log("fouthId=" + fouthId);
    var el = document.querySelector('#' + wrapperId);
    el.innerHTML = '<div><p>Hello~</p><p>Youtube Rendered:' + youtubeId + '</p></div>';
}

```

Input: 
```youtube
XGSy3_Czz8k
11111
22222
33333
```

Console output:
![extension-debug-output](https://user-images.githubusercontent.com/1308706/62359490-7b74c100-b549-11e9-8dc3-f48787a427b8.png)

**Comment by taurenshaman** [comment]
OK, I tried add a select control to switch some options.
http://taurenshaman.github.io/tui.editor+cytoscape.html

**Comment by seonim-ryu** [comment]
@taurenshaman 
Sorry for late reply. 😭

The `replacer` function used by the extension currently only supports up to [two parameters](https://github.com/nhn/tui.editor/blob/master/src/js/codeBlockManager.js#L49). The `codeText` parameter's value corresponds to the data entered in the code block. How about manipulating this value? I think you can set the ids and values like this and then parse it in the `replacer` function. Consider this method!

![](https://user-images.githubusercontent.com/18183560/62865176-b72d3900-bd48-11e9-9646-e01056ead01a.png)

**Comment by taurenshaman** [comment]
Done. Thank you very much!
Code: https://github.com/tunaltd/tui.editor-modules/blob/master/cytoscape/cytoscape-module.js
Example: http://taurenshaman.github.io/tui.editor+cytoscape.html
