### ISSUE TITLE
Should there be a backslash infront of html written in wysiwyg?

### ISSUE THREAD

**Issue by DPerkunas** [nhn/tui.editor#595]
Is it normal behavior in wysiwyg editor I write `<div>`and when i do` editor.getMarkdown()`, the value is `\<div>`? I would expect it to return `<div>` as it's written. I want the `<div>` to show up as text `<div>` in the markdown. When it's inside of a code-block or code, it works as expected.

## Version
1.4.5

## Test Environment
Chrome latest

## Current Behavior
return with backslash infront of <

## Expected Behavior
return raw, without a backslash.

**Comment by seonim-ryu** [comment]
@DPerkunas 
That's normal behavior. The tag you enter on WYSIWYG is a string, so when you get it into Markdown data, it is escaped.
