### ISSUE TITLE
How to send text to a post controller?

### ISSUE THREAD

**Issue by Ande1232** [nhn/tui.editor#602]
## Version
1.4.5
## Test Environment
Chrome, Windows 10

## Current Behavior
Does not send the editor text to the database.

```js
  var initial_form_state, last_form_state;
  var editor = new tui.Editor({
    el: document.querySelector('#editor'),
    language: 'it_IT',
    initialEditType: 'markdown',
    previewStyle: 'tab',
    height: '500px',
    events: {
        change: function() {
          last_form_state = $('form').serialize();
        }
    }
  });
  $(window).bind('beforeunload', function(e) {
    if(last_form_state != initial_form_state){
      return false;
    }});
  $(document).on("submit","form",function(event){
    $('[name=document__text]').attr('value', editor.getMarkdown());
  $(window).off('beforeunload');
});
```

```
<div id="editor" name="testo">{{$articoli->testo}}</div>
```

## Expected Behavior
I am installing Tui.Editor in Laravel 5.8, I installed the editor correctly only when I go to send the form, it completely ignores what I wrote:
```
[00:14:33] LOG.info: The given data was invalid. {
"url":"http:\/\/127.0.0.1:8000\/admin\/articoli\/edit\/7234",
"previus":"http:\/\/127.0.0.1:8000\/admin\/articoli\/edit\/7234",
"input":{"_token":"8jmiOAam4WVOkQxhkddA8Jh3LRtC6Oo",
"titolo":"testa",
"slug":"testa",
"testo":null}
```

As you can see, the "testo" field is null. what is the practice for sending text to a post controller? I also tried to include a textarea internally as suggested editor.md of pandao...

**Comment by seonim-ryu** [comment]
@Ande1232 
I think the usage is wrong. Are you trying to send data on server whenever the editor's value changes? If you want this, I think you should get the editor's value from calling `getMarkdown()` and submit it in `events.change` event. When I only see the code above, I'm not sure how to submit. 🤔
