### ISSUE TITLE
Get editor instance by id / Get all editor instances

### ISSUE THREAD

**Issue by jaydeepk** [nhn/tui.editor#619]
## Version
1.4.6

## Test Environment
Mac OS, Version: 76.0.3809.100 

I'm using jquery to centrally initialize all the editors on the page like shown in the code below

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
<link rel="stylesheet" href="https://uicdn.toast.com/tui-editor/latest/tui-editor.css"></link>
<link rel="stylesheet" href="https://uicdn.toast.com/tui-editor/latest/tui-editor-contents.css"></link>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.33.0/codemirror.css"></link>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css"></link>
<script src="https://uicdn.toast.com/tui-editor/latest/tui-editor-Editor-full.js"></script>

<div id="editor_1" class="markdown-editor"></div>
<div id="editor_2" class="markdown-editor"></div>


<script language="JavaScript">
   $(document).ready(function () {
    $('.markdown-editor').each(function () {
        var element = $(this);
        var config = {
           el: element.get(0),
           initialEditType: 'wysiwyg',
           initialValue: element.val(),
           height: '300px'
         };
        var editor= new tui.Editor(config);
    });
});
</script>
```
The editors are initialised perfectly well and function fine.
Now is there anyway (any method available) that I can get the tui-editor instance corresponding to the div with id = editor_2. ..so that I can wire up some event on it?

Also, is there any method to get a list/array of all editor instances initialised on the page?

Thanks

**Comment by seonim-ryu** [comment]
@jaydeepk 
You can use [getInstances](https://nhn.github.io/tui.editor/api/latest/ToastUIEditor.html#.getInstances) static method to get all created instances. Just call this method to get all instances and call APIs for each instance.
```js
const editors = tui.Editor.getInstances();

editors[0].getValue(); // id="editor_1"
editors[1].getValue(); // id="editor_2"
...
```
And "so that I can wire up some event on it?" I'm not sure what this sentence means. 
Did you ask how to register events for each instance? Sorry, can you explain it again? 😅

**Comment by jaydeepk** [comment]
Thanks @seonim-ryu .
tui.Editor.getInstances() does give me a list of all the editor instances.

The other thing  that I wanted to do was to retrieve a particular instance and attach events on it.
So lets say I have 10 editors on the page :

```
<div id="editor_1" class="markdown-editor"></div>
<div id="editor_2" class="markdown-editor"></div>
<div id="editor_3" class="markdown-editor"></div>
.
.
<div id="editor_10" class="markdown-editor"></div>
```

Now I want to attach 'change' event on editor_3.
So now instead of fetching the editor instance by index like:

 ```
  const editors = tui.Editor.getInstances();
  var editor_3  = editors[2];
```

is there a way I could fetch the editor instance using the id set on the div:
```
   // something like
   var editor_3 = tui.editor.get('editor_3');

   // so that I can wire a change event on that specific instance
   editor.eventManager.listen('change', function ( evt) {
          // do something
    });
```
Thanks

**Comment by seonim-ryu** [comment]
@jaydeepk 
I understand! It would be nice to have a function like `getInstanceById`. I'll consider adding this API and let you know when it's decided. Thanks.

**Comment by jaydeepk** [comment]
Thanks @seonim-ryu , that's exactly what I need.

**Comment by sergeizhukov** [comment]
Same here xD Would be cool to get an instance of editor.

**Comment by BettyJJ** [comment]
Is the `getInstances` method removed from the current version? How can we do this now?
