### ISSUE TITLE
Broken text of a links (with span)

### ISSUE THREAD

**Issue by artemmolotov** [nhn/tui.editor#627]
## Version
v1.4.6

## Test Environment
Firefox Quantum 69.0 (64bit)... or Chrome

## Current Behavior
1. Add link in wysiwyg;
2. Select a part of text of the link;
3. Execute color;
4. Now part of text is colored;
5. Convert to html (`editor.getHtml()`).

```html
<p><a href="http://google.com" rel="noopener noreferrer">
Go&lt;span class="colour" style="color:#0043A4"&gt;ogleGoog&lt;/span&gt;le
</a></p>
```

## Expected Behavior
```html
<p><a href="http://google.com" rel="noopener noreferrer">
Go<span class="colour" style="color:#0043A4">ogleGoog</span>le
</a></p>
```

or

```html
<p><a href="http://google.com" rel="noopener noreferrer">
GoogleGoogle
</a></p>
```

**Comment by artemmolotov** [comment]
#557

**Comment by seonim-ryu** [comment]
#557 Issue resolved and closed.
