### ISSUE TITLE
XSS Vulnerability using anchor tags

### ISSUE THREAD

**Issue by kleyu** [nhn/tui.editor#628]
## Version

The one present in example [page](https://nhn.github.io/tui.editor/api/latest/tutorial-example02-editor-basic.html#), also happening on latest (1.4.6), probably any tui editor with html enabled

## Test Environment

Chrome Version 79.0.3909.0 (Official Build) canary (64-bit)
MacOS 10.14.6

## Current Behavior

Enter in editor:
```html
<a href="javascript:alert(document.cookie)"> text </a>
```
When you clicked on previewed link, alert will pop up with browser cookies (if have any). You can also put `window.localStorage` or other malicious actions

## Expected Behavior

Output is properly sanitised

**Comment by seonim-ryu** [comment]
@kleyu @artemmolotov

Yes, this is a serious issue.. 🤔
I've seen how GitHub and `markdown-it` editors work, and each editor works like this:

### GitHub
```
<a href="javascript:alert(document.cookie)"> text </a>

<a href="https://github.com/nhn/tui.editor"> text </a>

<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==
">

<img src="https://user-images.githubusercontent.com/1215767/34348387-a2e64588-ea4d-11e7-8267-a43365103afe.png" />
```

<img width="737" alt="github" src="https://user-images.githubusercontent.com/18183560/65154653-dbc2b200-da66-11e9-8335-262b4bc975e9.png">

### markdown-it
* Disable html
<img width="1168" alt="markdown" src="https://user-images.githubusercontent.com/18183560/65154703-f137dc00-da66-11e9-8f16-49a226cdfe4d.png">

* Enable html
<img width="1167" alt="markdown-it-html" src="https://user-images.githubusercontent.com/18183560/65154883-3fe57600-da67-11e9-8037-e785e0bd3bb1.png">


I noticed the same issue with `markdown-it` when html is enabled. So I think we should check `markdown-it` first. Whether links that are prohibited by `markdown-it` are valid only when html is disabled.

And I'll check the your PR this week and let you know the result.

Thanks for reporting the issue.
