### ISSUE TITLE
Unable to bold link text in wysiwyg

### ISSUE THREAD

**Issue by gregroyal** [nhn/tui.editor#631]
## Version
1.4.6

## Test Environment
Chrome 76, windows 10

## Current Behavior
Cannot bold link text in wysiwyg if that is the only thing you highlight

## Expected Behavior
If you highlight the link and hit bold, the line will be bold

**Comment by gregroyal** [comment]
Almost seems like this is was done on purpose?
https://github.com/nhn/tui.editor/blob/master/src/js/wysiwygCommands/bold.js#L48

**Comment by seonim-ryu** [comment]
@gregroyal 
It's not intended, it looks like a bug. Because it's a spec that works fine in Markdown. I'll check the issue!
