### ISSUE TITLE
code highlight not work in wysiwygEditor

### ISSUE THREAD

**Issue by kingecg** [nhn/tui.editor#635]
## Version
latest

## Test Environment
angular and Mac

## Current Behavior
set markdown content which contain a codeblock to wysiwygEditor by setMarkdown method.
The code block not highlight.

## Expected Behavior
The code should be highlight.

## Reason
this problem is due to code at line 465 of editor.js. You directly convert markdown to plain html, not process codeblock highlight.

**Comment by seonim-ryu** [comment]
@kingecg 
I think this issue means that when you call api from WYSIWYG as below:

```js
editor.setMarkdown('```javascript \n var foo = 1; \n```');
```
<img width="382" alt="wwe" src="https://user-images.githubusercontent.com/18183560/65369961-cb8d1b80-dc8e-11e9-9fc3-c3cc67eb6a19.png">

If this is right, this is normal behavior.

> this problem is due to code at line 465 of editor.js

And the code location you said is right [here](https://github.com/nhn/tui.editor/blob/master/src/js/editor.js#L465)? This code is only executed in the editor when it is in markdown mode and without the value of the `initialValue` option.  So it doesn't matter what the issue you said.

If you think I understand something wrong, please comment again.
