### ISSUE TITLE
Brackets cause trouble

### ISSUE THREAD

**Issue by cbbfcd** [nhn/tui.editor#642]
## Version
1.4.5

## Test Environment
All

## Current Behavior
In the markdown edit mode, the brackets do not seem to be handled correctly.

now the result like this:
```js
 ** （should be blod）**
```
but we want this:

**（should be blod）**

## Expected Behavior

![uiQNDg.png](https://s2.ax1x.com/2019/09/23/uiQNDg.png)

**Comment by seonim-ryu** [comment]
@cbbfcd
That's normal behavior. The [CommonMark's specification](https://spec.commonmark.org/0.29/#example-351) is that if there are spaces, the markdown syntax is broken.

**Comment by cbbfcd** [comment]
thanks replay @seonim-ryu 
i have a try，the issue is in Chinese brackets and there are no spaces.
![uiG9Yj.png](https://s2.ax1x.com/2019/09/23/uiG9Yj.png)

**Comment by cbbfcd** [comment]
i found the reason, thx so much.
