### ISSUE TITLE
No wrapping in WYSIWYG

### ISSUE THREAD

**Issue by marcoXbresciani** [nhn/tui.editor#649]
## Version
v.1.4.6 online example at https://nhn.github.io/tui.editor/api/latest/tutorial-example00-editor-with-extensions.html

## Test Environment
Google Chrome 77.0.3865.90 (Build ufficiale) (a 64 bit) on Windows 10 Pro.

## Current Behavior
Copy-paste a text wrapped at 72 characters. e.g.:
```markdown
# My Code Conventions
This document contains the code conventions I've defined in these years
and I'm using, evolving them based on needs. This document is written
using [Markdown](https://daringfireball.net/projects/markdown/) as a
mean to keep the file simple, both readable as a plain text file and
with the possibility to render it in a nicer format. I'm currently
writing it with [IntelliJ IDEA](https://www.jetbrains.com/idea/)
[Markdown plugin](https://www.jetbrains.com/help/idea/markdown.html)
using the [GitHub Flavored Markdown](https://github.github.com/gfm/)
format.

**Update 2019-09-23**.
```
The WYSIWYG renders with the same wrapping (see attachment).

## Expected Behavior
Expectation is that the sentence should be written as a single continuous HTML paragraph, without any line break. See https://daringfireball.net/projects/markdown/basics

**Comment by marcoXbresciani** [comment]
It seems I can't attach the screenshot file...

**Comment by seonim-ryu** [comment]
@marcoXbresciani 
TOAST UI Editor uses the [`breaks` option of `markdown-it`](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20My%20Code%20Conventions%5CnThis%20document%20contains%20the%20code%20conventions%20I%27ve%20defined%20in%20these%20years%5Cnand%20I%27m%20using%2C%20evolving%20them%20based%20on%20needs.%20This%20document%20is%20written%5Cnusing%20%5BMarkdown%5D%28https%3A%2F%2Fdaringfireball.net%2Fprojects%2Fmarkdown%2F%29%20as%20a%5Cnmean%20to%20keep%20the%20file%20simple%2C%20both%20readable%20as%20a%20plain%20text%20file%20and%5Cnwith%20the%20possibility%20to%20render%20it%20in%20a%20nicer%20format.%20I%27m%20currently%5Cnwriting%20it%20with%20%5BIntelliJ%20IDEA%5D%28https%3A%2F%2Fwww.jetbrains.com%2Fidea%2F%29%5Cn%5BMarkdown%20plugin%5D%28https%3A%2F%2Fwww.jetbrains.com%2Fhelp%2Fidea%2Fmarkdown.html%29%5Cnusing%20the%20%5BGitHub%20Flavored%20Markdown%5D%28https%3A%2F%2Fgithub.github.com%2Fgfm%2F%29%5Cnformat.%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Atrue%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D). In other words, if a paragraph contains a newline, it is rendered as newline when it is rendered. The paragraph you added as an example above contains newline characters(e.g. , ` ... these years\nand I'm using, ...`) so when you paste it, it will appear as newline.

![markdown-it](https://user-images.githubusercontent.com/18183560/65750467-6da37c80-e143-11e9-87f8-ae9b1600531a.png)

**Comment by marcoXbresciani** [comment]
Is it possible to configure/customize such behaviour, just like the "break" checkbox in the markdown-it box?

**Comment by seonim-ryu** [comment]
@marcoXbresciani 
There are no options available now. And because of the WYSIWYG and Markdown transformations, I think it's hard to put this feature right now.

**Comment by darron1217** [comment]
Any update on this issue?

This is seriously related to compatibility.

Most of markdown language renderer ignores line break. This should be re-discussed.
