### ISSUE TITLE
<br> Tags with Whitespace Above them are being Doubled on Re-Render

### ISSUE THREAD

**Issue by Bravo-Bear** [nhn/tui.editor#650]
## Version 
1.4.6

## Test Environment
Google Chrome, macOS 10.14.6

## Current Behavior
I'm running plain TUI Editor in React (This issue also occurs using the wrapper for React) and every time there is a re-render, any `<br>` tag with white space above it will be doubled. 

*Example Code:* https://codesandbox.io/s/tui-editor-bug-bukyh?fontsize=14

---
![Screen Shot 2019-09-25 at 2 10 12 PM](https://user-images.githubusercontent.com/42663507/65627852-3b0c4f00-df9e-11e9-861f-aadf6c872999.png)
---
I have some filler text, and I want to add more text two lines below it

![Screen Shot 2019-09-25 at 2 06 40 PM](https://user-images.githubusercontent.com/42663507/65627716-f41e5980-df9d-11e9-9fc9-d5a00282624a.png)
---
I press enter twice and add slightly more filler text, I then switch to mark down to verify that a `<br>` was created when I pressed enter the second time

![Screen Shot 2019-09-25 at 2 12 14 PM](https://user-images.githubusercontent.com/42663507/65627988-84f53500-df9e-11e9-852e-47f85b78ea44.png)
---
But when I toggle edit off I see that my text is slightly further then I when I left it

![Screen Shot 2019-09-25 at 2 07 05 PM](https://user-images.githubusercontent.com/42663507/65628154-e4534500-df9e-11e9-8f9d-0948c10f68c8.png)
---
And when I go back to the editor I can see that an additional `<br>` was created when I toggled edit

![Screen Shot 2019-09-25 at 2 07 44 PM](https://user-images.githubusercontent.com/42663507/65628283-23819600-df9f-11e9-89bf-ce00e3df03bb.png)
This occurs exponentially, every time I toggle edit the amount `<br>` tags is doubled    

## Expected Behavior
In the case that there is a `<br>` tag with white space above it,  the amount of `<br>`s should remain the same whenever the editor is rendered to the screen

**Comment by seonim-ryu** [comment]
@Bravo-Bear 
I'm checking the issue you mentioned, and the link you gave is different from the page I'm looking at. Below is the page I'm looking at. And when I edit the content and click the toggle button, it seems to behave differently.

![example](https://user-images.githubusercontent.com/18183560/65741034-c2d09580-e125-11e9-91e0-eb05349bc5b9.png)

Can you confirm that the link you gave me works correctly?

**Comment by Bravo-Bear** [comment]
Sorry for the inconvenience, Was testing a potential workaround and saved it into the incorrect repository, Should be functioning as expected now

**Comment by devo-wm** [comment]
Yeah we're just running into this as well. +1

**Comment by worldtopone1** [comment]
me too. + 1
