### ISSUE TITLE
App freezes after using the editor

### ISSUE THREAD

**Issue by buruguduys** [nhn/tui.editor#652]
## Version
"tui-editor": "1.4.0",

## Test Environment
IOS(browser, application)

## Current Behavior
After saving content in the editor the app freezes. Only happening on IOS

## Expected Behavior
Save the content

**Comment by seonim-ryu** [comment]
@buruguduys 
I can't figure out what's going on with this information alone. Can you explain the code you used or more?

**Comment by buruguduys** [comment]
`<tui-editor class="purpose-input" [options]="options" *ngIf="!preview"></tui-editor>` 
with just this simple code on HTML

and the TS having this code
`this.purpose = this.editorService.getHtml().toString();`
this cause the app to freeze  after clicking random buttons
