### ISSUE TITLE
Incorrect escape character inserted before " | "

### ISSUE THREAD

**Issue by kelvinkoko** [nhn/tui.editor#660]
## Version
1.4.6

## Test Environment
Chrome and Safari browser

## Current Behavior
When you input the following in WYSIWYG mode
(not a table)
```
|1|
```
and change to Markdown mode, it become
```
\|1\|
```
## Expected Behavior
In markdown mode, should also display as
```
|1|
```

**Comment by seonim-ryu** [comment]
@kelvinkoko 
That's not a bug. It's currently a spec that escaping some [punctuation character](https://spec.commonmark.org/0.29/#ascii-punctuation-character) in WYSIWYG. ([ref.](https://github.com/nhn/to-mark/blob/production/src/renderer.js))

**Comment by kelvinkoko** [comment]
I see, thank you for your reference, I will close this issue
