### ISSUE TITLE
Text color is reset after applying "Bold", "Italic", or "Strikethrough" (in the wysiwyg)

### ISSUE THREAD

**Issue by artemmolotov** [nhn/tui.editor#661]
## Version
1.4.7

## Test Environment
Firefox Quantum 69.0 (64bit)... or Chrome

## Current Behavior
1. Add text in the editor (wysiwyg mode);
2. Select a part of the text;
3. Execute "Color";
4. Select a part of the colored text;
5. Execute "Bold", "Italic" or "Strikethrough";
6. Rendering result is different between wysiwyg.

![](https://habrastorage.org/webt/n5/xp/9e/n5xp9er2rfplxp3kaomp8kzppqk.gif)

## Current Behavior
1. Add text in the editor (wysiwyg mode);
2. Select a part of the text;
3. Execute "Bold";
4. Select a part of the bold text;
5. Execute "Color";
6. Select a part of the colored text;
7. Execute "Italic" or "Strikethrough";
8. Rendering result is different between wysiwyg.

![](https://habrastorage.org/webt/ob/xp/io/obxpiog9nwpwmvtlfopitogrllg.gif)

P.S.: Thank you for the editor!

**Comment by seonim-ryu** [comment]
@artemmolotov Thanks for the detailed explanation! 

But.. when I tested it on Safari and Chrome, it didn't work. Are you working on Windows? And did the previous version work well? I think I need more information.

![wwe](https://user-images.githubusercontent.com/18183560/66536321-776fab80-eb57-11e9-96f6-69e5fee8a677.gif)

**Comment by artemmolotov** [comment]
I'm sorry. When I looked deeply, it turned out that the problem is in some overridden CSS...
