### ISSUE TITLE
HELP NEEDED: Confused on how to get started.

### ISSUE THREAD

**Issue by N6REJ** [nhn/tui.editor#666]
I'm not using the template cause it's not a bug.
I'm trying to figure out how to create the editor.  I've followed the steps in the readme's and probably made a mess of things with a bunch of stuff I don't need, ergo my request for help.
I made my repo https://github.com/N6REJ/toast .  I didn't fork because I didn't want my mess being related to your cool looking software.
What I'm wanting to do is to create a wysiwyg md editor that will allow me to work with files in my .daux folder on other projects.
2 future things would be ..

A) add a button that would run 
cd .daux 
daux generate ../public

b) created a Joomla 4 "editor" extension/plugin for creating md in articles.

For now I'll be perfectly happy to use it as a 3rd party editor and edit my .daux files that way.

**Comment by seonim-ryu** [comment]
@N6REJ 
I'm sorry but I don't know exactly what you mean.. 😭

Here's what I understood: Are you going to use the editor to  create an extension for Joomla 4 editor? Did you ask how to use the editor because you don't know how to use it?

I would like to be more specific please!

**Comment by N6REJ** [comment]
Here's my use case... 
I'm using daux to create the documentation for my template and possibly all future J! objects.
the problem is the markdown editing in phpstorm SUCKS!!!!!!!!!!
I stink @ markdown in the worst way, so really NEED a wysiwyg editor for it.  ergo, tui.
now, if I could ALSO use it as a editor in J! ( maybe with more features *shrug* ) then that is icing on the cake.  but right now I need an editor that will simply let me write good markdown and then IF POSSIBLE have a single menu/button that would fire off daux generation..
`daux generate -d ../public`
thats whats required for gitlab to auto-magically publish the generated docs as a gitlab page.  I assume github is the same way though I've not tried.

**Comment by seonim-ryu** [comment]
@N6REJ 
The answer is late. In fact, I don't understand everything you say.. But when I guess I think you're confused because the data used by the document generator called [daux](https://daux.io/) is markdown.

Do you want to use the WYSIWYG editor when editing data used by daux? If so, why don't you create a page where you want to edit the data, attach `tui-editor` to it, create the edited data as markdown, and then use the generated markdown data when you run the `duax` command?

**Comment by N6REJ** [comment]
That will be great if I can figure out how to get tui to do that.
