### ISSUE TITLE
Scroll position jump back to the top when the content longer then one screen height in WYSIWYG mode

### ISSUE THREAD

**Issue by kelvinkoko** [nhn/tui.editor#667]
## Version
1.4.7

## Test Environment
Android Chrome 
(I understand mobile browser is not fully supported, but would like to see any solution/workaround from your understanding)

## Current Behavior
1. Open WYSIWYG mode in Android Chrome.
2. Try to type content make it longer then screen height (scroll bar appear)
3. Scroll to bottom (or any non top position), keep typing and when press enter, it will scroll back to top

## Expected Behavior
Scroll position should not change

**Comment by seonim-ryu** [comment]
@kelvinkoko
Can you tell me if this issue occurs on all Android devices or only on certain devices?
It seems like a mobile browser scrolling issue, but I'm not sure if I can fix.. I'll check the device information once you give me a comment.

**Comment by kelvinkoko** [comment]
I just checked, this problem just occur in latest Chrome (78.0.3904)
I tried on some old device with Chrome (59.0.3071) it work normally.

**Comment by madhavarshney** [comment]
@seonim-ryu I can confirm this issue happens on Chrome on Android (tested on Android Oreo) with TUI Editor `v2.0.1`. The scroll position also resets when you move the cursor by tapping on the editor.  Do you know why this may be happening or what specific parts of the code might be causing this? Thanks!
