### ISSUE TITLE
Add undo button to the Toolbar

### ISSUE THREAD

**Issue by werthd** [nhn/tui.editor#669]
## Version
Latest
## Test Environment
Chrome Macos Catalina
## Current Behavior
No undo button.
I would like to know how i can call the
```js
rt.undo = function() {
                if (0 !== this._undoIndex || !this._isInUndoState) {
                    this._recordUndoState(this.getSelection(), !1),
                    this._undoIndex -= 1,
                    this._setHTML(this._undoStack[this._undoIndex]);
                    var e = this._getRangeAndRemoveBookmark();
                    e && this.setSelection(e),
                    this._isInUndoState = !0,
                    this.fireEvent("undoStateChange", {
                        canUndo: 0 !== this._undoIndex,
                        canRedo: !0
                    }),
                    this.fireEvent("input")
                }
                return this
            }
```
function myself.

## Expected Behavior
something like ```editor.undo``` to connect it manually to a button in the Toolbar.

Great free editor thx nhn.

**Comment by seonim-ryu** [comment]
@werthd 
We've provided the feature to customize the toolbar. Can you check this example?
* https://nhn.github.io/tui.editor/latest/tutorial-example11-customize-toolbar

Please comment if you can't use this feature to implement the feature you want.

**Comment by werthd** [comment]
@seonim-ryu 
Thanks for the response.
This is the part i was able to figure out (and it worked).
My question was if there is a function to get the same effect as pressing the cmd|str + z buttons.
Something like ``` editor.undo ```.

Btw: it is not about the toolbar but about the Function it should trigger.

**Comment by seonim-ryu** [comment]
@werthd 
I got it! There are apis in the editor that return an instance of the Markdown or WYSIWYG editor.

First, call each api as shown below to get an instance depending on the editor mode.
```js
const mde = editor.getCodeMirror();
const wwe = editor.getSquire();
```
The `mde` is an instance of [Code Mirror](https://codemirror.net/doc/manual.html), the `wwe` is  an instance of [Squire](https://github.com/neilj/Squire/blob/master/README.md). And by calling the methods on each instance, you can implement the logic you want. (e.g. https://github.com/neilj/Squire/blob/master/README.md#undo)

```js
mde.undo();
wwe.undo();
```

When the button is clicked, you can call each of the following codes depending on the editor mode.

Can you check it?

**Comment by werthd** [comment]
Perfekt!
I just tried it and thats exactly what i wanted.
Thanks for your help and time!
