### ISSUE TITLE
[Question] Can we set Tab space in WYSIWYG mode?

### ISSUE THREAD

**Issue by kelvinkoko** [nhn/tui.editor#670]
Currently it is 2 space for Tab, can I set it to 4?

**Comment by seonim-ryu** [comment]
@kelvinkoko 
Currently that feature is not available. Can you explain why you need it?

**Comment by kelvinkoko** [comment]
@seonim-ryu 
From my application user base, I got certain request about whether can change the tab to 4 space.
I think it is kind of user preference. 
It may not be something everyone want. If I want to modify it, do you have any suggestion of which part of source code I can check about it.

**Comment by seonim-ryu** [comment]
@kelvinkoko Sorry, the answer is late.
But I have a question. In WYSIWYG, the tab is entering 4 spaces.

![tab](https://user-images.githubusercontent.com/18183560/68383077-486d4980-0198-11ea-829d-2f2da4e8527e.gif)

Didn't you originally ask that you want to change 4 to 2?
