### ISSUE TITLE
为什么光标只能在正中间?

### ISSUE THREAD

**Issue by Nisus-Liu** [nhn/tui.editor#673]
如图, 光标只能在正中间, 无法左右移动.
![image](https://user-images.githubusercontent.com/18654833/68068288-dfe42e00-fd8d-11e9-8b05-6a7860fc11ab.png)

**Comment by jack9603301** [comment]
Please write issues in English. Foreigners may not understand you. Thank you!

请使用英文书写issues，外国人可能无法读懂你的话。谢谢！

**Comment by seonim-ryu** [comment]
@Nisus-Liu 
I translated and came out like this. Did you ask this?

> 为什么光标只能在正中间?
Why is the cursor only in the middle?

> 如图, 光标只能在正中间, 无法左右移动.
As shown in the figure, the cursor can only be in the middle and cannot be moved left and right.

First I can't see what's wrong with this. And I guess the style you are using overrides the editor's style.

I can't confirm the issue and close it. If necessary, clear the issue and then reopen it.
