### ISSUE TITLE
Need to Customize the Text size of Viewer/Editor

### ISSUE THREAD

**Issue by shanhuiyang** [nhn/tui.editor#674]
## Version
The latest, I am using React Wrapper v1.0.1

## Test Environment
Chrome, OSX

## Current Behavior

The font size is too small to read, either in Viewer or Editor.
In the same browser comparing plan text in Tui.editor Viewer/Editor and Github, the font size of text in Tui.editor is too small. 

Even I enlarge the font-size in html and body css selector, the font size of other part of site will become bigger, but the text in Viewer wont't change, still too small.

It's seems like Tui.editor did not provide any interface to change the appearence of the element.

## Expected Behavior

Tui.editor provide a option to change the base font-size in px.

## Update
I checked out the file tui-editor-contents.css, found that the selector

.tui-editor-contents {
    font-size: 13px;
    margin: 0;
    padding: 0;
}

the size of plan text is absolute, i.e. use px instead of rem. So change the body font-size is useless.

I wonder if we can add an option to customize the font while we initialize the Editor or Viewer?
I don't want to change the css file in dist folder because that folder is ignored by git.

**Comment by shanhuiyang** [comment]
I can add a .css and include following to resolve the issue, then import the .css file after import the tui-editor-contents.css.

.tui-editor-contents {
    font-size: 1.1rem;
}

This looks good.

**Comment by Simhyeon** [comment]
I know this is old but you can also change font size of markdown editor without losing dragging feature with following css code.

.CodeMirror-lines {
font-size: 1.1rem;
}
