### ISSUE TITLE
Markdown right after a line of HTML is parsed, unlike CommonMark/GFM

### ISSUE THREAD

**Issue by outloudvi** [nhn/tui.editor#690]
## Version
Latest (v1.4.8 currently)

## Test Environment
Microsoft Edge 80.0.320.5 (Official build) dev (64-bit)

## Current Behavior
A sample is:

``` markdown

<br>
**test**
```

(P.S. The line before `<br>` need to be an empty line or nothing (i.e. The <br> is at the beginning of a document))

In TUI Editor's [demo page](https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic) it shows:

![Results for TUI](https://user-images.githubusercontent.com/19144373/68860531-a368e880-0724-11ea-866e-f18c529f4f4d.png)

## Expected Behavior
On [Commonmark's Dingus](https://spec.commonmark.org/dingus/) it shows:

![Results for Commonmark](https://user-images.githubusercontent.com/19144373/68860583-c398a780-0724-11ea-88ac-5bfa6675dc52.png)

Since markdown-it is on the `package.json`, I had a check on [`markdown-it`'s demo](https://markdown-it.github.io/) and it shows:

![Results for markdown-it on default settings](https://user-images.githubusercontent.com/19144373/68861017-a6b0a400-0725-11ea-8ec6-1df93890f222.png)

This part seems to be complying with neither CommonMark nor GFM. Is it a bug, or as said in #88, a part of "TOAST-flavored Markdown"?

**Comment by seonim-ryu** [comment]
@outloudvi Sorry for the late comments.

This is the latter. That's "TOAST-flavored Markdown." Currently, the `<br>` used in the editor is used for blank lines. So if the editor follows the common mark spec, the editor won't handle the following:

1. Enter a blank line and then bold the text in WYSIWYG.

![wwe](https://user-images.githubusercontent.com/18183560/69508934-225fdd00-0eec-11ea-861b-1cc1231c24fc.png)

2. `<br>` and bold styles should be preserved when converting to Markdown.

![mde](https://user-images.githubusercontent.com/18183560/69508999-428f9c00-0eec-11ea-9ba6-85759d0c1dbc.png)

Additionally, in the Markdown preview, the editor handles it internally so it doesn't break when `<br>` follows `**foo**`.

Then check it out.

**Comment by seonim-ryu** [comment]
@outloudvi Sorry for the late comments.

This is the latter. That's "TOAST-flavored Markdown." Currently, the `<br>` used in the editor is used for blank lines. So if the editor follows the common mark spec, the editor won't handle the following:

1. Enter a blank line and then bold the text in WYSIWYG.

![wwe](https://user-images.githubusercontent.com/18183560/69508934-225fdd00-0eec-11ea-861b-1cc1231c24fc.png)

2. `<br>` and bold styles should be preserved when converting to Markdown.

![mde](https://user-images.githubusercontent.com/18183560/69508999-428f9c00-0eec-11ea-9ba6-85759d0c1dbc.png)

Additionally, in the Markdown preview, the editor handles it internally so it doesn't break when `<br>` follows `**foo**`.

Then check it out.

**Comment by outloudvi** [comment]
Okay. I see that, thanks!
