### ISSUE TITLE
Exception thrown when pasting example code into WYSIWYG editor

### ISSUE THREAD

**Issue by docent** [nhn/tui.editor#693]
## Version
1.4.8

## Test Environment
Linux, Chromium 78.0

## Current Behavior
Open the editor "basic" example, select the example below and paste into WYSIWYG editor:
<pre class="hljs language-js"><code><span class="hljs-keyword">var</span> foo = <span class="hljs-function"><span class="hljs-keyword">function</span> (<span class="hljs-params">bar</span>) </span>{
  <span class="hljs-keyword">return</span> bar++;
};
</code></pre>

## Expected Behavior
No exceptions should be thrown, but the following exception is thrown:
```
TypeError: Cannot set property 'innerHTML' of null
    at VM25 tui-editor-Editor-full.js:107801
    at Array.forEach (<anonymous>)
    at WwClipboardManager._replaceNewLineToBr (VM25 tui-editor-Editor-full.js:107799)
    at WwClipboardManager._preparePaste (VM25 tui-editor-Editor-full.js:107947)
    at WwClipboardManager._onWillPaste (VM25 tui-editor-Editor-full.js:107813)
    at WwClipboardManager._executeHandler (VM25 tui-editor-Editor-full.js:107707)
    at VM25 tui-editor-Editor-full.js:107685
    at VM25 tui-editor-Editor-full.js:36952
    at forEachArray (VM25 tui-editor-Editor-full.js:11653)
    at Object.forEach (VM25 tui-editor-Editor-full.js:11730)
```

**Comment by seonim-ryu** [comment]
@docent 
That's right. Thanks for the bug report.

**Comment by seonim-ryu** [comment]
## Case 1

When plain text containing a newline is pasted into the editor, the newline should be changed to `<br>`.

```html
<span class="highlight" style="..."><span class="colour" style="..."><span class="font" style="..."><span class="size" style="font-size:13px">foo
bar</span></span></span></span>
```

## Case 2

Newline characters should be preserved when text containing newline characters in the code block is pasted into the editor.

```html
<pre style="..."><code style="..."><span style="box-sizing: border-box;">var</span> foo = <span style="box-sizing: border-box;"><span style="box-sizing: border-box;">function</span> (<span style="box-sizing: border-box;">bar</span>) </span>{
  <span style="box-sizing: border-box;">return</span> bar++;
};</code><br></pre>
```
