### ISSUE TITLE
Adjust the action buttons' order on the editor bar.

### ISSUE THREAD

**Issue by shanhuiyang** [nhn/tui.editor#695]
##  Version
the latest, I am using the React Wrapper v1.0.1

## Test Environment
Chrome, OSX

## Current Behavior
The order of the action buttons cannot be adjusted.

## Expected Behavior
I would like to adjust the order of action buttons. For example, I thin **image insertion is the most useful action for my customers**, then I would like to put the insert image button in the first place. It looks like there is no way to do that now.

**Comment by seonim-ryu** [comment]
@shanhuiyang 
The editor provides an `toolbarItems` option. The toolbar is managed as an array and defaults to:

https://github.com/nhn/tui.editor/blob/4be7ee2ab1fb82a8fb498e86c92c4eeec304ffda/src/js/editor.js#L152-L172

I think you can use this option if you want.

```js
toolbarItems: [
  'image',
  // ...
],
// ...
```
