### ISSUE TITLE
Code block identified as HTML

### ISSUE THREAD

**Issue by keac** [nhn/tui.editor#696]
## Version
1.4.8

## Test Environment
Chrome78 Windows10

## Current Behavior

```js

?name=<img onerror=.alert(/xss/) src=1 > (Delete . )

```

## Expected Behavior

Show ```?name=<img `` no onerror and =

**Comment by seonim-ryu** [comment]
@keac 
I don't know what's wrong with this description. Is it a problem because it looks like this in Markdown?

![md](https://user-images.githubusercontent.com/18183560/70036063-dc002300-1568-11ea-9491-c22a44ca51ca.png)

**Comment by keac** [comment]
I want show this code in markdown `?name=<img onerror=.alert(/xss/) src=1 >` (del dot) , not `?name=<img `
