### ISSUE TITLE
Add custom button to insert html after user input

### ISSUE THREAD

**Issue by vsoch** [nhn/tui.editor#697]
## Version
1.4.6

## Test Environment
linux on Chrome and Firefox (not relevant)

## Current Behavior
Hey maintainers! I'm really loving the editor so far - it's met every single one of my needs! I have a quick question - I'm looking to add a custom button that, on click, takes user input and then inserts a custom span element. I was able to easily find the code for [adding a button](https://github.com/nhn/tui.editor/blob/master/examples/example11-customize-toolbar.html#L73) and then I can create a [custom event](https://github.com/nhn/tui.editor/blob/master/examples/example11-customize-toolbar.html#L89) to link to it, and I'm hoping you can point me (or tell me) after I've collected some content in the custom event, how I can insert it directly where the user cursor is?

I hope this is easy to answer - thank you kindly!

**Comment by seonim-ryu** [comment]
@vsoch 
The editor currently provides the instance that manages the cursor position and the text in the selection. I think you can use this instance. 

Calling [`editor.getTextObject()`](https://nhn.github.io/tui.editor/latest/ToastUIEditor#getTextObject) will return an instance of [`MdTextObject`](https://nhn.github.io/tui.editor/latest/MdTextObject) in Markdown mode and an instance of [`WysiwygEditor`](https://nhn.github.io/tui.editor/latest/WwTextObject) in WYSIWYG mode. This allows you to add text to the current cursor.

```js
editor.eventManager.listen('customEvent', () => {
  const textObj = editor.getTextObject();
  const range = editor.getRange();

  textObj.setEndBeforeRange(range);
  textObj.replaceContent('hello editor world!');
});
```

Is this the feature you're trying to implement? Please check! :)

**Comment by vsoch** [comment]
This is totally perfect! I'm going to work on it now and I'll post here with questions, and update if/when I get everything working. Thank you for the prompt reply, and for leaving the issue open as I figure this out.

**Comment by vsoch** [comment]
okay all set! I was able to add a custom button, and link it to a modal that takes user input, and on submit inserts a custom span into the editor, screenshots here:

https://vsoch.github.io/askci/docs/getting-started/#edit-an-article

Thank you so kindly for your help, and for this beautiful editor!

**Comment by seonim-ryu** [comment]
@vsoch 
I checked the link you gave me. Your project is awesome!!! Thank you for using the editor. 🙏
