### ISSUE TITLE
Markdown code formatting is different from output formatting

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [nhn/tui.editor#70]
## Version
1.0.2

## Test Environment
Firefox Developer Edition (latest), nw.js (webkit latest).

## Current Behavior
Go to https://nhnent.github.io/tui.editor/
Write
```
****text****
**text**
```

First 'text' is not bold in a code view but is rendered as bold. The second 'text' is ok. So the markdown syntax highlighting in code view is buggy.

The same affects four underscores (`____text____`).

## Expected Behavior
Text formatting should be correct for both views (`****text****` should be shown as a bold text).

**Comment by kyuwoo-choi** [comment]
it's the codemirror issue.

https://github.com/codemirror/CodeMirror/issues/5271

**Comment by seonim-ryu** [comment]
Resolved in v2.0 to close this issue.

## v1.4.x
![v1.4.x](https://user-images.githubusercontent.com/18183560/77281967-fa528000-6d0b-11ea-8873-6c4549e0f813.png)

## v2.0.0
![v2.0.0](https://user-images.githubusercontent.com/18183560/77282019-1e15c600-6d0c-11ea-835e-63738f6feb74.png)

## CommonMark
![CommonMark](https://user-images.githubusercontent.com/18183560/77282061-40a7df00-6d0c-11ea-818f-134da9e7f89d.png)
