### ISSUE TITLE
Feature request: lazy loading of images

### ISSUE THREAD

**Issue by Machiaweliczny** [nhn/tui.editor#702]
### Motivation:

As browser are capped by default to ~5 http connections per domain, loading of images can block modern SPA applications unless served from different (sub)domain. 

### Implementation:

Having this in mind it would be very nice if `tui.editor` had lazy loading of images implemented. For newer browser it would be enough to just add `loading="lazy"` attribute. More info at https://web.dev/native-lazy-loading/

Not sure if this is desired in all cases so probably would be nice if this was configurable.

I'm thinking this probably can be easily implemented by writing extension - https://github.com/nhn/tui.editor/blob/master/docs/writing-your-own-extension.md

If you can guide me a little how can I add such extension (how to find IMG nodes in editor) then I could contribute such functionality.

BTW would be really nice if you had codesandbox link or similar in https://github.com/nhn/tui.editor/blob/master/docs/writing-your-own-extension.md documentation.

**Comment by seonim-ryu** [comment]
@Machiaweliczny Thanks for the good idea! 

The `loading` attribute has browser limitations and can't be taken to the editor's default functionality, but as you say, this feature can be handled using extensions. I'm testing it now, and I'll give you a comment after the test is over.
