### ISSUE TITLE
The data changes when I move between markdown and wysiwyg mode.

### ISSUE THREAD

**Issue by web24365** [nhn/tui.editor#705]
I used to make my own css style. ex:<mark-yellow>
Thinks likely commonly used ex:\<b\> operate normally but the sytle I make changes.

Markdown mode:
~~~
<mark-yellow>environ</mark-yellow>
<b>desc</b>
~~~

click wysiwyg mode:
~~~
environ
<br>
<b>desc</b>
~~~

\<make-yellow\> tag is disappeared.
add \<br\> tag.

after that, I add the \<make-yellow\> tag in Markdown mode again and then I go back to wysiwyg mode.
The tag disappears again and the \<br\> tag is added.
I have two \<br\> tag.

The more it repeats, the more it is added.

~~~
<script>
    var $el = $('#{{ widget.attrs.id }}');

    var editor = $('#editor_{{ widget.attrs.id }}').tuiEditor({
        initialEditType: 'markdown',
        previewStyle: 'vertical',
        initialValue: $el.val(),
        height: 'auto',
        events: {
            change: function() {
                var markdown = editor.data('tuiEditor').getMarkdown();
                $el.val(markdown);
            }
        }
    });
</script>
~~~

**Comment by seonim-ryu** [comment]
@web24365 
You can't use custom tags in the editor. According to the CommonMark specification, [custom tags can be used in markdown mode](https://spec.commonmark.org/0.29/#example-133), but the editor restricts the use of custom tags for data compatibility with WYSIWYG. So when you convert to WYSIWYG, it's normal for the tags you enter to disappear.

**Comment by isecure-kr** [comment]
I didn't know much about that part. thanks for your answer.

**Comment by web24365** [comment]
I didn't know much about that part. Thank you for your answer.
