### ISSUE TITLE
Editor capitalizing some code blocks

### ISSUE THREAD

**Issue by vsoch** [nhn/tui.editor#707]
hey @nhn another quick question! I can't reproduce this on my computer (I have Ubuntu 16.04 and Firefox) but some of my testers are reporting that the markdown renderer mysteriously capitalizes some code block letters. For example, take a look at the `-l` rendered below:
![image](https://user-images.githubusercontent.com/814322/70402323-d468d000-19e7-11ea-9467-cc5d1c317034.png)

It of course doesn't come through in the raw text submit via the interface, but the rendering. Any ideas for what we can look for / test?

**Comment by seonim-ryu** [comment]
@vsoch Hmm ... it doesn't reproduce when I check.

The first thing to check is that all characters are converted to uppercase?
Just looking at the screenshots, does the lowercase **i** look like an uppercase **L** because of the _font style_?

**Comment by vsoch** [comment]
I can't produce it either, and just checked the editor for some font setting (I don't see one!) I'm going to ping @katgit to get her feedback on the font her browser is using. @katgit and what browser / OS produces the error (and did another browser not?) Can you check what browser extensions are on?

**Comment by katgit** [comment]
Hi, I tried to use Chrome and Firefox and in both editors I get the same behavior: all lowercase "-l" symbols are turned into uppercase"-L" 
![image](https://user-images.githubusercontent.com/6410612/70489946-1880d100-1acb-11ea-9dd9-48379bc321e6.png)

**Comment by katgit** [comment]
I used the same browsers to view if the same behavior happens if I use the same bash script code within README.md file in github and it does not. Everything works perfectly fine in that environment.

**Comment by seonim-ryu** [comment]
@katgit Thank you for your detailed description.

Can you confirm two more things?

First of all, the Markdown Preview in the editor(right screen of markdown mode) uses the renderer of [markdown-it](https://github.com/markdown-it/markdown-it). Can you check the same issue in the demo page below?

* https://markdown-it.github.io/

Secondly, when you view an element in Chrome Developer Tools, can you check the text value of that element?

![developer tools](https://user-images.githubusercontent.com/18183560/70674009-e38d9d80-1cc7-11ea-88d8-5bf3cd3b014f.png)

**Comment by katgit** [comment]
Here is a screenshot output from markdown-it.github.io:

![bug1](https://user-images.githubusercontent.com/6410612/70675568-835f1300-1c57-11ea-827f-e5ddd5125f8f.png)

**Comment by katgit** [comment]
To answer the second question: The HTML source code for the element it is correct:
<span class="hljs-comment">#!/bin/bash -l</span>

**Comment by katgit** [comment]
I also just copied the output from the window on the right and pasted it into a text editor and I got lowercase l. From all these experiments I conclude that the issue is related to the font that is being used to display the output. In this particular font the lowercase l looks like L. 

I looked at the element font family and it is coded as:

font-family: Consolas, Courier, "Apple SD 산돌고딕 Neo", -apple-system, "Lucida Grande", "Apple SD Gothic Neo", "맑은 고딕", "Malgun Gothic", "Segoe UI", "돋움", dotum, sans-serif;
    border: 0;

If I paste the content of the "right window" text to the Word it says that "Consolas" font is used, but if I select consolas myself and write a text in the word it looks like this: 
![bug2](https://user-images.githubusercontent.com/6410612/70676234-73483300-1c59-11ea-971f-2b81a734fe5b.png)

**Comment by katgit** [comment]
But if I make it Italic then I get the same weird looking l that looks like L:
![bug3](https://user-images.githubusercontent.com/6410612/70676320-d0dc7f80-1c59-11ea-9485-95cf6df93252.png)

**Comment by katgit** [comment]
In my word document it is not very bad, but I guess in the browser and when the font size is small, then the letter looks like L

**Comment by seonim-ryu** [comment]
@katgit Oh, very detailed! Thanks. And I found the environment you talked about, tested it, and confirmed the issue.

![windows-chrome](https://user-images.githubusercontent.com/18183560/70712655-9c36f980-1d27-11ea-9bad-b93ad2bbd819.png)

But the font family that is the cause of the current issue is the default style, so it's hard to change right now. The major version may have to change.

If this is the case, you can override the default font family in your product. 🤔

> https://github.com/nhn/tui.editor/blob/53ab4e10f93271741ebe4149bf1a380bc7d8aab5/src/css/tui-editor.css#L1158-L1159

**Comment by vsoch** [comment]
@katgit I just reduced the set of default fonts for the editor on askci, see here https://github.com/vsoch/askci/blob/master/askci/apps/main/templates/articles/article_details.html#L11 It's live if you want to test it out! Let is know if the issue is resolved. If not, @seonim-ryu you might take a look and let me know if I removed the wrong ones.
