### ISSUE TITLE
<br> tag after a Line is added at every getMarkdown

### ISSUE THREAD

**Issue by DellaMoraWalter** [nhn/tui.editor#710]
##  Description
If after a Line there is a ```<br>``` and after that some other text, the getMarkdown function add an extra ```<br>```.

## To Reproduce
1. Go to https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic
2. Switch mode to WYSIWYG
3. Add a Line with toolbar button
4. Press enter
5. Add some text
6. Switch mode to Markdown
7. Switch mode to WYSIWYG
8. Repeat from 6 how many times you want

## Version
1.4.10

**Comment by seonim-ryu** [comment]
It seems to be related to this issue.

> https://github.com/nhn/tui.editor/issues/624

**Comment by peymanforceman** [comment]
I have the same issue , it makes <br> tags ( when I enter a few times ) on WYSIWYG mode and then moving back to Markdown mode.

**Comment by BjoernRave** [comment]
this issue still exists
