### ISSUE TITLE
https://nhnent.github.io/ site not found

### ISSUE THREAD

**Issue by pansila** [nhn/tui.editor#712]
## Describe the bug
Site not found for https://nhnent.github.io/, all docs on the site are not found.

## To Reproduce
1. open the rul https://nhnent.github.io/ in a web browser
2. See error

## Expected behavior
The page should be available

## Desktop (please complete the following information):
 - OS: Windows 7
 - Browser: Chrome 79
 - Version: NA

**Comment by seonim-ryu** [comment]
@pansila 
This year our company's name changed. So the organization name of the GitHub repository has changed. **nhn** is right.

Anything that is **nhnent** in the url has been changed to **nhn**. Is there a place that is still exposed as **nhnent**? If so, please report it!

**Comment by last-partizan** [comment]
@seonim-ryu docs are missing at new address: https://nhn.github.io/tui.editor/api/latest

And here is 404 too: https://nhn.github.io/

**Comment by seonim-ryu** [comment]
@last-partizan 
Oops ... the API document's URL has changed. Changed to make the url the same as the other products in TOAST UI.

Have you ever seen a web page that is exposed with a previous url? If so, please let me know?

**Comment by last-partizan** [comment]
No, i haven't seen it, just followed some links from don't remember where already :)

I've found correct links and it's working https://nhn.github.io/tui.editor/latest/

**Comment by seonim-ryu** [comment]
This seems to have been resolved, so I'll close it. :)
