### ISSUE TITLE
Prevent escaping underscores with '\' when going from WYSIWYG to Markdown?

### ISSUE THREAD

**Issue by michael-roschenwimmer** [nhn/tui.editor#715]
Hello,

It seems that underscores are escaped with a backslash '\' when you go from WYSIWYG mode to Markdown mode. For example:

**WYSIWYG** :     

> `test_test_test`

**Markdown** :     

> `test\_test\_test`

What is the best way to prevent this or stop it from occurring? Do we need to customize the regex in `markdownTextToEscapeRx`?

Thank you in advance!

**Comment by seonim-ryu** [comment]
@michael-roschenwimmer 
We had some issues, so the `_`, `*`, `~`, and backtick(`) characters entered in WYSIWYG all escaped when converted to Markdown.

> tui-editor : https://github.com/nhn/tui.editor/issues/617
> to-mark : https://github.com/nhn/to-mark/issues/30

Unfortunately, there is currently no way to control this with options in the editor. :(

**Comment by michael-roschenwimmer** [comment]
@seonim-ryu 
I see. Thank you for following up with me!
