### ISSUE TITLE
Disable Certain Markdown Tags

### ISSUE THREAD

**Issue by theopathy** [nhn/tui.editor#723]
I would like to disable the image tag within the editor viewer if this possible? I couldn't find anything so I'm sorry if I'm being blind. Thank you

**Comment by seonim-ryu** [comment]
@theopathy 
The editor doesn't provide that feature. But I think you can do it this way. The editor can use html in markdown data, use the `<img>` tag and then style when using the image. You can refer to the value set in the `initialValue` option in the example below. How is this way?

```js
const instance = new Viewer({
  el: document.querySelector('#viewer'),
  previewStyle: 'vertical',
  height: '500px',
  initialValue: `<img src="" style="display:none;" />`,
  plugins: [Viewer.plugin.chart]
});
```
