### ISSUE TITLE
에디터 툴바 item 관련 질문입니다 :-)

### ISSUE THREAD

**Issue by moonja89** [nhn/tui.editor#728]
## Version
tui.editor-1.4.10

## Development Environment
Chrome

## Current Behavior
에디터 컴포넌트 중 정렬, font-size, font-family 설정 하는 부분이 없어 추가하고자 합니다
There's no features for font-size, font-align, font-fam configuration, so wanna add the functions.

```js
editor.eventManager.addEventType('evt1');
editor.eventManager.listen('evt1', function() {
        var wwe = editor.wwEditor;
        var sq = wwe.getEditor();
        wwe.focus();
        if (sq.hasFormat('table')) {
            editor.exec('AlignCol', 'left');
        } else {
            // 1 선택되어 있는 text 또는 전체 text return - need to get whole text or selected text
            // 2 tag 에 class 또는 style 추가 - add some class or style to tag
            // 3 content replace
        }
    });

var toolbar = editor.getUI().getToolbar();
    toolbar.addButton(
        [{
            name: 'customize',
            className: 'fab fa-accessible-icon',
            event: 'evt1',
            tooltip: '왼쪽 정렬', //left align
            $el: $('<button type="button" class="custom-button" style="color: #e790c7; font-weight: bold;">L</button>')
        }], 1);

```

## Expected Behavior
기본 적으로 wysiwyg사용토록 했고, using 'wysiwyg',
1. 툴바 버튼 생성 create toolbar button
2. table에서의 정렬 버튼 실행 / contents 내 정렬 버튼 실행  Set the text alignment for text in table or div tag
3. 현재 드래그 된 위치의 행 전체 tag 또는 선택이 안돼 있다면, 에디터를 감싸고 있는 tag 및 text return 부터 막혀있습니다 ㅠ
stuck in getting return the text 

1 선택되어 있는 text 또는 전체 text return
2 tag 에 class 또는 style 추가
3 content replace

원하는 작업을 하고 싶은데, 실력이 딸려서 힘드네용 도움 부탁드립니다 ㅠ_ㅠ

**Comment by seonim-ryu** [comment]
@moonja89  Thanks for the detailed question first!

I understand what you asked. I think you want to select a portion of the text you entered and replace that text. I have a similar question before, so please refer to the link below. That's how you use the `TextObject`.

> https://github.com/nhn/tui.editor/issues/697#issuecomment-561059689

And in our policy, all questions and answers on GitHub Issue are in English. So if possible, can you change it to the English issue you posted? I would appreciate it. 🙏

**Comment by moonja89** [comment]
sure!
