### ISSUE TITLE
Optional dependencies with webpack

### ISSUE THREAD

**Issue by mredaelli** [nhn/tui.editor#730]
## Summary
When analyzing the bundle for my app, generated with webpack, with `webpack-bundle-analyzer`, I see:

- ~~`tui-editor-Editor-all.js` and `tui-editor-Editor.js`. They are suspiciously similar in size. Are they both necessary?~~
- `highlight.js`. Is this a hard dependency, or can it be removed? I don't need highlighting, so I'd be happy to remove it. Using the `IgnorePlugin`  I tried removing the whole `highlight.js`, but my `vendor` bundle tries to load it, so not sure what to do (I will try removing the languages, which are most of the size, but I would still prefer to remove it completely)
- `codemirror`. Is this also a hard dependency?
- ~~`tui-chart`. We have no need of this. Can it be removed?~~

Edit: the first and last were due to a bad import statement. The remaining two are still a problem :)

## Version
1.4.6

## Additional context
This is an angular app

**Comment by douglasg14b** [comment]
I'm very much interested in getting rid of HighlightJS and Codemirror when it's not needed.

As it currently stands TUI Editor accounts for ~50% of the bundle size of our application... 

![image](https://user-images.githubusercontent.com/1400380/73309311-d7599300-41d6-11ea-9777-86117eb4f7c2.png)

**Comment by mredaelli** [comment]
I was able to remove `highlight.js` with a webpack hack, which I can share, but I think codemirror is necessary :)

**Comment by seonim-ryu** [comment]
@mredaelli @douglasg14b Thanks for the good comments! :)

We also know a big bundle size issue. So now we're working on changing the editor to import only the languages ​​needed, not the way including all languages ​​of `hightlight.js`. If this is done, I think it's possible to turn off the highlighting you said.

The `CodeMirror` is used in the markdown editor, which makes them hard to remove. However, there are some areas to improve, so I plan to proceed later.

**Comment by seonim-ryu** [comment]
@mredaelli @douglasg14b In v2.0, hightlight.js has been separated into the [code-syntax-highlight plugin](https://github.com/nhn/tui.editor/tree/master/plugins/code-syntax-highlight). So this issue is closed. :)
