### ISSUE TITLE
Invoking Bold action incorrectly formats text a Bold & Italic

### ISSUE THREAD

**Issue by rwhepburn** [nhn/tui.editor#736]
## Describe the bug
Invoking the Bold action when the cursor is at the start of a line temporarily causes both the **Bold** and **Italic** toolbar actions to appear selected.

## To Reproduce
1. Open the basic editor example: https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic
2. In the **Markdown Editor (not the WYSIWYG editor)**, on the first line, type a text value (e.g. "Foobar")
3. Place the cursor at the start of the text value.
4. Click the **Bold** toolbar button (or press **CTRL-B** on windows) to invoke the **Bold** action.
5. "\****" is inserted ahead of the text, but unexpectedly both the **Bold** AND **Italics** toolbar button appear enabled, even though only the Bold action was invoked. The **_"Foobar"_** text appear both bolded AND italicized.
6. If instead of clicking the **Bold** toolbar button, you click the **Italics** toolbar button, "\**" will be placed in front of the text, but the **Bold** toolbar button is selected instead of the **Italics** toolbar button. The **"Foobar"** text is only bolded in this case.

## Expected behavior
1. When the **Bold** action is invoked, only the **Bold** toolbar button should be invoked. The text after the cursor should appear only as bolded, not bolded AND italicized.
1. When the **Italics** action is invoked, only the **Italics** toolbar button should be invoked. The text after the cursor should appear only as italicized, not bolded.

## Screenshots
When the cursor is placed before the text and the **Bold** action is invoked:

![image](https://user-images.githubusercontent.com/3857782/73804128-cbe70880-4790-11ea-981a-348339916221.png)

When the cursor is placed before the text and the **Italics** action is invoked:

![image](https://user-images.githubusercontent.com/3857782/73804489-f2f20a00-4791-11ea-9d24-cff4101f5aa1.png)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Chrome
 - Version 79.0.3945.130 64-bit

**Comment by seonim-ryu** [comment]
@rwhepburn Thank you for the detailed explanation first. I think this is an issue that comes from understanding behavior rather than a bug. 🤔

First, the toolbar behavior for the emphasis syntax (`*`, `_`) in the Markdown Editor is: When an emphasis syntax is entered, the toolbar displays a style that can be applied based on the next syntax entered.

It's the same as this situation. (Check in Markdown Editor)

1. Enter `****`
2. Enter text (e.g. `****foo`)
3. Bold and italic buttons are now active in the toolbar
4. Enter `**` or `*` at the end of the text
5. If `**` is entered (e.g. `****foo**`), bold is applied to the text; if `*` is entered (e.g. `****foo*`), italic is applied to the text.

So even if `****` is entered through the toolbar with the cursor in front of the text, the emphasis syntax can be applied according to the following syntax, so the toolbar is activated as it is now. (In the case of italic syntax (`**`) the same)

Please leave a comment if you have any other ideas. Thanks. :)

**Comment by rwhepburn** [comment]
Understanding the edit behavior is certainly tricky. I guess I don't feel the current behavior would be expected by users. The behavior doesn't seem consistent and it is hard to understand why the text formatting in the Markdown editor is different than in the Preview. 

In the screenshot below, the markdown preview looks correct "****test**" (bolded), but in the Markdown editor it's shows as "*****text***" (bolded & italic)

![image](https://user-images.githubusercontent.com/3857782/74051249-9bc48300-49a5-11ea-8192-34719f9039be.png)

Another example:

![image](https://user-images.githubusercontent.com/3857782/74051612-4d63b400-49a6-11ea-8e22-5f4dfb529b23.png)

Would it make sense when emphasizing/italicizing text to use double underscores "_" instead of double asterisks "*"? This may make it more clear in the Markdown editor. For example:

![image](https://user-images.githubusercontent.com/3857782/74052084-47ba9e00-49a7-11ea-9f93-1127f23428f4.png)

**Comment by seonim-ryu** [comment]
@rwhepburn Sorry for the late reply. 😭

As you reported this issue, Markdown Editor had a serious problem with syntax highlighting. The parsers of the modules used in the editing area and the preview area are different, so the syntax highlighting was not synchronized properly. To fix this, **we created and applied a [new parser](https://github.com/nhn/tui.editor/tree/master/libs/toastmark) in 2.0**.

We made the following improvements in 2.0.

* v1.4

![v1 4](https://user-images.githubusercontent.com/18183560/77645899-e5454d80-6fa6-11ea-8d00-8bfe56fefb59.png)

* v2.0

![v2 0](https://user-images.githubusercontent.com/18183560/77646197-6997d080-6fa7-11ea-93e4-0c7bc62e838c.png)

I recommend upgrading to 2.0. I would appreciate it if you try 2.0 and give me a comment. Once I think this issue has been resolved, I'll close it. If there are other issues, please register again! :)
