### ISSUE TITLE
Remove 'JQuery' from custom toolbar

### ISSUE THREAD

**Issue by ryum91** [nhn/tui.editor#750]
## Version
1.4.10

## Development Environment
none

## Current Behavior
JQuery must be used when writing custom toolbar

```js
  interface IButtonOptions {
    className: string;
    $el: JQuery; // change or add 'HTMLElement'
    command?: string;
    event?: string;
    text?: string;
    tooltip?: string;
    style?: string;
    state?: string;
  }
```

## Expected Behavior
Remove 'JQuery' from custom toolbar
or add 'HTMLElement' if possible.

**Comment by seonim-ryu** [comment]
@ryum91 Sorry for the late check. I think it's right to add the `HTMLElement` type. Thanks for reporting the issue. 👍

**Comment by seonim-ryu** [comment]
@ryum91 Fixed issues related to types in TOAST UI Editor 2.0. Could you update it to 2.0 and use it? :)

**Comment by ryum91** [comment]
@seonim-ryu 
Yes. Thank you.

Related to this, I tried to register Bugs.
The type of toolbarItems in EditorOptions is incorrect as `string[]`
Therefore, it is currently used by changing to any[]

https://github.com/nhn/tui.editor/blob/173155852174dbb5ee6279e6b193f205d7d57a2a/apps/editor/index.d.ts#L57

**Comment by ryum91** [comment]
I reference to that [example19-customizing-toolbar-buttons](https://github.com/nhn/tui.editor/blob/master/apps/editor/examples/example19-customizing-toolbar-buttons.html),
Currently, it cannot be written in TypeScript.

Thanks you.
