### ISSUE TITLE
Retrieve editor ColorPicker instance

### ISSUE THREAD

**Issue by Gilles-GitHub** [nhn/tui.editor#751]
Hi,

I'm using tui-editor with the color-picker extension.
It works nice but I would like to customize the preset colors.

I see that I can create an instance of the color picker from scratch independantly from the editor (https://ui.toast.com/tui-color-picker/), but i don't see any way to retrieve the instance created through tui-editor.

I there a way to retrieve this instance in order to modify its options ?
Thanks

**Comment by seonim-ryu** [comment]
@Gilles-GitHub I'm sorry for the late check. You can use the `colorSyntax` option for the color syntax extension. This option was missing a description in the documentation. I'll add this. 😥

```js
const editor = new Editor({
  // ...
  colorSyntax: {
    preset: ['#181818', '#292929', '#393939']
  },
  exts: ['colorSyntax']
});
```

**Comment by Gilles-GitHub** [comment]
Great news ! Thanks for the reply @seonim-ryu
