### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by ernsheong** [nhn/tui.editor#754]
I do not wish to use jQuery in my application, but I would really love to use this editor (once it loses the bloat and jQuery)

Thanks!

**Comment by seonim-ryu** [comment]
@ernsheong I'm working hard to get rid of jQuery in the editor. I wish I could get rid of them and use the editor without the burden of using jQuery. Please wait a bit longer! 👀

**Comment by seonim-ryu** [comment]
@ernsheong Last week TOAST UI Editor was updated to 2.0 and jQuery was removed. I hope you try it. And I'll close this issue!

**Comment by ernsheong** [comment]
That's fantastic. Will give it another spin! Thanks again
