### ISSUE TITLE
First click on bulleted/numbered list is not detected as change

### ISSUE THREAD

**Issue by michgerts** [nhn/tui.editor#757]
## Describe the bug
Clicking on bulleted/ordered list for the first time is not considered a change in text

## To Reproduce
1. Go to  https://jsfiddle.net/hzj2k16c/16/
2. Click on bulleted list or ordered list
3. See that the counter doesn't change unlike for the other options 

## Expected behavior
First bullet/ 1. should be recognised as changes (same as second bullet etc, otherwise it doesn't appear after text save)

## Desktop (please complete the following information):
 - macOS Catalina 10.15.2
 - Chrome 80.0.3987.116

**Comment by seonim-ryu** [comment]
@michgerts I'm sorry for the late check. 😭

If what you describe is like the image below it is a bug.
![ordered](https://user-images.githubusercontent.com/18183560/76047913-8db75180-5fa7-11ea-880f-561040c2288f.png)

Thank you for your report.

**Comment by Imagine-F** [comment]
Hello together,
we are using your rte in a customer project and the customer complained this error too. Is it planned to be fixed? If yes, can you tell when?
Thank you in advance!
