### ISSUE TITLE
"linkAttribute" Property not defined in typescript.

### ISSUE THREAD

**Issue by jinguenee** [nhn/tui.editor#759]
## Describe the bug
"linkAttribute" Property not defined in typescript.
However, the property is defined within JS file.

## Expected behavior
Need "linkAttribute" typescript attribute

## Screenshots
https://github.com/nhn/tui.editor/blob/83d799788cbdbabc5a44a2a37330b9ce5ab54c23/index.d.ts#L35-L55

https://github.com/nhn/tui.editor/blob/83d799788cbdbabc5a44a2a37330b9ce5ab54c23/src/js/editor.js#L136
https://github.com/nhn/tui.editor/blob/83d799788cbdbabc5a44a2a37330b9ce5ab54c23/src/js/editor.js#L228-L233

## Desktop (please complete the following information):
 - OS: [windows10]
 - Browser [chrome]
 - Version [1.4.10]

**Comment by seonim-ryu** [comment]
@jinguenee This issue was fixed in 2.0. I recommend upgrading to 2.0!

> https://github.com/nhn/tui.editor/blob/173155852174dbb5ee6279e6b193f205d7d57a2a/apps/editor/index.d.ts#L62
