### ISSUE TITLE
How can I use events in 1.4.10

### ISSUE THREAD

**Issue by cyrusnimda** [nhn/tui.editor#772]
## Summary
I did migrate from version 1.2.6 to 1.4.10. Problem is that my code is broken now, if I remove events property in the config, all works fine. 

I can't find any example of events in the documentation. Sorry if I missed something.

## Additional context
I have something like this:
```
const instance = new Editor({
  el: document.querySelector('#editorSection'),
  initialEditType: 'markdown',
  previewStyle: 'vertical',
  height: '300px',
  events: [{
        change : () => console.log("changed!")
      }],
});
```

In the past I had the same without the []. Any help would be really appreciated.

## Error message
TypeError: typeStr.split is not a function
    at EventManager._getTypeInfo (tui-editor-Editor.js:3086)
    at EventManager.listen (tui-editor-Editor.js:2997)
    at ToastUIEditor.on (tui-editor-Editor.js:10851)
    at tui-editor-Editor.js:10664
    at forEachArray (tui-code-snippet.js:947)
    at Object.forEach (tui-code-snippet.js:1024)
    at new ToastUIEditor (tui-editor-Editor.js:10663)

**Comment by cyrusnimda** [comment]
I did fix it by adding a listener:
```
const instance = new Editor({
  el: document.querySelector('#editorSection'),
  initialEditType: 'markdown',
  previewStyle: 'vertical',
  height: '300px',
});

instance.eventManager.listen('change', function ( evt) {
  console.log("changed!")
});

```
but it has to be another way, as there is an "events" option in typeScript document.

**Comment by seonim-ryu** [comment]
@cyrusnimda I'm sorry.. I missed your issue while checking the issue. 😭

First, the `event` option value should not be set as an array. It must be set as an object to work correctly. (I will explain based on v1.4.10)

```js
import Editor from 'tui-editor';

const editor = new Editor({
  // ...
  events: {
    change: () => {
      console.log('change!');
    }
  }
});
```

I checked and it seems that JSDoc is wrong. I'll fix this. And a while ago, v2.0 came out, I recommend upgrading and using it!
