### ISSUE TITLE
Can I limit method of uploading images.

### ISSUE THREAD

**Issue by swhoro** [nhn/tui.editor#816]
Can I only enable uploading image by "URL" but disable uploading through "File"?
I don't whether this is possible or how to do this.

**Comment by campbellgoe** [comment]
In my case I want to add an extra option to choose from existing images.

The image popup code can be found here:

https://github.com/nhn/tui.editor/blob/master/apps/editor/src/js/ui/popupAddImage.js

If we could make this popup customizable e.g. simply to be able to configure the tabs and tab content, that could work?

**Comment by campbellgoe** [comment]
You can customize the toolbar with the toolbarItems array option https://nhn.github.io/tui.editor/latest/tutorial-example19-customizing-toolbar-buttons
If you create your own popup and attach it with a custom toolbar item `{ options: { el: customPopupButton() } }` you can then ensure you only have the upload method in your custom UI. Then you can use editor instance along with the method `.exec('AddImage', { altText, imageUrl })` to add the image to the editor/viewer.
