### ISSUE TITLE
Does tui editor support rtl?

### ISSUE THREAD

**Issue by kishorethecoder** [nhn/tui.editor#838]
I have using the tui editor for more than a year and it is awesome. I want to know whether the editor supports rtl?. I have gone through the documentation and couldn't find the option. Can you guide me how to achieve the **rtl** in markdown mode?

**Comment by seonim-ryu** [comment]
@kishorethecoder I'm sorry... what is **rtl**? Could you explain it in more detail? 🤔

**Comment by kishorethecoder** [comment]
Hi @seonim-ryu, rtl stands for right-to-left. Some languages of the world (Arabic, Hebrew etc.) are RTL, meaning they are read right-to-left, instead of left-to-right.

**Comment by seonim-ryu** [comment]
@kishorethecoder Thanks for the detailed explanation! :)
Unfortunately, RTL is not supported in the editor.

**Comment by ubershmekel** [comment]
Hey stale bot. One month is all it takes to shut down an issue? I'd like to vote to keep this open.

**Comment by carsnwd** [comment]
We've been able to kind of hack around the CSS styles and get most of it RTL when needed....just the typing isn't. It isn't a standard text area/input element its a div, so doing just direction: rtl doesnt work there.

```
html[dir="rtl"] {
    .tui-editor-defaultUI {
        button {
            float: right !important;
        }
    }
    .tui-editor-contents-placeholder::before {
        position: unset;
        float: right;
    }
}
```
