### ISSUE TITLE
editor.getValue is not a method

### ISSUE THREAD

**Issue by NateScarlet** [nhn/tui.editor#839]
## Describe the bug
#807 removed `getValue/setValue` 

while vue-editor still using it

https://github.com/nhn/tui.editor/blob/d50474ea25a67b71897723e875750ab4e75cbe34/apps/vue-editor/src/Editor.vue#L68

and type definition is not updated.

https://github.com/nhn/tui.editor/blob/d50474ea25a67b71897723e875750ab4e75cbe34/apps/editor/index.d.ts#L588

## To Reproduce
1. Try to use vue-editor
2. Input event never emit

## Expected behavior
No code using removed method

## Desktop (please complete the following information):
 - OS: Windows 7
 - Browser  Chrome 80
 - Version 2.0.0

**Comment by Rorke76753** [comment]
Hi guy, I am using this editor in my application too.Could you show me some example code that getting the value of the content?
I wrap it in my component and I've tried 
```
console.log(this.$refs.editor.getHtml);
```
Every time it prints 'undefined' in console.

**Comment by pepeloper** [comment]
It's already documented right here: [Instance methods](https://github.com/nhn/tui.editor/tree/master/apps/vue-editor#instance-methods
)

`this.$refs.toastuiEditor.invoke('getHtml');`

Anyway the best way to ask these kind of questions it's to open another issue with the question label 👍

**Comment by Rorke76753** [comment]
> It's already documented right here: [Instance methods](https://github.com/nhn/tui.editor/tree/master/apps/vue-editor#instance-methods)
> 
> `this.$refs.toastuiEditor.invoke('getHtml');`
> 
> Anyway the best way to ask these kind of questions it's to open another issue with the question label 👍

Thank you very much , this help me a lot.

Btw,I have already open an issue before this comment.

**Comment by dsvanidze** [comment]
I get this Error `Uncaught TypeError: t.editor.getValue is not a function` if `v-model="editorContent"` is set to the component.  How can I fix it?

**Comment by pepeloper** [comment]
I'm currently listening the `change` event as a workaround

`<Editor ref="editor" @change="onEditorChange" />`

And then assign the document content to a data property:

```
methods: {
  onEditorChange() {
    this.content = this.$refs.editor.invoke('getMarkdown')
  },
}
```

Note that you can invoke any [available method](https://nhn.github.io/tui.editor/latest/ToastUIEditor#addHook), such as getHtml

**Comment by dsvanidze** [comment]
@pepeloper Thank you.

I implemented it in the same way

```ts
onChange(event: any) {
  const markdownText = this.invoke('getMarkdown')
  this.$emit(
    'input',
    (typeof this.value === 'undefined' || this.value === null) &&
      markdownText === ''
      ? this.value
      : markdownText,
  )
},
invoke(tuiMethodName: string) {
  return this.$refs.toastuiEditor.invoke(tuiMethodName)
}
```

However, if v-model does not work we need to check the case, when `value` is `undefined` or `null`.  It will otherwise change `undefined` and `null` values to empty string `''`
