### ISSUE TITLE
react-editor 2.x is not working with typescript.

### ISSUE THREAD

**Issue by nzhl** [nhn/tui.editor#841]
It seems the type declaration of Editor component has set `el` as  required, which is not expected.

![image](https://user-images.githubusercontent.com/16397293/77146028-039ddb80-6ac5-11ea-8b18-3c90cee8794b.png)

**Comment by nzhl** [comment]
A workaround should be 

```
import { Editor } from '@toast-ui/react-editor';
const AnyEditor: React.FC<any> = Editor as any;
```
Then you are free to go without el prop.

**Comment by seonim-ryu** [comment]
@nzhl I confirmed the issue. Thanks for reporting.

**Comment by seonim-ryu** [comment]
## Current Status
![react-editor](https://user-images.githubusercontent.com/18183560/77616950-4143ae00-6f76-11ea-8c0f-36e99abd008b.png)
