### ISSUE TITLE
How to get the content from editor?

### ISSUE THREAD

**Issue by Rorke76753** [nhn/tui.editor#842]
I use the vue wrapper of editor in my application.
I have try 
```
console.log(this.$refs.editor.getHtml);
```
But every time the console prints "undefined".

How can I get the content in the editor correctly?

**Comment by seonim-ryu** [comment]
@Rorke76753 What you called above is to check the existence of the method, so the usage is wrong. When getting the value entered in the current editor, the following instance method should be called.

```jsx
<template>
  <div>
    <button v-on:click="getMarkdown">getMarkdown</button>
    <button v-on:click="getHtml">getHtml</button>
    <editor ref="toastuiEditor" />
  </div>
</template>

<script>
import 'codemirror/lib/codemirror.css';
import '@toast-ui/editor/dist/toastui-editor.css';

import { Editor } from '@toast-ui/vue-editor';

export default {
  components: {
    editor: Editor
  },
  methods: {
    getMarkdown() {
      let markdown = this.$refs.toastuiEditor.invoke('getMarkdown');

      console.log(markdown);
    },
    getHtml() {
      let html = this.$refs.toastuiEditor.invoke('getHtml');

      console.log(html);
    }
  }
};
</script>
```
![vue-editor](https://user-images.githubusercontent.com/18183560/77277118-9d50cd00-6cff-11ea-8723-fe852d9bb03f.png)

**Comment by Rorke76753** [comment]
> @Rorke76753 What you called above is to check the existence of the method, so the usage is wrong. When getting the value entered in the current editor, the following instance method should be called.
> 
> ```js-jsx
> <template>
>   <div>
>     <button v-on:click="getMarkdown">getMarkdown</button>
>     <button v-on:click="getHtml">getHtml</button>
>     <editor ref="toastuiEditor" />
>   </div>
> </template>
> 
> <script>
> import 'codemirror/lib/codemirror.css';
> import '@toast-ui/editor/dist/toastui-editor.css';
> 
> import { Editor } from '@toast-ui/vue-editor';
> 
> export default {
>   components: {
>     editor: Editor
>   },
>   methods: {
>     getMarkdown() {
>       let markdown = this.$refs.toastuiEditor.invoke('getMarkdown');
> 
>       console.log(markdown);
>     },
>     getHtml() {
>       let html = this.$refs.toastuiEditor.invoke('getHtml');
> 
>       console.log(html);
>     }
>   }
> };
> </script>
> ```
> 
> ![vue-editor](https://user-images.githubusercontent.com/18183560/77277118-9d50cd00-6cff-11ea-8723-fe852d9bb03f.png)

Thank you , this help me a lot.

**Comment by serfend** [comment]
![image](https://user-images.githubusercontent.com/20139227/103173235-80e84f00-4894-11eb-9922-213d27318f93.png)
why i get no content but a empty string

**Comment by jack9603301** [comment]
Is there such a way to get content? I remember I didn't do it that way

```
editor.getMarkdown()
```

https://github.com/jackworkshop/WP-ReliableMD/blob/9ba15480897530a933283299e16af55cbe14372c/js/WPReliableMD_Admin.js#L240-L250

**Comment by porndet** [comment]
dsadasda

**Comment by Taichi-morales** [comment]
fcdfdfdfdfdfdf
