### ISSUE TITLE
How to create a custom command that can automatically add content at the cursor

### ISSUE THREAD

**Issue by jack9603301** [nhn/tui.editor#844]
How to create a custom command that can automatically add content at the cursor？

**Comment by seonim-ryu** [comment]
@jack9603301 TOAST UI Editor does not provide a custom command function. Can you tell me what function you want to handle?

**Comment by mistris** [comment]
Hello! I would also like to know how to add custom command. I want to integrate Elfinder (https://studio-42.github.io/elFinder/#elf_l1_RG93bmxvYWRzL0V4YW1wbGU) so that popup window is opened after clicking on custom toolbar button and after that I want to insert the path to selected file at the cursor.

**Comment by jack9603301** [comment]
When I click a command, I can automatically create the latex math environment such as \ (\). I have realized the support of sneaking into mathjax or KAtex in ordinary text (not code block). I also see the method of adding buttons from docs, but I hope to realize this function!

**Comment by sharshach** [comment]
> @jack9603301 TOAST UI Editor does not provide a custom command function. Can you tell me what function you want to handle?

underline

**Comment by Xing-He** [comment]
```js
const CommandManager = editor.commandManager;
const cusCommand = CommandManager.addCommand('markdown', {
  name: 'customCommand',
  exec: (mde, data) => {
    // do some stuff
    const cm = mde.getEditor();
    const doc = cm.getDoc();
    const range = mde.getCurrentRange();

    const from = {
      line: range.from.line,
      ch: range.from.ch,
    };

    const to = {
      line: range.to.line,
      ch: range.to.ch,
    };

    let { text, url } = data;
    const replaceText = `<a src="${url}" class="attachment" target="_blank">${text}</a>`;

    doc.replaceRange(replaceText, from, to, '+customCommand');
  },
});

editor.addCommand(cusCommand);

editor.exec('customCommand', {
  url: url,
  text: fileName,
});
```

- [`addImage` ](https://github.com/nhn/tui.editor/blob/master/apps/editor/src/js/markdownCommands/addImage.js) source code

**Comment by danddinh** [comment]
(Feb 2026): the addCommand above doesn't work for me, seems the param list is different, mine is:
```
function add_ref(Payload) {
        var { Text, Url } = Payload;
        // ToastUI Editor
        const Editor = this.Visual_Editor.getCurrentModeEditor();
        // ProseMirror view
        const View = Editor.view;
        const { state,dispatch } = View;
        const { from,to } = state.selection;

        // ToastUI Editor uses linkUrl in ProseMirror schema, not 'href'
        const Mark = state.schema.marks.link.create({
            linkUrl: Url
        });

        // ProseMirror transform
        const Transform = state.tr
            .insertText(Text, from, to)
            .addMark(from, from + Text.length, Mark);

        dispatch(Transform);
}

editor.addCommand("wysiwyg", "addRef", add_ref);
```
