### ISSUE TITLE
Cannot read property 'offsetTop' of null 

### ISSUE THREAD

**Issue by dbuchet** [nhn/tui.editor#849]
## Describe the bug
React-Editor put in Modal from material-ui triggers a `Cannot read property 'offsetTop' of null` when using Toolbar

## Expected behavior
Toolbar & ContextMenu should work

## Additional context
When Editor is in Portal or Modal component, the `getOffset` loop never reach the end condition `while (element !== document.body) ` 
because of `element.offsetParent` which is not `document.body` for Modal Components.

**Comment by seonim-ryu** [comment]
@dbuchet Is there any problem when creating `@toast-ui/react-editor` using [this](https://material-ui.com/components/modal/)?

I checked your PR, and I think the problem will be solved by `do-while` statement. Would you please check if there was no problem when I handled it the way I reviewed

**Comment by dbuchet** [comment]
Yes, i'm speaking about [this](https://material-ui.com/components/modal/) :)
Your `do-while` statement also fixes the problem. I'll update my PR with your solution
Thanks :)
