### ISSUE TITLE
Random <br> tag on enter more than twice

### ISSUE THREAD

**Issue by chansbro** [nhn/tui.editor#851]
## Describe the bug
In WYSIWYG mode, when you enter more than twice, any extra enter will be shown as `<br>` tag with TUIViewer. 

## To Reproduce
1. Use WYSIWYG mode (not Markdown)
2. Type anything and try to create multiple enters

## Expected behavior
No `<br>` tag should be shown in TuiViewer

## Screenshots
![z](https://user-images.githubusercontent.com/50089847/77381141-74444100-6dc0-11ea-8e85-408ae96f0a7e.PNG)

## Additional context
한국사람입니다 :)

**Comment by seonim-ryu** [comment]
@chansbro Thanks for reporting the issue! :)

**Comment by seonim-ryu** [comment]
@chansbro I was confused with another issue. 😅 It's not a bug, it's TOAST UI Editor's spec. It seems to be the same as the issue below, and I'd like you to check the comments I left earlier.

> https://github.com/nhn/tui.editor/issues/621#issuecomment-528350485

**Comment by XQDD** [comment]
####  I think it is a bug of `wysiwyg` mode, `markdown` mode will not act like this
> I just call getHtml() and set it

![Peek 2020-05-18 10-04](https://user-images.githubusercontent.com/20871761/82167661-1418d980-98ef-11ea-93bd-5351eaae971f.gif)

**Comment by XQDD** [comment]
@seonim-ryu 
Are you sure it's work normally

**Comment by XQDD** [comment]
Well, I think I should use getMarkdown() and set it
