### ISSUE TITLE
@toast-ui/vue-editor   window is not defined

### ISSUE THREAD

**Issue by Hxmic** [nhn/tui.editor#852]
How  to resolve it?

**Comment by seonim-ryu** [comment]
@Hxmic I just don't know what's wrong with this.. Could you explain it in more detail?

**Comment by Hxmic** [comment]
In vue page, import  it,  "window is not defined".

I resolved  it,  in nuxt.

NUXT

first  mkdir  tui-editor.js ,   import  vue-editor  and  vue ,  then  vue use it.

seond  import tui-editor.js ,  in config.index.js

**Comment by farshidrezaei** [comment]
> In vue page, import it, "window is not defined".
> 
> I resolved it, in nuxt.
> 
> NUXT
> 
> first mkdir tui-editor.js , import vue-editor and vue , then vue use it.
> 
> seond import tui-editor.js , in config.index.js

@ChangJoo-Park 

i  do like you , but i get this error:
`Uncaught TypeError: Cannot read property 'install' of undefined`

**Comment by ChangJoo-Park** [comment]
@farshidrezaei are you using Nuxt too?

**Comment by farshidrezaei** [comment]
@ChangJoo-Park

 yes. i use nuxt.

**Comment by ChangJoo-Park** [comment]
@farshidrezaei 

Can you check [this repo](https://github.com/ChangJoo-Park/fix-852-tui.editor-with-nuxt)?

1. create `plugins\tui_editor.client.js`  [code](https://github.com/ChangJoo-Park/fix-852-tui.editor-with-nuxt/blob/master/plugins/tui_editor.client.js)
2. add plugins to `nuxt.config.js` [code](https://github.com/ChangJoo-Park/fix-852-tui.editor-with-nuxt/blob/master/nuxt.config.js#L30-L32)
```js
  // ...
  plugins: [
    '~/plugins/tui_editor.client.js'
  ],
  // ...
```

3. using like this everywhere you want. [code](https://github.com/ChangJoo-Park/fix-852-tui.editor-with-nuxt/blob/master/pages/index.vue#L29-L31)
```html
<!-- in template -->
<client-only>
  <editor />
</client-only>
```



![image](https://user-images.githubusercontent.com/1451365/79830097-ae185f80-83df-11ea-988f-46458e1072b0.png)

I usually use tui.editor this way. I think you will get better answer from authors. good luck 😄

**Comment by farshidrezaei** [comment]
@ChangJoo-Park it's worked. thank you.

**Comment by HarrisonLee1998** [comment]
@ChangJoo-Park I also tried your way in nuxt, but it only works in 'spa' mode, not in 'universal', although add the 'client-only'. this is very strange.

**Comment by ChangJoo-Park** [comment]
@HarrisonLee1998 Please check my repo [here](https://github.com/ChangJoo-Park/fix-852-tui.editor-with-nuxt)

It is universal nuxt application using `npx create-nuxt-app`

**Comment by Hxmic** [comment]
In nuxt  
first: ![image](https://user-images.githubusercontent.com/23522154/80167625-772a8f80-8613-11ea-926d-da618c38162c.png)

second: 
![image](https://user-images.githubusercontent.com/23522154/80167678-975a4e80-8613-11ea-82ac-bc076ff18d04.png)

@HarrisonLee1998
