### ISSUE TITLE
Is it possible to get editor value via class when adding to FormData()?

### ISSUE THREAD

**Issue by brendonexus** [nhn/tui.editor#853]
I have multiple editors on a page, initiated as below:

```
$('.editor').each(function () {
    var uid = $(this).data('uid');
    $('.' + uid).toastuiEditor({
    height: '300px',
    width: '200px',
    initialValue: '',
    initialEditType: 'wysiwyg',
    hideModeSwitch: true
   });
});
```

When I try and get the values from the editors by using the below code I get a getValue() is not defined. 

```
form.children('.editor').each(function () {
   var uid = $(this).data('uid');
   fd.append(uid, $('.' + uid).getValue());
 });
```

I am using the jQuery version with the all.min.js file.

**Comment by seonim-ryu** [comment]
@brendonexus The question you asked seems to be the same as below. I think you can use the `$.toastuiEditor()` function as I commented.

> https://github.com/nhn/tui.editor/issues/837#issuecomment-604172648

 Also, please note that `getValue()` instance method has been removed in v2.0.
