### ISSUE TITLE
Wrap element with fixed position causes "Cannot read property 'offsetTop' of null" in Chrome

### ISSUE THREAD

**Issue by niklas-englert** [nhn/tui.editor#860]
## Describe the bug
Tooltips and other features of the editor aren't working if the editor is inside an element with `position: fixed;` style. The bug applies only to WebKit/Chromium browsers like Google Chrome and Opera (Firefox does fine).   
Note: The fixed element doesn't have to be the first parent element of the editor. That doesn't matter.

## To Reproduce

1. This issue only appears in Google Chrome and Opera (as tested so far). To reproduce do the following steps in Chrome or a direkt fork of the Chromium browser.
2. Go to https://jsfiddle.net/niklasenglert/L59myv2h/5/
3. Hover over the buttons on the editors header. 
4. See (or not see) how no tooltips appear.
5. Press F12 to see the errors throwen inside the console.

## Expected behavior
It should display the tooltips of the editor buttons and don't throw errors in the console.

## Screenshots
Errors on hover:
![](https://niklas-englert.de/s/20200327131725?raw)

No scrolling possible on "Markdown" mode.
![](https://niklas-englert.de/s/20200327131820?raw)

#### Chrome [reproducable]
- User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
 - OS: Linux Ubuntu 18.04
 - Browser: Google Chrome
 - Version 80.0.3987.149

#### Opera [reproducable]
- User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109
 - OS: Linux Ubuntu 18.04
 - Browser: Opera
 - Version 60.0.3255.109

#### Firefox [works fine]
- User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0
 - OS: Linux Ubuntu 18.04
 - Browser: Mozilla Firefox
 - Version 74.0

## Additional context
This bug was discovered by using the editor inside a [Materialize Modal](https://materializecss.com/modals.html).

**Comment by seonim-ryu** [comment]
@niklas-englert I think it seems to be the same issue as [this one](https://github.com/nhn/tui.editor/issues/849). It will be resolved and patched today or tomorrow. Thanks for explaining the issue in detail.

**Comment by niklas-englert** [comment]
@seonim-ryu Thanks for that information. I must have missed the issue #849 on my research in this repo. I'm looking forward to your patch. I really love your software. <3
