### ISSUE TITLE
This dependency was not found:  * toastui-editor in ./node_modules/@toast-ui/editor/dist/i18n/zh-cn.js  To install it, you can run: npm install --save toastui-editor     

### ISSUE THREAD

**Issue by 1124863805** [nhn/tui.editor#862]
This dependency was not found:

* toastui-editor in ./node_modules/@toast-ui/editor/dist/i18n/zh-cn.js

To install it, you can run: npm install --save toastui-editor     

<template>
  <div class="app-container">
    <div ref="toastuiEditor"></div>
  </div>
</template>

<script>
import 'codemirror/lib/codemirror.css'
import '@toast-ui/editor/dist/toastui-editor.css'
import Editor from '@toast-ui/editor'
import '@toast-ui/editor/dist/i18n/zh-cn'
export default {
  name: 'NewsVue',
  data() {
    return {
      editor: null
    }
  },
  mounted() {
    const options = {
      el: this.$refs.toastuiEditor,
      language: 'zh-CN',
      usageStatistics: false
    }
    this.editor = new Editor(options)
  }
}
</script>

<style scoped>

</style>

**Comment by 1124863805** [comment]
`<template>
  <div class="app-container">
    <div ref="toastuiEditor"></div>
  </div>
</template>

<script>
import 'codemirror/lib/codemirror.css'
import '@toast-ui/editor/dist/toastui-editor.css'
import Editor from '@toast-ui/editor'
import '@toast-ui/editor/dist/i18n/zh-cn'
export default {
  name: 'NewsVue',
  data() {
    return {
      editor: null
    }
  },
  mounted() {
    const options = {
      el: this.$refs.toastuiEditor,
      language: 'zh-CN',
      usageStatistics: false
    }
    this.editor = new Editor(options)
  }
}
</script>

<style scoped>

</style>
`

**Comment by seonim-ryu** [comment]
@1124863805 This issue has been fixed and will be patched today or tomorrow. Thanks for reporting the issue.
> Refs. https://github.com/nhn/tui.editor/pull/843

**Comment by seonim-ryu** [comment]
@1124863805 I'll close this issue because it seems to have been resolved. :)

> Refs. https://github.com/nhn/tui.editor/releases/tag/v2.0.1

**Comment by 1124863805** [comment]
ok ，I temporarily changed the editor，try again later
