### ISSUE TITLE
CDN editor/latest still pointing to v2.0.0 instead of v2.0.1

### ISSUE THREAD

**Issue by niklas-englert** [nhn/tui.editor#865]
## Describe the bug
Your CDN  is still resolving the files for the version 2.0.0 instead of the new version 2.0.1 published today (UTC) under [https://uicdn.toast.com/editor/latest/*](#).

## To reproduce
1. Go to [https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js](https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js)
2. See the comment at the top containing the version:
```js
/*!
 * @toast-ui/editor
 * @version 2.0.0 | Wed Mar 18 2020
 * @author NHN FE Development Lab <dl_javascript@nhn.com>
 * @license MIT
 */
```

## Expected behavior
It should send the file [https://uicdn.toast.com/editor/2.0.1/toastui-editor-all.min.js](https://uicdn.toast.com/editor/2.0.1/toastui-editor-all.min.js) starting with:
```js
/*!
 * @toast-ui/editor
 * @version 2.0.1 | Mon Mar 30 2020
 * @author NHN FE Development Lab <dl_javascript@nhn.com>
 * @license MIT
 */
```

**Comment by seonim-ryu** [comment]
@niklas-englert I think some of the CDN files' cache remained. I'll check this situation with the person in charge. First of all, I have updated all the caches. Would you like to check again? Thanks for reporting the issue!

**Comment by niklas-englert** [comment]
It's now sending the v2.0.1 files. As far as I can see, this was not a cache problem, at least not on the client side. The response headers (of e.g. https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js) do not  instruct the user to cache the file:

```http
accept-ranges: bytes
content-encoding: gzip
content-length: 171676
content-type: text/javascript
date: Tue, 31 Mar 2020 08:20:27 GMT
etag: e67125bc28b896a478e2e03e20f918d5
last-modified: Mon, 30 Mar 2020 10:46:31 GMT
status: 304
vary: Accept-Encoding
x-all-audit-logging: False
x-openstack-request-id: tx5bf3c264295941ae9187e-005e82fbb5
x-timestamp: 1585565190.30542
x-trans-id: tx5bf3c264295941ae9187e-005e82fbb5
```

It only uses [ETag headers](https://en.wikipedia.org/wiki/HTTP_ETag) to check on changes and return the status 304 (not modified) if no changes found.  
But I might be wrong. I'm no expert at this.

**Comment by seonim-ryu** [comment]
@niklas-englert I think my explanation was misrepresented.. 😅
What I said was that the process of updating a cache after uploading the editor's CDN file to the server had a problem. It's not the client side's problem.

I would be grateful if you would make sure there are no problems using CDN files. Thanks!

**Comment by niklas-englert** [comment]
@seonim-ryu As I said "It's now sending the v2.0.1 files." so the CDN is working fine. I'll close the issue.
