### ISSUE TITLE
how to add click event on hyperlink? 

### ISSUE THREAD

**Issue by cs-ajay-chakkar** [nhn/tui.editor#868]
I want to add click event on a hyperlink and need to execute some code to show/hide records.
I have the number of records and want to render as pagination, for that using Show more and show less hyperlink but, didn't get click event for the hyperlink, I am passing onclick attribute but editor removes those attributes.

Please suggest how I can achieve this.

**Comment by seonim-ryu** [comment]
@cs-ajay-chakkar Currently, the editor does not provide a click event. To bypass, I think you can use the `event.focus` option of the officially provided editor instance creation options, or informally use the `mousedown` event of `editor.eventManager`, but I don't recommend it.

I don't understand the function you are trying to create, but can you explain it in more detail? I would be grateful if you could explain all the features of the Markdown Editor and WYSIWYG Editor.
