### ISSUE TITLE
execute javascript code on click or on load in preview mode.

### ISSUE THREAD

**Issue by cs-ajay-chakkar** [nhn/tui.editor#869]
Need to execute javascript code on click event or on load of html data but editor removes the attribute of javascript code.
Is there any way to keep these attributes or options to add attributes in the whitelist attributes?

**Comment by seonim-ryu** [comment]
@cs-ajay-chakkar What is **preview mode**? Are you referring to the preview area on the right side in the markdown editor or [Viewer](https://nhn.github.io/tui.editor/latest/tutorial-example04-viewer)? It's hard to understand by just explaining it now.. Could you explain it in more detail?

**Comment by cs-ajay-chakkar** [comment]
@seonim-ryu  need to execute javascript code on onclick method of element render in preview area on the right side in markdown editor.

Here is code is markdown editor - 

```
this is test of markdown editor
<span onclick="somefunction();">show more</span>
```
Need to execute `somefunction()` from preview area on right side in markdown editor.
And one more need to add button as well in markdown but it gets removes from dom.
