### ISSUE TITLE
WYSIWYG Mode: Enter key deletes line unexpectedly

### ISSUE THREAD

**Issue by rfox12** [nhn/tui.editor#872]
This editor looks amazing!  I was playing around with the WYSIWYG editor in your published examples and noticed behavior that made me pause... if you set your cursor at the very beginning of a line (I chose the "Header 4" line) and press the enter key it will simply delete that line.  I (and probably almost anyone) would have expected the editor to insert a blank line in the line above.  This makes me not "trust" the WYSIWYG editor for serious editing.  I'm on latest Chrome Windows 10.

**Comment by js87zz** [comment]
@rfox12 
we checked the bug.
It looks critical. we will fix it ASAP.

**Comment by seonim-ryu** [comment]
@rfox12 This issue has been fixed in the [2.1.0 release version](https://github.com/nhn/tui.editor/releases/tag/v2.1.0) and I will close this issue.
