### ISSUE TITLE
Set style property at Viewer on version 1.0.1 in ReactJS

### ISSUE THREAD

**Issue by doosanpark** [nhn/tui.editor#873]
## Summary
I need to set word-break style on Viewer like this : 

`<Viewer style={{wordWrap: 'break-all', marginBottom: 20}} initialValue={this.state.contents}/`

But I failed to do this.
What should I do?

cf) word-break is a style that split a word if the word long enough to get out of form

## Version
1.0.1

**Comment by js87zz** [comment]
@doosanpark 
Currently, The editor option is only allowed to react-wrapper as props so that style props cannot be applied to viewer.
How about adding style to the container element after wrapping the viewer component?
