### ISSUE TITLE
[WYSIWYG] Style remains when overwriting text

### ISSUE THREAD

**Issue by ryum91** [nhn/tui.editor#877]
## Describe
Style remains when overwriting text

## To Reproduce
1. Apply 'Heading' style to text
2. Copy and overwrite other text
3. Heading style remains

## Expected behavior
I think both text and style should be overwritten.

## Screenshots
![tui-editor](https://user-images.githubusercontent.com/18422353/78329311-4d55ee00-75bc-11ea-9cfd-b1a37403a294.gif)

## Desktop (please complete the following information):
 - Chrome

## Additional context
If it is a bug, please change it to a bug.

**Comment by rfox12** [comment]
I think nice behavior would be: 

- If the selection only spans 1 style: keep that style when editing/pasting
- If the selection spans multiple styles: remove the style when editing/pasting
