### ISSUE TITLE
[WYSIWYG] Text remove bug when changing Style

### ISSUE THREAD

**Issue by ryum91** [nhn/tui.editor#878]
## Describe the bug
Text remove bug when changing Style

## To Reproduce
1. Text input after apply Heading style
2. Erase all, input text again
3. Change heading style
4. remove text.

## Screenshots
![tui-editor2](https://user-images.githubusercontent.com/18422353/78331193-81331280-75c0-11ea-98f8-49aad8ec49c1.gif)

## Version
 - chrome 80
 - tui.editor 2.0.1

**Comment by rfox12** [comment]
Maybe this issue is related to #872 ?

**Comment by seonim-ryu** [comment]
@rfox12 This is a different issue from issue #872 . It has been identified as an issue occurring in version 1, and I will try to fix it as soon as possible.

**Comment by seonim-ryu** [comment]
## Cause
`<div>` tag in the heading tag disappears when there is no content.

![foo](https://user-images.githubusercontent.com/18183560/78677357-9bebeb00-7922-11ea-91eb-a0e75e826b0e.png)

![empty](https://user-images.githubusercontent.com/18183560/78677820-26344f00-7923-11ea-94ac-9cd4ecbd3936.png)

![bar](https://user-images.githubusercontent.com/18183560/78677510-cb9af300-7922-11ea-95dc-f73446b5f5b9.png)
