### ISSUE TITLE
Is it possible to use this inside a form?

### ISSUE THREAD

**Issue by Puyodead1** [nhn/tui.editor#884]
I'm using laravel and posting a form to a database, I imported the jQuery version of tui.editor but when I put the editor into a form element, it threw an error ``Cannot read property 'classList' of null``.
Is it possible to do this inside form tags or is there a way to make the editor appear in the same place inside the form?

**Comment by seonim-ryu** [comment]
@Puyodead1 Your question seems to be related to [this issue](https://github.com/nhn/tui.editor/issues/837).  As I answered in that issue, why not put a `form` tag outside the editor and call the `getHtml()`, `getMarkdown()` API to get the data and use it as form data?

**Comment by seonim-ryu** [comment]
Related to this PR and resolved.
> https://github.com/nhn/tui.editor/pull/890
