### ISSUE TITLE
markdown에서 video 기능 제공하게 하려면 어떻게해야하나요?

### ISSUE THREAD

**Issue by CarpediemBDev** [nhn/tui.editor#886]
markdown에서 video 기능 제공하게 하려면 어떻게해야하나요?
tui-editor.js 부분을 커스터마이징해야하나요?

**Comment by js87zz** [comment]
@CarpediemBDev 
Please respect our issue form and write your issue **in English** to share the issue other people.

**Comment by CarpediemBDev** [comment]
Ok.
how to Using video tags in tui-editor markdown mode?
