### ISSUE TITLE
Popup table editor text overflows

### ISSUE THREAD

**Issue by Zulcom** [nhn/tui.editor#891]
## Describe the bug
Russian translation (maybe not only russian) text is too long for table popup utils lines:
![image](https://user-images.githubusercontent.com/11247988/78740080-7b418680-795e-11ea-9b50-aa46469b6f0b.png)

## To Reproduce
1. set `language: 'ru'`
2. Set WYSIWYG mode
2. Right-click table
3. See text overflows with of `,te-popup-table-utils`
4. (See error)

## Expected behavior
![image](https://user-images.githubusercontent.com/11247988/78740216-dd9a8700-795e-11ea-94f1-d3e011bf2e02.png)

## Desktop (please complete the following information):
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.95`
 - OS: Windows 10
 - Browser Opera (Blink based)
 - Version 66 (As Chrome 79) 

## Additional
Can be simply fixed (But sadly I have not enough time resources to make PR): 
remove width from `.te-popup-table-utils` and `.te-popup-table-utils button`
add `display:block` to `.te-popup-table-utils button`

**Comment by seonim-ryu** [comment]
@Zulcom Thanks for reporting the issue!
