### ISSUE TITLE
Math/Latex

### ISSUE THREAD

**Issue by homlex** [nhn/tui.editor#893]
Very nice one, I hope that it will support math formulas and text highlighting 
![image](https://user-images.githubusercontent.com/48396880/79041906-f7b9bb00-7c25-11ea-93f8-ae38acc70586.png)
![image](https://user-images.githubusercontent.com/48396880/79041909-fee0c900-7c25-11ea-8d90-5b6f4dbebe3c.png)

**Comment by js87zz** [comment]
@homlex 
We have the plan to improve the text highlighting gradually. There is no plan for the math formula but we will discuss about it. Thank you!
