### ISSUE TITLE
In reactJs how can i add youtubeplugin?

### ISSUE THREAD

**Issue by yoojeen126** [nhn/tui.editor#899]
## Summary
Use React like doc in https://nhn.github.io/tui.editor/latest/tutorial-example17-creating-plugin
Got error in  Editor.codeBlockManager.setReplacer.

## Version
"@toast-ui/react-editor": "^2.0.1",
## Additional context
import { Editor} from '@toast-ui/react-editor';
...
<Editor  placeholder="hello react editor world!"
              previewStyle="vertical"
              initialEditType="wysiwyg"
              initialValue="Hello world"
              usageStatistics={false}
              ref={editorRef}
              plugins={[colorSyntax, youtubePlugin]}
              onChange={getPostInfo}
 />

 const youtubePlugin =() => {
   //TypeError: Cannot read property 'setReplacer' of undefined
   Editor.codeBlockManager.setReplacer('youtube', function(youtubeId) { 
      ...
   });
 }

**Comment by js87zz** [comment]
@yoojeen126 
`codeBlockManager` is static property, so that you can use as below. 
We consider improving the way to provide static method in wrapper for usability.
```js
import ToastEditor from '@toast-ui/editor';
import { Editor } from '@toast-ui/react-editor';

// ...
const youtubePlugin =() => {
  ToastEditor.codeBlockManager.setReplacer('youtube', function(youtubeId) {
  // ...
  }
});

<Editor placeholder="hello react editor world!"
  previewStyle="vertical"
  initialEditType="wysiwyg"
  initialValue="Hello world"
  usageStatistics={false}
  ref={editorRef}
  plugins={[colorSyntax, youtubePlugin]}
  onChange={getPostInfo}
/>
```

**Comment by leeonfield** [comment]
> @yoojeen126
> `codeBlockManager` is static property, so that you can use as below.
> We consider improving the way to provide static method in wrapper for usability.
> 
> ```js
> import ToastEditor from '@toast-ui/editor';
> import { Editor } from '@toast-ui/react-editor';
> 
> // ...
> const youtubePlugin =() => {
>   ToastEditor.codeBlockManager.setReplacer('youtube', function(youtubeId) {
>   // ...
>   }
> });
> 
> <Editor placeholder="hello react editor world!"
>   previewStyle="vertical"
>   initialEditType="wysiwyg"
>   initialValue="Hello world"
>   usageStatistics={false}
>   ref={editorRef}
>   plugins={[colorSyntax, youtubePlugin]}
>   onChange={getPostInfo}
> />
> ```

is this way work in Viewer ? 

i define the video plugin function which use in Editor and Viewer, but only work in Editor

**Comment by leeonfield** [comment]
```js
const videoPlugin = (editor) => {
  const { codeBlockManager } = Object.getPrototypeOf(editor).constructor
  codeBlockManager.setReplacer('youtube', function(sourceId) {
  ……
}
```
this way work in Editor and Viewer

**Comment by leeonfield** [comment]
[@leeonfield/editor-plugin-video](https://www.npmjs.com/package/@leeonfield/editor-plugin-video) now can help to insert video in Tui.editor

**Comment by Ats1999** [comment]
> ```js
> const videoPlugin = (editor) => {
>   const { codeBlockManager } = Object.getPrototypeOf(editor).constructor
>   codeBlockManager.setReplacer('youtube', function(sourceId) {
>   ……
> }
> ```
> 
> this way work in Editor and Viewer

How we can get the reference of `editor`.

**Comment by leeonfield** [comment]
> > ```js
> > const videoPlugin = (editor) => {
> >   const { codeBlockManager } = Object.getPrototypeOf(editor).constructor
> >   codeBlockManager.setReplacer('youtube', function(sourceId) {
> >   ……
> > }
> > ```
> > 
> > 
> > this way work in Editor and Viewer
> 
> How we can get the reference of `editor`.

`editor` is the param of this plugin,no need to get  the reference of `editor`
```js
const plugins = [videoPlugin]
<TuiEditor plugins={plugins} />
```

**Comment by Ats1999** [comment]
> > > ```js
> > > const videoPlugin = (editor) => {
> > >   const { codeBlockManager } = Object.getPrototypeOf(editor).constructor
> > >   codeBlockManager.setReplacer('youtube', function(sourceId) {
> > >   ……
> > > }
> > > ```
> > > 
> > > 
> > > this way work in Editor and Viewer
> > 
> > 
> > How we can get the reference of `editor`.
> 
> `editor` is the param of this plugin,no need to get the reference of `editor`
> 
> ```js
> const plugins = [videoPlugin]
> <TuiEditor plugins={plugins} />
> ```

Thanks, It worked.
