### ISSUE TITLE
Paste from docx include embed image

### ISSUE THREAD

**Issue by rickywu** [nhn/tui.editor#902]
I wrote one Office Add-in to support copy MS Word docx and include embed images, 
then we can paste directly in Toast UI editor

One more thing is you need save base64 MIME image data to file and replace as link on server side

https://github.com/rickywu/visualpaste

**Comment by seonim-ryu** [comment]
@rickywu Would you please confirm that what I understood was correct? Do you need the function to paste the image copied from MS to TOAST UI Editor and then transfer the pasted image to the server?

**Comment by rickywu** [comment]
@seonim-ryu I want TOAST UI Editor support paste the image copied from MS Word, so I created one Office Add-in to implement this function and shared it here.

The next step which should be implemented by your self is transfer base64 code to image file and replace as link,
