### ISSUE TITLE
How to change style (font, color, etc) of editor?

### ISSUE THREAD

**Issue by suregi** [nhn/tui.editor#905]
I want to change css style (font, color, etc) of editor components. I do not see any reference in any document.

- https://nhn.github.io/tui.editor/latest/ToastUIEditor
- https://github.com/nhn/tui.editor/tree/master/apps/react-editor

There were similar issues: 
- https://github.com/nhn/tui.editor/issues/177 
- https://github.com/nhn/tui.editor/issues/544
- https://github.com/nhn/tui.editor/issues/674

#177 - seems to indicate existence of solution, but the solution was not published (July 2018 conversation)
#544
#674 - this can be a solution; is this official recommendation? If so, it would be helpful to have some guidance on which class to target for which component.

**Comment by seonim-ryu** [comment]
@suregi Currently, the Editor doesn't offer an option related styles. It is right to resolve this issue as you find it. You can override styles with `.tui-editor-contents`.

And as you said, it's a good idea to have a guide in the Editor. Thanks for your comment!
