### ISSUE TITLE
[WYSIWYG]: bold and italic text returns as a mix of html and markdown

### ISSUE THREAD

**Issue by bolaisacat** [nhn/tui.editor#906]
## Describe the bug
In WYSIWYG mode, bold and italic text are output as a mix of html and markdown

## To Reproduce
1. Go to the basic editor: https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic
2. Select the WYSIWYG tab to put the editor into WYSIWYG editing mode.
3. Enter any sentence  (e.g. "abc");
4. Select character 'b'
5. Click Bold button to bold 'b'
6. Click Italic button to italicize 'b'
7. Click 'Markdown' tab to switch to markdown editor
8. The text appears incorrectly as 'a<b>*b*</b>c'

## Expected behavior
a***b***c

## Screenshots
WYSIWYG mode
![image](https://user-images.githubusercontent.com/63823899/79517367-99b91900-8013-11ea-8f52-138d3315099f.png)

Switching to Markdown mode
![image](https://user-images.githubusercontent.com/63823899/79517413-b5bcba80-8013-11ea-8f31-14b6ecf48c6c.png)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81

## Additional context
Same result (mix of html and markdown) returns when I call the API getMarkdown. Also, if selecting the whole line and format it in bold and italic, the result is correct.

**Comment by seonim-ryu** [comment]
@bolaisacat The editor had [this issue](https://github.com/nhn/tui.editor/issues/557) before. Because it's handled like this, it is correct to work in the current situation. Markdown syntax also allows html, so it's hard to see as a bug. 🤔

**Comment by bolaisacat** [comment]
@seonim-ryu thanks. well, at least there are some inconsistencies here. Since selecting a whole line and bold+italic works and returns ***abc***, while mixed html and markdown are returned when only part of the line is selected.

**Comment by treyssatvincent** [comment]
I think that most of Markdown's users prefer to use only markdown in that case:

~~~ md
**strong*italic***
~~~
**strong*italic***
