### ISSUE TITLE
Is there any reason not to support underline (u tag) for ToolbarItem?

### ISSUE THREAD

**Issue by hanjoongcho** [nhn/tui.editor#915]
## Summary
If you look at the base64 sprite image included in the tui editor, the u tag icon is included.
There is no u tag feature in the reference document or example.
Please inquire if there is any special reason.

## Screenshots
sprite image base64 encoded
![image](https://user-images.githubusercontent.com/7098851/79874640-95ca3400-8423-11ea-9273-a9b36448b199.png)

## Version
v2.0.1

**Comment by seonim-ryu** [comment]
@hanjoongcho 
The underline is not a [CommonMark specification](https://spec.commonmark.org/0.29/). Actually, it shouldn't be included in that image. And that image will be modified. Anyway, thanks for the comments. :)

**Comment by hanjoongcho** [comment]
@seonim-ryu 
That's because of markdown and compatibility issues.
Okay. Thank you.
