### ISSUE TITLE
Scroll Sync position not correct

### ISSUE THREAD

**Issue by xinshangshangxin** [nhn/tui.editor#92]
## Version
1.0.4

## Test Environment

`chrome 64.0.3282.186`
with page https://nhnent.github.io/tui.editor/api/latest/tutorial-example05-scrollsync.html
set next code

## Current Behavior

![image](https://user-images.githubusercontent.com/8779091/36734205-c1139ca8-1c0d-11e8-94ec-1cf61453826a.png)

<pre>
# head 1
## head 2
*test*
*tui.editor*
## head 3
```bash
# install
npm install tui.editor
```

## head 4
```bash
# install
npm install tui.editor
npm install tui.editor
```

## head 5
```bash
# install
npm install tui.editor
npm install tui.editor
```
## head 6
```bash
# install
npm install tui.editor
npm install tui.editor
npm install tui.editor
npm install tui.editor
npm install tui.editor
npm install tui.editor
npm install tui.editor
npm install tui.editor
```
</pre>

## Expected Behavior

left and right should be same

**Comment by existme** [comment]
I would say this is still the most problematic issue and makes me disable autoscroll almost always
