### ISSUE TITLE
Does not work inside <form> (vue version)

### ISSUE THREAD

**Issue by coyotte508** [nhn/tui.editor#943]
## Describe the bug

Trying to put the editor inside a form yields an error

## To Reproduce

```
<template>
  <form>
    <editor />
  </form>
</template>
```

## Expected behavior

It works

## Screenshots

![image](https://user-images.githubusercontent.com/342922/80312854-f40e6280-87e7-11ea-8b43-9f90fe1a2d89.png)

![image](https://user-images.githubusercontent.com/342922/80312845-e527b000-87e7-11ea-96dd-de19cfec04ed.png)

## Desktop (please complete the following information):
 - OS: Windows
- Browser: Chrome

**Comment by seonim-ryu** [comment]
@coyotte508 
I think it's the same problem as this one. This is currently resolved and will be included in the 2.1.0 release.

> https://github.com/nhn/tui.editor/pull/890
