### ISSUE TITLE
Yarn add tui-editor failed

### ISSUE THREAD

**Issue by Zuojiangtao** [nhn/tui.editor#964]
## Describe the bug
yarn install failed

## To Reproduce
1. yarn add tui-editor

## Expected behavior
yarn add success

## Screenshots
report error

## Desktop (please complete the following information):
 Yarn version: 
  1.22.4

Node version: 
  12.16.3

Npm version:
  6.14.4

Platform: 
  win32 x64

## Additional context
I reported an error when I installed:
````
error An unexpected error occurred: "https://raw.githubusercontent.com/seonim-ryu/Squire/fd40b4e3020845825701e9689f190bab3f4775d4/package.json: getaddrinfo ENOENT r
aw.githubusercontent.com".
````
## This is error.log
[yarn-error.log](https://github.com/nhn/tui.editor/files/4555960/yarn-error.log)

**Comment by seonim-ryu** [comment]
@Zuojiangtao Do you still have the same problem? I cannot reproduce. Looking for the issue, I think it happened when the resource in question could not be accessed at some time. Can you check if you can access the file below?

> https://raw.githubusercontent.com/seonim-ryu/Squire/fd40b4e3020845825701e9689f190bab3f4775d4/package.json

**Comment by Zuojiangtao** [comment]
> @Zuojiangtao Do you still have the same problem? I cannot reproduce. Looking for the issue, I think it happened when the resource in question could not be accessed at some time. Can you check if you can access the file below?
> 
> > https://raw.githubusercontent.com/seonim-ryu/Squire/fd40b4e3020845825701e9689f190bab3f4775d4/package.json
> 
> And I recommend using version 2. Have you ever used the Editor before and updated the version?

I have not used it before. I guess it is because of network reasons that I cannot install normally, and I cannot access this link.

**Comment by seonim-ryu** [comment]
@Zuojiangtao If the link above does not work, it seems that the network you are using is blocking access to that domain. We do not know why it is blocked.

**Comment by Zuojiangtao** [comment]
> @Zuojiangtao If the link above does not work, it seems that the network you are using is blocking access to that domain. We do not know why it is blocked.

The strange thing is that there is no problem when installing using npm, now I have used npm to install dependencies. But if possible, I still want to be able to use yarn to install dependencies.
