### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by SydnieBan** [nhn/tui.editor#965]
I user tui-editor in comment area, when mode is 'markdown', set up chrome performancecpu 4 *slowdown，the display is very slow after input, causing the user to freeze. but when mode is 'wysiwyg',  this will not happen

**Comment by SydnieBan** [comment]
i want to know why is the browser performance affected when the mode is `markdown`, but not affected when the mode is `wysiwyg`?

**Comment by seonim-ryu** [comment]
@SydnieBan I have a question. Guessing that you are saying `tui-editor`, I think you are using editor version 1, right? And if possible, can you show the performance results you measured?

**Comment by SydnieBan** [comment]
@seonim-ryu yes, i am using editor version 1

[](https://img-blog.csdnimg.cn/20200521133817787.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM4MzI4NzYy,size_16,color_FFFFFF,t_70)

[](https://img-blog.csdnimg.cn/20200521133817756.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM4MzI4NzYy,size_16,color_FFFFFF,t_70)
