### ISSUE TITLE
Disabled Editor instead of Viewer for ReactJS

### ISSUE THREAD

**Issue by Yash-GitB** [nhn/tui.editor#976]
Hi,

I wanted to know if it's feasible to add a disabled editor instead of a viewer. I need to disable all buttons and the editor edibility. Also, would like to know the usage of setValue(). Do share some examples if available for both.

Thanks,
Yash

**Comment by hochan222** [comment]
At least a year ago, contributor said it was a feature that was not supported.

Duplicate of switch from the editor to the viewer #510 
<pre>
There is no way to switch from the editor to the viewer and vice versa. 
The editor and the viewer is independent component so we do not provide switching feature.
Switching between the editor and the viewer is something that people using tui.editor should implement.
</pre>
- sohee-lee7 [Contributor] -
