### ISSUE TITLE
Replace suggestion text at cursor position

### ISSUE THREAD

**Issue by dpatra** [nhn/tui.editor#982]
## Summary
TUI Editor does not provide autocomplete or hint api, for user mention, hashtag, emoji text ( : based) out of the box.

So I tried implementing the autocomplete on my own to show on keydown/keyup events from tui editor.

But I am stuck at replacing a current typed word OR a word with current cursor position (can be any word in the editor) with the selected suggestion (text).

**Comment by seonim-ryu** [comment]
@dpatra I think the function you need is about this issue. Can you check the content below?

> https://github.com/nhn/tui.editor/issues/968#issuecomment-625706640

**Comment by dpatra** [comment]
I developed my custom autocomplete and implemented it. The combination of Code Mirror, Markdown and WYSIWYG editors are so complex ; to get a simple thing.

However, I was able to get what I want after a lot RnD.

Closing this issue, as I think there would be no help regarding this.

**Comment by seanwang1998** [comment]
> 
I have the same demand as you now, could you please provide the code to solve it? Thank you very much
