### ISSUE TITLE
why does change font-family?

### ISSUE THREAD

**Issue by t-mori-sm** [nhn/tui.editor#983]
## Summary
It's hard to use.
before:
```
font-family: Open Sans,Helvetica Neue,Helvetica,Arial,sans-serif;
```
after:
```
font-family:Open Sans,Helvetica Neue,Helvetica,Arial,나눔바른고딕,Nanum Barun Gothic,맑은고딕,Malgun Gothic,sans-serif
```
## Version
2.1.0

## Additional context
https://github.com/nhn/tui.editor/commit/422a9e8e98f9f5dba4c4dd37fbac449fdfbb6a84#diff-3f7ddde7ba9a65be48ea6f37d7a3cf1b

**Comment by seonim-ryu** [comment]
@t-mori-sm Changed to improve the [syntax highlighting function of the Markdown editor in 2.1.0](https://github.com/nhn/tui.editor/releases/tag/v2.1.0) so that the content can be displayed better. I don't understand what it means to be difficult to use, can you explain it in detail?
