### ISSUE TITLE
How can toas-ui editor be added to a sapper app ?

### ISSUE THREAD

**Issue by wolfiton** [nhn/tui.editor#985]
## Summary
How can toas-ui editor be added to a sapper app  with webpack?
https://github.com/wolfiton/sapper-webpack
## Version
Latest "@toast-ui/editor": "^2.1.2",
## Additional context
https://github.com/wolfiton/sapper-webpack

**Comment by seonim-ryu** [comment]
@wolfiton Looking for [Sapper](https://sapper.svelte.dev/), I think Sapper is a framework used by Svelt. Just looking at the link you gave me seems like a problem with using Svelt. Currently the Editor is not considering using Svelt.

**Comment by wolfiton** [comment]
Hi @seonim-ryu ,

It's unfortunate you don't want to adapt your editor to svelte.

I may retry this idea in the future than on my own.

Thanks for the reply.
