### ISSUE TITLE
Get Markdown content in form

### ISSUE THREAD

**Issue by bastienu** [nhn/tui.editor#994]
## Summary
I'm using the toastui-jquery-editor.min.js. Everything is working correctly : the two blocks are well displayed, the code mirror is doing the job, etc. Here is the code:

**HTML:**
```html
<div id="editor"></div>
```

**jQuery:**
```js
var editor = $('#editor').toastuiEditor({
  previewStyle: 'vertical',
  height: '500px',
  language: 'fr',
  initialEditType:'markdown',
  hideModeSwitch: true,
  previewHighlight: false,
  events: {
    change: function() { 
      console.log('changed!');
    },
  }
});
```

This HTML is in a form and my problem is that I can't find how to get the markdown content. I can create an hidden field in my form, no problem, but I still don't know how to get the markdown content to put it in my hidden field. I've tried to use the change event, but can't find on to get the content in this function.

In the API, in find some functions like `getTextContent()`, but I can't understand where and hows to use them? On which instance?

## Screenshots

See, everything is working correctly on the front page!
<img width="520" alt="Capture d’écran 2020-05-20 à 00 06 41" src="https://user-images.githubusercontent.com/1685778/82383316-d2db1380-9a2d-11ea-9b1b-46b3481110d8.png">

## Version
I'm using tui.editor v 2.1.2, [from CDN](https://uicdn.toast.com/editor/latest/toastui-jquery-editor.min.js).

Thanks a lot If you can help me :-)

**Comment by seonim-ryu** [comment]
@bastienu If you want to get Markdown data, you can use [`getMarkdown()`](https://nhn.github.io/tui.editor/latest/ToastUIEditor#getMarkdown) API. When using jQuery, you can call it to get the value.
```js
// ...
$('#editor').toastuiEditor({
  // ...
});

const content = $('#editor').toastuiEditor('getMarkdown');

console.log(content);
```

**Comment by Jeffryhui** [comment]
@bastienu 
```js
var editor = $('#editor').toastuiEditor({
  previewStyle: 'vertical',
  height: '500px',
  language: 'fr',
  initialEditType:'markdown',
  hideModeSwitch: true,
  previewHighlight: false,
  events: {
    change: function() { 
      console.log(editor.getMarkdown());
      console.log(editor.getHtml());
    },
  }
});
```
