### ISSUE TITLE
How to use '\n' or '\t' for new line or tab

### ISSUE THREAD

**Issue by cs-ajay-chakkar** [nhn/tui.editor#995]
1) How we can use`\n` and `\t` to display a new line and tab spacing in the preview?

**Comment by seonim-ryu** [comment]
@cs-ajay-chakkar The preview area is responsible for rendering the Markdown data. First, `\n` is a character used for newline, and this can be used to show the newline status using the `<br>` tag. However, `\t` corresponds to the indentation behavior, and the tab character can be used only in [this case in the Markdown specification](https://spec.commonmark.org/0.29/#tabs). In other words, you cannot use the tab characters used in plain text (paragraphs). In other words, there is no way to render tab characters used in plain text (`paragraph`).

**Comment by cs-ajay-chakkar** [comment]
@seonim-ryu  thank you for the response.
One more question,
Like we are using **bold** to display bold text, in the same way, 
is it possible to add a custom tag?
for e.g *****boldItalicUnderline***** will print text in bold italic and have underline.
another example,  ^2 will display the superscript. 
Is there any provision to add such customization?
