### ISSUE TITLE
i can not set Value

### ISSUE THREAD

**Issue by mrsai** [nhn/tui.editor#996]
## Summary
When using @toast-ui/vue-editor in my project, I cannot set the data that I asynchronously requested back to the editor
I think there is no "watch initialValue". I also use the "invoke" method and it doesn't work. Is there a problem with my usage?
## Screenshots

```
watch: {
        file(newVal) {

        // it is not works

        this.$refs.toastuiEditor.invoke("setValue", "hahahahahah");

        // it is  works well

        let html = this.$refs.toastuiEditor.invoke("getHtml");

        console.log(html);
   
    }

  }
```

## Version
"@toast-ui/vue-editor": "^2.1.2",.

## Additional context
null

**Comment by giscafer** [comment]
so do i, is it any problem?
```
 console.log(content)
 this.$refs.remarkEditorRef.invoke('setValue', content)
```

**Comment by Dulan666** [comment]
> ```
>  console.log(content)
>  this.$refs.remarkEditorRef.invoke('setHtml', content)
> ```

Thanks! it works.

**Comment by mrsai** [comment]
> ```
>  console.log(content)
>  this.$refs.remarkEditorRef.invoke('setHtml', content)
> ```

thanks！

**Comment by chjaved83** [comment]
async function addText() {
  const baseText = selected.value?.text || 'Sample Text';
  const text = isUppercase.value ? baseText.toUpperCase() : baseText;

  const textObj = await editor.value?.addText(text);
  console.log(textObj)
  if (textObj) {
    
    textObj.set({
      fontFamily: fontFamily.value,
      fontSize: fontSize.value,
      fontWeight: isBold.value ? 'bold' : 'normal',
      fontStyle: isItalic.value ? 'italic' : 'normal',
      textAlign: mapAlign(selectedAlign.value),
      fill: selectedColor.value,
      underline: isUnderline.value,
    });

    const canvas = editor.value?._graphics?.getCanvas();
    if (canvas) {
      canvas.setActiveObject(textObj);
      canvas.renderAll();
    }

    selected.value = textObj;
  }
}


.set is not working
