### ISSUE TITLE
에디터에 사진 첨부 시 리사이징

### ISSUE THREAD

**Issue by soreus** [nhn/tui.editor#997]
현재 프로젝트가 하이브리드 앱으로 개발 중인데

사용은 ios랑 android 만 앱으로 제공하여 사용할 예정이구요 

웹뷰로 씌어서 하고 있습니다...그래서 에디터 기능을 사용하려는데 

사진 첨부 시 사진 해상도가 클때 리사이징 하는 방법이 궁금합니다.

디비에 저장 시 에디터 html 상태로 그대로 때려넣거든요..

**Comment by seonim-ryu** [comment]
@soreus 

> ⚠️ Please change the issue title and issue content to English so that other foreigners can confirm the issue.

First of all, the Editor doesn't fully support mobile devices, so be careful. And in the case of the question you asked, I think the `hooks.addImageBlobHook` option of the editor instance can handle the image before uploading it.

```js
const edtior = new Editor({
  hooks: {
    addImageBlobHook: () => {
      // ...
    }
  }
});
