### ISSUE TITLE
How set height for fill all the available space

### ISSUE THREAD

**Issue by DellaMoraWalter** [nhn/tui.editor#999]
### The goal 
is to use all available height.

### Context
Tui-Editor ver 2.1.2
toastui-editor-all.min.js

### Editor declaration
```
      const editor = new toastui.Editor({
        el: document.querySelector('#editor'),
        previewStyle: 'vertical',
        minHeight: '100%',
        height: '100%',
        initialEditType: 'wysiwyg',
        hideModeSwitch: true,
        usageStatistics: false,
        toolbarItems: [
            'heading',
            'bold',
            'italic',
            'strike',
            'divider',
            'ul',
            'ol',
            'indent',
            'outdent',
            'divider',
            'hr'
        ]
      });
```

### css
```
html, body {
    margin: 0px;
    padding: 0px 0px;
    height: 100%;
}

.tui-doc-contents .btn {
    margin: 0px;
    padding: 0px;
    height: 100%;
    overflow-y: hidden;
    overflow-x: hidden;
    font-family: 'Roboto', sans-serif;
}
```

### The problem
Only the toolbar is rendered as expected.
The edit area have 0 pixels height.

### Note
With ver 1.4.10 this configuration works as expected.

Thanks

**Comment by seonim-ryu** [comment]
@DellaMoraWalter I tried to reproduce it with the code you gave me, but I don't understand what part is the problem. Can you explain in more detail? It would be better if you give me a screenshot.

![height](https://user-images.githubusercontent.com/18183560/83217536-f711bf80-a1a6-11ea-92e9-610b5608def6.png)

**Comment by DellaMoraWalter** [comment]
@seonim-ryu i've attached a sample for reproduce the problem. You can execute editor.html and see.
[TextEditor.zip](https://github.com/nhn/tui.editor/files/4702127/TextEditor.zip)

thanks!
